import H0mework.NavierStokes.Galerkin.NonlinearNegativeSobolev
import H0mework.NavierStokes.GeneratedPaths.CriticalAbsorption
import H0mework.NavierStokes.Galerkin.CriticalSerrinBudget

/-!
# Negative-Sobolev time budget for actual finite Galerkin updates

The nonlinear estimate supplies a cutoff-independent `H⁻¹` mass, while the
exact viscous row pays the same mass with the vorticity-gradient ledger.
Combining them gives

```text
‖∂ₜω‖_{H⁻¹}²
  ≤ 8 M(u)² Y(ω) + 2 ν² (2π)² Z(ω).
```

The final source theorem integrates this inequality on the actual trajectory
generated by an arbitrary finite scale path.  Its bound reads only the
initial critical mass, viscosity, and the generated absorption coefficient;
it contains no mode count, maximum frequency, trajectory, time interval, or
analytic budget premise.

This is the compactness branch downstream of the exact mild identity.
Mathlib supplies Bochner integration and abstract compact operators, but no
ready torus Sobolev/Rellich/Aubin--Lions theorem.  Accordingly this module
closes the uniform `L²_t H⁻¹` derivative ledger and leaves subsequence
compactness as the next independent target consumer.
-/

namespace SaturationMonoid
namespace NavierStokes
namespace ThreeDimensionalVorticityCoefficientFiniteGalerkinNegativeSobolevTimeBudget

open scoped BigOperators Matrix Topology Interval ENNReal

open Set
open MeasureTheory
open Matrix
open ThreeDimensionalPeriodicCoarseFilterCore
open ThreeDimensionalPeriodicIntegerCharacterCoarseFilter
open ThreeDimensionalPeriodicFilteredNavierStokesGenerator
open ThreeDimensionalVorticityCoefficientRawSourceCore
open ThreeDimensionalVorticityCoefficientGeneratedIntegerShellSource
open ThreeDimensionalVorticityCoefficientGeneratedIntegerShellPath
open ThreeDimensionalVorticityCoefficientGeneratedIntegerShellTraceCumulative
open ThreeDimensionalVorticityCoefficientGeneratedShellSerrinGeometry
open ThreeDimensionalVorticityCoefficientGeneratedShellViscousParseval
open ThreeDimensionalVorticityCoefficientFiniteSupportComplexTrajectory
open ThreeDimensionalVorticityCoefficientFiniteSupportPhysicalInvariantTrajectory
open ThreeDimensionalVorticityCoefficientFiniteSupportRealityTrajectory
open ThreeDimensionalVorticityCoefficientFiniteSupportCriticalSobolev
open ThreeDimensionalVorticityCoefficientFiniteGalerkinAmbientNorm
open ThreeDimensionalVorticityCoefficientFiniteGalerkinEnstrophyBalance
open ThreeDimensionalVorticityCoefficientFiniteGalerkinCriticalEnstrophyBarrier
open ThreeDimensionalVorticityCoefficientGeneratedPathStretchingBudget
open ThreeDimensionalVorticityCoefficientGeneratedPathCriticalAbsorption
open ThreeDimensionalVorticityCoefficientGeneratedPathCriticalTimeConsumer
open ThreeDimensionalVorticityCoefficientFiniteGalerkinCriticalSerrinBudget
open ThreeDimensionalVorticityCoefficientFiniteGalerkinNonlinearNegativeSobolev

noncomputable section

/-! ## The common negative-one carrier -/

private theorem continuousAt_finset_sum_negativeOne
    {α E : Type}
    [DecidableEq α]
    [TopologicalSpace E]
    [AddCommMonoid E]
    [ContinuousAdd E]
    (indices : Finset α)
    (summand : α → ℝ → E)
    (t : ℝ)
    (continuousSummand :
      ∀ index ∈ indices, ContinuousAt (summand index) t) :
    ContinuousAt (fun time => ∑ index ∈ indices, summand index time) t := by
  induction indices using Finset.induction_on with
  | empty =>
      simpa using
        (continuousAt_const : ContinuousAt (fun _ : ℝ => (0 : E)) t)
  | @insert index indices indexNotMem inductionHypothesis =>
      simp only [Finset.sum_insert indexNotMem]
      exact
        (continuousSummand index (by simp)).add
          (inductionHypothesis fun later laterMem =>
            continuousSummand later (by simp [laterMem]))

/-- Physical homogeneous `H⁻¹` mass of any actual finite-carrier tangent.
The denominator is the exact Fourier multiplier of `-Δ`; the zero row is
assigned zero. -/
def finiteStateVorticityNegativeOneMass
    (modes : Finset IntegerWavevector)
    (tangent : ComplexVorticityHilbertState) : ℝ :=
  ∑ output ∈ modes,
    if output = 0 then 0
    else
      ‖tangent output‖ ^ 2 /
        integerWaveViscousMultiplier output

theorem finiteStateVorticityNegativeOneMass_nonneg
    (modes : Finset IntegerWavevector)
    (tangent : ComplexVorticityHilbertState) :
    0 ≤ finiteStateVorticityNegativeOneMass modes tangent := by
  unfold finiteStateVorticityNegativeOneMass
  apply Finset.sum_nonneg
  intro output outputMem
  by_cases outputZero : output = 0
  · simp [outputZero]
  · rw [if_neg outputZero]
    exact div_nonneg (sq_nonneg _)
      (mul_nonneg (sq_nonneg _)
      (integerWaveNormSq_nonneg output))

/-- On a zero-free integer inventory, homogeneous `H⁻¹` tangent mass is
bounded by the ambient Hilbert norm squared.  The estimate is independent
of the mode count and largest frequency. -/
theorem finiteStateVorticityNegativeOneMass_le_norm_sq
    (modes : Finset IntegerWavevector)
    (zeroNotMem : (0 : IntegerWavevector) ∉ modes)
    (tangent : ComplexVorticityHilbertState) :
    finiteStateVorticityNegativeOneMass modes tangent ≤
      ‖tangent‖ ^ 2 := by
  have rowSummable :
      Summable fun wave : IntegerWavevector =>
        ‖tangent wave‖ ^ 2 := by
    simpa only [ENNReal.toReal_ofNat, Real.rpow_two] using
      Memℓp.summable (by norm_num) tangent.2
  have finiteRowsLe :
      (∑ wave ∈ modes, ‖tangent wave‖ ^ 2) ≤
        ∑' wave : IntegerWavevector, ‖tangent wave‖ ^ 2 :=
    rowSummable.sum_le_tsum modes
      (fun wave waveMem => sq_nonneg _)
  have normIdentity :
      ‖tangent‖ ^ 2 =
        ∑' wave : IntegerWavevector, ‖tangent wave‖ ^ 2 := by
    simpa using
      (lp.norm_rpow_eq_tsum
        (p := (2 : ℝ≥0∞)) (by norm_num) tangent)
  calc
    finiteStateVorticityNegativeOneMass modes tangent =
        ∑ output ∈ modes,
          ‖tangent output‖ ^ 2 /
            integerWaveViscousMultiplier output := by
      unfold finiteStateVorticityNegativeOneMass
      apply Finset.sum_congr rfl
      intro output outputMem
      have outputNe : output ≠ 0 := by
        intro outputZero
        subst output
        exact zeroNotMem outputMem
      rw [if_neg outputNe]
    _ ≤
        ∑ output ∈ modes, ‖tangent output‖ ^ 2 := by
      apply Finset.sum_le_sum
      intro output outputMem
      have outputNe : output ≠ 0 := by
        intro outputZero
        subst output
        exact zeroNotMem outputMem
      have oneLeNormSq :
          (1 : ℝ) ≤ integerWaveNormSq output := by
        rw [integerWaveNormSq_eq_integerWaveShellSq]
        exact_mod_cast integerWaveShellSq_pos outputNe
      have oneLeTwoPiSq : (1 : ℝ) ≤ (2 * Real.pi) ^ 2 := by
        nlinarith [Real.pi_gt_three]
      have oneLeMultiplier :
          (1 : ℝ) ≤ integerWaveViscousMultiplier output := by
        unfold integerWaveViscousMultiplier
        nlinarith
      exact div_le_self (sq_nonneg _) oneLeMultiplier
    _ ≤
        ∑' wave : IntegerWavevector, ‖tangent wave‖ ^ 2 :=
      finiteRowsLe
    _ = ‖tangent‖ ^ 2 :=
      normIdentity.symm

theorem finiteStateVorticityGenerator_negativeOneMass_continuousAt
    (modes : Finset IntegerWavevector)
    (ν : ℝ)
    (trajectory : ℝ → ComplexVorticityHilbertState)
    (t : ℝ)
    (evolves :
      HasDerivAt trajectory
        (finiteStateVorticityGenerator
          modes ν (trajectory t)) t) :
    ContinuousAt
      (fun time =>
        finiteStateVorticityNegativeOneMass modes
          (finiteStateVorticityGenerator
            modes ν (trajectory time))) t := by
  unfold finiteStateVorticityNegativeOneMass
  exact continuousAt_finset_sum_negativeOne modes
    (fun output time =>
      if output = 0 then 0
      else
        ‖finiteStateVorticityGenerator
            modes ν (trajectory time) output‖ ^ 2 /
          integerWaveViscousMultiplier output) t
    (fun output _ => by
      by_cases outputZero : output = 0
      · simp only [if_pos outputZero]
        exact continuousAt_const
      · simp only [if_neg outputZero]
        have rowContinuous :
            ContinuousAt
              (fun time =>
                finiteStateVorticityGenerator
                  modes ν (trajectory time) output) t := by
          exact
            (((complexVorticityEvaluation_contDiff output).continuous.comp
              (finiteStateVorticityGenerator_contDiff
                modes ν).continuous).continuousAt.comp
                  evolves.continuousAt)
        exact (rowContinuous.norm.pow 2).div_const _)

private theorem norm_sub_sq_le_two
    (left right : ComplexCoordinateVector) :
    ‖left - right‖ ^ 2 ≤
      2 * (‖left‖ ^ 2 + ‖right‖ ^ 2) := by
  have normLe :
      ‖left - right‖ ≤ ‖left‖ + ‖right‖ :=
    norm_sub_le left right
  have squareLe :
      ‖left - right‖ ^ 2 ≤
        (‖left‖ + ‖right‖) ^ 2 :=
    (sq_le_sq₀
      (norm_nonneg _)
      (add_nonneg (norm_nonneg _) (norm_nonneg _))).mpr normLe
  nlinarith [sq_nonneg (‖left‖ - ‖right‖)]

private theorem viscousNegativeOneRow_le
    (ν : ℝ)
    (state : ComplexVorticityHilbertState)
    (wave : IntegerWavevector)
    (waveNe : wave ≠ 0) :
    ‖(ν * integerWaveViscousMultiplier wave) • state wave‖ ^ 2 /
          integerWaveViscousMultiplier wave ≤
      ν ^ 2 * integerWaveViscousMultiplier wave *
        complexCoordinateAmplitudeSq (state wave) := by
  let multiplier : ℝ := integerWaveViscousMultiplier wave
  let row : ComplexCoordinateVector := state wave
  change
    ‖(ν * multiplier) • row‖ ^ 2 / multiplier ≤
      ν ^ 2 * multiplier * complexCoordinateAmplitudeSq row
  have multiplierPos : 0 < multiplier := by
    dsimp [multiplier]
    unfold integerWaveViscousMultiplier
    exact
      mul_pos
        (sq_pos_of_pos (mul_pos (by norm_num) Real.pi_pos))
        (integerWaveNormSq_pos waveNe)
  have normSqLe :
      ‖row‖ ^ 2 ≤ complexCoordinateAmplitudeSq row :=
    complexCoordinateVector_norm_sq_le_amplitudeSq _
  have smulNorm :
      ‖(ν * multiplier) • row‖ =
        |ν * multiplier| * ‖row‖ := by
    exact norm_smul (ν * multiplier) row
  rw [smulNorm, abs_mul, abs_of_nonneg multiplierPos.le]
  simp only [mul_pow, sq_abs]
  calc
    (ν ^ 2 * multiplier ^ 2 * ‖row‖ ^ 2) / multiplier =
        ν ^ 2 * multiplier * ‖row‖ ^ 2 := by
      field_simp [ne_of_gt multiplierPos]
    _ ≤
        ν ^ 2 * multiplier *
          complexCoordinateAmplitudeSq row := by
      exact
        mul_le_mul_of_nonneg_left normSqLe
          (mul_nonneg (sq_nonneg _) multiplierPos.le)

/-! ## Pointwise actual-update bound -/

/-- The complete actual Galerkin update has cutoff-independent negative-one
mass.  The two terms on the right are precisely the nonlinear critical
carrier and the viscous gradient carrier already generated elsewhere. -/
theorem finiteStateVorticityGenerator_negativeOneMass_le
    (modes : Finset IntegerWavevector)
    (ν : ℝ)
    (state : ComplexVorticityHilbertState)
    (stateTransverse : FiniteStateTransverseOn modes state) :
    finiteStateVorticityNegativeOneMass modes
        (finiteStateVorticityGenerator modes ν state) ≤
      8 * finiteStateVelocityMajorant modes state ^ 2 *
          finiteStateVorticityCoefficientEnstrophy modes state +
        2 * ν ^ 2 * (2 * Real.pi) ^ 2 *
          finiteStateVorticityEnstrophyMass modes state := by
  have splitBound :
      finiteStateVorticityNegativeOneMass modes
          (finiteStateVorticityGenerator modes ν state) ≤
        2 *
            finiteStateVorticityNonlinearNegativeOneMass
              modes state +
          2 * ν ^ 2 * (2 * Real.pi) ^ 2 *
            finiteStateVorticityEnstrophyMass modes state := by
    unfold finiteStateVorticityNegativeOneMass
      finiteStateVorticityNonlinearNegativeOneMass
      finiteStateVorticityEnstrophyMass
    rw [Finset.mul_sum, Finset.mul_sum]
    rw [← Finset.sum_add_distrib]
    apply Finset.sum_le_sum
    intro output outputMem
    by_cases outputZero : output = 0
    · simp [outputZero, integerWaveNormSq]
    · rw [if_neg outputZero, if_neg outputZero]
      rw [finiteStateVorticityGenerator_apply,
        if_pos outputMem]
      have multiplierPos :
          0 < integerWaveViscousMultiplier output := by
        unfold integerWaveViscousMultiplier
        exact
          mul_pos
            (sq_pos_of_pos
              (mul_pos (by norm_num) Real.pi_pos))
            (integerWaveNormSq_pos outputZero)
      have rowSplit :=
        norm_sub_sq_le_two
          (finiteStateVorticityNonlinearCoefficientAt
            modes state output)
          ((ν * integerWaveViscousMultiplier output) •
            state output)
      have divided :
          ‖finiteStateVorticityNonlinearCoefficientAt
                modes state output -
              (ν * integerWaveViscousMultiplier output) •
                state output‖ ^ 2 /
                integerWaveViscousMultiplier output ≤
            (2 *
              (‖finiteStateVorticityNonlinearCoefficientAt
                  modes state output‖ ^ 2 +
                ‖(ν * integerWaveViscousMultiplier output) •
                    state output‖ ^ 2)) /
              integerWaveViscousMultiplier output :=
        div_le_div_of_nonneg_right rowSplit multiplierPos.le
      calc
        ‖finiteStateVorticityNonlinearCoefficientAt
              modes state output -
            (ν * integerWaveViscousMultiplier output) •
              state output‖ ^ 2 /
              integerWaveViscousMultiplier output ≤
            (2 *
              (‖finiteStateVorticityNonlinearCoefficientAt
                  modes state output‖ ^ 2 +
                ‖(ν * integerWaveViscousMultiplier output) •
                    state output‖ ^ 2)) /
              integerWaveViscousMultiplier output :=
          divided
        _ =
            2 *
                (‖finiteStateVorticityNonlinearCoefficientAt
                    modes state output‖ ^ 2 /
                  integerWaveViscousMultiplier output) +
              2 *
                (‖(ν * integerWaveViscousMultiplier output) •
                    state output‖ ^ 2 /
                  integerWaveViscousMultiplier output) := by
          field_simp [ne_of_gt multiplierPos]
        _ ≤
            2 *
                (‖finiteStateVorticityNonlinearCoefficientAt
                    modes state output‖ ^ 2 /
                  integerWaveViscousMultiplier output) +
              2 *
                (ν ^ 2 *
                  integerWaveViscousMultiplier output *
                  complexCoordinateAmplitudeSq
                    (state output)) := by
          have viscousRowBound :=
            viscousNegativeOneRow_le
              ν state output outputZero
          have twoViscousRowBound :
              2 *
                    (‖(ν * integerWaveViscousMultiplier output) •
                        state output‖ ^ 2 /
                      integerWaveViscousMultiplier output) ≤
                2 *
                    (ν ^ 2 *
                      integerWaveViscousMultiplier output *
                      complexCoordinateAmplitudeSq
                        (state output)) :=
            mul_le_mul_of_nonneg_left viscousRowBound
              (show (0 : ℝ) ≤ 2 by norm_num)
          exact add_le_add_right twoViscousRowBound _
        _ =
            2 *
                (‖finiteStateVorticityNonlinearCoefficientAt
                    modes state output‖ ^ 2 /
                  integerWaveViscousMultiplier output) +
              2 * ν ^ 2 * (2 * Real.pi) ^ 2 *
                (integerWaveNormSq output *
                  complexCoordinateAmplitudeSq
                    (state output)) := by
          unfold integerWaveViscousMultiplier
          ring
  have nonlinearBound :=
    finiteStateVorticityNonlinearNegativeOneMass_le
      modes state stateTransverse
  calc
    finiteStateVorticityNegativeOneMass modes
        (finiteStateVorticityGenerator modes ν state) ≤
      2 *
          finiteStateVorticityNonlinearNegativeOneMass
            modes state +
        2 * ν ^ 2 * (2 * Real.pi) ^ 2 *
          finiteStateVorticityEnstrophyMass modes state :=
      splitBound
    _ ≤
      2 *
          (4 * finiteStateVelocityMajorant modes state ^ 2 *
            finiteStateVorticityCoefficientEnstrophy
              modes state) +
        2 * ν ^ 2 * (2 * Real.pi) ^ 2 *
          finiteStateVorticityEnstrophyMass modes state :=
      add_le_add
        (mul_le_mul_of_nonneg_left nonlinearBound (by norm_num))
        le_rfl
    _ =
      8 * finiteStateVelocityMajorant modes state ^ 2 *
          finiteStateVorticityCoefficientEnstrophy modes state +
        2 * ν ^ 2 * (2 * Real.pi) ^ 2 *
          finiteStateVorticityEnstrophyMass modes state := by
      ring

/-! ## Source-generated cumulative budget -/

/-- Every source-generated finite scale path inside a strict critical
margin produces an actual Galerkin interval whose complete time derivative
has a cutoff-independent `L²_t H⁻¹` budget.

The right side depends only on the initial coefficient enstrophy, viscosity,
and the generated critical constants.  In particular it contains no mode
count, largest frequency, occupancy time, trajectory, terminal state, or
pre-supplied analytic budget. -/
theorem generatedIntegerShellReachable_drives_negativeOneTimeBudget
    {seed current : RawVorticityFourierSource}
    (arrival : GeneratedIntegerShellReachable seed current)
    (ν : Viscosity)
    (θ : ℝ)
    (θLtOne : θ < 1)
    (initialMargin :
      criticalEnstrophyLatticeConstant *
          finiteStateVorticityCoefficientEnstrophy
            (generatedSupport current)
            (generatedComplexVorticityState current
              (generatedSupport current)) ≤
        θ * ν.coeff ^ 2 * (2 * Real.pi) ^ 2) :
    ∃ (trajectory : ℝ → ComplexVorticityHilbertState)
        (occupancyTime : ℝ),
      0 < occupancyTime ∧
        trajectory 0 =
          generatedComplexVorticityState current
            (generatedSupport current) ∧
        (∀ t ∈ Icc (0 : ℝ) occupancyTime,
          HasDerivAt trajectory
              (finiteStateVorticityGenerator
                (generatedSupport current) ν.coeff (trajectory t)) t ∧
            (∀ wave,
              wave ∉ generatedSupport current →
                trajectory t wave = 0) ∧
            (∀ wave,
              complexWavevector wave ⬝ᵥ trajectory t wave = 0) ∧
            FiniteStateFourierReality (trajectory t)) ∧
        (∫ t in (0 : ℝ)..occupancyTime,
          finiteStateVorticityNegativeOneMass
            (generatedSupport current)
            (finiteStateVorticityGenerator
              (generatedSupport current) ν.coeff (trajectory t))) ≤
          (4 * criticalEnstrophyLatticeConstant *
                finiteStateVorticityCoefficientEnstrophy
                    (generatedSupport current) (trajectory 0) ^ 2 +
              ν.coeff ^ 2 * (2 * Real.pi) ^ 2 *
                finiteStateVorticityCoefficientEnstrophy
                  (generatedSupport current) (trajectory 0)) /
            criticalEnstrophyAbsorptionCoefficient θ ν := by
  obtain
      ⟨trajectory, occupancyTime, occupancyTimePos, initial,
        physicalProperties, pointwiseAbsorption,
        integratedAbsorption, pathAbsorption⟩ :=
    generatedIntegerShellReachable_drives_criticalAbsorption
      arrival ν θ θLtOne initialMargin
  let modes := generatedSupport current
  have intervalOrder : (0 : ℝ) ≤ occupancyTime :=
    occupancyTimePos.le
  have negClosed :
      ∀ wave, wave ∈ modes → waveNeg wave ∈ modes := by
    intro wave waveMem
    exact generatedSupport_waveNeg_mem current waveMem
  have evolves :
      ∀ t ∈ Icc (0 : ℝ) occupancyTime,
        HasDerivAt trajectory
          (finiteStateVorticityGenerator
            modes ν.coeff (trajectory t)) t := by
    intro t tMem
    exact (physicalProperties t tMem).1
  have reality :
      ∀ t ∈ Icc (0 : ℝ) occupancyTime,
        FiniteStateFourierReality (trajectory t) := by
    intro t tMem
    exact (physicalProperties t tMem).2.2.2
  have transverse :
      ∀ t ∈ Icc (0 : ℝ) occupancyTime,
        ∀ wave ∈ modes,
          complexWavevector wave ⬝ᵥ trajectory t wave = 0 := by
    intro t tMem wave waveMem
    exact (physicalProperties t tMem).2.2.1 wave
  have initialMarginActual :
      criticalEnstrophyLatticeConstant *
          finiteStateVorticityCoefficientEnstrophy
            modes (trajectory 0) ≤
        θ * ν.coeff ^ 2 * (2 * Real.pi) ^ 2 := by
    rw [initial]
    exact initialMargin
  obtain
      ⟨pointwiseConclusion, integratedEnstrophy,
        serrinAbsorption, serrinBound⟩ :=
    finiteStateVorticity_criticalSerrinBudget_on_Icc
      modes negClosed ν θ θLtOne trajectory 0 occupancyTime
      intervalOrder evolves reality transverse initialMarginActual
  have generatorMassContinuousOn :
      ContinuousOn
        (fun t =>
          finiteStateVorticityNegativeOneMass modes
            (finiteStateVorticityGenerator
              modes ν.coeff (trajectory t)))
        (Icc (0 : ℝ) occupancyTime) := by
    intro t tMem
    exact
      (finiteStateVorticityGenerator_negativeOneMass_continuousAt
        modes ν.coeff trajectory t (evolves t tMem)).continuousWithinAt
  have majorantContinuousOn :
      ContinuousOn
        (fun t =>
          finiteStateVelocityMajorant modes (trajectory t) ^ 2)
        (Icc (0 : ℝ) occupancyTime) := by
    intro t tMem
    exact
      ((finiteStateVelocityMajorant_continuousAt_of_hasDerivAt
        modes trajectory t
        (finiteStateVorticityGenerator
          modes ν.coeff (trajectory t))
        (evolves t tMem)).pow 2).continuousWithinAt
  have enstrophyMassContinuousOn :
      ContinuousOn
        (fun t =>
          finiteStateVorticityEnstrophyMass modes (trajectory t))
        (Icc (0 : ℝ) occupancyTime) := by
    intro t tMem
    exact
      (finiteStateVorticityEnstrophyMass_continuousAt_of_hasDerivAt
        modes trajectory t
        (finiteStateVorticityGenerator
          modes ν.coeff (trajectory t))
        (evolves t tMem)).continuousWithinAt
  have generatorMassIntegrable :
      IntervalIntegrable
        (fun t =>
          finiteStateVorticityNegativeOneMass modes
            (finiteStateVorticityGenerator
              modes ν.coeff (trajectory t)))
        volume 0 occupancyTime :=
    ContinuousOn.intervalIntegrable_of_Icc
      intervalOrder generatorMassContinuousOn
  have majorantIntegrable :
      IntervalIntegrable
        (fun t =>
          finiteStateVelocityMajorant modes (trajectory t) ^ 2)
        volume 0 occupancyTime :=
    ContinuousOn.intervalIntegrable_of_Icc
      intervalOrder majorantContinuousOn
  have enstrophyMassIntegrable :
      IntervalIntegrable
        (fun t =>
          finiteStateVorticityEnstrophyMass modes (trajectory t))
        volume 0 occupancyTime :=
    ContinuousOn.intervalIntegrable_of_Icc
      intervalOrder enstrophyMassContinuousOn
  have initialEnstrophyNonneg :
      0 ≤
        finiteStateVorticityCoefficientEnstrophy
          modes (trajectory 0) := by
    unfold finiteStateVorticityCoefficientEnstrophy
    exact Finset.sum_nonneg fun _ _ =>
      complexCoordinateAmplitudeSq_nonneg _
  have pointwiseGeneratorBound :
      ∀ t ∈ Icc (0 : ℝ) occupancyTime,
        finiteStateVorticityNegativeOneMass modes
            (finiteStateVorticityGenerator
              modes ν.coeff (trajectory t)) ≤
          8 *
                finiteStateVorticityCoefficientEnstrophy
                  modes (trajectory 0) *
                finiteStateVelocityMajorant modes (trajectory t) ^ 2 +
            2 * ν.coeff ^ 2 * (2 * Real.pi) ^ 2 *
              finiteStateVorticityEnstrophyMass
                modes (trajectory t) := by
    intro t tMem
    have currentEnstrophyLe :
        finiteStateVorticityCoefficientEnstrophy
              modes (trajectory t) ≤
          finiteStateVorticityCoefficientEnstrophy
            modes (trajectory 0) := by
      have halfLe := (pointwiseConclusion t tMem).1
      unfold finiteStateVorticityHalfEnstrophy at halfLe
      linarith
    have nonlinearLe :
        8 * finiteStateVelocityMajorant modes (trajectory t) ^ 2 *
              finiteStateVorticityCoefficientEnstrophy
                modes (trajectory t) ≤
          8 * finiteStateVelocityMajorant modes (trajectory t) ^ 2 *
              finiteStateVorticityCoefficientEnstrophy
                modes (trajectory 0) :=
      mul_le_mul_of_nonneg_left currentEnstrophyLe
        (mul_nonneg (by norm_num) (sq_nonneg _))
    calc
      finiteStateVorticityNegativeOneMass modes
          (finiteStateVorticityGenerator
            modes ν.coeff (trajectory t)) ≤
        8 * finiteStateVelocityMajorant modes (trajectory t) ^ 2 *
              finiteStateVorticityCoefficientEnstrophy
                modes (trajectory t) +
          2 * ν.coeff ^ 2 * (2 * Real.pi) ^ 2 *
            finiteStateVorticityEnstrophyMass
              modes (trajectory t) :=
        finiteStateVorticityGenerator_negativeOneMass_le
          modes ν.coeff (trajectory t)
          (fun wave waveMem =>
            transverse t tMem wave waveMem)
      _ ≤
        8 * finiteStateVelocityMajorant modes (trajectory t) ^ 2 *
              finiteStateVorticityCoefficientEnstrophy
                modes (trajectory 0) +
          2 * ν.coeff ^ 2 * (2 * Real.pi) ^ 2 *
            finiteStateVorticityEnstrophyMass
              modes (trajectory t) :=
        add_le_add_left nonlinearLe _
      _ =
        8 *
              finiteStateVorticityCoefficientEnstrophy
                modes (trajectory 0) *
              finiteStateVelocityMajorant modes (trajectory t) ^ 2 +
          2 * ν.coeff ^ 2 * (2 * Real.pi) ^ 2 *
            finiteStateVorticityEnstrophyMass
              modes (trajectory t) := by
        ring
  have rhsIntegrable :
      IntervalIntegrable
        (fun t =>
          8 *
                finiteStateVorticityCoefficientEnstrophy
                  modes (trajectory 0) *
                finiteStateVelocityMajorant modes (trajectory t) ^ 2 +
            2 * ν.coeff ^ 2 * (2 * Real.pi) ^ 2 *
              finiteStateVorticityEnstrophyMass
                modes (trajectory t))
        volume 0 occupancyTime :=
    (majorantIntegrable.const_mul
      (8 *
        finiteStateVorticityCoefficientEnstrophy
          modes (trajectory 0))).add
      (enstrophyMassIntegrable.const_mul
        (2 * ν.coeff ^ 2 * (2 * Real.pi) ^ 2))
  have integratedGeneratorBound :=
    intervalIntegral.integral_mono_on
      intervalOrder generatorMassIntegrable rhsIntegrable
      pointwiseGeneratorBound
  rw [intervalIntegral.integral_add
      (majorantIntegrable.const_mul
        (8 *
          finiteStateVorticityCoefficientEnstrophy
            modes (trajectory 0)))
      (enstrophyMassIntegrable.const_mul
        (2 * ν.coeff ^ 2 * (2 * Real.pi) ^ 2)),
    intervalIntegral.integral_const_mul,
    intervalIntegral.integral_const_mul] at integratedGeneratorBound
  have absorptionCoefficientPos :
      0 < criticalEnstrophyAbsorptionCoefficient θ ν :=
    criticalEnstrophyAbsorptionCoefficient_pos θ θLtOne ν
  have terminalHalfEnstrophyNonneg :
      0 ≤
        finiteStateVorticityHalfEnstrophy
          modes (trajectory occupancyTime) :=
    finiteStateVorticityHalfEnstrophy_nonneg modes _
  have integratedEnstrophyWithoutTerminal :
      criticalEnstrophyAbsorptionCoefficient θ ν *
            (∫ t in (0 : ℝ)..occupancyTime,
              finiteStateVorticityEnstrophyMass
                modes (trajectory t)) ≤
          finiteStateVorticityHalfEnstrophy
            modes (trajectory 0) :=
    integratedEnstrophy.trans
      (sub_le_self _ terminalHalfEnstrophyNonneg)
  have enstrophyMassIntegralBound :
      (∫ t in (0 : ℝ)..occupancyTime,
          finiteStateVorticityEnstrophyMass
            modes (trajectory t)) ≤
        finiteStateVorticityHalfEnstrophy
              modes (trajectory 0) /
          criticalEnstrophyAbsorptionCoefficient θ ν := by
    exact
      (le_div_iff₀ absorptionCoefficientPos).2 (by
        simpa [mul_comm] using integratedEnstrophyWithoutTerminal)
  have integratedUpper :
      (∫ t in (0 : ℝ)..occupancyTime,
          finiteStateVorticityNegativeOneMass modes
            (finiteStateVorticityGenerator
              modes ν.coeff (trajectory t))) ≤
        8 *
              finiteStateVorticityCoefficientEnstrophy
                modes (trajectory 0) *
              (criticalEnstrophyLatticeConstant *
                    finiteStateVorticityHalfEnstrophy
                      modes (trajectory 0) /
                  criticalEnstrophyAbsorptionCoefficient θ ν) +
          2 * ν.coeff ^ 2 * (2 * Real.pi) ^ 2 *
              (finiteStateVorticityHalfEnstrophy
                    modes (trajectory 0) /
                criticalEnstrophyAbsorptionCoefficient θ ν) := by
    exact integratedGeneratorBound.trans
      (add_le_add
        (mul_le_mul_of_nonneg_left serrinBound
          (mul_nonneg (by norm_num) initialEnstrophyNonneg))
        (mul_le_mul_of_nonneg_left enstrophyMassIntegralBound
          (mul_nonneg
            (mul_nonneg (by norm_num) (sq_nonneg _))
            (sq_nonneg _))))
  refine
    ⟨trajectory, occupancyTime, occupancyTimePos, initial,
      physicalProperties, ?_⟩
  change
    (∫ t in (0 : ℝ)..occupancyTime,
      finiteStateVorticityNegativeOneMass modes
        (finiteStateVorticityGenerator
          modes ν.coeff (trajectory t))) ≤
      (4 * criticalEnstrophyLatticeConstant *
            finiteStateVorticityCoefficientEnstrophy
                modes (trajectory 0) ^ 2 +
          ν.coeff ^ 2 * (2 * Real.pi) ^ 2 *
            finiteStateVorticityCoefficientEnstrophy
              modes (trajectory 0)) /
        criticalEnstrophyAbsorptionCoefficient θ ν
  calc
    (∫ t in (0 : ℝ)..occupancyTime,
      finiteStateVorticityNegativeOneMass modes
        (finiteStateVorticityGenerator
          modes ν.coeff (trajectory t))) ≤
        8 *
              finiteStateVorticityCoefficientEnstrophy
                modes (trajectory 0) *
              (criticalEnstrophyLatticeConstant *
                    finiteStateVorticityHalfEnstrophy
                      modes (trajectory 0) /
                  criticalEnstrophyAbsorptionCoefficient θ ν) +
          2 * ν.coeff ^ 2 * (2 * Real.pi) ^ 2 *
              (finiteStateVorticityHalfEnstrophy
                    modes (trajectory 0) /
                criticalEnstrophyAbsorptionCoefficient θ ν) :=
      integratedUpper
    _ =
      (4 * criticalEnstrophyLatticeConstant *
            finiteStateVorticityCoefficientEnstrophy
                modes (trajectory 0) ^ 2 +
          ν.coeff ^ 2 * (2 * Real.pi) ^ 2 *
            finiteStateVorticityCoefficientEnstrophy
              modes (trajectory 0)) /
        criticalEnstrophyAbsorptionCoefficient θ ν := by
      unfold finiteStateVorticityHalfEnstrophy
      field_simp [ne_of_gt absorptionCoefficientPos]
      ring

end

end ThreeDimensionalVorticityCoefficientFiniteGalerkinNegativeSobolevTimeBudget
end NavierStokes
end SaturationMonoid
