import H0mework.Versions.R9c73a630.Chemistry.LAlanineBandTaylor010.HullMatrixData
import H0mework.Versions.R9c73a630.Chemistry.LAlanineBandHighJet.MatrixCheck

set_option autoImplicit false
set_option maxHeartbeats 0
set_option maxRecDepth 16384
namespace SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.BasinRefinement.WholeBandGenerated.Sample021
open HighJet.MatrixChecking
checkHighJetMatrixRows 30 35
end SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.BasinRefinement.WholeBandGenerated.Sample021
