import H0mework.Arithmetic.Tempered.MuntzTheta

/-!
# Weak functional-equation pair generated by an arbitrary Schwartz test

The existing quarter-strip convergence pays local integrability of the
actual scale remainder.  Together with Poisson reciprocity and rapid theta
decay, this constructs a literal weight-one Mathlib weak FE-pair.
-/

set_option autoImplicit false
set_option maxHeartbeats 3000000

namespace SaturationMonoid
namespace ResponsibilityLifecycle
namespace LivingLawEvolution
namespace ConstructiveRoot
namespace NoIslandNoMagic
namespace CanonicalRiemann
namespace ClozelGeneralizedDual

open Complex FourierTransform MeasureTheory Set Filter Asymptotics
open ClozelEndpointSourceEffect
open scoped SchwartzMap RealInnerProductSpace Topology

noncomputable section

theorem positiveMellinExtension_quarter_eq_scaleRemainder_rpow
    (test : SchwartzMap ℝ ℂ) :
    positiveMellinExtension (coPoissonQuarterMellinMap test) =
      fun t : ℝ => coPoissonMuntzScaleRemainder test (t ^ (1 / 2 : ℝ)) := by
  funext t
  by_cases positive : 0 < t
  · simp only [positiveMellinExtension, LinearMap.coe_mk, AddHom.coe_mk,
      dif_pos positive, coPoissonQuarterMellinMap]
    rw [← Real.sqrt_eq_rpow]
    simp only [coPoissonMuntzScaleRemainder,
      dif_pos (Real.sqrt_pos.2 positive)]
  · have nonpositive : t ≤ 0 := le_of_not_gt positive
    rw [← Real.sqrt_eq_rpow, Real.sqrt_eq_zero_of_nonpos nonpositive]
    simp [positiveMellinExtension, positive,
      coPoissonMuntzScaleRemainder]

theorem coPoissonMuntzScaleRemainder_mellinConvergent_half
    (test : SchwartzMap ℝ ℂ) :
    MellinConvergent (coPoissonMuntzScaleRemainder test) (1 / 2 : ℂ) := by
  have quarter :=
    positiveMellinExtension_coPoissonQuarterMellinMap_mellinConvergent
      (1 / 4 : ℂ) (by norm_num) (by norm_num) test
  rw [positiveMellinExtension_quarter_eq_scaleRemainder_rpow] at quarter
  have source := (MellinConvergent.comp_rpow
    (f := coPoissonMuntzScaleRemainder test)
    (s := (1 / 4 : ℂ)) (a := (1 / 2 : ℝ)) (by norm_num)).mp quarter
  convert source using 1
  norm_num

theorem coPoissonMuntzScaleRemainder_locallyIntegrableOn
    (test : SchwartzMap ℝ ℂ) :
    LocallyIntegrableOn (coPoissonMuntzScaleRemainder test) (Ioi 0) := by
  have convergent := coPoissonMuntzScaleRemainder_mellinConvergent_half test
  have weightedLocal : LocallyIntegrableOn
      (fun t : ℝ => (t : ℂ) ^ ((1 / 2 : ℂ) - 1) •
        coPoissonMuntzScaleRemainder test t) (Ioi 0) := by
    exact convergent.locallyIntegrableOn
  have weightContinuous : ContinuousOn
      (fun t : ℝ => (t : ℂ) ^ (1 / 2 : ℂ)) (Ioi 0) := by
    intro t ht
    exact (continuousAt_ofReal_cpow_const _ _
      (Or.inr ht.ne')).continuousWithinAt
  have productLocal := LocallyIntegrableOn.continuousOn_smul
    isOpen_Ioi.isLocallyClosed weightedLocal weightContinuous
  apply productLocal.congr
  filter_upwards [ae_restrict_mem measurableSet_Ioi] with t positive
  simp only [smul_eq_mul]
  rw [← mul_assoc, ← Complex.cpow_add _ _
    (ofReal_ne_zero.mpr positive.ne')]
  norm_num

theorem coPoissonMuntzThetaNonzero_locallyIntegrableOn
    (test : SchwartzMap ℝ ℂ) :
    LocallyIntegrableOn (coPoissonMuntzThetaNonzero test) (Ioi 0) := by
  have correctionContinuous : ContinuousOn
      (fun scale : ℝ => (scale⁻¹ : ℝ) • ∫ x : ℝ, test x) (Ioi 0) := by
    intro scale positive
    exact (continuousAt_inv₀ positive.ne').continuousWithinAt.smul
      continuousWithinAt_const
  have correctionLocal : LocallyIntegrableOn
      (fun scale : ℝ => (scale⁻¹ : ℝ) • ∫ x : ℝ, test x)
      (Ioi 0) (volume : Measure ℝ) :=
    correctionContinuous.locallyIntegrableOn measurableSet_Ioi
  have sumLocal :=
    (coPoissonMuntzScaleRemainder_locallyIntegrableOn test).add correctionLocal
  apply sumLocal.congr
  filter_upwards [ae_restrict_mem measurableSet_Ioi] with scale positive
  change coPoissonMuntzScaleRemainder test scale +
      (scale⁻¹ : ℝ) • ∫ x : ℝ, test x =
    coPoissonMuntzThetaNonzero test scale
  rw [coPoissonMuntzScaleRemainder_eq test positive]
  abel

theorem coPoissonMuntzTheta_locallyIntegrableOn
    (test : SchwartzMap ℝ ℂ) :
    LocallyIntegrableOn (coPoissonMuntzTheta test) (Ioi 0) := by
  exact (coPoissonMuntzThetaNonzero_locallyIntegrableOn test).add
    (locallyIntegrableOn_const (test 0))

/-- The arbitrary-Schwartz theta pair.  Its functional equation is literal
Poisson summation; its local integrability is paid by the already installed
quarter-strip convergence of the actual co-Poisson remainder. -/
def coPoissonMuntzWeakFEPair
    (test : SchwartzMap ℝ ℂ) : WeakFEPair ℂ where
  f := coPoissonMuntzTheta test
  g := coPoissonMuntzTheta (FourierTransform.fourier test)
  k := 1
  ε := 1
  f₀ := test 0
  g₀ := FourierTransform.fourier test 0
  hf_int := coPoissonMuntzTheta_locallyIntegrableOn test
  hg_int := coPoissonMuntzTheta_locallyIntegrableOn
    (FourierTransform.fourier test)
  hk := one_pos
  hε := one_ne_zero
  h_feq := by
    intro scale positive
    simpa only [one_mul, one_smul, Real.rpow_one] using
      coPoissonMuntzTheta_fourier_equation test positive
  hf_top := by
    intro exponent
    simpa only [coPoissonMuntzTheta, add_sub_cancel_right] using
      coPoissonMuntzThetaNonzero_isBigO_atTop test exponent
  hg_top := by
    intro exponent
    simpa only [coPoissonMuntzTheta, add_sub_cancel_right] using
      coPoissonMuntzThetaNonzero_isBigO_atTop
        (FourierTransform.fourier test) exponent


end

end ClozelGeneralizedDual
end CanonicalRiemann
end NoIslandNoMagic
end ConstructiveRoot
end LivingLawEvolution
end ResponsibilityLifecycle
end SaturationMonoid
