import H0mework.Papers.PhysicsCommonSourceAeRelease
import Lean

set_option autoImplicit false
set_option maxRecDepth 200000
set_option maxHeartbeats 0
open Lean Elab Command
private def releaseName (value : String) : Name :=
  (value.splitOn ".").foldl Name.str .anonymous

private def completeRefs (info : ConstantInfo) : NameSet := Id.run do
  let mut refs := info.type.getUsedConstantsAsSet ++ info.getUsedConstantsAsSet
  if let some value := info.value? true then refs := refs ++ value.getUsedConstantsAsSet
  match info with
  | .defnInfo val => for name in val.all do refs := refs.insert name
  | .thmInfo val => for name in val.all do refs := refs.insert name
  | .opaqueInfo val => for name in val.all do refs := refs.insert name
  | .inductInfo val =>
      for name in val.all ++ val.ctors do refs := refs.insert name
  | .ctorInfo val => refs := refs.insert val.induct
  | .recInfo val =>
      for name in val.all do refs := refs.insert name
      for rule in val.rules do
        refs := refs.insert rule.ctor
        refs := refs ++ rule.rhs.getUsedConstantsAsSet
  | _ => pure ()
  return refs

private partial def recoveryClosure (env : Environment) (pending : List Name)
    (seen : NameSet := {}) : NameSet :=
  match pending with
  | [] => seen
  | name :: rest =>
      if seen.contains name then recoveryClosure env rest seen
      else
        let children := match env.checked.get.find? name with
          | some info => (completeRefs info).toArray.toList
          | none => []
        recoveryClosure env (children ++ rest) (seen.insert name)

run_cmd do
  let env ← getEnv
  let roots : List (String × String) := [("LowEnergy.PreparationVacuumCurrentHalfOperator.sourceCurrentPrice", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceHalfAxisCurrentOperator"),
    ("LowEnergy.PreparationVacuumCurrentHalfOperator.sourceCurrentPrice_nonnegative", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceHalfAxisCurrentOperator"),
    ("LowEnergy.PreparationVacuumCurrentHalfOperator.sourceCurrentTailPrice", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceHalfAxisCurrentOperator"),
    ("LowEnergy.PreparationVacuumCurrentHalfOperator.sourceCurrentTailPrice_zero", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceHalfAxisCurrentOperator"),
    ("LowEnergy.PreparationVacuumCurrentHalfOperator.sourceCurvatureJacobian_operatorNorm", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceHalfAxisFieldOperator"),
    ("LowEnergy.PreparationVacuumCurrentHalfOperator.sourceCurvatureOperatorFactor", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceHalfAxisFieldOperator"),
    ("LowEnergy.PreparationVacuumCurrentHalfOperator.sourceFieldJacobian_operatorNorm", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceHalfAxisFieldOperator"),
    ("LowEnergy.PreparationVacuumCurrentHalfOperator.sourceFieldOperatorFactor", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceHalfAxisFieldOperator"),
    ("LowEnergy.PreparationVacuumCurrentHalfOperator.sourceHalfCurrent", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceHalfAxisCurrentOperator"),
    ("LowEnergy.PreparationVacuumCurrentHalfOperator.sourceHalfCurrent_generated", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceHalfAxisCurrentOperator"),
    ("LowEnergy.PreparationVacuumCurrentHalfOperator.sourceHalfCurrent_price", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceHalfAxisCurrentOperator"),
    ("LowEnergy.PreparationVacuumCurrentHalfOperator.sourceHalfCurrent_reality", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceHalfAxisFieldOperator"),
    ("LowEnergy.PreparationVacuumCurrentHalfOperator.sourceHalfCurrent_tail", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceHalfAxisCurrentOperator"),
    ("LowEnergy.PreparationVacuumCurrentHalfOperator.sourceHalfCurvatureOperator", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceHalfAxisFieldOperator"),
    ("LowEnergy.PreparationVacuumCurrentHalfOperator.sourceHalfCurvatureOperator_generated", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceHalfAxisFieldOperator"),
    ("LowEnergy.PreparationVacuumCurrentHalfOperator.sourceHalfCurvatureOperator_mate", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceHalfAxisFieldOperator"),
    ("LowEnergy.PreparationVacuumCurrentHalfOperator.sourceHalfCurvatureOperator_price", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceHalfAxisFieldOperator"),
    ("LowEnergy.PreparationVacuumCurrentHalfOperator.sourceHalfCurvatureOperator_tail", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceHalfAxisFieldOperator"),
    ("LowEnergy.PreparationVacuumCurrentHalfOperator.sourceHalfFieldOperator", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceHalfAxisFieldOperator"),
    ("LowEnergy.PreparationVacuumCurrentHalfOperator.sourceHalfFieldOperator_generated", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceHalfAxisFieldOperator"),
    ("LowEnergy.PreparationVacuumCurrentHalfOperator.sourceHalfFieldOperator_native", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceHalfAxisFieldOperator"),
    ("LowEnergy.PreparationVacuumCurrentHalfOperator.sourceHalfFieldOperator_price", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceHalfAxisFieldOperator"),
    ("LowEnergy.PreparationVacuumCurrentHalfOperator.sourceHalfFieldOperator_tail", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceHalfAxisFieldOperator"),
    ("LowEnergy.PreparationVacuumCurrentHalfOperator.sourceWeightedCurrent", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceHalfAxisCurrentOperator"),
    ("LowEnergy.PreparationVacuumCurrentHalfOperator.sourceWeightedCurrent_continuous", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceHalfAxisCurrentOperator"),
    ("LowEnergy.PreparationVacuumCurrentHalfOperator.sourceWeightedCurrent_generated", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceHalfAxisCurrentOperator"),
    ("LowEnergy.PreparationVacuumCurrentHalfOperator.sourceWeightedCurrent_integrable", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceHalfAxisCurrentOperator"),
    ("LowEnergy.PreparationVacuumCurrentHalfOperator.sourceWeightedCurrent_price", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceHalfAxisCurrentOperator"),
    ("LowEnergy.PreparationVacuumCurrentHalfOperator.sourceWindowJacobian_integral", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceHalfAxisCurrentOperator"),
    ("LowEnergy.PreparationVacuumCurrentHalfOperator.sourceWindowJacobian_operatorNorm", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceHalfAxisCurrentOperator"),
    ("LowEnergy.PreparationVacuumCurrentNativeLaplaceBridge.sourceNativeBoundary", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceNativeSignalLaplaceReturn"),
    ("LowEnergy.PreparationVacuumCurrentNativeLaplaceBridge.sourceNativeBoundary_history", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceNativeSignalLaplaceReturn"),
    ("LowEnergy.PreparationVacuumCurrentNativeLaplaceBridge.sourceNativeBoundary_initial", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceNativeSignalLaplaceReturn"),
    ("LowEnergy.PreparationVacuumCurrentNativeLaplaceBridge.sourceNativeEulerWindow", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceNativeSignalLaplaceReturn"),
    ("LowEnergy.PreparationVacuumCurrentNativeLaplaceBridge.sourceNativeEulerWindow_actual", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceNativeSignalLaplaceReturn"),
    ("LowEnergy.PreparationVacuumCurrentNativeLaplaceBridge.sourceNativePlaneWindow", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceNativeSignalLaplaceReturn"),
    ("LowEnergy.PreparationVacuumCurrentNativeLaplaceBridge.sourceNativePlaneWindow_ordinary", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceNativeSignalLaplaceReturn"),
    ("LowEnergy.PreparationVacuumCurrentNativeLaplaceBridge.sourceNativeSignal_weighted", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceNativeSignalLaplaceReturn"),
    ("LowEnergy.PreparationVacuumCurrentNativeLaplaceBridge.sourceNativeTimeFirst", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceNativeSignalLaplaceReturn"),
    ("LowEnergy.PreparationVacuumCurrentNativeLaplaceBridge.sourceNativeTimeFirst_actual", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceNativeSignalLaplaceReturn"),
    ("LowEnergy.PreparationVacuumCurrentNativeLaplaceBridge.sourceNativeTimeValue", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceNativeSignalLaplaceReturn"),
    ("LowEnergy.PreparationVacuumCurrentNativeLaplaceBridge.sourceNativeTimeValue_actual", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceNativeSignalLaplaceReturn"),
    ("LowEnergy.PreparationVacuumCurrentNativeLaplaceBridge.sourcePlaneHalfScalar", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceNativeSignalLaplaceReturn"),
    ("LowEnergy.PreparationVacuumCurrentNativeLaplaceBridge.sourcePlaneHalfScalar_actual", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceNativeSignalLaplaceReturn"),
    ("LowEnergy.PreparationVacuumCurrentNativeLaplaceBridge.sourcePlaneWindowScalar", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceNativeSignalLaplaceReturn"),
    ("LowEnergy.PreparationVacuumCurrentNativeLaplaceBridge.sourcePlaneWindowScalar_derivative", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceNativeSignalLaplaceReturn"),
    ("LowEnergy.PreparationVacuumCurrentNativeLaplaceBridge.sourcePlaneWindowScalar_limit", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceNativeSignalLaplaceReturn"),
    ("LowEnergy.PreparationVacuumCurrentNativeLaplaceBridge.sourcePreparedEulerWindow", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceNativeSignalLaplaceReturn"),
    ("LowEnergy.PreparationVacuumCurrentNativeLaplaceBridge.sourcePreparedEulerWindow_generated", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceNativeSignalLaplaceReturn"),
    ("LowEnergy.PreparationVacuumCurrentNativeLaplaceBridge.sourcePreparedEulerWindow_native", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceNativeSignalLaplaceReturn"),
    ("LowEnergy.PreparationVacuumCurrentSignalOperator.SignalAmplitude", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceOrderedSignalOperator"),
    ("LowEnergy.PreparationVacuumCurrentSignalOperator.SourceOp", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceOrderedSignalOperator"),
    ("LowEnergy.PreparationVacuumCurrentSignalOperator.sourceCausalCoefficient", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceSignalCausalResponse"),
    ("LowEnergy.PreparationVacuumCurrentSignalOperator.sourceCausalCurvatureOperator", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceSignalCausalResponse"),
    ("LowEnergy.PreparationVacuumCurrentSignalOperator.sourceCausalCurvatureOperator_actual", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceSignalCausalResponse"),
    ("LowEnergy.PreparationVacuumCurrentSignalOperator.sourceCausalCurvatureOperator_native", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceSignalCausalResponse"),
    ("LowEnergy.PreparationVacuumCurrentSignalOperator.sourceCausalEta", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceSignalCausalResponse"),
    ("LowEnergy.PreparationVacuumCurrentSignalOperator.sourceCausalFieldOperator", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceSignalCausalResponse"),
    ("LowEnergy.PreparationVacuumCurrentSignalOperator.sourceCausalFieldOperator_native", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceSignalCausalResponse"),
    ("LowEnergy.PreparationVacuumCurrentSignalOperator.sourceCausalHalfOperator", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceSignalCausalResponse"),
    ("LowEnergy.PreparationVacuumCurrentSignalOperator.sourceCausalHalfOperator_tail", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceSignalCausalResponse"),
    ("LowEnergy.PreparationVacuumCurrentSignalOperator.sourceCausalTailPrice", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceSignalCausalResponse"),
    ("LowEnergy.PreparationVacuumCurrentSignalOperator.sourceCausalWindow", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceSignalCausalResponse"),
    ("LowEnergy.PreparationVacuumCurrentSignalOperator.sourceCausalWindow_actual", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceSignalCausalResponse"),
    ("LowEnergy.PreparationVacuumCurrentSignalOperator.sourceCausalWindow_cosources", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceSignalCausalResponse"),
    ("LowEnergy.PreparationVacuumCurrentSignalOperator.sourceCausalWindow_noether", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceSignalCausalResponse"),
    ("LowEnergy.PreparationVacuumCurrentSignalOperator.sourceCausalWindow_operatorNorm", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceSignalCausalResponse"),
    ("LowEnergy.PreparationVacuumCurrentSignalOperator.sourceClockGrowth", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceSignalOperatorPrice"),
    ("LowEnergy.PreparationVacuumCurrentSignalOperator.sourceClockGrowth_nonnegative", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceSignalOperatorPrice"),
    ("LowEnergy.PreparationVacuumCurrentSignalOperator.sourceContactMap", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceSignalOperatorPrice"),
    ("LowEnergy.PreparationVacuumCurrentSignalOperator.sourceCurrentCoefficient_nonnegative", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceSignalOperatorPrice"),
    ("LowEnergy.PreparationVacuumCurrentSignalOperator.sourceCurrentConstantCoefficient", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceSignalOperatorPrice"),
    ("LowEnergy.PreparationVacuumCurrentSignalOperator.sourceCurrentLinearCoefficient", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceSignalOperatorPrice"),
    ("LowEnergy.PreparationVacuumCurrentSignalOperator.sourceCurrentOperator", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceOrderedSignalOperator"),
    ("LowEnergy.PreparationVacuumCurrentSignalOperator.sourceCurrentOperator_actual", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceOrderedSignalOperator"),
    ("LowEnergy.PreparationVacuumCurrentSignalOperator.sourceCurrentOperator_continuous", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceSignalOperatorPrice"),
    ("LowEnergy.PreparationVacuumCurrentSignalOperator.sourceCurrentOperator_price", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceSignalOperatorPrice"),
    ("LowEnergy.PreparationVacuumCurrentSignalOperator.sourceDualCoefficient", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceSignalOperatorPrice"),
    ("LowEnergy.PreparationVacuumCurrentSignalOperator.sourceHistoryConstantCoefficient", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceSignalOperatorPrice"),
    ("LowEnergy.PreparationVacuumCurrentSignalOperator.sourceHistoryInput", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceOrderedSignalOperator"),
    ("LowEnergy.PreparationVacuumCurrentSignalOperator.sourceHistoryInput_actual", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceOrderedSignalOperator"),
    ("LowEnergy.PreparationVacuumCurrentSignalOperator.sourceHistoryInput_continuous", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceOrderedSignalOperator"),
    ("LowEnergy.PreparationVacuumCurrentSignalOperator.sourceHistoryInput_price", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceSignalOperatorPrice"),
    ("LowEnergy.PreparationVacuumCurrentSignalOperator.sourceHistoryLinearCoefficient", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceSignalOperatorPrice"),
    ("LowEnergy.PreparationVacuumCurrentSignalOperator.sourceHistoryOperator", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceOrderedSignalOperator"),
    ("LowEnergy.PreparationVacuumCurrentSignalOperator.sourceHistoryOperator_actual", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceOrderedSignalOperator"),
    ("LowEnergy.PreparationVacuumCurrentSignalOperator.sourceHistoryOperator_price", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceSignalOperatorPrice"),
    ("LowEnergy.PreparationVacuumCurrentSignalOperator.sourceIndependentDualOperator", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceOrderedSignalOperator"),
    ("LowEnergy.PreparationVacuumCurrentSignalOperator.sourceIndependentDualOperator_actual", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceOrderedSignalOperator"),
    ("LowEnergy.PreparationVacuumCurrentSignalOperator.sourceIndependentDualOperator_price", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceSignalOperatorPrice"),
    ("LowEnergy.PreparationVacuumCurrentSignalOperator.sourceLeftDrive", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceOrderedSignalOperator"),
    ("LowEnergy.PreparationVacuumCurrentSignalOperator.sourceLeftDrive_continuous", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceOrderedSignalOperator"),
    ("LowEnergy.PreparationVacuumCurrentSignalOperator.sourceLeftDrive_price", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceSignalOperatorPrice"),
    ("LowEnergy.PreparationVacuumCurrentSignalOperator.sourceMaterialMap", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceSignalOperatorPrice"),
    ("LowEnergy.PreparationVacuumCurrentSignalOperator.sourceMiddleCoefficient", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceSignalOperatorPrice"),
    ("LowEnergy.PreparationVacuumCurrentSignalOperator.sourceMiddleOperator", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceOrderedSignalOperator"),
    ("LowEnergy.PreparationVacuumCurrentSignalOperator.sourceMiddleOperator_price", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceSignalOperatorPrice"),
    ("LowEnergy.PreparationVacuumCurrentSignalOperator.sourceMiddleOperator_source_maps", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceSignalOperatorPrice"),
    ("LowEnergy.PreparationVacuumCurrentSignalOperator.sourcePrimalCoefficient", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceSignalOperatorPrice"),
    ("LowEnergy.PreparationVacuumCurrentSignalOperator.sourcePrimalOperator", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceOrderedSignalOperator"),
    ("LowEnergy.PreparationVacuumCurrentSignalOperator.sourcePrimalOperator_actual", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceOrderedSignalOperator"),
    ("LowEnergy.PreparationVacuumCurrentSignalOperator.sourcePrimalOperator_price", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceSignalOperatorPrice"),
    ("LowEnergy.PreparationVacuumCurrentSignalOperator.sourceQuadratureCurrent", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceSignalCausalResponse"),
    ("LowEnergy.PreparationVacuumCurrentSignalOperator.sourceQuadratureCurrent_actual", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceSignalCausalResponse"),
    ("LowEnergy.PreparationVacuumCurrentSignalOperator.sourceQuadratureCurrent_continuous", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceSignalCausalResponse"),
    ("LowEnergy.PreparationVacuumCurrentSignalOperator.sourceQuadratureCurrent_price", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceSignalCausalResponse"),
    ("LowEnergy.PreparationVacuumCurrentSignalOperator.sourceQuadratureOperator", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceSignalCausalResponse"),
    ("LowEnergy.PreparationVacuumCurrentSignalOperator.sourceReadGap", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceSignalCausalResponse"),
    ("LowEnergy.PreparationVacuumCurrentSignalOperator.sourceRightDrive", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceOrderedSignalOperator"),
    ("LowEnergy.PreparationVacuumCurrentSignalOperator.sourceRightDrive_continuous", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceOrderedSignalOperator"),
    ("LowEnergy.PreparationVacuumCurrentSignalOperator.sourceRightDrive_price", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceSignalOperatorPrice"),
    ("LowEnergy.PreparationVacuumCurrentSignalOperator.sourceWeightedQuadrature", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceSignalCausalResponse"),
    ("LowEnergy.PreparationVacuumCurrentSignalOperator.sourceWeightedQuadrature_continuous", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceSignalCausalResponse"),
    ("LowEnergy.PreparationVacuumCurrentSignalOperator.sourceWeightedQuadrature_integrable", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceSignalCausalResponse"),
    ("LowEnergy.PreparationVacuumCurrentSignalOperator.sourceWeightedQuadrature_price", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceSignalCausalResponse"),
    ("LowEnergy.PreparationVacuumCurrentSignalRealization.sourcePhase", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceNativeRealFourierSignal"),
    ("LowEnergy.PreparationVacuumCurrentSignalRealization.sourcePhase_apply", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceNativeRealFourierSignal"),
    ("LowEnergy.PreparationVacuumCurrentSignalRealization.sourcePhase_coordinate", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceNativeRealFourierSignal"),
    ("LowEnergy.PreparationVacuumCurrentSignalRealization.sourcePreparedQuadrature_generated", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourcePreparedSignalEuler"),
    ("LowEnergy.PreparationVacuumCurrentSignalRealization.sourceRawSignalEuler_generated", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourcePreparedSignalEuler"),
    ("LowEnergy.PreparationVacuumCurrentSignalRealization.sourceRealEuler_Fourier", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceNativeRealFourierSignal"),
    ("LowEnergy.PreparationVacuumCurrentSignalRealization.sourceRealFirstJet", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceNativeRealFourierSignal"),
    ("LowEnergy.PreparationVacuumCurrentSignalRealization.sourceRealJet_coefficient", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceNativeRealFourierSignal"),
    ("LowEnergy.PreparationVacuumCurrentSignalRealization.sourceRealSecondJet", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceNativeRealFourierSignal"),
    ("LowEnergy.PreparationVacuumCurrentSignalRealization.sourceRealSignal", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceNativeRealFourierSignal"),
    ("LowEnergy.PreparationVacuumCurrentSignalRealization.sourceRealSignal_firstJet", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceNativeRealFourierSignal"),
    ("LowEnergy.PreparationVacuumCurrentSignalRealization.sourceRealSignal_originalDensity", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceNativeRealFourierSignal"),
    ("LowEnergy.PreparationVacuumCurrentSignalRealization.sourceRealSignal_originalEuler", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceNativeRealFourierSignal"),
    ("LowEnergy.PreparationVacuumCurrentSignalRealization.sourceRealSignal_secondJet", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceNativeRealFourierSignal"),
    ("LowEnergy.PreparationVacuumCurrentSignalRealization.sourceRealSignal_smooth", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceNativeRealFourierSignal"),
    ("LowEnergy.PreparationVacuumCurrentSignalRealization.sourceSignalAmplitude", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceNativeRealFourierSignal"),
    ("LowEnergy.PreparationVacuumCurrentSignalRealization.sourceSignalCurrent", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourcePreparedSignalEuler"),
    ("LowEnergy.PreparationVacuumCurrentSignalRealization.sourceSignalCurrent_actual", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourcePreparedSignalEuler"),
    ("LowEnergy.PreparationVacuumCurrentSignalRealization.sourceSignalDuration", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourcePreparedSignalEuler"),
    ("LowEnergy.PreparationVacuumCurrentSignalRealization.sourceSignalDuration_positive", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourcePreparedSignalEuler"),
    ("LowEnergy.PreparationVacuumCurrentSignalRealization.sourceSignalField", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourcePreparedSignalEuler"),
    ("LowEnergy.PreparationVacuumCurrentSignalRealization.sourceSignalField_native", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourcePreparedSignalEuler"),
    ("LowEnergy.PreparationVacuumCurrentSignalRealization.sourceSignalField_native36", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourcePreparedSignalEuler"),
    ("LowEnergy.PreparationVacuumCurrentSignalRealization.sourceSignalForcing", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourcePreparedSignalEuler"),
    ("LowEnergy.PreparationVacuumCurrentSignalRealization.sourceSignalForcing_actual", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourcePreparedSignalEuler"),
    ("LowEnergy.PreparationVacuumCurrentSignalRealization.sourceSignalForcing_cosources", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourcePreparedSignalEuler"),
    ("LowEnergy.PreparationVacuumCurrentSignalRealization.sourceSignalOrdinaryRemainder_generated", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourcePreparedSignalEuler"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.Heavy.flag", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginInverse"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.Heavy.inverse", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginInverse"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.Heavy.inverseTerms", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginInverse"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.Heavy.inverse_left", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginInverse"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.Heavy.inverse_left_support", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginInverse"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.Heavy.inverse_right_support", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginInverse"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.Heavy.originTerms", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginInverse"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.Heavy.origin_generated", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginInverse"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.Heavy.projection", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginInverse"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.activeKernel_right", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginCurrent"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.active_null", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginCurrent"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.active_square", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginCurrent"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.actualCosource", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginCurrent"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.actualCurrent", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginCurrent"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.actualField", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginCurrent"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.actualForcing", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginCurrent"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.actualMomentum", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginCurrent"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.actualNativeField", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginCurrent"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.actual_complement_return", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginCurrent"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.actual_current_ward", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginCurrent"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.actual_effective_dynamics", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginCurrent"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.actual_effective_response_price", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginCurrent"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.actual_forcing_twoSectors", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginCurrent"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.actual_inside", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginCurrent"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.actual_native_reconstruction", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginCurrent"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.actual_origin_kernel_read", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginCurrent"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.actual_source", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginCurrent"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.actual_whole_native", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginCurrent"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.actual_whole_reconstruction", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginCurrent"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.blockComplement", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginCurrent"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.blockComplement_generated", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginCurrent"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.blockComplement_supported", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginCurrent"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.blockCoordinates", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginCurrent"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.complementGreen", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.complementGreen_delta", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.complementGreen_delta_price", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.complementGreen_left", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.complementGreen_left_support", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.complementGreen_origin", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.complementGreen_price", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.complementGreen_right", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.complementGreen_right_support", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.complementKernel", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginInverse"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.complementKernel_continuous", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.complementKernel_left", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.complementKernel_right", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.complementOrigin", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.complementRegular", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.complementRegular_near_origin", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.complement_delta_price", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.complement_full_inverse_price", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.complement_response", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.componentFlag", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginInverse"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.componentInverse", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginInverse"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.componentInverseTerms", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginInverse"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.componentOrigin", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginInverse"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.componentOriginTerms", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginInverse"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.componentProjection", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginInverse"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.component_inverse_cross", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginInverse"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.component_inverse_left", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginInverse"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.component_inverse_left_support", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginInverse"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.component_inverse_right_support", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginInverse"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.controlledPoint", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.dualInjection", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.dualInjectionTerms", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.effectiveErrorBudget", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.effectiveErrorBudget_nonneg", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.effectiveFrame", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.effectiveKernel", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.effectiveKernel_complete_return", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.effectiveKernel_frame", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.effectiveKernel_generated", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.effectiveKernel_leading_price", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.effectiveKernel_origin", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.effectiveKernel_source_tensor", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.effectiveReader", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.effectiveReader_complement", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.effective_actual_equation", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginCurrent"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.effective_field_reconstruction", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginCurrent"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.frozenTensor", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.frozenTensor_generated", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.fullComplementFlag", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginInverse"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.fullComplementProjection", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginInverse"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.fullComplementProjection_price", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.fullHigherTerms", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.fullInverse", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginInverse"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.fullInverseResidualTerms", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.fullInverseResidual_generated", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.fullInverseTerms", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.fullInverse_generated", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.fullInverse_left", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginInverse"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.fullInverse_left_support", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginInverse"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.fullInverse_price", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.fullInverse_right_support", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginInverse"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.fullKernelFrame", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.fullKernelTerms", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.fullKernel_coordinates", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginCurrent"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.fullKernel_generated", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.fullKernel_independent", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginCurrent"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.fullKernel_origin", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.fullKernel_price", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.fullLeadingTerms", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.fullNativeOrigin", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginCurrent"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.fullNativeOriginTerms", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginCurrent"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.fullNativeOrigin_generated", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginCurrent"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.fullOrigin", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginInverse"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.fullOriginTerms", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginInverse"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.fullOrigin_generated", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginInverse"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.fullOrigin_sum", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginInverse"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.fullProjection_piece", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginInverse"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.fullProjection_square", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginInverse"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.fullProjection_sum", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginInverse"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.fullResidualTerms", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.fullResidual_generated", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.higherBudget", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.higherBudget_nonneg", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.higherPrice_exact", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.higherTensor", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.higherTensor_price", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.higher_degrees", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.inverseBudget", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.inverseBudget_ge_one", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.inversePrice_exact", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.kernelBudget", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.kernelBudget_nonneg", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.kernelPrice_exact", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.leadingTensor", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.leading_degrees", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.modeSelector", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginCurrent"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.nativeEffectiveFrame", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.originInverse", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginInverse"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.originInverse_left", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginInverse"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.originInverse_price", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.originInverse_right", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginInverse"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.origin_determinant", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginInverse"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.origin_kernel_complete", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginCurrent"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.piece_fullProjection", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginInverse"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.selectorTerms", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginCurrent"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.sourceRadius", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.sourceRadius_exact", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.sourceRadius_le_one", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.sourceRadius_pos", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.sourceRadius_regular", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur"),
    ("LowEnergy.PreparationVacuumFullOriginResponse.source_neumann_price", "H0mework.Versions.AE.Physics.LowEnergy.AlphaSource.CanonicalPreparationSourceFullOriginSchur")]
  for (decl, owner) in roots do
    let name := releaseName decl
    unless (env.checked.get.find? name).isSome do throwError "MISSING_DECLARATION {name}"
    let some index := env.getModuleIdxFor? name | throwError "MISSING_DECLARATION_MODULE {name}"
    unless env.header.moduleNames[index]! == releaseName owner do
      throwError "WRONG_DECLARATION_MODULE {name} expected={owner} actual={env.header.moduleNames[index]!}"
  let closure := recoveryClosure env (roots.map fun item => releaseName item.1)
  let allowed := #[``propext, ``Classical.choice, ``Quot.sound]
  let mut axioms : NameSet := {}
  let mut edges := 0
  for name in closure.toArray do
    let some info := env.checked.get.find? name | throwError "UNCHECKED_CONSTANT {name}"
    if info.isUnsafe || info.isPartial then throwError "UNSAFE_PARTIAL {name}"
    edges := edges + (completeRefs info).size
    match info with
    | .axiomInfo _ =>
        unless allowed.contains name do throwError "UNAPPROVED_AXIOM {name}"
        axioms := axioms.insert name
    | .defnInfo _ | .thmInfo _ | .opaqueInfo _ =>
        unless (info.value? true).isSome do throwError "MISSING_CONSTANT_VALUE {name}"
    | _ => pure ()
  let report := Json.mkObj [
    ("token", toJson "c08a64cb242acf1fad528fefcf1136a61c9388a9920cbd20a014a89d8238a520"), ("roots", toJson roots.length),
    ("constants", toJson closure.size), ("edges", toJson edges),
    ("axioms", toJson (axioms.toArray.toList.map Name.toString)),
    ("unsafe", toJson (0 : Nat)), ("partial", toJson (0 : Nat)),
    ("full_metadata", toJson true)]
  logInfo m!"FIRST_RELEASE_TRUST {report.compress}"
