import H0mework.Chemistry.LAlanineBandCall010.TubeMatrixData
import H0mework.Chemistry.LAlanineWholeCell.MatrixCertificate

namespace SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.BasinRefinement.TrueTubeWholeMatrix.C10

checkWholeCellMatrixRow 2
checkWholeCellMatrixRow 3

end SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.BasinRefinement.TrueTubeWholeMatrix.C10
