import H0mework.Chemistry.LAlanineBandTaylor060.CenterGroups
import H0mework.Chemistry.LAlanineBandTaylor060.CenterOrbitals
import H0mework.Chemistry.LAlanineBandTaylor060.CenterMatrixPart0
import H0mework.Chemistry.LAlanineBandTaylor060.CenterMatrixPart1
import H0mework.Chemistry.LAlanineBandTaylor060.CenterMatrixPart2
import H0mework.Chemistry.LAlanineBandTaylor060.CenterMatrixPart3
import H0mework.Chemistry.LAlanineBandTaylor060.CenterDensityCheck
import H0mework.Chemistry.LAlanineBandHighJet.Assembly

set_option autoImplicit false
set_option maxHeartbeats 0
set_option maxRecDepth 16384
namespace SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.BasinRefinement.WholeBandGenerated.Sample120
open HighJet.MatrixChecking HighJet.Assembly
assembleHighJetMatrix
assembleHighJetMaterial 0
end SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.BasinRefinement.WholeBandGenerated.Sample120
