import H0mework.Versions.Y.Arithmetic.MellinBoundary.PositiveMellinQuarterExtension
import H0mework.Versions.Y.Arithmetic.MellinBoundary.PositiveMellinQuarterBoundedEigenNoGoBase

/-!
# Coverage-complete deletion of the whole-quarter-`L²` extension candidate

The actual compact shell generated by the low correction has a nonzero
Mellin readback whenever `Re z > 0`.  Its scale-three translation orbit is
orthonormal after normalization.  Therefore an everywhere-defined continuous
quarter-`L²` Mellin extension satisfying the actual translation eigenlaw would
both read the shell nontrivially and vanish on it by Bessel/Riesz.  The
contradiction is unconditional on the character modulus: that modulus is
derived from the extension's nonzero readback and the existing isometric
translation boundary.

This is a representation-level diagnostic, not a replacement producer for
the A1c radial-zero mouth.  It closes the whole-`L²` branch and leaves the
proper source-owned Mellin domain as the live analytic representation.
-/

set_option autoImplicit false
set_option maxHeartbeats 3000000

namespace SaturationMonoid
namespace ResponsibilityLifecycle
namespace LivingLawEvolution
namespace ConstructiveRoot
namespace NoIslandNoMagic
namespace CanonicalRiemann

open Complex MeasureTheory Set
open scoped ENNReal

noncomputable section

theorem positiveMellinQuarterNoGoShellLp_extension_readback
    (z : ℂ) (hz : 0 < z.re)
    (functional : PositiveMellinQuarterEnergy →L[ℂ] ℂ)
    (extension : IsQuarterMellinExtension z functional) :
    functional positiveMellinQuarterNoGoShellLp =
      positiveMellinFunctional z
        (positiveMellinQuarterNoGoShellElement z hz) := by
  have h := extension positiveMellinQuarterNoGoShellL2
    (positiveMellinQuarterNoGoShellElement z hz).2
  change functional (positiveMellinQuarterLpValue
    positiveMellinQuarterNoGoShellL2) = _
  rw [h]
  rfl

theorem positiveMellinQuarterNoGoShellLp_ne_zero_of_extension
    (z : ℂ) (hz : 0 < z.re)
    (functional : PositiveMellinQuarterEnergy →L[ℂ] ℂ)
    (extension : IsQuarterMellinExtension z functional) :
    positiveMellinQuarterNoGoShellLp ≠ 0 := by
  intro baseZero
  have readback := positiveMellinQuarterNoGoShellLp_extension_readback
    z hz functional extension
  rw [baseZero, map_zero] at readback
  exact (positiveMellinQuarterNoGoShellElement_value_ne_zero z hz)
    readback.symm

theorem positiveMellinQuarterNoGoShellLp_functional_ne_zero_of_extension
    (z : ℂ) (hz : 0 < z.re)
    (functional : PositiveMellinQuarterEnergy →L[ℂ] ℂ)
    (extension : IsQuarterMellinExtension z functional) :
    functional positiveMellinQuarterNoGoShellLp ≠ 0 := by
  rw [positiveMellinQuarterNoGoShellLp_extension_readback z hz
    functional extension]
  exact positiveMellinQuarterNoGoShellElement_value_ne_zero z hz

/-- No continuous functional on the complete quarter `L²` carrier can at
once be the source Mellin extension on its convergent domain and obey the
actual scale-three translation character law. -/
theorem no_wholeL2_mellin_extension_at_qRich_scale_zero
    (z : ℂ) (hz : 0 < z.re)
    (functional : PositiveMellinQuarterEnergy →L[ℂ] ℂ)
    (extension : IsQuarterMellinExtension z functional)
    (character : ℂ)
    (eigenlaw : ∀ value,
      functional (positiveMellinQuarterEnergyTranslation
        (Real.log positiveMellinQuarterNoGoScale) value) =
        character * functional value) :
    False := by
  have functionalNe : functional ≠ 0 :=
    isQuarterMellinExtension_nonzero hz functional extension
  have characterNorm :=
    positiveMellinQuarterEnergy_character_norm_eq_one
      (Real.log positiveMellinQuarterNoGoScale)
      character functional functionalNe eigenlaw
  have baseNe := positiveMellinQuarterNoGoShellLp_ne_zero_of_extension
    z hz functional extension
  have unitZero :=
    positiveMellinQuarterNoGoShellUnit_functional_zero_of_eigenlaw
      baseNe functional character characterNorm eigenlaw
  have baseReadNe :=
    positiveMellinQuarterNoGoShellLp_functional_ne_zero_of_extension
      z hz functional extension
  have normNe : ‖positiveMellinQuarterNoGoShellLp‖ ≠ 0 :=
    norm_ne_zero_iff.mpr baseNe
  have scalarNe :
      (‖positiveMellinQuarterNoGoShellLp‖⁻¹ : ℂ) ≠ 0 := by
    have hcast : (‖positiveMellinQuarterNoGoShellLp‖⁻¹ : ℂ) =
        (‖positiveMellinQuarterNoGoShellLp‖ : ℂ)⁻¹ := by
      norm_num
    rw [hcast]
    exact inv_ne_zero (ofReal_ne_zero.mpr normNe)
  have scaledZero :
      (‖positiveMellinQuarterNoGoShellLp‖⁻¹ : ℂ) *
        functional positiveMellinQuarterNoGoShellLp = 0 := by
    change functional ((‖positiveMellinQuarterNoGoShellLp‖⁻¹ : ℂ) •
      positiveMellinQuarterNoGoShellLp) = 0 at unitZero
    rw [map_smul] at unitZero
    simpa only [smul_eq_mul] using unitZero
  exact baseReadNe ((mul_eq_zero.mp scaledZero).resolve_left scalarNe)

end
end CanonicalRiemann
end NoIslandNoMagic
end ConstructiveRoot
end LivingLawEvolution
end ResponsibilityLifecycle
end SaturationMonoid
