import H0mework.Chemistry.LAlanineBandCall115.FieldMatrixData

set_option autoImplicit false
set_option maxRecDepth 4096

namespace SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule
namespace LAlanine40K2025.BasinRefinement.WholeBandCache.Call115

checkWholeBandMatrixRows 0 1

end LAlanine40K2025.BasinRefinement.WholeBandCache.Call115
end SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule
