import H0mework.Chemistry.LAlanineBandCall091.FieldMatrixData

set_option autoImplicit false
set_option maxRecDepth 4096

namespace SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule
namespace LAlanine40K2025.BasinRefinement.WholeBandCache.Call91

checkWholeBandMatrixRows 0 1

end LAlanine40K2025.BasinRefinement.WholeBandCache.Call91
end SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule
