import H0mework.Chemistry.LAlanineBandCall100.FieldData

set_option autoImplicit false

namespace SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule
namespace LAlanine40K2025.BasinRefinement.WholeBandCache.Call100

checkWholeBandOrbitals 0 98

end LAlanine40K2025.BasinRefinement.WholeBandCache.Call100
end SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule
