import H0mework.Chemistry.LAlanineBandCall012.TubeMatrixData
import H0mework.Chemistry.LAlanineWholeCell.MatrixCertificate

namespace SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.BasinRefinement.TrueTubeWholeMatrix.C12

checkWholeCellMatrixRow 4
checkWholeCellMatrixRow 5

end SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.BasinRefinement.TrueTubeWholeMatrix.C12
