import H0mework.Versions.R9c73a630.Chemistry.LAlanineBandCall003.TubeMatrixAssembled
import H0mework.Versions.R9c73a630.Chemistry.LAlanineBandCall003.TubeCacheComplete

namespace SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.BasinRefinement.TrueTubeWholeMatrix.C3

open WholeCellMatrix SourceIntegerGrid SourceFields SourceFiniteData SourceSignedEvaluator SourceRectangle SourceGaussianModel

assembleTrueTubeCallMatrix 3

end SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.BasinRefinement.TrueTubeWholeMatrix.C3
