import H0mework.Chemistry.LAlanineBandTaylor038.HullMatrixData
import H0mework.Chemistry.LAlanineBandHighJet.MatrixCheck

set_option autoImplicit false
set_option maxHeartbeats 0
set_option maxRecDepth 16384
namespace SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.BasinRefinement.WholeBandGenerated.Sample077
open HighJet.MatrixChecking
checkHighJetMatrixRows 25 30
end SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.BasinRefinement.WholeBandGenerated.Sample077
