import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Unified.Orbitals.Attraction.Precise.Rows.V096_096_098

set_option autoImplicit false
set_option maxRecDepth 16384
namespace SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule
namespace LAlanine40K2025.UnifiedOrbitals.Attraction.Precise.Rows
open LAlanine40K2025.BasinRefinement.SourceFiniteData

theorem upper_row_96 (j : Basis) (ordered : (96 : Basis) ≤ j) :
    |aoIntegral (96 : Basis) j - (recordedAttraction (96 : Basis) j : ℝ)| ≤
      (1/10^12 : ℝ) := by
  have rowSame : (96 : Basis) = ⟨96,by decide⟩ := by decide
  rw [rowSame]
  fin_cases j
  · exact False.elim ((show ¬(96 : Basis) ≤ (0 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (1 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (2 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (3 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (4 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (5 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (6 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (7 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (8 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (9 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (10 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (11 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (12 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (13 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (14 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (15 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (16 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (17 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (18 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (19 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (20 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (21 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (22 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (23 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (24 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (25 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (26 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (27 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (28 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (29 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (30 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (31 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (32 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (33 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (34 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (35 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (36 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (37 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (38 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (39 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (40 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (41 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (42 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (43 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (44 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (45 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (46 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (47 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (48 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (49 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (50 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (51 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (52 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (53 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (54 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (55 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (56 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (57 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (58 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (59 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (60 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (61 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (62 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (63 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (64 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (65 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (66 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (67 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (68 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (69 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (70 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (71 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (72 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (73 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (74 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (75 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (76 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (77 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (78 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (79 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (80 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (81 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (82 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (83 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (84 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (85 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (86 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (87 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (88 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (89 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (90 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (91 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (92 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (93 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (94 : Basis) by decide) ordered)
  · exact False.elim ((show ¬(96 : Basis) ≤ (95 : Basis) by decide) ordered)
  · convert vcell96_96_error using 1; norm_num
  · convert vcell96_97_error using 1; norm_num

end LAlanine40K2025.UnifiedOrbitals.Attraction.Precise.Rows
end SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule
