import H0mework.Chemistry.LAlanineTrueTubeHull.MatrixData
import H0mework.Chemistry.LAlanineWholeCell.MatrixCertificate

namespace SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.BasinRefinement.TrueTubeHullMatrix

checkWholeCellMatrixRow 8
checkWholeCellMatrixRow 9

end SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.BasinRefinement.TrueTubeHullMatrix
