import H0mework.Realization.Operations.FiniteRecurrence

/-! The existing largest invisible invariant kernel is generated by the finite source recurrence. -/

set_option autoImplicit false

namespace SaturationMonoid.ResponsibilityLifecycle.LivingLawEvolution.ConstructiveRoot
namespace SourceGeneratedActionObservationHistory.FiniteRecurrence

noncomputable section

universe r u

variable {R : Type r} [CommRing R]
variable {C B : Type u} [AddCommGroup C] [Module R C] [AddCommGroup B] [Module R B]
variable (action : C →ₗ[R] C) (observation : C →ₗ[R] B)
variable (bound : Nat) (coefficients : Fin (bound + 1) → R)
variable (sourceLaw : observation.comp (action ^ (bound + 1)) =
  ∑ index : Fin (bound + 1), coefficients index • stageEvaluator action observation index.val)

include sourceLaw

theorem prefix_kernel_invariant :
    LinearMap.ker (prefixEvaluator action observation bound) ≤
      (LinearMap.ker (prefixEvaluator action observation bound)).comap action := by
  intro value invisible
  change prefixEvaluator action observation bound value = 0 at invisible
  change prefixEvaluator action observation bound (action value) = 0
  have generated := LinearMap.congr_fun (advance_source action observation bound coefficients sourceLaw) value
  change advance bound coefficients (prefixEvaluator action observation bound value) =
    prefixEvaluator action observation bound (action value) at generated
  rw [invisible, map_zero] at generated
  exact generated.symm

theorem prefix_kernel_eq_full :
    LinearMap.ker (prefixEvaluator action observation bound) = LinearMap.ker (sourceMap action observation) := by
  apply le_antisymm
  · apply invariant_submodule_le_kernel action observation (LinearMap.ker (prefixEvaluator action observation bound))
    · intro value invisible
      change prefixEvaluator action observation bound value = 0 at invisible
      exact congrFun invisible 0
    · exact prefix_kernel_invariant action observation bound coefficients sourceLaw
  · intro value invisible
    change prefixEvaluator action observation bound value = 0
    funext index
    exact (mem_kernel_iff action observation value).mp invisible index.val

theorem prefix_fibre_iff_model (left right : C) :
    prefixEvaluator action observation bound left = prefixEvaluator action observation bound right ↔
      projection action observation left = projection action observation right := by
  calc
    _ ↔ left - right ∈ LinearMap.ker (prefixEvaluator action observation bound) := by
      rw [LinearMap.mem_ker, map_sub, sub_eq_zero]
    _ ↔ left - right ∈ LinearMap.ker (sourceMap action observation) := by
      rw [prefix_kernel_eq_full action observation bound coefficients sourceLaw]
    _ ↔ sourceMap action observation left = sourceMap action observation right := by
      rw [LinearMap.mem_ker, map_sub, sub_eq_zero]
    _ ↔ _ := (source_fibre_iff action observation left right).trans
      (model_fibre_iff action observation left right).symm

end
end SourceGeneratedActionObservationHistory.FiniteRecurrence
end SaturationMonoid.ResponsibilityLifecycle.LivingLawEvolution.ConstructiveRoot
