import H0mework.Chemistry.LAlanineBandCall023.FieldMatrixData

set_option autoImplicit false
set_option maxRecDepth 4096

namespace SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule
namespace LAlanine40K2025.BasinRefinement.WholeBandCache.Call23

checkWholeBandMatrixRows 0 1

end LAlanine40K2025.BasinRefinement.WholeBandCache.Call23
end SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule
