import H0mework.Versions.R9c73a630.Chemistry.LAlanineCellField60.MatrixAssembled
import H0mework.Versions.R9c73a630.Chemistry.LAlanineCellField60.CacheComplete

namespace SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.BasinRefinement.WholeCellMatrix.F60

open SourceIntegerGrid SourceFields SourceFiniteData SourceSignedEvaluator SourceRectangle SourceGaussianModel

assembleWholeCellMatrix 60

end SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.BasinRefinement.WholeCellMatrix.F60
