import H0mework.Versions.R9c73a630.Chemistry.LAlanineBandCall049.TubeCacheB0
import H0mework.Versions.R9c73a630.Chemistry.LAlanineBandCall049.TubeCacheB1
import H0mework.Versions.R9c73a630.Chemistry.LAlanineBandCall049.TubeCacheB2
import H0mework.Versions.R9c73a630.Chemistry.LAlanineBandCall049.TubeCacheB3
import H0mework.Versions.R9c73a630.Chemistry.LAlanineBandCall049.TubeCacheB4
import H0mework.Versions.R9c73a630.Chemistry.LAlanineBandCall049.TubeCacheB5
import H0mework.Versions.R9c73a630.Chemistry.LAlanineBandCall049.TubeCacheB6
import H0mework.Versions.R9c73a630.Chemistry.LAlanineBandCall049.TubeCacheB7

set_option autoImplicit false

namespace SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.BasinRefinement.TrueTubeWholeCache.Call49

open SourceRectangle SourceSignedEvaluator SourceGaussianModel SourceFiniteData SourceRectangleChecks SourceFields

assembleLowFieldAOs

end SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.BasinRefinement.TrueTubeWholeCache.Call49
