import H0mework.Chemistry.LAlanineTrueTubeCache.F1B0
import H0mework.Chemistry.LAlanineTrueTubeCache.F1B1
import H0mework.Chemistry.LAlanineTrueTubeCache.F1B2
import H0mework.Chemistry.LAlanineTrueTubeCache.F1B3
import H0mework.Chemistry.LAlanineTrueTubeCache.F1B4
import H0mework.Chemistry.LAlanineTrueTubeCache.F1B5
import H0mework.Chemistry.LAlanineTrueTubeCache.F1B6
import H0mework.Chemistry.LAlanineTrueTubeCache.F1B7

set_option autoImplicit false

namespace SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.BasinRefinement.TrueTubeCache.Field1

open SourceRectangle SourceSignedEvaluator SourceGaussianModel SourceFiniteData SourceRectangleChecks SourceFields

assembleLowFieldGroups

end SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.BasinRefinement.TrueTubeCache.Field1
