import H0mework.Versions.R9c73a630.Chemistry.LAlanineBandCall061.TubeMatrixData
import H0mework.Versions.R9c73a630.Chemistry.LAlanineWholeCell.MatrixCertificate

namespace SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.BasinRefinement.TrueTubeWholeMatrix.C61

checkWholeCellMatrixRow 0
checkWholeCellMatrixRow 1

end SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.BasinRefinement.TrueTubeWholeMatrix.C61
