import H0mework.Versions.R9c73a630.Chemistry.LAlanineContinuousChecks.AOCertificate

set_option autoImplicit false

namespace SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.BasinRefinement.SourceRectangleChecks.AOChecks

checkCachedAO 0
checkCachedAO 97

end SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.BasinRefinement.SourceRectangleChecks.AOChecks
