import H0mework.Versions.R9c73a630.Chemistry.LAlanineBandCall038.TubeCacheB0
import H0mework.Versions.R9c73a630.Chemistry.LAlanineBandCall038.TubeCacheB1
import H0mework.Versions.R9c73a630.Chemistry.LAlanineBandCall038.TubeCacheB2
import H0mework.Versions.R9c73a630.Chemistry.LAlanineBandCall038.TubeCacheB3
import H0mework.Versions.R9c73a630.Chemistry.LAlanineBandCall038.TubeCacheB4
import H0mework.Versions.R9c73a630.Chemistry.LAlanineBandCall038.TubeCacheB5
import H0mework.Versions.R9c73a630.Chemistry.LAlanineBandCall038.TubeCacheB6
import H0mework.Versions.R9c73a630.Chemistry.LAlanineBandCall038.TubeCacheB7

set_option autoImplicit false

namespace SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.BasinRefinement.TrueTubeWholeCache.Call38

open SourceRectangle SourceSignedEvaluator SourceGaussianModel SourceFiniteData SourceRectangleChecks SourceFields

assembleLowFieldGroups

end SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.BasinRefinement.TrueTubeWholeCache.Call38
