import H0mework.Chemistry.LAlanineBandCall013.FieldData

set_option autoImplicit false

namespace SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule
namespace LAlanine40K2025.BasinRefinement.WholeBandCache.Call13

checkWholeBandGroups 0 94

end LAlanine40K2025.BasinRefinement.WholeBandCache.Call13
end SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule
