import H0mework.Chemistry.LAlanineBandAttractor.SourceA007HullMatrixData
import H0mework.Chemistry.LAlanineBandHighJet.MatrixCheck
set_option autoImplicit false
set_option maxHeartbeats 0
set_option maxRecDepth 16384
namespace SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.BasinRefinement.WholeBandAttractor.Atom007.Hull
open WholeBandGenerated HighJet.MatrixChecking
checkHighJetMatrixRows 0 5
end SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.BasinRefinement.WholeBandAttractor.Atom007.Hull
