import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.OrdinaryPair
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P178
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P179
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P180
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P181
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P182

set_option autoImplicit false
namespace SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule
namespace LAlanine40K2025.Thermal.Recovery.Reservoir.Pointer.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Rows
open Propagation.Interface
noncomputable section

set_option maxHeartbeats 400000 in
def row36 : (b : Basis) → (36 : Basis) < b → OrdinaryPair 36 b :=
  Fin.cases (fun (ordered : (36 : Basis) < (0 : Basis)) => False.elim ((by decide +kernel : ¬ (36 : Basis) < (0 : Basis)) ordered))
    (Fin.cases (fun (ordered : (36 : Basis) < (1 : Basis)) => False.elim ((by decide +kernel : ¬ (36 : Basis) < (1 : Basis)) ordered))
    (Fin.cases (fun (ordered : (36 : Basis) < (2 : Basis)) => False.elim ((by decide +kernel : ¬ (36 : Basis) < (2 : Basis)) ordered))
    (Fin.cases (fun (ordered : (36 : Basis) < (3 : Basis)) => False.elim ((by decide +kernel : ¬ (36 : Basis) < (3 : Basis)) ordered))
    (Fin.cases (fun (ordered : (36 : Basis) < (4 : Basis)) => False.elim ((by decide +kernel : ¬ (36 : Basis) < (4 : Basis)) ordered))
    (Fin.cases (fun (ordered : (36 : Basis) < (5 : Basis)) => False.elim ((by decide +kernel : ¬ (36 : Basis) < (5 : Basis)) ordered))
    (Fin.cases (fun (ordered : (36 : Basis) < (6 : Basis)) => False.elim ((by decide +kernel : ¬ (36 : Basis) < (6 : Basis)) ordered))
    (Fin.cases (fun (ordered : (36 : Basis) < (7 : Basis)) => False.elim ((by decide +kernel : ¬ (36 : Basis) < (7 : Basis)) ordered))
    (Fin.cases (fun (ordered : (36 : Basis) < (8 : Basis)) => False.elim ((by decide +kernel : ¬ (36 : Basis) < (8 : Basis)) ordered))
    (Fin.cases (fun (ordered : (36 : Basis) < (9 : Basis)) => False.elim ((by decide +kernel : ¬ (36 : Basis) < (9 : Basis)) ordered))
    (Fin.cases (fun (ordered : (36 : Basis) < (10 : Basis)) => False.elim ((by decide +kernel : ¬ (36 : Basis) < (10 : Basis)) ordered))
    (Fin.cases (fun (ordered : (36 : Basis) < (11 : Basis)) => False.elim ((by decide +kernel : ¬ (36 : Basis) < (11 : Basis)) ordered))
    (Fin.cases (fun (ordered : (36 : Basis) < (12 : Basis)) => False.elim ((by decide +kernel : ¬ (36 : Basis) < (12 : Basis)) ordered))
    (Fin.cases (fun (ordered : (36 : Basis) < (13 : Basis)) => False.elim ((by decide +kernel : ¬ (36 : Basis) < (13 : Basis)) ordered))
    (Fin.cases (fun (ordered : (36 : Basis) < (14 : Basis)) => False.elim ((by decide +kernel : ¬ (36 : Basis) < (14 : Basis)) ordered))
    (Fin.cases (fun (ordered : (36 : Basis) < (15 : Basis)) => False.elim ((by decide +kernel : ¬ (36 : Basis) < (15 : Basis)) ordered))
    (Fin.cases (fun (ordered : (36 : Basis) < (16 : Basis)) => False.elim ((by decide +kernel : ¬ (36 : Basis) < (16 : Basis)) ordered))
    (Fin.cases (fun (ordered : (36 : Basis) < (17 : Basis)) => False.elim ((by decide +kernel : ¬ (36 : Basis) < (17 : Basis)) ordered))
    (Fin.cases (fun (ordered : (36 : Basis) < (18 : Basis)) => False.elim ((by decide +kernel : ¬ (36 : Basis) < (18 : Basis)) ordered))
    (Fin.cases (fun (ordered : (36 : Basis) < (19 : Basis)) => False.elim ((by decide +kernel : ¬ (36 : Basis) < (19 : Basis)) ordered))
    (Fin.cases (fun (ordered : (36 : Basis) < (20 : Basis)) => False.elim ((by decide +kernel : ¬ (36 : Basis) < (20 : Basis)) ordered))
    (Fin.cases (fun (ordered : (36 : Basis) < (21 : Basis)) => False.elim ((by decide +kernel : ¬ (36 : Basis) < (21 : Basis)) ordered))
    (Fin.cases (fun (ordered : (36 : Basis) < (22 : Basis)) => False.elim ((by decide +kernel : ¬ (36 : Basis) < (22 : Basis)) ordered))
    (Fin.cases (fun (ordered : (36 : Basis) < (23 : Basis)) => False.elim ((by decide +kernel : ¬ (36 : Basis) < (23 : Basis)) ordered))
    (Fin.cases (fun (ordered : (36 : Basis) < (24 : Basis)) => False.elim ((by decide +kernel : ¬ (36 : Basis) < (24 : Basis)) ordered))
    (Fin.cases (fun (ordered : (36 : Basis) < (25 : Basis)) => False.elim ((by decide +kernel : ¬ (36 : Basis) < (25 : Basis)) ordered))
    (Fin.cases (fun (ordered : (36 : Basis) < (26 : Basis)) => False.elim ((by decide +kernel : ¬ (36 : Basis) < (26 : Basis)) ordered))
    (Fin.cases (fun (ordered : (36 : Basis) < (27 : Basis)) => False.elim ((by decide +kernel : ¬ (36 : Basis) < (27 : Basis)) ordered))
    (Fin.cases (fun (ordered : (36 : Basis) < (28 : Basis)) => False.elim ((by decide +kernel : ¬ (36 : Basis) < (28 : Basis)) ordered))
    (Fin.cases (fun (ordered : (36 : Basis) < (29 : Basis)) => False.elim ((by decide +kernel : ¬ (36 : Basis) < (29 : Basis)) ordered))
    (Fin.cases (fun (ordered : (36 : Basis) < (30 : Basis)) => False.elim ((by decide +kernel : ¬ (36 : Basis) < (30 : Basis)) ordered))
    (Fin.cases (fun (ordered : (36 : Basis) < (31 : Basis)) => False.elim ((by decide +kernel : ¬ (36 : Basis) < (31 : Basis)) ordered))
    (Fin.cases (fun (ordered : (36 : Basis) < (32 : Basis)) => False.elim ((by decide +kernel : ¬ (36 : Basis) < (32 : Basis)) ordered))
    (Fin.cases (fun (ordered : (36 : Basis) < (33 : Basis)) => False.elim ((by decide +kernel : ¬ (36 : Basis) < (33 : Basis)) ordered))
    (Fin.cases (fun (ordered : (36 : Basis) < (34 : Basis)) => False.elim ((by decide +kernel : ¬ (36 : Basis) < (34 : Basis)) ordered))
    (Fin.cases (fun (ordered : (36 : Basis) < (35 : Basis)) => False.elim ((by decide +kernel : ¬ (36 : Basis) < (35 : Basis)) ordered))
    (Fin.cases (fun (ordered : (36 : Basis) < (36 : Basis)) => False.elim ((by decide +kernel : ¬ (36 : Basis) < (36 : Basis)) ordered))
    (Fin.cases (fun _ => ⟨⟨Factors.P178.factor13Plus,0,Factors.P178.checked13Plus⟩,⟨Factors.P178.factor13Minus,0,Factors.P178.checked13Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P178.factor14Plus,0,Factors.P178.checked14Plus⟩,⟨Factors.P178.factor14Minus,0,Factors.P178.checked14Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P178.factor15Plus,0,Factors.P178.checked15Plus⟩,⟨Factors.P178.factor15Minus,0,Factors.P178.checked15Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P179.factor0Plus,0,Factors.P179.checked0Plus⟩,⟨Factors.P179.factor0Minus,0,Factors.P179.checked0Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P179.factor1Plus,0,Factors.P179.checked1Plus⟩,⟨Factors.P179.factor1Minus,0,Factors.P179.checked1Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P179.factor2Plus,0,Factors.P179.checked2Plus⟩,⟨Factors.P179.factor2Minus,0,Factors.P179.checked2Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P179.factor3Plus,0,Factors.P179.checked3Plus⟩,⟨Factors.P179.factor3Minus,0,Factors.P179.checked3Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P179.factor4Plus,0,Factors.P179.checked4Plus⟩,⟨Factors.P179.factor4Minus,0,Factors.P179.checked4Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P179.factor5Plus,0,Factors.P179.checked5Plus⟩,⟨Factors.P179.factor5Minus,0,Factors.P179.checked5Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P179.factor6Plus,0,Factors.P179.checked6Plus⟩,⟨Factors.P179.factor6Minus,0,Factors.P179.checked6Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P179.factor7Plus,0,Factors.P179.checked7Plus⟩,⟨Factors.P179.factor7Minus,0,Factors.P179.checked7Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P179.factor8Plus,0,Factors.P179.checked8Plus⟩,⟨Factors.P179.factor8Minus,0,Factors.P179.checked8Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P179.factor9Plus,0,Factors.P179.checked9Plus⟩,⟨Factors.P179.factor9Minus,0,Factors.P179.checked9Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P179.factor10Plus,0,Factors.P179.checked10Plus⟩,⟨Factors.P179.factor10Minus,0,Factors.P179.checked10Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P179.factor11Plus,0,Factors.P179.checked11Plus⟩,⟨Factors.P179.factor11Minus,0,Factors.P179.checked11Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P179.factor12Plus,0,Factors.P179.checked12Plus⟩,⟨Factors.P179.factor12Minus,0,Factors.P179.checked12Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P179.factor13Plus,0,Factors.P179.checked13Plus⟩,⟨Factors.P179.factor13Minus,0,Factors.P179.checked13Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P179.factor14Plus,0,Factors.P179.checked14Plus⟩,⟨Factors.P179.factor14Minus,0,Factors.P179.checked14Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P179.factor15Plus,0,Factors.P179.checked15Plus⟩,⟨Factors.P179.factor15Minus,0,Factors.P179.checked15Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P180.factor0Plus,0,Factors.P180.checked0Plus⟩,⟨Factors.P180.factor0Minus,0,Factors.P180.checked0Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P180.factor1Plus,0,Factors.P180.checked1Plus⟩,⟨Factors.P180.factor1Minus,0,Factors.P180.checked1Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P180.factor2Plus,0,Factors.P180.checked2Plus⟩,⟨Factors.P180.factor2Minus,0,Factors.P180.checked2Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P180.factor3Plus,0,Factors.P180.checked3Plus⟩,⟨Factors.P180.factor3Minus,0,Factors.P180.checked3Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P180.factor4Plus,0,Factors.P180.checked4Plus⟩,⟨Factors.P180.factor4Minus,0,Factors.P180.checked4Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P180.factor5Plus,0,Factors.P180.checked5Plus⟩,⟨Factors.P180.factor5Minus,0,Factors.P180.checked5Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P180.factor6Plus,0,Factors.P180.checked6Plus⟩,⟨Factors.P180.factor6Minus,0,Factors.P180.checked6Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P180.factor7Plus,0,Factors.P180.checked7Plus⟩,⟨Factors.P180.factor7Minus,0,Factors.P180.checked7Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P180.factor8Plus,0,Factors.P180.checked8Plus⟩,⟨Factors.P180.factor8Minus,0,Factors.P180.checked8Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P180.factor9Plus,0,Factors.P180.checked9Plus⟩,⟨Factors.P180.factor9Minus,0,Factors.P180.checked9Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P180.factor10Plus,0,Factors.P180.checked10Plus⟩,⟨Factors.P180.factor10Minus,0,Factors.P180.checked10Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P180.factor11Plus,0,Factors.P180.checked11Plus⟩,⟨Factors.P180.factor11Minus,0,Factors.P180.checked11Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P180.factor12Plus,0,Factors.P180.checked12Plus⟩,⟨Factors.P180.factor12Minus,0,Factors.P180.checked12Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P180.factor13Plus,0,Factors.P180.checked13Plus⟩,⟨Factors.P180.factor13Minus,0,Factors.P180.checked13Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P180.factor14Plus,0,Factors.P180.checked14Plus⟩,⟨Factors.P180.factor14Minus,0,Factors.P180.checked14Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P180.factor15Plus,0,Factors.P180.checked15Plus⟩,⟨Factors.P180.factor15Minus,0,Factors.P180.checked15Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P181.factor0Plus,0,Factors.P181.checked0Plus⟩,⟨Factors.P181.factor0Minus,0,Factors.P181.checked0Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P181.factor1Plus,0,Factors.P181.checked1Plus⟩,⟨Factors.P181.factor1Minus,0,Factors.P181.checked1Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P181.factor2Plus,0,Factors.P181.checked2Plus⟩,⟨Factors.P181.factor2Minus,0,Factors.P181.checked2Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P181.factor3Plus,0,Factors.P181.checked3Plus⟩,⟨Factors.P181.factor3Minus,0,Factors.P181.checked3Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P181.factor4Plus,0,Factors.P181.checked4Plus⟩,⟨Factors.P181.factor4Minus,0,Factors.P181.checked4Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P181.factor5Plus,0,Factors.P181.checked5Plus⟩,⟨Factors.P181.factor5Minus,0,Factors.P181.checked5Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P181.factor6Plus,0,Factors.P181.checked6Plus⟩,⟨Factors.P181.factor6Minus,0,Factors.P181.checked6Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P181.factor7Plus,0,Factors.P181.checked7Plus⟩,⟨Factors.P181.factor7Minus,0,Factors.P181.checked7Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P181.factor8Plus,0,Factors.P181.checked8Plus⟩,⟨Factors.P181.factor8Minus,0,Factors.P181.checked8Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P181.factor9Plus,0,Factors.P181.checked9Plus⟩,⟨Factors.P181.factor9Minus,0,Factors.P181.checked9Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P181.factor10Plus,0,Factors.P181.checked10Plus⟩,⟨Factors.P181.factor10Minus,0,Factors.P181.checked10Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P181.factor11Plus,0,Factors.P181.checked11Plus⟩,⟨Factors.P181.factor11Minus,0,Factors.P181.checked11Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P181.factor12Plus,0,Factors.P181.checked12Plus⟩,⟨Factors.P181.factor12Minus,0,Factors.P181.checked12Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P181.factor13Plus,0,Factors.P181.checked13Plus⟩,⟨Factors.P181.factor13Minus,0,Factors.P181.checked13Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P181.factor14Plus,0,Factors.P181.checked14Plus⟩,⟨Factors.P181.factor14Minus,0,Factors.P181.checked14Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P181.factor15Plus,0,Factors.P181.checked15Plus⟩,⟨Factors.P181.factor15Minus,0,Factors.P181.checked15Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P182.factor0Plus,0,Factors.P182.checked0Plus⟩,⟨Factors.P182.factor0Minus,0,Factors.P182.checked0Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P182.factor1Plus,0,Factors.P182.checked1Plus⟩,⟨Factors.P182.factor1Minus,0,Factors.P182.checked1Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P182.factor2Plus,0,Factors.P182.checked2Plus⟩,⟨Factors.P182.factor2Minus,0,Factors.P182.checked2Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P182.factor3Plus,0,Factors.P182.checked3Plus⟩,⟨Factors.P182.factor3Minus,0,Factors.P182.checked3Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P182.factor4Plus,0,Factors.P182.checked4Plus⟩,⟨Factors.P182.factor4Minus,0,Factors.P182.checked4Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P182.factor5Plus,0,Factors.P182.checked5Plus⟩,⟨Factors.P182.factor5Minus,0,Factors.P182.checked5Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P182.factor6Plus,0,Factors.P182.checked6Plus⟩,⟨Factors.P182.factor6Minus,0,Factors.P182.checked6Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P182.factor7Plus,0,Factors.P182.checked7Plus⟩,⟨Factors.P182.factor7Minus,0,Factors.P182.checked7Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P182.factor8Plus,0,Factors.P182.checked8Plus⟩,⟨Factors.P182.factor8Minus,0,Factors.P182.checked8Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P182.factor9Plus,0,Factors.P182.checked9Plus⟩,⟨Factors.P182.factor9Minus,0,Factors.P182.checked9Minus⟩⟩)
    ((fun impossible => Fin.elim0 impossible)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))

end
end LAlanine40K2025.Thermal.Recovery.Reservoir.Pointer.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Rows
end SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule
