import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.OrdinaryPair
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P182
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P183
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P184
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P185
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P186

set_option autoImplicit false
namespace SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule
namespace LAlanine40K2025.Thermal.Recovery.Reservoir.Pointer.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Rows
open Propagation.Interface
noncomputable section

set_option maxHeartbeats 400000 in
def row37 : (b : Basis) → (37 : Basis) < b → OrdinaryPair 37 b :=
  Fin.cases (fun (ordered : (37 : Basis) < (0 : Basis)) => False.elim ((by decide +kernel : ¬ (37 : Basis) < (0 : Basis)) ordered))
    (Fin.cases (fun (ordered : (37 : Basis) < (1 : Basis)) => False.elim ((by decide +kernel : ¬ (37 : Basis) < (1 : Basis)) ordered))
    (Fin.cases (fun (ordered : (37 : Basis) < (2 : Basis)) => False.elim ((by decide +kernel : ¬ (37 : Basis) < (2 : Basis)) ordered))
    (Fin.cases (fun (ordered : (37 : Basis) < (3 : Basis)) => False.elim ((by decide +kernel : ¬ (37 : Basis) < (3 : Basis)) ordered))
    (Fin.cases (fun (ordered : (37 : Basis) < (4 : Basis)) => False.elim ((by decide +kernel : ¬ (37 : Basis) < (4 : Basis)) ordered))
    (Fin.cases (fun (ordered : (37 : Basis) < (5 : Basis)) => False.elim ((by decide +kernel : ¬ (37 : Basis) < (5 : Basis)) ordered))
    (Fin.cases (fun (ordered : (37 : Basis) < (6 : Basis)) => False.elim ((by decide +kernel : ¬ (37 : Basis) < (6 : Basis)) ordered))
    (Fin.cases (fun (ordered : (37 : Basis) < (7 : Basis)) => False.elim ((by decide +kernel : ¬ (37 : Basis) < (7 : Basis)) ordered))
    (Fin.cases (fun (ordered : (37 : Basis) < (8 : Basis)) => False.elim ((by decide +kernel : ¬ (37 : Basis) < (8 : Basis)) ordered))
    (Fin.cases (fun (ordered : (37 : Basis) < (9 : Basis)) => False.elim ((by decide +kernel : ¬ (37 : Basis) < (9 : Basis)) ordered))
    (Fin.cases (fun (ordered : (37 : Basis) < (10 : Basis)) => False.elim ((by decide +kernel : ¬ (37 : Basis) < (10 : Basis)) ordered))
    (Fin.cases (fun (ordered : (37 : Basis) < (11 : Basis)) => False.elim ((by decide +kernel : ¬ (37 : Basis) < (11 : Basis)) ordered))
    (Fin.cases (fun (ordered : (37 : Basis) < (12 : Basis)) => False.elim ((by decide +kernel : ¬ (37 : Basis) < (12 : Basis)) ordered))
    (Fin.cases (fun (ordered : (37 : Basis) < (13 : Basis)) => False.elim ((by decide +kernel : ¬ (37 : Basis) < (13 : Basis)) ordered))
    (Fin.cases (fun (ordered : (37 : Basis) < (14 : Basis)) => False.elim ((by decide +kernel : ¬ (37 : Basis) < (14 : Basis)) ordered))
    (Fin.cases (fun (ordered : (37 : Basis) < (15 : Basis)) => False.elim ((by decide +kernel : ¬ (37 : Basis) < (15 : Basis)) ordered))
    (Fin.cases (fun (ordered : (37 : Basis) < (16 : Basis)) => False.elim ((by decide +kernel : ¬ (37 : Basis) < (16 : Basis)) ordered))
    (Fin.cases (fun (ordered : (37 : Basis) < (17 : Basis)) => False.elim ((by decide +kernel : ¬ (37 : Basis) < (17 : Basis)) ordered))
    (Fin.cases (fun (ordered : (37 : Basis) < (18 : Basis)) => False.elim ((by decide +kernel : ¬ (37 : Basis) < (18 : Basis)) ordered))
    (Fin.cases (fun (ordered : (37 : Basis) < (19 : Basis)) => False.elim ((by decide +kernel : ¬ (37 : Basis) < (19 : Basis)) ordered))
    (Fin.cases (fun (ordered : (37 : Basis) < (20 : Basis)) => False.elim ((by decide +kernel : ¬ (37 : Basis) < (20 : Basis)) ordered))
    (Fin.cases (fun (ordered : (37 : Basis) < (21 : Basis)) => False.elim ((by decide +kernel : ¬ (37 : Basis) < (21 : Basis)) ordered))
    (Fin.cases (fun (ordered : (37 : Basis) < (22 : Basis)) => False.elim ((by decide +kernel : ¬ (37 : Basis) < (22 : Basis)) ordered))
    (Fin.cases (fun (ordered : (37 : Basis) < (23 : Basis)) => False.elim ((by decide +kernel : ¬ (37 : Basis) < (23 : Basis)) ordered))
    (Fin.cases (fun (ordered : (37 : Basis) < (24 : Basis)) => False.elim ((by decide +kernel : ¬ (37 : Basis) < (24 : Basis)) ordered))
    (Fin.cases (fun (ordered : (37 : Basis) < (25 : Basis)) => False.elim ((by decide +kernel : ¬ (37 : Basis) < (25 : Basis)) ordered))
    (Fin.cases (fun (ordered : (37 : Basis) < (26 : Basis)) => False.elim ((by decide +kernel : ¬ (37 : Basis) < (26 : Basis)) ordered))
    (Fin.cases (fun (ordered : (37 : Basis) < (27 : Basis)) => False.elim ((by decide +kernel : ¬ (37 : Basis) < (27 : Basis)) ordered))
    (Fin.cases (fun (ordered : (37 : Basis) < (28 : Basis)) => False.elim ((by decide +kernel : ¬ (37 : Basis) < (28 : Basis)) ordered))
    (Fin.cases (fun (ordered : (37 : Basis) < (29 : Basis)) => False.elim ((by decide +kernel : ¬ (37 : Basis) < (29 : Basis)) ordered))
    (Fin.cases (fun (ordered : (37 : Basis) < (30 : Basis)) => False.elim ((by decide +kernel : ¬ (37 : Basis) < (30 : Basis)) ordered))
    (Fin.cases (fun (ordered : (37 : Basis) < (31 : Basis)) => False.elim ((by decide +kernel : ¬ (37 : Basis) < (31 : Basis)) ordered))
    (Fin.cases (fun (ordered : (37 : Basis) < (32 : Basis)) => False.elim ((by decide +kernel : ¬ (37 : Basis) < (32 : Basis)) ordered))
    (Fin.cases (fun (ordered : (37 : Basis) < (33 : Basis)) => False.elim ((by decide +kernel : ¬ (37 : Basis) < (33 : Basis)) ordered))
    (Fin.cases (fun (ordered : (37 : Basis) < (34 : Basis)) => False.elim ((by decide +kernel : ¬ (37 : Basis) < (34 : Basis)) ordered))
    (Fin.cases (fun (ordered : (37 : Basis) < (35 : Basis)) => False.elim ((by decide +kernel : ¬ (37 : Basis) < (35 : Basis)) ordered))
    (Fin.cases (fun (ordered : (37 : Basis) < (36 : Basis)) => False.elim ((by decide +kernel : ¬ (37 : Basis) < (36 : Basis)) ordered))
    (Fin.cases (fun (ordered : (37 : Basis) < (37 : Basis)) => False.elim ((by decide +kernel : ¬ (37 : Basis) < (37 : Basis)) ordered))
    (Fin.cases (fun _ => ⟨⟨Factors.P182.factor10Plus,0,Factors.P182.checked10Plus⟩,⟨Factors.P182.factor10Minus,0,Factors.P182.checked10Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P182.factor11Plus,0,Factors.P182.checked11Plus⟩,⟨Factors.P182.factor11Minus,0,Factors.P182.checked11Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P182.factor12Plus,0,Factors.P182.checked12Plus⟩,⟨Factors.P182.factor12Minus,0,Factors.P182.checked12Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P182.factor13Plus,0,Factors.P182.checked13Plus⟩,⟨Factors.P182.factor13Minus,0,Factors.P182.checked13Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P182.factor14Plus,0,Factors.P182.checked14Plus⟩,⟨Factors.P182.factor14Minus,0,Factors.P182.checked14Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P182.factor15Plus,0,Factors.P182.checked15Plus⟩,⟨Factors.P182.factor15Minus,0,Factors.P182.checked15Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P183.factor0Plus,0,Factors.P183.checked0Plus⟩,⟨Factors.P183.factor0Minus,0,Factors.P183.checked0Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P183.factor1Plus,0,Factors.P183.checked1Plus⟩,⟨Factors.P183.factor1Minus,0,Factors.P183.checked1Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P183.factor2Plus,0,Factors.P183.checked2Plus⟩,⟨Factors.P183.factor2Minus,0,Factors.P183.checked2Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P183.factor3Plus,0,Factors.P183.checked3Plus⟩,⟨Factors.P183.factor3Minus,0,Factors.P183.checked3Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P183.factor4Plus,0,Factors.P183.checked4Plus⟩,⟨Factors.P183.factor4Minus,0,Factors.P183.checked4Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P183.factor5Plus,0,Factors.P183.checked5Plus⟩,⟨Factors.P183.factor5Minus,0,Factors.P183.checked5Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P183.factor6Plus,0,Factors.P183.checked6Plus⟩,⟨Factors.P183.factor6Minus,0,Factors.P183.checked6Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P183.factor7Plus,0,Factors.P183.checked7Plus⟩,⟨Factors.P183.factor7Minus,0,Factors.P183.checked7Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P183.factor8Plus,0,Factors.P183.checked8Plus⟩,⟨Factors.P183.factor8Minus,0,Factors.P183.checked8Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P183.factor9Plus,0,Factors.P183.checked9Plus⟩,⟨Factors.P183.factor9Minus,0,Factors.P183.checked9Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P183.factor10Plus,0,Factors.P183.checked10Plus⟩,⟨Factors.P183.factor10Minus,0,Factors.P183.checked10Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P183.factor11Plus,0,Factors.P183.checked11Plus⟩,⟨Factors.P183.factor11Minus,0,Factors.P183.checked11Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P183.factor12Plus,0,Factors.P183.checked12Plus⟩,⟨Factors.P183.factor12Minus,0,Factors.P183.checked12Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P183.factor13Plus,0,Factors.P183.checked13Plus⟩,⟨Factors.P183.factor13Minus,0,Factors.P183.checked13Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P183.factor14Plus,0,Factors.P183.checked14Plus⟩,⟨Factors.P183.factor14Minus,0,Factors.P183.checked14Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P183.factor15Plus,0,Factors.P183.checked15Plus⟩,⟨Factors.P183.factor15Minus,0,Factors.P183.checked15Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P184.factor0Plus,0,Factors.P184.checked0Plus⟩,⟨Factors.P184.factor0Minus,0,Factors.P184.checked0Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P184.factor1Plus,0,Factors.P184.checked1Plus⟩,⟨Factors.P184.factor1Minus,0,Factors.P184.checked1Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P184.factor2Plus,0,Factors.P184.checked2Plus⟩,⟨Factors.P184.factor2Minus,0,Factors.P184.checked2Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P184.factor3Plus,0,Factors.P184.checked3Plus⟩,⟨Factors.P184.factor3Minus,0,Factors.P184.checked3Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P184.factor4Plus,0,Factors.P184.checked4Plus⟩,⟨Factors.P184.factor4Minus,0,Factors.P184.checked4Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P184.factor5Plus,0,Factors.P184.checked5Plus⟩,⟨Factors.P184.factor5Minus,0,Factors.P184.checked5Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P184.factor6Plus,0,Factors.P184.checked6Plus⟩,⟨Factors.P184.factor6Minus,0,Factors.P184.checked6Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P184.factor7Plus,0,Factors.P184.checked7Plus⟩,⟨Factors.P184.factor7Minus,0,Factors.P184.checked7Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P184.factor8Plus,0,Factors.P184.checked8Plus⟩,⟨Factors.P184.factor8Minus,0,Factors.P184.checked8Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P184.factor9Plus,0,Factors.P184.checked9Plus⟩,⟨Factors.P184.factor9Minus,0,Factors.P184.checked9Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P184.factor10Plus,0,Factors.P184.checked10Plus⟩,⟨Factors.P184.factor10Minus,0,Factors.P184.checked10Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P184.factor11Plus,0,Factors.P184.checked11Plus⟩,⟨Factors.P184.factor11Minus,0,Factors.P184.checked11Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P184.factor12Plus,0,Factors.P184.checked12Plus⟩,⟨Factors.P184.factor12Minus,0,Factors.P184.checked12Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P184.factor13Plus,0,Factors.P184.checked13Plus⟩,⟨Factors.P184.factor13Minus,0,Factors.P184.checked13Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P184.factor14Plus,0,Factors.P184.checked14Plus⟩,⟨Factors.P184.factor14Minus,0,Factors.P184.checked14Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P184.factor15Plus,0,Factors.P184.checked15Plus⟩,⟨Factors.P184.factor15Minus,0,Factors.P184.checked15Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P185.factor0Plus,0,Factors.P185.checked0Plus⟩,⟨Factors.P185.factor0Minus,0,Factors.P185.checked0Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P185.factor1Plus,0,Factors.P185.checked1Plus⟩,⟨Factors.P185.factor1Minus,0,Factors.P185.checked1Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P185.factor2Plus,0,Factors.P185.checked2Plus⟩,⟨Factors.P185.factor2Minus,0,Factors.P185.checked2Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P185.factor3Plus,0,Factors.P185.checked3Plus⟩,⟨Factors.P185.factor3Minus,0,Factors.P185.checked3Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P185.factor4Plus,0,Factors.P185.checked4Plus⟩,⟨Factors.P185.factor4Minus,0,Factors.P185.checked4Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P185.factor5Plus,0,Factors.P185.checked5Plus⟩,⟨Factors.P185.factor5Minus,0,Factors.P185.checked5Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P185.factor6Plus,0,Factors.P185.checked6Plus⟩,⟨Factors.P185.factor6Minus,0,Factors.P185.checked6Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P185.factor7Plus,0,Factors.P185.checked7Plus⟩,⟨Factors.P185.factor7Minus,0,Factors.P185.checked7Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P185.factor8Plus,0,Factors.P185.checked8Plus⟩,⟨Factors.P185.factor8Minus,0,Factors.P185.checked8Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P185.factor9Plus,0,Factors.P185.checked9Plus⟩,⟨Factors.P185.factor9Minus,0,Factors.P185.checked9Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P185.factor10Plus,0,Factors.P185.checked10Plus⟩,⟨Factors.P185.factor10Minus,0,Factors.P185.checked10Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P185.factor11Plus,0,Factors.P185.checked11Plus⟩,⟨Factors.P185.factor11Minus,0,Factors.P185.checked11Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P185.factor12Plus,0,Factors.P185.checked12Plus⟩,⟨Factors.P185.factor12Minus,0,Factors.P185.checked12Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P185.factor13Plus,0,Factors.P185.checked13Plus⟩,⟨Factors.P185.factor13Minus,0,Factors.P185.checked13Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P185.factor14Plus,0,Factors.P185.checked14Plus⟩,⟨Factors.P185.factor14Minus,0,Factors.P185.checked14Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P185.factor15Plus,0,Factors.P185.checked15Plus⟩,⟨Factors.P185.factor15Minus,0,Factors.P185.checked15Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P186.factor0Plus,0,Factors.P186.checked0Plus⟩,⟨Factors.P186.factor0Minus,0,Factors.P186.checked0Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P186.factor1Plus,0,Factors.P186.checked1Plus⟩,⟨Factors.P186.factor1Minus,0,Factors.P186.checked1Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P186.factor2Plus,0,Factors.P186.checked2Plus⟩,⟨Factors.P186.factor2Minus,0,Factors.P186.checked2Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P186.factor3Plus,0,Factors.P186.checked3Plus⟩,⟨Factors.P186.factor3Minus,0,Factors.P186.checked3Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P186.factor4Plus,0,Factors.P186.checked4Plus⟩,⟨Factors.P186.factor4Minus,0,Factors.P186.checked4Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P186.factor5Plus,0,Factors.P186.checked5Plus⟩,⟨Factors.P186.factor5Minus,0,Factors.P186.checked5Minus⟩⟩)
    ((fun impossible => Fin.elim0 impossible)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))

end
end LAlanine40K2025.Thermal.Recovery.Reservoir.Pointer.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Rows
end SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule
