import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.OrdinaryPair
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P186
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P187
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P188
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P189
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P190

set_option autoImplicit false
namespace SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule
namespace LAlanine40K2025.Thermal.Recovery.Reservoir.Pointer.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Rows
open Propagation.Interface
noncomputable section

set_option maxHeartbeats 400000 in
def row38 : (b : Basis) → (38 : Basis) < b → OrdinaryPair 38 b :=
  Fin.cases (fun (ordered : (38 : Basis) < (0 : Basis)) => False.elim ((by decide +kernel : ¬ (38 : Basis) < (0 : Basis)) ordered))
    (Fin.cases (fun (ordered : (38 : Basis) < (1 : Basis)) => False.elim ((by decide +kernel : ¬ (38 : Basis) < (1 : Basis)) ordered))
    (Fin.cases (fun (ordered : (38 : Basis) < (2 : Basis)) => False.elim ((by decide +kernel : ¬ (38 : Basis) < (2 : Basis)) ordered))
    (Fin.cases (fun (ordered : (38 : Basis) < (3 : Basis)) => False.elim ((by decide +kernel : ¬ (38 : Basis) < (3 : Basis)) ordered))
    (Fin.cases (fun (ordered : (38 : Basis) < (4 : Basis)) => False.elim ((by decide +kernel : ¬ (38 : Basis) < (4 : Basis)) ordered))
    (Fin.cases (fun (ordered : (38 : Basis) < (5 : Basis)) => False.elim ((by decide +kernel : ¬ (38 : Basis) < (5 : Basis)) ordered))
    (Fin.cases (fun (ordered : (38 : Basis) < (6 : Basis)) => False.elim ((by decide +kernel : ¬ (38 : Basis) < (6 : Basis)) ordered))
    (Fin.cases (fun (ordered : (38 : Basis) < (7 : Basis)) => False.elim ((by decide +kernel : ¬ (38 : Basis) < (7 : Basis)) ordered))
    (Fin.cases (fun (ordered : (38 : Basis) < (8 : Basis)) => False.elim ((by decide +kernel : ¬ (38 : Basis) < (8 : Basis)) ordered))
    (Fin.cases (fun (ordered : (38 : Basis) < (9 : Basis)) => False.elim ((by decide +kernel : ¬ (38 : Basis) < (9 : Basis)) ordered))
    (Fin.cases (fun (ordered : (38 : Basis) < (10 : Basis)) => False.elim ((by decide +kernel : ¬ (38 : Basis) < (10 : Basis)) ordered))
    (Fin.cases (fun (ordered : (38 : Basis) < (11 : Basis)) => False.elim ((by decide +kernel : ¬ (38 : Basis) < (11 : Basis)) ordered))
    (Fin.cases (fun (ordered : (38 : Basis) < (12 : Basis)) => False.elim ((by decide +kernel : ¬ (38 : Basis) < (12 : Basis)) ordered))
    (Fin.cases (fun (ordered : (38 : Basis) < (13 : Basis)) => False.elim ((by decide +kernel : ¬ (38 : Basis) < (13 : Basis)) ordered))
    (Fin.cases (fun (ordered : (38 : Basis) < (14 : Basis)) => False.elim ((by decide +kernel : ¬ (38 : Basis) < (14 : Basis)) ordered))
    (Fin.cases (fun (ordered : (38 : Basis) < (15 : Basis)) => False.elim ((by decide +kernel : ¬ (38 : Basis) < (15 : Basis)) ordered))
    (Fin.cases (fun (ordered : (38 : Basis) < (16 : Basis)) => False.elim ((by decide +kernel : ¬ (38 : Basis) < (16 : Basis)) ordered))
    (Fin.cases (fun (ordered : (38 : Basis) < (17 : Basis)) => False.elim ((by decide +kernel : ¬ (38 : Basis) < (17 : Basis)) ordered))
    (Fin.cases (fun (ordered : (38 : Basis) < (18 : Basis)) => False.elim ((by decide +kernel : ¬ (38 : Basis) < (18 : Basis)) ordered))
    (Fin.cases (fun (ordered : (38 : Basis) < (19 : Basis)) => False.elim ((by decide +kernel : ¬ (38 : Basis) < (19 : Basis)) ordered))
    (Fin.cases (fun (ordered : (38 : Basis) < (20 : Basis)) => False.elim ((by decide +kernel : ¬ (38 : Basis) < (20 : Basis)) ordered))
    (Fin.cases (fun (ordered : (38 : Basis) < (21 : Basis)) => False.elim ((by decide +kernel : ¬ (38 : Basis) < (21 : Basis)) ordered))
    (Fin.cases (fun (ordered : (38 : Basis) < (22 : Basis)) => False.elim ((by decide +kernel : ¬ (38 : Basis) < (22 : Basis)) ordered))
    (Fin.cases (fun (ordered : (38 : Basis) < (23 : Basis)) => False.elim ((by decide +kernel : ¬ (38 : Basis) < (23 : Basis)) ordered))
    (Fin.cases (fun (ordered : (38 : Basis) < (24 : Basis)) => False.elim ((by decide +kernel : ¬ (38 : Basis) < (24 : Basis)) ordered))
    (Fin.cases (fun (ordered : (38 : Basis) < (25 : Basis)) => False.elim ((by decide +kernel : ¬ (38 : Basis) < (25 : Basis)) ordered))
    (Fin.cases (fun (ordered : (38 : Basis) < (26 : Basis)) => False.elim ((by decide +kernel : ¬ (38 : Basis) < (26 : Basis)) ordered))
    (Fin.cases (fun (ordered : (38 : Basis) < (27 : Basis)) => False.elim ((by decide +kernel : ¬ (38 : Basis) < (27 : Basis)) ordered))
    (Fin.cases (fun (ordered : (38 : Basis) < (28 : Basis)) => False.elim ((by decide +kernel : ¬ (38 : Basis) < (28 : Basis)) ordered))
    (Fin.cases (fun (ordered : (38 : Basis) < (29 : Basis)) => False.elim ((by decide +kernel : ¬ (38 : Basis) < (29 : Basis)) ordered))
    (Fin.cases (fun (ordered : (38 : Basis) < (30 : Basis)) => False.elim ((by decide +kernel : ¬ (38 : Basis) < (30 : Basis)) ordered))
    (Fin.cases (fun (ordered : (38 : Basis) < (31 : Basis)) => False.elim ((by decide +kernel : ¬ (38 : Basis) < (31 : Basis)) ordered))
    (Fin.cases (fun (ordered : (38 : Basis) < (32 : Basis)) => False.elim ((by decide +kernel : ¬ (38 : Basis) < (32 : Basis)) ordered))
    (Fin.cases (fun (ordered : (38 : Basis) < (33 : Basis)) => False.elim ((by decide +kernel : ¬ (38 : Basis) < (33 : Basis)) ordered))
    (Fin.cases (fun (ordered : (38 : Basis) < (34 : Basis)) => False.elim ((by decide +kernel : ¬ (38 : Basis) < (34 : Basis)) ordered))
    (Fin.cases (fun (ordered : (38 : Basis) < (35 : Basis)) => False.elim ((by decide +kernel : ¬ (38 : Basis) < (35 : Basis)) ordered))
    (Fin.cases (fun (ordered : (38 : Basis) < (36 : Basis)) => False.elim ((by decide +kernel : ¬ (38 : Basis) < (36 : Basis)) ordered))
    (Fin.cases (fun (ordered : (38 : Basis) < (37 : Basis)) => False.elim ((by decide +kernel : ¬ (38 : Basis) < (37 : Basis)) ordered))
    (Fin.cases (fun (ordered : (38 : Basis) < (38 : Basis)) => False.elim ((by decide +kernel : ¬ (38 : Basis) < (38 : Basis)) ordered))
    (Fin.cases (fun _ => ⟨⟨Factors.P186.factor6Plus,0,Factors.P186.checked6Plus⟩,⟨Factors.P186.factor6Minus,0,Factors.P186.checked6Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P186.factor7Plus,0,Factors.P186.checked7Plus⟩,⟨Factors.P186.factor7Minus,0,Factors.P186.checked7Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P186.factor8Plus,0,Factors.P186.checked8Plus⟩,⟨Factors.P186.factor8Minus,0,Factors.P186.checked8Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P186.factor9Plus,0,Factors.P186.checked9Plus⟩,⟨Factors.P186.factor9Minus,0,Factors.P186.checked9Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P186.factor10Plus,0,Factors.P186.checked10Plus⟩,⟨Factors.P186.factor10Minus,0,Factors.P186.checked10Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P186.factor11Plus,0,Factors.P186.checked11Plus⟩,⟨Factors.P186.factor11Minus,0,Factors.P186.checked11Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P186.factor12Plus,0,Factors.P186.checked12Plus⟩,⟨Factors.P186.factor12Minus,0,Factors.P186.checked12Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P186.factor13Plus,0,Factors.P186.checked13Plus⟩,⟨Factors.P186.factor13Minus,0,Factors.P186.checked13Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P186.factor14Plus,0,Factors.P186.checked14Plus⟩,⟨Factors.P186.factor14Minus,0,Factors.P186.checked14Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P186.factor15Plus,0,Factors.P186.checked15Plus⟩,⟨Factors.P186.factor15Minus,0,Factors.P186.checked15Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P187.factor0Plus,0,Factors.P187.checked0Plus⟩,⟨Factors.P187.factor0Minus,0,Factors.P187.checked0Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P187.factor1Plus,0,Factors.P187.checked1Plus⟩,⟨Factors.P187.factor1Minus,0,Factors.P187.checked1Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P187.factor2Plus,0,Factors.P187.checked2Plus⟩,⟨Factors.P187.factor2Minus,0,Factors.P187.checked2Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P187.factor3Plus,0,Factors.P187.checked3Plus⟩,⟨Factors.P187.factor3Minus,0,Factors.P187.checked3Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P187.factor4Plus,0,Factors.P187.checked4Plus⟩,⟨Factors.P187.factor4Minus,0,Factors.P187.checked4Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P187.factor5Plus,0,Factors.P187.checked5Plus⟩,⟨Factors.P187.factor5Minus,0,Factors.P187.checked5Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P187.factor6Plus,0,Factors.P187.checked6Plus⟩,⟨Factors.P187.factor6Minus,0,Factors.P187.checked6Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P187.factor7Plus,0,Factors.P187.checked7Plus⟩,⟨Factors.P187.factor7Minus,0,Factors.P187.checked7Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P187.factor8Plus,0,Factors.P187.checked8Plus⟩,⟨Factors.P187.factor8Minus,0,Factors.P187.checked8Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P187.factor9Plus,0,Factors.P187.checked9Plus⟩,⟨Factors.P187.factor9Minus,0,Factors.P187.checked9Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P187.factor10Plus,0,Factors.P187.checked10Plus⟩,⟨Factors.P187.factor10Minus,0,Factors.P187.checked10Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P187.factor11Plus,0,Factors.P187.checked11Plus⟩,⟨Factors.P187.factor11Minus,0,Factors.P187.checked11Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P187.factor12Plus,0,Factors.P187.checked12Plus⟩,⟨Factors.P187.factor12Minus,0,Factors.P187.checked12Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P187.factor13Plus,0,Factors.P187.checked13Plus⟩,⟨Factors.P187.factor13Minus,0,Factors.P187.checked13Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P187.factor14Plus,0,Factors.P187.checked14Plus⟩,⟨Factors.P187.factor14Minus,0,Factors.P187.checked14Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P187.factor15Plus,0,Factors.P187.checked15Plus⟩,⟨Factors.P187.factor15Minus,0,Factors.P187.checked15Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P188.factor0Plus,0,Factors.P188.checked0Plus⟩,⟨Factors.P188.factor0Minus,0,Factors.P188.checked0Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P188.factor1Plus,0,Factors.P188.checked1Plus⟩,⟨Factors.P188.factor1Minus,0,Factors.P188.checked1Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P188.factor2Plus,0,Factors.P188.checked2Plus⟩,⟨Factors.P188.factor2Minus,0,Factors.P188.checked2Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P188.factor3Plus,0,Factors.P188.checked3Plus⟩,⟨Factors.P188.factor3Minus,0,Factors.P188.checked3Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P188.factor4Plus,0,Factors.P188.checked4Plus⟩,⟨Factors.P188.factor4Minus,0,Factors.P188.checked4Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P188.factor5Plus,0,Factors.P188.checked5Plus⟩,⟨Factors.P188.factor5Minus,0,Factors.P188.checked5Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P188.factor6Plus,0,Factors.P188.checked6Plus⟩,⟨Factors.P188.factor6Minus,0,Factors.P188.checked6Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P188.factor7Plus,0,Factors.P188.checked7Plus⟩,⟨Factors.P188.factor7Minus,0,Factors.P188.checked7Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P188.factor8Plus,0,Factors.P188.checked8Plus⟩,⟨Factors.P188.factor8Minus,0,Factors.P188.checked8Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P188.factor9Plus,0,Factors.P188.checked9Plus⟩,⟨Factors.P188.factor9Minus,0,Factors.P188.checked9Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P188.factor10Plus,0,Factors.P188.checked10Plus⟩,⟨Factors.P188.factor10Minus,0,Factors.P188.checked10Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P188.factor11Plus,0,Factors.P188.checked11Plus⟩,⟨Factors.P188.factor11Minus,0,Factors.P188.checked11Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P188.factor12Plus,0,Factors.P188.checked12Plus⟩,⟨Factors.P188.factor12Minus,0,Factors.P188.checked12Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P188.factor13Plus,0,Factors.P188.checked13Plus⟩,⟨Factors.P188.factor13Minus,0,Factors.P188.checked13Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P188.factor14Plus,0,Factors.P188.checked14Plus⟩,⟨Factors.P188.factor14Minus,0,Factors.P188.checked14Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P188.factor15Plus,0,Factors.P188.checked15Plus⟩,⟨Factors.P188.factor15Minus,0,Factors.P188.checked15Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P189.factor0Plus,0,Factors.P189.checked0Plus⟩,⟨Factors.P189.factor0Minus,0,Factors.P189.checked0Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P189.factor1Plus,0,Factors.P189.checked1Plus⟩,⟨Factors.P189.factor1Minus,0,Factors.P189.checked1Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P189.factor2Plus,0,Factors.P189.checked2Plus⟩,⟨Factors.P189.factor2Minus,0,Factors.P189.checked2Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P189.factor3Plus,0,Factors.P189.checked3Plus⟩,⟨Factors.P189.factor3Minus,0,Factors.P189.checked3Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P189.factor4Plus,0,Factors.P189.checked4Plus⟩,⟨Factors.P189.factor4Minus,0,Factors.P189.checked4Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P189.factor5Plus,0,Factors.P189.checked5Plus⟩,⟨Factors.P189.factor5Minus,0,Factors.P189.checked5Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P189.factor6Plus,0,Factors.P189.checked6Plus⟩,⟨Factors.P189.factor6Minus,0,Factors.P189.checked6Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P189.factor7Plus,0,Factors.P189.checked7Plus⟩,⟨Factors.P189.factor7Minus,0,Factors.P189.checked7Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P189.factor8Plus,0,Factors.P189.checked8Plus⟩,⟨Factors.P189.factor8Minus,0,Factors.P189.checked8Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P189.factor9Plus,0,Factors.P189.checked9Plus⟩,⟨Factors.P189.factor9Minus,0,Factors.P189.checked9Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P189.factor10Plus,0,Factors.P189.checked10Plus⟩,⟨Factors.P189.factor10Minus,0,Factors.P189.checked10Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P189.factor11Plus,0,Factors.P189.checked11Plus⟩,⟨Factors.P189.factor11Minus,0,Factors.P189.checked11Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P189.factor12Plus,0,Factors.P189.checked12Plus⟩,⟨Factors.P189.factor12Minus,0,Factors.P189.checked12Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P189.factor13Plus,0,Factors.P189.checked13Plus⟩,⟨Factors.P189.factor13Minus,0,Factors.P189.checked13Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P189.factor14Plus,0,Factors.P189.checked14Plus⟩,⟨Factors.P189.factor14Minus,0,Factors.P189.checked14Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P189.factor15Plus,0,Factors.P189.checked15Plus⟩,⟨Factors.P189.factor15Minus,0,Factors.P189.checked15Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P190.factor0Plus,0,Factors.P190.checked0Plus⟩,⟨Factors.P190.factor0Minus,0,Factors.P190.checked0Minus⟩⟩)
    ((fun impossible => Fin.elim0 impossible)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))

end
end LAlanine40K2025.Thermal.Recovery.Reservoir.Pointer.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Rows
end SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule
