import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.OrdinaryPair
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P193
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P194
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P195
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P196
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P197

set_option autoImplicit false
namespace SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule
namespace LAlanine40K2025.Thermal.Recovery.Reservoir.Pointer.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Rows
open Propagation.Interface
noncomputable section

set_option maxHeartbeats 400000 in
def row40 : (b : Basis) → (40 : Basis) < b → OrdinaryPair 40 b :=
  Fin.cases (fun (ordered : (40 : Basis) < (0 : Basis)) => False.elim ((by decide +kernel : ¬ (40 : Basis) < (0 : Basis)) ordered))
    (Fin.cases (fun (ordered : (40 : Basis) < (1 : Basis)) => False.elim ((by decide +kernel : ¬ (40 : Basis) < (1 : Basis)) ordered))
    (Fin.cases (fun (ordered : (40 : Basis) < (2 : Basis)) => False.elim ((by decide +kernel : ¬ (40 : Basis) < (2 : Basis)) ordered))
    (Fin.cases (fun (ordered : (40 : Basis) < (3 : Basis)) => False.elim ((by decide +kernel : ¬ (40 : Basis) < (3 : Basis)) ordered))
    (Fin.cases (fun (ordered : (40 : Basis) < (4 : Basis)) => False.elim ((by decide +kernel : ¬ (40 : Basis) < (4 : Basis)) ordered))
    (Fin.cases (fun (ordered : (40 : Basis) < (5 : Basis)) => False.elim ((by decide +kernel : ¬ (40 : Basis) < (5 : Basis)) ordered))
    (Fin.cases (fun (ordered : (40 : Basis) < (6 : Basis)) => False.elim ((by decide +kernel : ¬ (40 : Basis) < (6 : Basis)) ordered))
    (Fin.cases (fun (ordered : (40 : Basis) < (7 : Basis)) => False.elim ((by decide +kernel : ¬ (40 : Basis) < (7 : Basis)) ordered))
    (Fin.cases (fun (ordered : (40 : Basis) < (8 : Basis)) => False.elim ((by decide +kernel : ¬ (40 : Basis) < (8 : Basis)) ordered))
    (Fin.cases (fun (ordered : (40 : Basis) < (9 : Basis)) => False.elim ((by decide +kernel : ¬ (40 : Basis) < (9 : Basis)) ordered))
    (Fin.cases (fun (ordered : (40 : Basis) < (10 : Basis)) => False.elim ((by decide +kernel : ¬ (40 : Basis) < (10 : Basis)) ordered))
    (Fin.cases (fun (ordered : (40 : Basis) < (11 : Basis)) => False.elim ((by decide +kernel : ¬ (40 : Basis) < (11 : Basis)) ordered))
    (Fin.cases (fun (ordered : (40 : Basis) < (12 : Basis)) => False.elim ((by decide +kernel : ¬ (40 : Basis) < (12 : Basis)) ordered))
    (Fin.cases (fun (ordered : (40 : Basis) < (13 : Basis)) => False.elim ((by decide +kernel : ¬ (40 : Basis) < (13 : Basis)) ordered))
    (Fin.cases (fun (ordered : (40 : Basis) < (14 : Basis)) => False.elim ((by decide +kernel : ¬ (40 : Basis) < (14 : Basis)) ordered))
    (Fin.cases (fun (ordered : (40 : Basis) < (15 : Basis)) => False.elim ((by decide +kernel : ¬ (40 : Basis) < (15 : Basis)) ordered))
    (Fin.cases (fun (ordered : (40 : Basis) < (16 : Basis)) => False.elim ((by decide +kernel : ¬ (40 : Basis) < (16 : Basis)) ordered))
    (Fin.cases (fun (ordered : (40 : Basis) < (17 : Basis)) => False.elim ((by decide +kernel : ¬ (40 : Basis) < (17 : Basis)) ordered))
    (Fin.cases (fun (ordered : (40 : Basis) < (18 : Basis)) => False.elim ((by decide +kernel : ¬ (40 : Basis) < (18 : Basis)) ordered))
    (Fin.cases (fun (ordered : (40 : Basis) < (19 : Basis)) => False.elim ((by decide +kernel : ¬ (40 : Basis) < (19 : Basis)) ordered))
    (Fin.cases (fun (ordered : (40 : Basis) < (20 : Basis)) => False.elim ((by decide +kernel : ¬ (40 : Basis) < (20 : Basis)) ordered))
    (Fin.cases (fun (ordered : (40 : Basis) < (21 : Basis)) => False.elim ((by decide +kernel : ¬ (40 : Basis) < (21 : Basis)) ordered))
    (Fin.cases (fun (ordered : (40 : Basis) < (22 : Basis)) => False.elim ((by decide +kernel : ¬ (40 : Basis) < (22 : Basis)) ordered))
    (Fin.cases (fun (ordered : (40 : Basis) < (23 : Basis)) => False.elim ((by decide +kernel : ¬ (40 : Basis) < (23 : Basis)) ordered))
    (Fin.cases (fun (ordered : (40 : Basis) < (24 : Basis)) => False.elim ((by decide +kernel : ¬ (40 : Basis) < (24 : Basis)) ordered))
    (Fin.cases (fun (ordered : (40 : Basis) < (25 : Basis)) => False.elim ((by decide +kernel : ¬ (40 : Basis) < (25 : Basis)) ordered))
    (Fin.cases (fun (ordered : (40 : Basis) < (26 : Basis)) => False.elim ((by decide +kernel : ¬ (40 : Basis) < (26 : Basis)) ordered))
    (Fin.cases (fun (ordered : (40 : Basis) < (27 : Basis)) => False.elim ((by decide +kernel : ¬ (40 : Basis) < (27 : Basis)) ordered))
    (Fin.cases (fun (ordered : (40 : Basis) < (28 : Basis)) => False.elim ((by decide +kernel : ¬ (40 : Basis) < (28 : Basis)) ordered))
    (Fin.cases (fun (ordered : (40 : Basis) < (29 : Basis)) => False.elim ((by decide +kernel : ¬ (40 : Basis) < (29 : Basis)) ordered))
    (Fin.cases (fun (ordered : (40 : Basis) < (30 : Basis)) => False.elim ((by decide +kernel : ¬ (40 : Basis) < (30 : Basis)) ordered))
    (Fin.cases (fun (ordered : (40 : Basis) < (31 : Basis)) => False.elim ((by decide +kernel : ¬ (40 : Basis) < (31 : Basis)) ordered))
    (Fin.cases (fun (ordered : (40 : Basis) < (32 : Basis)) => False.elim ((by decide +kernel : ¬ (40 : Basis) < (32 : Basis)) ordered))
    (Fin.cases (fun (ordered : (40 : Basis) < (33 : Basis)) => False.elim ((by decide +kernel : ¬ (40 : Basis) < (33 : Basis)) ordered))
    (Fin.cases (fun (ordered : (40 : Basis) < (34 : Basis)) => False.elim ((by decide +kernel : ¬ (40 : Basis) < (34 : Basis)) ordered))
    (Fin.cases (fun (ordered : (40 : Basis) < (35 : Basis)) => False.elim ((by decide +kernel : ¬ (40 : Basis) < (35 : Basis)) ordered))
    (Fin.cases (fun (ordered : (40 : Basis) < (36 : Basis)) => False.elim ((by decide +kernel : ¬ (40 : Basis) < (36 : Basis)) ordered))
    (Fin.cases (fun (ordered : (40 : Basis) < (37 : Basis)) => False.elim ((by decide +kernel : ¬ (40 : Basis) < (37 : Basis)) ordered))
    (Fin.cases (fun (ordered : (40 : Basis) < (38 : Basis)) => False.elim ((by decide +kernel : ¬ (40 : Basis) < (38 : Basis)) ordered))
    (Fin.cases (fun (ordered : (40 : Basis) < (39 : Basis)) => False.elim ((by decide +kernel : ¬ (40 : Basis) < (39 : Basis)) ordered))
    (Fin.cases (fun (ordered : (40 : Basis) < (40 : Basis)) => False.elim ((by decide +kernel : ¬ (40 : Basis) < (40 : Basis)) ordered))
    (Fin.cases (fun _ => ⟨⟨Factors.P193.factor11Plus,0,Factors.P193.checked11Plus⟩,⟨Factors.P193.factor11Minus,0,Factors.P193.checked11Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P193.factor12Plus,0,Factors.P193.checked12Plus⟩,⟨Factors.P193.factor12Minus,0,Factors.P193.checked12Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P193.factor13Plus,0,Factors.P193.checked13Plus⟩,⟨Factors.P193.factor13Minus,0,Factors.P193.checked13Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P193.factor14Plus,0,Factors.P193.checked14Plus⟩,⟨Factors.P193.factor14Minus,0,Factors.P193.checked14Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P193.factor15Plus,0,Factors.P193.checked15Plus⟩,⟨Factors.P193.factor15Minus,0,Factors.P193.checked15Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P194.factor0Plus,0,Factors.P194.checked0Plus⟩,⟨Factors.P194.factor0Minus,0,Factors.P194.checked0Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P194.factor1Plus,0,Factors.P194.checked1Plus⟩,⟨Factors.P194.factor1Minus,0,Factors.P194.checked1Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P194.factor2Plus,0,Factors.P194.checked2Plus⟩,⟨Factors.P194.factor2Minus,0,Factors.P194.checked2Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P194.factor3Plus,0,Factors.P194.checked3Plus⟩,⟨Factors.P194.factor3Minus,0,Factors.P194.checked3Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P194.factor4Plus,0,Factors.P194.checked4Plus⟩,⟨Factors.P194.factor4Minus,0,Factors.P194.checked4Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P194.factor5Plus,0,Factors.P194.checked5Plus⟩,⟨Factors.P194.factor5Minus,0,Factors.P194.checked5Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P194.factor6Plus,0,Factors.P194.checked6Plus⟩,⟨Factors.P194.factor6Minus,0,Factors.P194.checked6Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P194.factor7Plus,0,Factors.P194.checked7Plus⟩,⟨Factors.P194.factor7Minus,0,Factors.P194.checked7Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P194.factor8Plus,0,Factors.P194.checked8Plus⟩,⟨Factors.P194.factor8Minus,0,Factors.P194.checked8Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P194.factor9Plus,0,Factors.P194.checked9Plus⟩,⟨Factors.P194.factor9Minus,0,Factors.P194.checked9Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P194.factor10Plus,0,Factors.P194.checked10Plus⟩,⟨Factors.P194.factor10Minus,0,Factors.P194.checked10Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P194.factor11Plus,0,Factors.P194.checked11Plus⟩,⟨Factors.P194.factor11Minus,0,Factors.P194.checked11Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P194.factor12Plus,0,Factors.P194.checked12Plus⟩,⟨Factors.P194.factor12Minus,0,Factors.P194.checked12Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P194.factor13Plus,0,Factors.P194.checked13Plus⟩,⟨Factors.P194.factor13Minus,0,Factors.P194.checked13Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P194.factor14Plus,0,Factors.P194.checked14Plus⟩,⟨Factors.P194.factor14Minus,0,Factors.P194.checked14Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P194.factor15Plus,0,Factors.P194.checked15Plus⟩,⟨Factors.P194.factor15Minus,0,Factors.P194.checked15Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P195.factor0Plus,0,Factors.P195.checked0Plus⟩,⟨Factors.P195.factor0Minus,0,Factors.P195.checked0Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P195.factor1Plus,0,Factors.P195.checked1Plus⟩,⟨Factors.P195.factor1Minus,0,Factors.P195.checked1Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P195.factor2Plus,0,Factors.P195.checked2Plus⟩,⟨Factors.P195.factor2Minus,0,Factors.P195.checked2Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P195.factor3Plus,0,Factors.P195.checked3Plus⟩,⟨Factors.P195.factor3Minus,0,Factors.P195.checked3Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P195.factor4Plus,0,Factors.P195.checked4Plus⟩,⟨Factors.P195.factor4Minus,0,Factors.P195.checked4Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P195.factor5Plus,0,Factors.P195.checked5Plus⟩,⟨Factors.P195.factor5Minus,0,Factors.P195.checked5Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P195.factor6Plus,0,Factors.P195.checked6Plus⟩,⟨Factors.P195.factor6Minus,0,Factors.P195.checked6Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P195.factor7Plus,0,Factors.P195.checked7Plus⟩,⟨Factors.P195.factor7Minus,0,Factors.P195.checked7Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P195.factor8Plus,0,Factors.P195.checked8Plus⟩,⟨Factors.P195.factor8Minus,0,Factors.P195.checked8Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P195.factor9Plus,0,Factors.P195.checked9Plus⟩,⟨Factors.P195.factor9Minus,0,Factors.P195.checked9Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P195.factor10Plus,0,Factors.P195.checked10Plus⟩,⟨Factors.P195.factor10Minus,0,Factors.P195.checked10Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P195.factor11Plus,0,Factors.P195.checked11Plus⟩,⟨Factors.P195.factor11Minus,0,Factors.P195.checked11Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P195.factor12Plus,0,Factors.P195.checked12Plus⟩,⟨Factors.P195.factor12Minus,0,Factors.P195.checked12Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P195.factor13Plus,0,Factors.P195.checked13Plus⟩,⟨Factors.P195.factor13Minus,0,Factors.P195.checked13Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P195.factor14Plus,0,Factors.P195.checked14Plus⟩,⟨Factors.P195.factor14Minus,0,Factors.P195.checked14Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P195.factor15Plus,0,Factors.P195.checked15Plus⟩,⟨Factors.P195.factor15Minus,0,Factors.P195.checked15Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P196.factor0Plus,0,Factors.P196.checked0Plus⟩,⟨Factors.P196.factor0Minus,0,Factors.P196.checked0Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P196.factor1Plus,0,Factors.P196.checked1Plus⟩,⟨Factors.P196.factor1Minus,0,Factors.P196.checked1Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P196.factor2Plus,0,Factors.P196.checked2Plus⟩,⟨Factors.P196.factor2Minus,0,Factors.P196.checked2Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P196.factor3Plus,0,Factors.P196.checked3Plus⟩,⟨Factors.P196.factor3Minus,0,Factors.P196.checked3Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P196.factor4Plus,0,Factors.P196.checked4Plus⟩,⟨Factors.P196.factor4Minus,0,Factors.P196.checked4Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P196.factor5Plus,0,Factors.P196.checked5Plus⟩,⟨Factors.P196.factor5Minus,0,Factors.P196.checked5Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P196.factor6Plus,0,Factors.P196.checked6Plus⟩,⟨Factors.P196.factor6Minus,0,Factors.P196.checked6Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P196.factor7Plus,0,Factors.P196.checked7Plus⟩,⟨Factors.P196.factor7Minus,0,Factors.P196.checked7Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P196.factor8Plus,0,Factors.P196.checked8Plus⟩,⟨Factors.P196.factor8Minus,0,Factors.P196.checked8Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P196.factor9Plus,0,Factors.P196.checked9Plus⟩,⟨Factors.P196.factor9Minus,0,Factors.P196.checked9Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P196.factor10Plus,0,Factors.P196.checked10Plus⟩,⟨Factors.P196.factor10Minus,0,Factors.P196.checked10Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P196.factor11Plus,0,Factors.P196.checked11Plus⟩,⟨Factors.P196.factor11Minus,0,Factors.P196.checked11Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P196.factor12Plus,0,Factors.P196.checked12Plus⟩,⟨Factors.P196.factor12Minus,0,Factors.P196.checked12Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P196.factor13Plus,0,Factors.P196.checked13Plus⟩,⟨Factors.P196.factor13Minus,0,Factors.P196.checked13Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P196.factor14Plus,0,Factors.P196.checked14Plus⟩,⟨Factors.P196.factor14Minus,0,Factors.P196.checked14Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P196.factor15Plus,0,Factors.P196.checked15Plus⟩,⟨Factors.P196.factor15Minus,0,Factors.P196.checked15Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P197.factor0Plus,0,Factors.P197.checked0Plus⟩,⟨Factors.P197.factor0Minus,0,Factors.P197.checked0Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P197.factor1Plus,0,Factors.P197.checked1Plus⟩,⟨Factors.P197.factor1Minus,0,Factors.P197.checked1Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P197.factor2Plus,0,Factors.P197.checked2Plus⟩,⟨Factors.P197.factor2Minus,0,Factors.P197.checked2Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P197.factor3Plus,0,Factors.P197.checked3Plus⟩,⟨Factors.P197.factor3Minus,0,Factors.P197.checked3Minus⟩⟩)
    ((fun impossible => Fin.elim0 impossible)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))

end
end LAlanine40K2025.Thermal.Recovery.Reservoir.Pointer.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Rows
end SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule
