import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.OrdinaryPair
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P197
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P198
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P199
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P200

set_option autoImplicit false
namespace SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule
namespace LAlanine40K2025.Thermal.Recovery.Reservoir.Pointer.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Rows
open Propagation.Interface
noncomputable section

set_option maxHeartbeats 400000 in
def row41 : (b : Basis) → (41 : Basis) < b → OrdinaryPair 41 b :=
  Fin.cases (fun (ordered : (41 : Basis) < (0 : Basis)) => False.elim ((by decide +kernel : ¬ (41 : Basis) < (0 : Basis)) ordered))
    (Fin.cases (fun (ordered : (41 : Basis) < (1 : Basis)) => False.elim ((by decide +kernel : ¬ (41 : Basis) < (1 : Basis)) ordered))
    (Fin.cases (fun (ordered : (41 : Basis) < (2 : Basis)) => False.elim ((by decide +kernel : ¬ (41 : Basis) < (2 : Basis)) ordered))
    (Fin.cases (fun (ordered : (41 : Basis) < (3 : Basis)) => False.elim ((by decide +kernel : ¬ (41 : Basis) < (3 : Basis)) ordered))
    (Fin.cases (fun (ordered : (41 : Basis) < (4 : Basis)) => False.elim ((by decide +kernel : ¬ (41 : Basis) < (4 : Basis)) ordered))
    (Fin.cases (fun (ordered : (41 : Basis) < (5 : Basis)) => False.elim ((by decide +kernel : ¬ (41 : Basis) < (5 : Basis)) ordered))
    (Fin.cases (fun (ordered : (41 : Basis) < (6 : Basis)) => False.elim ((by decide +kernel : ¬ (41 : Basis) < (6 : Basis)) ordered))
    (Fin.cases (fun (ordered : (41 : Basis) < (7 : Basis)) => False.elim ((by decide +kernel : ¬ (41 : Basis) < (7 : Basis)) ordered))
    (Fin.cases (fun (ordered : (41 : Basis) < (8 : Basis)) => False.elim ((by decide +kernel : ¬ (41 : Basis) < (8 : Basis)) ordered))
    (Fin.cases (fun (ordered : (41 : Basis) < (9 : Basis)) => False.elim ((by decide +kernel : ¬ (41 : Basis) < (9 : Basis)) ordered))
    (Fin.cases (fun (ordered : (41 : Basis) < (10 : Basis)) => False.elim ((by decide +kernel : ¬ (41 : Basis) < (10 : Basis)) ordered))
    (Fin.cases (fun (ordered : (41 : Basis) < (11 : Basis)) => False.elim ((by decide +kernel : ¬ (41 : Basis) < (11 : Basis)) ordered))
    (Fin.cases (fun (ordered : (41 : Basis) < (12 : Basis)) => False.elim ((by decide +kernel : ¬ (41 : Basis) < (12 : Basis)) ordered))
    (Fin.cases (fun (ordered : (41 : Basis) < (13 : Basis)) => False.elim ((by decide +kernel : ¬ (41 : Basis) < (13 : Basis)) ordered))
    (Fin.cases (fun (ordered : (41 : Basis) < (14 : Basis)) => False.elim ((by decide +kernel : ¬ (41 : Basis) < (14 : Basis)) ordered))
    (Fin.cases (fun (ordered : (41 : Basis) < (15 : Basis)) => False.elim ((by decide +kernel : ¬ (41 : Basis) < (15 : Basis)) ordered))
    (Fin.cases (fun (ordered : (41 : Basis) < (16 : Basis)) => False.elim ((by decide +kernel : ¬ (41 : Basis) < (16 : Basis)) ordered))
    (Fin.cases (fun (ordered : (41 : Basis) < (17 : Basis)) => False.elim ((by decide +kernel : ¬ (41 : Basis) < (17 : Basis)) ordered))
    (Fin.cases (fun (ordered : (41 : Basis) < (18 : Basis)) => False.elim ((by decide +kernel : ¬ (41 : Basis) < (18 : Basis)) ordered))
    (Fin.cases (fun (ordered : (41 : Basis) < (19 : Basis)) => False.elim ((by decide +kernel : ¬ (41 : Basis) < (19 : Basis)) ordered))
    (Fin.cases (fun (ordered : (41 : Basis) < (20 : Basis)) => False.elim ((by decide +kernel : ¬ (41 : Basis) < (20 : Basis)) ordered))
    (Fin.cases (fun (ordered : (41 : Basis) < (21 : Basis)) => False.elim ((by decide +kernel : ¬ (41 : Basis) < (21 : Basis)) ordered))
    (Fin.cases (fun (ordered : (41 : Basis) < (22 : Basis)) => False.elim ((by decide +kernel : ¬ (41 : Basis) < (22 : Basis)) ordered))
    (Fin.cases (fun (ordered : (41 : Basis) < (23 : Basis)) => False.elim ((by decide +kernel : ¬ (41 : Basis) < (23 : Basis)) ordered))
    (Fin.cases (fun (ordered : (41 : Basis) < (24 : Basis)) => False.elim ((by decide +kernel : ¬ (41 : Basis) < (24 : Basis)) ordered))
    (Fin.cases (fun (ordered : (41 : Basis) < (25 : Basis)) => False.elim ((by decide +kernel : ¬ (41 : Basis) < (25 : Basis)) ordered))
    (Fin.cases (fun (ordered : (41 : Basis) < (26 : Basis)) => False.elim ((by decide +kernel : ¬ (41 : Basis) < (26 : Basis)) ordered))
    (Fin.cases (fun (ordered : (41 : Basis) < (27 : Basis)) => False.elim ((by decide +kernel : ¬ (41 : Basis) < (27 : Basis)) ordered))
    (Fin.cases (fun (ordered : (41 : Basis) < (28 : Basis)) => False.elim ((by decide +kernel : ¬ (41 : Basis) < (28 : Basis)) ordered))
    (Fin.cases (fun (ordered : (41 : Basis) < (29 : Basis)) => False.elim ((by decide +kernel : ¬ (41 : Basis) < (29 : Basis)) ordered))
    (Fin.cases (fun (ordered : (41 : Basis) < (30 : Basis)) => False.elim ((by decide +kernel : ¬ (41 : Basis) < (30 : Basis)) ordered))
    (Fin.cases (fun (ordered : (41 : Basis) < (31 : Basis)) => False.elim ((by decide +kernel : ¬ (41 : Basis) < (31 : Basis)) ordered))
    (Fin.cases (fun (ordered : (41 : Basis) < (32 : Basis)) => False.elim ((by decide +kernel : ¬ (41 : Basis) < (32 : Basis)) ordered))
    (Fin.cases (fun (ordered : (41 : Basis) < (33 : Basis)) => False.elim ((by decide +kernel : ¬ (41 : Basis) < (33 : Basis)) ordered))
    (Fin.cases (fun (ordered : (41 : Basis) < (34 : Basis)) => False.elim ((by decide +kernel : ¬ (41 : Basis) < (34 : Basis)) ordered))
    (Fin.cases (fun (ordered : (41 : Basis) < (35 : Basis)) => False.elim ((by decide +kernel : ¬ (41 : Basis) < (35 : Basis)) ordered))
    (Fin.cases (fun (ordered : (41 : Basis) < (36 : Basis)) => False.elim ((by decide +kernel : ¬ (41 : Basis) < (36 : Basis)) ordered))
    (Fin.cases (fun (ordered : (41 : Basis) < (37 : Basis)) => False.elim ((by decide +kernel : ¬ (41 : Basis) < (37 : Basis)) ordered))
    (Fin.cases (fun (ordered : (41 : Basis) < (38 : Basis)) => False.elim ((by decide +kernel : ¬ (41 : Basis) < (38 : Basis)) ordered))
    (Fin.cases (fun (ordered : (41 : Basis) < (39 : Basis)) => False.elim ((by decide +kernel : ¬ (41 : Basis) < (39 : Basis)) ordered))
    (Fin.cases (fun (ordered : (41 : Basis) < (40 : Basis)) => False.elim ((by decide +kernel : ¬ (41 : Basis) < (40 : Basis)) ordered))
    (Fin.cases (fun (ordered : (41 : Basis) < (41 : Basis)) => False.elim ((by decide +kernel : ¬ (41 : Basis) < (41 : Basis)) ordered))
    (Fin.cases (fun _ => ⟨⟨Factors.P197.factor4Plus,0,Factors.P197.checked4Plus⟩,⟨Factors.P197.factor4Minus,0,Factors.P197.checked4Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P197.factor5Plus,0,Factors.P197.checked5Plus⟩,⟨Factors.P197.factor5Minus,0,Factors.P197.checked5Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P197.factor6Plus,0,Factors.P197.checked6Plus⟩,⟨Factors.P197.factor6Minus,0,Factors.P197.checked6Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P197.factor7Plus,0,Factors.P197.checked7Plus⟩,⟨Factors.P197.factor7Minus,0,Factors.P197.checked7Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P197.factor8Plus,0,Factors.P197.checked8Plus⟩,⟨Factors.P197.factor8Minus,0,Factors.P197.checked8Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P197.factor9Plus,0,Factors.P197.checked9Plus⟩,⟨Factors.P197.factor9Minus,0,Factors.P197.checked9Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P197.factor10Plus,0,Factors.P197.checked10Plus⟩,⟨Factors.P197.factor10Minus,0,Factors.P197.checked10Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P197.factor11Plus,0,Factors.P197.checked11Plus⟩,⟨Factors.P197.factor11Minus,0,Factors.P197.checked11Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P197.factor12Plus,0,Factors.P197.checked12Plus⟩,⟨Factors.P197.factor12Minus,0,Factors.P197.checked12Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P197.factor13Plus,0,Factors.P197.checked13Plus⟩,⟨Factors.P197.factor13Minus,0,Factors.P197.checked13Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P197.factor14Plus,0,Factors.P197.checked14Plus⟩,⟨Factors.P197.factor14Minus,0,Factors.P197.checked14Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P197.factor15Plus,0,Factors.P197.checked15Plus⟩,⟨Factors.P197.factor15Minus,0,Factors.P197.checked15Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P198.factor0Plus,0,Factors.P198.checked0Plus⟩,⟨Factors.P198.factor0Minus,0,Factors.P198.checked0Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P198.factor1Plus,0,Factors.P198.checked1Plus⟩,⟨Factors.P198.factor1Minus,0,Factors.P198.checked1Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P198.factor2Plus,0,Factors.P198.checked2Plus⟩,⟨Factors.P198.factor2Minus,0,Factors.P198.checked2Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P198.factor3Plus,0,Factors.P198.checked3Plus⟩,⟨Factors.P198.factor3Minus,0,Factors.P198.checked3Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P198.factor4Plus,0,Factors.P198.checked4Plus⟩,⟨Factors.P198.factor4Minus,0,Factors.P198.checked4Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P198.factor5Plus,0,Factors.P198.checked5Plus⟩,⟨Factors.P198.factor5Minus,0,Factors.P198.checked5Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P198.factor6Plus,0,Factors.P198.checked6Plus⟩,⟨Factors.P198.factor6Minus,0,Factors.P198.checked6Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P198.factor7Plus,0,Factors.P198.checked7Plus⟩,⟨Factors.P198.factor7Minus,0,Factors.P198.checked7Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P198.factor8Plus,0,Factors.P198.checked8Plus⟩,⟨Factors.P198.factor8Minus,0,Factors.P198.checked8Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P198.factor9Plus,0,Factors.P198.checked9Plus⟩,⟨Factors.P198.factor9Minus,0,Factors.P198.checked9Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P198.factor10Plus,0,Factors.P198.checked10Plus⟩,⟨Factors.P198.factor10Minus,0,Factors.P198.checked10Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P198.factor11Plus,0,Factors.P198.checked11Plus⟩,⟨Factors.P198.factor11Minus,0,Factors.P198.checked11Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P198.factor12Plus,0,Factors.P198.checked12Plus⟩,⟨Factors.P198.factor12Minus,0,Factors.P198.checked12Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P198.factor13Plus,0,Factors.P198.checked13Plus⟩,⟨Factors.P198.factor13Minus,0,Factors.P198.checked13Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P198.factor14Plus,0,Factors.P198.checked14Plus⟩,⟨Factors.P198.factor14Minus,0,Factors.P198.checked14Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P198.factor15Plus,0,Factors.P198.checked15Plus⟩,⟨Factors.P198.factor15Minus,0,Factors.P198.checked15Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P199.factor0Plus,0,Factors.P199.checked0Plus⟩,⟨Factors.P199.factor0Minus,0,Factors.P199.checked0Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P199.factor1Plus,0,Factors.P199.checked1Plus⟩,⟨Factors.P199.factor1Minus,0,Factors.P199.checked1Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P199.factor2Plus,0,Factors.P199.checked2Plus⟩,⟨Factors.P199.factor2Minus,0,Factors.P199.checked2Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P199.factor3Plus,0,Factors.P199.checked3Plus⟩,⟨Factors.P199.factor3Minus,0,Factors.P199.checked3Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P199.factor4Plus,0,Factors.P199.checked4Plus⟩,⟨Factors.P199.factor4Minus,0,Factors.P199.checked4Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P199.factor5Plus,0,Factors.P199.checked5Plus⟩,⟨Factors.P199.factor5Minus,0,Factors.P199.checked5Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P199.factor6Plus,0,Factors.P199.checked6Plus⟩,⟨Factors.P199.factor6Minus,0,Factors.P199.checked6Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P199.factor7Plus,0,Factors.P199.checked7Plus⟩,⟨Factors.P199.factor7Minus,0,Factors.P199.checked7Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P199.factor8Plus,0,Factors.P199.checked8Plus⟩,⟨Factors.P199.factor8Minus,0,Factors.P199.checked8Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P199.factor9Plus,0,Factors.P199.checked9Plus⟩,⟨Factors.P199.factor9Minus,0,Factors.P199.checked9Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P199.factor10Plus,0,Factors.P199.checked10Plus⟩,⟨Factors.P199.factor10Minus,0,Factors.P199.checked10Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P199.factor11Plus,0,Factors.P199.checked11Plus⟩,⟨Factors.P199.factor11Minus,0,Factors.P199.checked11Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P199.factor12Plus,0,Factors.P199.checked12Plus⟩,⟨Factors.P199.factor12Minus,0,Factors.P199.checked12Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P199.factor13Plus,0,Factors.P199.checked13Plus⟩,⟨Factors.P199.factor13Minus,0,Factors.P199.checked13Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P199.factor14Plus,0,Factors.P199.checked14Plus⟩,⟨Factors.P199.factor14Minus,0,Factors.P199.checked14Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P199.factor15Plus,0,Factors.P199.checked15Plus⟩,⟨Factors.P199.factor15Minus,0,Factors.P199.checked15Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P200.factor0Plus,0,Factors.P200.checked0Plus⟩,⟨Factors.P200.factor0Minus,0,Factors.P200.checked0Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P200.factor1Plus,0,Factors.P200.checked1Plus⟩,⟨Factors.P200.factor1Minus,0,Factors.P200.checked1Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P200.factor2Plus,0,Factors.P200.checked2Plus⟩,⟨Factors.P200.factor2Minus,0,Factors.P200.checked2Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P200.factor3Plus,0,Factors.P200.checked3Plus⟩,⟨Factors.P200.factor3Minus,0,Factors.P200.checked3Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P200.factor4Plus,0,Factors.P200.checked4Plus⟩,⟨Factors.P200.factor4Minus,0,Factors.P200.checked4Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P200.factor5Plus,0,Factors.P200.checked5Plus⟩,⟨Factors.P200.factor5Minus,0,Factors.P200.checked5Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P200.factor6Plus,0,Factors.P200.checked6Plus⟩,⟨Factors.P200.factor6Minus,0,Factors.P200.checked6Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P200.factor7Plus,0,Factors.P200.checked7Plus⟩,⟨Factors.P200.factor7Minus,0,Factors.P200.checked7Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P200.factor8Plus,0,Factors.P200.checked8Plus⟩,⟨Factors.P200.factor8Minus,0,Factors.P200.checked8Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P200.factor9Plus,0,Factors.P200.checked9Plus⟩,⟨Factors.P200.factor9Minus,0,Factors.P200.checked9Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P200.factor10Plus,0,Factors.P200.checked10Plus⟩,⟨Factors.P200.factor10Minus,0,Factors.P200.checked10Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P200.factor11Plus,0,Factors.P200.checked11Plus⟩,⟨Factors.P200.factor11Minus,0,Factors.P200.checked11Minus⟩⟩)
    ((fun impossible => Fin.elim0 impossible)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))

end
end LAlanine40K2025.Thermal.Recovery.Reservoir.Pointer.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Rows
end SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule
