import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.OrdinaryPair
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P204
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P205
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P206
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P207

set_option autoImplicit false
namespace SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule
namespace LAlanine40K2025.Thermal.Recovery.Reservoir.Pointer.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Rows
open Propagation.Interface
noncomputable section

set_option maxHeartbeats 400000 in
def row43 : (b : Basis) → (43 : Basis) < b → OrdinaryPair 43 b :=
  Fin.cases (fun (ordered : (43 : Basis) < (0 : Basis)) => False.elim ((by decide +kernel : ¬ (43 : Basis) < (0 : Basis)) ordered))
    (Fin.cases (fun (ordered : (43 : Basis) < (1 : Basis)) => False.elim ((by decide +kernel : ¬ (43 : Basis) < (1 : Basis)) ordered))
    (Fin.cases (fun (ordered : (43 : Basis) < (2 : Basis)) => False.elim ((by decide +kernel : ¬ (43 : Basis) < (2 : Basis)) ordered))
    (Fin.cases (fun (ordered : (43 : Basis) < (3 : Basis)) => False.elim ((by decide +kernel : ¬ (43 : Basis) < (3 : Basis)) ordered))
    (Fin.cases (fun (ordered : (43 : Basis) < (4 : Basis)) => False.elim ((by decide +kernel : ¬ (43 : Basis) < (4 : Basis)) ordered))
    (Fin.cases (fun (ordered : (43 : Basis) < (5 : Basis)) => False.elim ((by decide +kernel : ¬ (43 : Basis) < (5 : Basis)) ordered))
    (Fin.cases (fun (ordered : (43 : Basis) < (6 : Basis)) => False.elim ((by decide +kernel : ¬ (43 : Basis) < (6 : Basis)) ordered))
    (Fin.cases (fun (ordered : (43 : Basis) < (7 : Basis)) => False.elim ((by decide +kernel : ¬ (43 : Basis) < (7 : Basis)) ordered))
    (Fin.cases (fun (ordered : (43 : Basis) < (8 : Basis)) => False.elim ((by decide +kernel : ¬ (43 : Basis) < (8 : Basis)) ordered))
    (Fin.cases (fun (ordered : (43 : Basis) < (9 : Basis)) => False.elim ((by decide +kernel : ¬ (43 : Basis) < (9 : Basis)) ordered))
    (Fin.cases (fun (ordered : (43 : Basis) < (10 : Basis)) => False.elim ((by decide +kernel : ¬ (43 : Basis) < (10 : Basis)) ordered))
    (Fin.cases (fun (ordered : (43 : Basis) < (11 : Basis)) => False.elim ((by decide +kernel : ¬ (43 : Basis) < (11 : Basis)) ordered))
    (Fin.cases (fun (ordered : (43 : Basis) < (12 : Basis)) => False.elim ((by decide +kernel : ¬ (43 : Basis) < (12 : Basis)) ordered))
    (Fin.cases (fun (ordered : (43 : Basis) < (13 : Basis)) => False.elim ((by decide +kernel : ¬ (43 : Basis) < (13 : Basis)) ordered))
    (Fin.cases (fun (ordered : (43 : Basis) < (14 : Basis)) => False.elim ((by decide +kernel : ¬ (43 : Basis) < (14 : Basis)) ordered))
    (Fin.cases (fun (ordered : (43 : Basis) < (15 : Basis)) => False.elim ((by decide +kernel : ¬ (43 : Basis) < (15 : Basis)) ordered))
    (Fin.cases (fun (ordered : (43 : Basis) < (16 : Basis)) => False.elim ((by decide +kernel : ¬ (43 : Basis) < (16 : Basis)) ordered))
    (Fin.cases (fun (ordered : (43 : Basis) < (17 : Basis)) => False.elim ((by decide +kernel : ¬ (43 : Basis) < (17 : Basis)) ordered))
    (Fin.cases (fun (ordered : (43 : Basis) < (18 : Basis)) => False.elim ((by decide +kernel : ¬ (43 : Basis) < (18 : Basis)) ordered))
    (Fin.cases (fun (ordered : (43 : Basis) < (19 : Basis)) => False.elim ((by decide +kernel : ¬ (43 : Basis) < (19 : Basis)) ordered))
    (Fin.cases (fun (ordered : (43 : Basis) < (20 : Basis)) => False.elim ((by decide +kernel : ¬ (43 : Basis) < (20 : Basis)) ordered))
    (Fin.cases (fun (ordered : (43 : Basis) < (21 : Basis)) => False.elim ((by decide +kernel : ¬ (43 : Basis) < (21 : Basis)) ordered))
    (Fin.cases (fun (ordered : (43 : Basis) < (22 : Basis)) => False.elim ((by decide +kernel : ¬ (43 : Basis) < (22 : Basis)) ordered))
    (Fin.cases (fun (ordered : (43 : Basis) < (23 : Basis)) => False.elim ((by decide +kernel : ¬ (43 : Basis) < (23 : Basis)) ordered))
    (Fin.cases (fun (ordered : (43 : Basis) < (24 : Basis)) => False.elim ((by decide +kernel : ¬ (43 : Basis) < (24 : Basis)) ordered))
    (Fin.cases (fun (ordered : (43 : Basis) < (25 : Basis)) => False.elim ((by decide +kernel : ¬ (43 : Basis) < (25 : Basis)) ordered))
    (Fin.cases (fun (ordered : (43 : Basis) < (26 : Basis)) => False.elim ((by decide +kernel : ¬ (43 : Basis) < (26 : Basis)) ordered))
    (Fin.cases (fun (ordered : (43 : Basis) < (27 : Basis)) => False.elim ((by decide +kernel : ¬ (43 : Basis) < (27 : Basis)) ordered))
    (Fin.cases (fun (ordered : (43 : Basis) < (28 : Basis)) => False.elim ((by decide +kernel : ¬ (43 : Basis) < (28 : Basis)) ordered))
    (Fin.cases (fun (ordered : (43 : Basis) < (29 : Basis)) => False.elim ((by decide +kernel : ¬ (43 : Basis) < (29 : Basis)) ordered))
    (Fin.cases (fun (ordered : (43 : Basis) < (30 : Basis)) => False.elim ((by decide +kernel : ¬ (43 : Basis) < (30 : Basis)) ordered))
    (Fin.cases (fun (ordered : (43 : Basis) < (31 : Basis)) => False.elim ((by decide +kernel : ¬ (43 : Basis) < (31 : Basis)) ordered))
    (Fin.cases (fun (ordered : (43 : Basis) < (32 : Basis)) => False.elim ((by decide +kernel : ¬ (43 : Basis) < (32 : Basis)) ordered))
    (Fin.cases (fun (ordered : (43 : Basis) < (33 : Basis)) => False.elim ((by decide +kernel : ¬ (43 : Basis) < (33 : Basis)) ordered))
    (Fin.cases (fun (ordered : (43 : Basis) < (34 : Basis)) => False.elim ((by decide +kernel : ¬ (43 : Basis) < (34 : Basis)) ordered))
    (Fin.cases (fun (ordered : (43 : Basis) < (35 : Basis)) => False.elim ((by decide +kernel : ¬ (43 : Basis) < (35 : Basis)) ordered))
    (Fin.cases (fun (ordered : (43 : Basis) < (36 : Basis)) => False.elim ((by decide +kernel : ¬ (43 : Basis) < (36 : Basis)) ordered))
    (Fin.cases (fun (ordered : (43 : Basis) < (37 : Basis)) => False.elim ((by decide +kernel : ¬ (43 : Basis) < (37 : Basis)) ordered))
    (Fin.cases (fun (ordered : (43 : Basis) < (38 : Basis)) => False.elim ((by decide +kernel : ¬ (43 : Basis) < (38 : Basis)) ordered))
    (Fin.cases (fun (ordered : (43 : Basis) < (39 : Basis)) => False.elim ((by decide +kernel : ¬ (43 : Basis) < (39 : Basis)) ordered))
    (Fin.cases (fun (ordered : (43 : Basis) < (40 : Basis)) => False.elim ((by decide +kernel : ¬ (43 : Basis) < (40 : Basis)) ordered))
    (Fin.cases (fun (ordered : (43 : Basis) < (41 : Basis)) => False.elim ((by decide +kernel : ¬ (43 : Basis) < (41 : Basis)) ordered))
    (Fin.cases (fun (ordered : (43 : Basis) < (42 : Basis)) => False.elim ((by decide +kernel : ¬ (43 : Basis) < (42 : Basis)) ordered))
    (Fin.cases (fun (ordered : (43 : Basis) < (43 : Basis)) => False.elim ((by decide +kernel : ¬ (43 : Basis) < (43 : Basis)) ordered))
    (Fin.cases (fun _ => ⟨⟨Factors.P204.factor3Plus,0,Factors.P204.checked3Plus⟩,⟨Factors.P204.factor3Minus,0,Factors.P204.checked3Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P204.factor4Plus,0,Factors.P204.checked4Plus⟩,⟨Factors.P204.factor4Minus,0,Factors.P204.checked4Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P204.factor5Plus,0,Factors.P204.checked5Plus⟩,⟨Factors.P204.factor5Minus,0,Factors.P204.checked5Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P204.factor6Plus,0,Factors.P204.checked6Plus⟩,⟨Factors.P204.factor6Minus,0,Factors.P204.checked6Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P204.factor7Plus,0,Factors.P204.checked7Plus⟩,⟨Factors.P204.factor7Minus,0,Factors.P204.checked7Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P204.factor8Plus,0,Factors.P204.checked8Plus⟩,⟨Factors.P204.factor8Minus,0,Factors.P204.checked8Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P204.factor9Plus,0,Factors.P204.checked9Plus⟩,⟨Factors.P204.factor9Minus,0,Factors.P204.checked9Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P204.factor10Plus,0,Factors.P204.checked10Plus⟩,⟨Factors.P204.factor10Minus,0,Factors.P204.checked10Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P204.factor11Plus,0,Factors.P204.checked11Plus⟩,⟨Factors.P204.factor11Minus,0,Factors.P204.checked11Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P204.factor12Plus,0,Factors.P204.checked12Plus⟩,⟨Factors.P204.factor12Minus,0,Factors.P204.checked12Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P204.factor13Plus,0,Factors.P204.checked13Plus⟩,⟨Factors.P204.factor13Minus,0,Factors.P204.checked13Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P204.factor14Plus,0,Factors.P204.checked14Plus⟩,⟨Factors.P204.factor14Minus,0,Factors.P204.checked14Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P204.factor15Plus,0,Factors.P204.checked15Plus⟩,⟨Factors.P204.factor15Minus,0,Factors.P204.checked15Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P205.factor0Plus,0,Factors.P205.checked0Plus⟩,⟨Factors.P205.factor0Minus,0,Factors.P205.checked0Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P205.factor1Plus,0,Factors.P205.checked1Plus⟩,⟨Factors.P205.factor1Minus,0,Factors.P205.checked1Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P205.factor2Plus,0,Factors.P205.checked2Plus⟩,⟨Factors.P205.factor2Minus,0,Factors.P205.checked2Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P205.factor3Plus,0,Factors.P205.checked3Plus⟩,⟨Factors.P205.factor3Minus,0,Factors.P205.checked3Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P205.factor4Plus,0,Factors.P205.checked4Plus⟩,⟨Factors.P205.factor4Minus,0,Factors.P205.checked4Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P205.factor5Plus,0,Factors.P205.checked5Plus⟩,⟨Factors.P205.factor5Minus,0,Factors.P205.checked5Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P205.factor6Plus,0,Factors.P205.checked6Plus⟩,⟨Factors.P205.factor6Minus,0,Factors.P205.checked6Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P205.factor7Plus,0,Factors.P205.checked7Plus⟩,⟨Factors.P205.factor7Minus,0,Factors.P205.checked7Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P205.factor8Plus,0,Factors.P205.checked8Plus⟩,⟨Factors.P205.factor8Minus,0,Factors.P205.checked8Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P205.factor9Plus,0,Factors.P205.checked9Plus⟩,⟨Factors.P205.factor9Minus,0,Factors.P205.checked9Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P205.factor10Plus,0,Factors.P205.checked10Plus⟩,⟨Factors.P205.factor10Minus,0,Factors.P205.checked10Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P205.factor11Plus,0,Factors.P205.checked11Plus⟩,⟨Factors.P205.factor11Minus,0,Factors.P205.checked11Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P205.factor12Plus,0,Factors.P205.checked12Plus⟩,⟨Factors.P205.factor12Minus,0,Factors.P205.checked12Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P205.factor13Plus,0,Factors.P205.checked13Plus⟩,⟨Factors.P205.factor13Minus,0,Factors.P205.checked13Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P205.factor14Plus,0,Factors.P205.checked14Plus⟩,⟨Factors.P205.factor14Minus,0,Factors.P205.checked14Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P205.factor15Plus,0,Factors.P205.checked15Plus⟩,⟨Factors.P205.factor15Minus,0,Factors.P205.checked15Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P206.factor0Plus,0,Factors.P206.checked0Plus⟩,⟨Factors.P206.factor0Minus,0,Factors.P206.checked0Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P206.factor1Plus,0,Factors.P206.checked1Plus⟩,⟨Factors.P206.factor1Minus,0,Factors.P206.checked1Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P206.factor2Plus,0,Factors.P206.checked2Plus⟩,⟨Factors.P206.factor2Minus,0,Factors.P206.checked2Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P206.factor3Plus,0,Factors.P206.checked3Plus⟩,⟨Factors.P206.factor3Minus,0,Factors.P206.checked3Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P206.factor4Plus,0,Factors.P206.checked4Plus⟩,⟨Factors.P206.factor4Minus,0,Factors.P206.checked4Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P206.factor5Plus,0,Factors.P206.checked5Plus⟩,⟨Factors.P206.factor5Minus,0,Factors.P206.checked5Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P206.factor6Plus,0,Factors.P206.checked6Plus⟩,⟨Factors.P206.factor6Minus,0,Factors.P206.checked6Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P206.factor7Plus,0,Factors.P206.checked7Plus⟩,⟨Factors.P206.factor7Minus,0,Factors.P206.checked7Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P206.factor8Plus,0,Factors.P206.checked8Plus⟩,⟨Factors.P206.factor8Minus,0,Factors.P206.checked8Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P206.factor9Plus,0,Factors.P206.checked9Plus⟩,⟨Factors.P206.factor9Minus,0,Factors.P206.checked9Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P206.factor10Plus,0,Factors.P206.checked10Plus⟩,⟨Factors.P206.factor10Minus,0,Factors.P206.checked10Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P206.factor11Plus,0,Factors.P206.checked11Plus⟩,⟨Factors.P206.factor11Minus,0,Factors.P206.checked11Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P206.factor12Plus,0,Factors.P206.checked12Plus⟩,⟨Factors.P206.factor12Minus,0,Factors.P206.checked12Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P206.factor13Plus,0,Factors.P206.checked13Plus⟩,⟨Factors.P206.factor13Minus,0,Factors.P206.checked13Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P206.factor14Plus,0,Factors.P206.checked14Plus⟩,⟨Factors.P206.factor14Minus,0,Factors.P206.checked14Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P206.factor15Plus,0,Factors.P206.checked15Plus⟩,⟨Factors.P206.factor15Minus,0,Factors.P206.checked15Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P207.factor0Plus,0,Factors.P207.checked0Plus⟩,⟨Factors.P207.factor0Minus,0,Factors.P207.checked0Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P207.factor1Plus,0,Factors.P207.checked1Plus⟩,⟨Factors.P207.factor1Minus,0,Factors.P207.checked1Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P207.factor2Plus,0,Factors.P207.checked2Plus⟩,⟨Factors.P207.factor2Minus,0,Factors.P207.checked2Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P207.factor3Plus,0,Factors.P207.checked3Plus⟩,⟨Factors.P207.factor3Minus,0,Factors.P207.checked3Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P207.factor4Plus,0,Factors.P207.checked4Plus⟩,⟨Factors.P207.factor4Minus,0,Factors.P207.checked4Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P207.factor5Plus,0,Factors.P207.checked5Plus⟩,⟨Factors.P207.factor5Minus,0,Factors.P207.checked5Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P207.factor6Plus,0,Factors.P207.checked6Plus⟩,⟨Factors.P207.factor6Minus,0,Factors.P207.checked6Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P207.factor7Plus,0,Factors.P207.checked7Plus⟩,⟨Factors.P207.factor7Minus,0,Factors.P207.checked7Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P207.factor8Plus,0,Factors.P207.checked8Plus⟩,⟨Factors.P207.factor8Minus,0,Factors.P207.checked8Minus⟩⟩)
    ((fun impossible => Fin.elim0 impossible)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))

end
end LAlanine40K2025.Thermal.Recovery.Reservoir.Pointer.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Rows
end SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule
