import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.OrdinaryPair
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P210
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P211
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P212
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P213
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P214

set_option autoImplicit false
namespace SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule
namespace LAlanine40K2025.Thermal.Recovery.Reservoir.Pointer.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Rows
open Propagation.Interface
noncomputable section

set_option maxHeartbeats 400000 in
def row45 : (b : Basis) → (45 : Basis) < b → OrdinaryPair 45 b :=
  Fin.cases (fun (ordered : (45 : Basis) < (0 : Basis)) => False.elim ((by decide +kernel : ¬ (45 : Basis) < (0 : Basis)) ordered))
    (Fin.cases (fun (ordered : (45 : Basis) < (1 : Basis)) => False.elim ((by decide +kernel : ¬ (45 : Basis) < (1 : Basis)) ordered))
    (Fin.cases (fun (ordered : (45 : Basis) < (2 : Basis)) => False.elim ((by decide +kernel : ¬ (45 : Basis) < (2 : Basis)) ordered))
    (Fin.cases (fun (ordered : (45 : Basis) < (3 : Basis)) => False.elim ((by decide +kernel : ¬ (45 : Basis) < (3 : Basis)) ordered))
    (Fin.cases (fun (ordered : (45 : Basis) < (4 : Basis)) => False.elim ((by decide +kernel : ¬ (45 : Basis) < (4 : Basis)) ordered))
    (Fin.cases (fun (ordered : (45 : Basis) < (5 : Basis)) => False.elim ((by decide +kernel : ¬ (45 : Basis) < (5 : Basis)) ordered))
    (Fin.cases (fun (ordered : (45 : Basis) < (6 : Basis)) => False.elim ((by decide +kernel : ¬ (45 : Basis) < (6 : Basis)) ordered))
    (Fin.cases (fun (ordered : (45 : Basis) < (7 : Basis)) => False.elim ((by decide +kernel : ¬ (45 : Basis) < (7 : Basis)) ordered))
    (Fin.cases (fun (ordered : (45 : Basis) < (8 : Basis)) => False.elim ((by decide +kernel : ¬ (45 : Basis) < (8 : Basis)) ordered))
    (Fin.cases (fun (ordered : (45 : Basis) < (9 : Basis)) => False.elim ((by decide +kernel : ¬ (45 : Basis) < (9 : Basis)) ordered))
    (Fin.cases (fun (ordered : (45 : Basis) < (10 : Basis)) => False.elim ((by decide +kernel : ¬ (45 : Basis) < (10 : Basis)) ordered))
    (Fin.cases (fun (ordered : (45 : Basis) < (11 : Basis)) => False.elim ((by decide +kernel : ¬ (45 : Basis) < (11 : Basis)) ordered))
    (Fin.cases (fun (ordered : (45 : Basis) < (12 : Basis)) => False.elim ((by decide +kernel : ¬ (45 : Basis) < (12 : Basis)) ordered))
    (Fin.cases (fun (ordered : (45 : Basis) < (13 : Basis)) => False.elim ((by decide +kernel : ¬ (45 : Basis) < (13 : Basis)) ordered))
    (Fin.cases (fun (ordered : (45 : Basis) < (14 : Basis)) => False.elim ((by decide +kernel : ¬ (45 : Basis) < (14 : Basis)) ordered))
    (Fin.cases (fun (ordered : (45 : Basis) < (15 : Basis)) => False.elim ((by decide +kernel : ¬ (45 : Basis) < (15 : Basis)) ordered))
    (Fin.cases (fun (ordered : (45 : Basis) < (16 : Basis)) => False.elim ((by decide +kernel : ¬ (45 : Basis) < (16 : Basis)) ordered))
    (Fin.cases (fun (ordered : (45 : Basis) < (17 : Basis)) => False.elim ((by decide +kernel : ¬ (45 : Basis) < (17 : Basis)) ordered))
    (Fin.cases (fun (ordered : (45 : Basis) < (18 : Basis)) => False.elim ((by decide +kernel : ¬ (45 : Basis) < (18 : Basis)) ordered))
    (Fin.cases (fun (ordered : (45 : Basis) < (19 : Basis)) => False.elim ((by decide +kernel : ¬ (45 : Basis) < (19 : Basis)) ordered))
    (Fin.cases (fun (ordered : (45 : Basis) < (20 : Basis)) => False.elim ((by decide +kernel : ¬ (45 : Basis) < (20 : Basis)) ordered))
    (Fin.cases (fun (ordered : (45 : Basis) < (21 : Basis)) => False.elim ((by decide +kernel : ¬ (45 : Basis) < (21 : Basis)) ordered))
    (Fin.cases (fun (ordered : (45 : Basis) < (22 : Basis)) => False.elim ((by decide +kernel : ¬ (45 : Basis) < (22 : Basis)) ordered))
    (Fin.cases (fun (ordered : (45 : Basis) < (23 : Basis)) => False.elim ((by decide +kernel : ¬ (45 : Basis) < (23 : Basis)) ordered))
    (Fin.cases (fun (ordered : (45 : Basis) < (24 : Basis)) => False.elim ((by decide +kernel : ¬ (45 : Basis) < (24 : Basis)) ordered))
    (Fin.cases (fun (ordered : (45 : Basis) < (25 : Basis)) => False.elim ((by decide +kernel : ¬ (45 : Basis) < (25 : Basis)) ordered))
    (Fin.cases (fun (ordered : (45 : Basis) < (26 : Basis)) => False.elim ((by decide +kernel : ¬ (45 : Basis) < (26 : Basis)) ordered))
    (Fin.cases (fun (ordered : (45 : Basis) < (27 : Basis)) => False.elim ((by decide +kernel : ¬ (45 : Basis) < (27 : Basis)) ordered))
    (Fin.cases (fun (ordered : (45 : Basis) < (28 : Basis)) => False.elim ((by decide +kernel : ¬ (45 : Basis) < (28 : Basis)) ordered))
    (Fin.cases (fun (ordered : (45 : Basis) < (29 : Basis)) => False.elim ((by decide +kernel : ¬ (45 : Basis) < (29 : Basis)) ordered))
    (Fin.cases (fun (ordered : (45 : Basis) < (30 : Basis)) => False.elim ((by decide +kernel : ¬ (45 : Basis) < (30 : Basis)) ordered))
    (Fin.cases (fun (ordered : (45 : Basis) < (31 : Basis)) => False.elim ((by decide +kernel : ¬ (45 : Basis) < (31 : Basis)) ordered))
    (Fin.cases (fun (ordered : (45 : Basis) < (32 : Basis)) => False.elim ((by decide +kernel : ¬ (45 : Basis) < (32 : Basis)) ordered))
    (Fin.cases (fun (ordered : (45 : Basis) < (33 : Basis)) => False.elim ((by decide +kernel : ¬ (45 : Basis) < (33 : Basis)) ordered))
    (Fin.cases (fun (ordered : (45 : Basis) < (34 : Basis)) => False.elim ((by decide +kernel : ¬ (45 : Basis) < (34 : Basis)) ordered))
    (Fin.cases (fun (ordered : (45 : Basis) < (35 : Basis)) => False.elim ((by decide +kernel : ¬ (45 : Basis) < (35 : Basis)) ordered))
    (Fin.cases (fun (ordered : (45 : Basis) < (36 : Basis)) => False.elim ((by decide +kernel : ¬ (45 : Basis) < (36 : Basis)) ordered))
    (Fin.cases (fun (ordered : (45 : Basis) < (37 : Basis)) => False.elim ((by decide +kernel : ¬ (45 : Basis) < (37 : Basis)) ordered))
    (Fin.cases (fun (ordered : (45 : Basis) < (38 : Basis)) => False.elim ((by decide +kernel : ¬ (45 : Basis) < (38 : Basis)) ordered))
    (Fin.cases (fun (ordered : (45 : Basis) < (39 : Basis)) => False.elim ((by decide +kernel : ¬ (45 : Basis) < (39 : Basis)) ordered))
    (Fin.cases (fun (ordered : (45 : Basis) < (40 : Basis)) => False.elim ((by decide +kernel : ¬ (45 : Basis) < (40 : Basis)) ordered))
    (Fin.cases (fun (ordered : (45 : Basis) < (41 : Basis)) => False.elim ((by decide +kernel : ¬ (45 : Basis) < (41 : Basis)) ordered))
    (Fin.cases (fun (ordered : (45 : Basis) < (42 : Basis)) => False.elim ((by decide +kernel : ¬ (45 : Basis) < (42 : Basis)) ordered))
    (Fin.cases (fun (ordered : (45 : Basis) < (43 : Basis)) => False.elim ((by decide +kernel : ¬ (45 : Basis) < (43 : Basis)) ordered))
    (Fin.cases (fun (ordered : (45 : Basis) < (44 : Basis)) => False.elim ((by decide +kernel : ¬ (45 : Basis) < (44 : Basis)) ordered))
    (Fin.cases (fun (ordered : (45 : Basis) < (45 : Basis)) => False.elim ((by decide +kernel : ¬ (45 : Basis) < (45 : Basis)) ordered))
    (Fin.cases (fun _ => ⟨⟨Factors.P210.factor14Plus,0,Factors.P210.checked14Plus⟩,⟨Factors.P210.factor14Minus,0,Factors.P210.checked14Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P210.factor15Plus,0,Factors.P210.checked15Plus⟩,⟨Factors.P210.factor15Minus,0,Factors.P210.checked15Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P211.factor0Plus,0,Factors.P211.checked0Plus⟩,⟨Factors.P211.factor0Minus,0,Factors.P211.checked0Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P211.factor1Plus,0,Factors.P211.checked1Plus⟩,⟨Factors.P211.factor1Minus,0,Factors.P211.checked1Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P211.factor2Plus,0,Factors.P211.checked2Plus⟩,⟨Factors.P211.factor2Minus,0,Factors.P211.checked2Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P211.factor3Plus,0,Factors.P211.checked3Plus⟩,⟨Factors.P211.factor3Minus,0,Factors.P211.checked3Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P211.factor4Plus,0,Factors.P211.checked4Plus⟩,⟨Factors.P211.factor4Minus,0,Factors.P211.checked4Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P211.factor5Plus,0,Factors.P211.checked5Plus⟩,⟨Factors.P211.factor5Minus,0,Factors.P211.checked5Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P211.factor6Plus,0,Factors.P211.checked6Plus⟩,⟨Factors.P211.factor6Minus,0,Factors.P211.checked6Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P211.factor7Plus,0,Factors.P211.checked7Plus⟩,⟨Factors.P211.factor7Minus,0,Factors.P211.checked7Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P211.factor8Plus,0,Factors.P211.checked8Plus⟩,⟨Factors.P211.factor8Minus,0,Factors.P211.checked8Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P211.factor9Plus,0,Factors.P211.checked9Plus⟩,⟨Factors.P211.factor9Minus,0,Factors.P211.checked9Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P211.factor10Plus,0,Factors.P211.checked10Plus⟩,⟨Factors.P211.factor10Minus,0,Factors.P211.checked10Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P211.factor11Plus,0,Factors.P211.checked11Plus⟩,⟨Factors.P211.factor11Minus,0,Factors.P211.checked11Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P211.factor12Plus,0,Factors.P211.checked12Plus⟩,⟨Factors.P211.factor12Minus,0,Factors.P211.checked12Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P211.factor13Plus,0,Factors.P211.checked13Plus⟩,⟨Factors.P211.factor13Minus,0,Factors.P211.checked13Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P211.factor14Plus,0,Factors.P211.checked14Plus⟩,⟨Factors.P211.factor14Minus,0,Factors.P211.checked14Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P211.factor15Plus,0,Factors.P211.checked15Plus⟩,⟨Factors.P211.factor15Minus,0,Factors.P211.checked15Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P212.factor0Plus,0,Factors.P212.checked0Plus⟩,⟨Factors.P212.factor0Minus,0,Factors.P212.checked0Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P212.factor1Plus,0,Factors.P212.checked1Plus⟩,⟨Factors.P212.factor1Minus,0,Factors.P212.checked1Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P212.factor2Plus,0,Factors.P212.checked2Plus⟩,⟨Factors.P212.factor2Minus,0,Factors.P212.checked2Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P212.factor3Plus,0,Factors.P212.checked3Plus⟩,⟨Factors.P212.factor3Minus,0,Factors.P212.checked3Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P212.factor4Plus,0,Factors.P212.checked4Plus⟩,⟨Factors.P212.factor4Minus,0,Factors.P212.checked4Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P212.factor5Plus,0,Factors.P212.checked5Plus⟩,⟨Factors.P212.factor5Minus,0,Factors.P212.checked5Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P212.factor6Plus,0,Factors.P212.checked6Plus⟩,⟨Factors.P212.factor6Minus,0,Factors.P212.checked6Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P212.factor7Plus,0,Factors.P212.checked7Plus⟩,⟨Factors.P212.factor7Minus,0,Factors.P212.checked7Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P212.factor8Plus,0,Factors.P212.checked8Plus⟩,⟨Factors.P212.factor8Minus,0,Factors.P212.checked8Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P212.factor9Plus,0,Factors.P212.checked9Plus⟩,⟨Factors.P212.factor9Minus,0,Factors.P212.checked9Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P212.factor10Plus,0,Factors.P212.checked10Plus⟩,⟨Factors.P212.factor10Minus,0,Factors.P212.checked10Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P212.factor11Plus,0,Factors.P212.checked11Plus⟩,⟨Factors.P212.factor11Minus,0,Factors.P212.checked11Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P212.factor12Plus,0,Factors.P212.checked12Plus⟩,⟨Factors.P212.factor12Minus,0,Factors.P212.checked12Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P212.factor13Plus,0,Factors.P212.checked13Plus⟩,⟨Factors.P212.factor13Minus,0,Factors.P212.checked13Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P212.factor14Plus,0,Factors.P212.checked14Plus⟩,⟨Factors.P212.factor14Minus,0,Factors.P212.checked14Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P212.factor15Plus,0,Factors.P212.checked15Plus⟩,⟨Factors.P212.factor15Minus,0,Factors.P212.checked15Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P213.factor0Plus,0,Factors.P213.checked0Plus⟩,⟨Factors.P213.factor0Minus,0,Factors.P213.checked0Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P213.factor1Plus,0,Factors.P213.checked1Plus⟩,⟨Factors.P213.factor1Minus,0,Factors.P213.checked1Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P213.factor2Plus,0,Factors.P213.checked2Plus⟩,⟨Factors.P213.factor2Minus,0,Factors.P213.checked2Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P213.factor3Plus,0,Factors.P213.checked3Plus⟩,⟨Factors.P213.factor3Minus,0,Factors.P213.checked3Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P213.factor4Plus,0,Factors.P213.checked4Plus⟩,⟨Factors.P213.factor4Minus,0,Factors.P213.checked4Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P213.factor5Plus,0,Factors.P213.checked5Plus⟩,⟨Factors.P213.factor5Minus,0,Factors.P213.checked5Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P213.factor6Plus,0,Factors.P213.checked6Plus⟩,⟨Factors.P213.factor6Minus,0,Factors.P213.checked6Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P213.factor7Plus,0,Factors.P213.checked7Plus⟩,⟨Factors.P213.factor7Minus,0,Factors.P213.checked7Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P213.factor8Plus,0,Factors.P213.checked8Plus⟩,⟨Factors.P213.factor8Minus,0,Factors.P213.checked8Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P213.factor9Plus,0,Factors.P213.checked9Plus⟩,⟨Factors.P213.factor9Minus,0,Factors.P213.checked9Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P213.factor10Plus,0,Factors.P213.checked10Plus⟩,⟨Factors.P213.factor10Minus,0,Factors.P213.checked10Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P213.factor11Plus,0,Factors.P213.checked11Plus⟩,⟨Factors.P213.factor11Minus,0,Factors.P213.checked11Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P213.factor12Plus,0,Factors.P213.checked12Plus⟩,⟨Factors.P213.factor12Minus,0,Factors.P213.checked12Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P213.factor13Plus,0,Factors.P213.checked13Plus⟩,⟨Factors.P213.factor13Minus,0,Factors.P213.checked13Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P213.factor14Plus,0,Factors.P213.checked14Plus⟩,⟨Factors.P213.factor14Minus,0,Factors.P213.checked14Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P213.factor15Plus,0,Factors.P213.checked15Plus⟩,⟨Factors.P213.factor15Minus,0,Factors.P213.checked15Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P214.factor0Plus,0,Factors.P214.checked0Plus⟩,⟨Factors.P214.factor0Minus,0,Factors.P214.checked0Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P214.factor1Plus,0,Factors.P214.checked1Plus⟩,⟨Factors.P214.factor1Minus,0,Factors.P214.checked1Minus⟩⟩)
    ((fun impossible => Fin.elim0 impossible)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))

end
end LAlanine40K2025.Thermal.Recovery.Reservoir.Pointer.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Rows
end SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule
