import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.OrdinaryPair
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P217
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P218
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P219
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P220

set_option autoImplicit false
namespace SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule
namespace LAlanine40K2025.Thermal.Recovery.Reservoir.Pointer.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Rows
open Propagation.Interface
noncomputable section

set_option maxHeartbeats 400000 in
def row47 : (b : Basis) → (47 : Basis) < b → OrdinaryPair 47 b :=
  Fin.cases (fun (ordered : (47 : Basis) < (0 : Basis)) => False.elim ((by decide +kernel : ¬ (47 : Basis) < (0 : Basis)) ordered))
    (Fin.cases (fun (ordered : (47 : Basis) < (1 : Basis)) => False.elim ((by decide +kernel : ¬ (47 : Basis) < (1 : Basis)) ordered))
    (Fin.cases (fun (ordered : (47 : Basis) < (2 : Basis)) => False.elim ((by decide +kernel : ¬ (47 : Basis) < (2 : Basis)) ordered))
    (Fin.cases (fun (ordered : (47 : Basis) < (3 : Basis)) => False.elim ((by decide +kernel : ¬ (47 : Basis) < (3 : Basis)) ordered))
    (Fin.cases (fun (ordered : (47 : Basis) < (4 : Basis)) => False.elim ((by decide +kernel : ¬ (47 : Basis) < (4 : Basis)) ordered))
    (Fin.cases (fun (ordered : (47 : Basis) < (5 : Basis)) => False.elim ((by decide +kernel : ¬ (47 : Basis) < (5 : Basis)) ordered))
    (Fin.cases (fun (ordered : (47 : Basis) < (6 : Basis)) => False.elim ((by decide +kernel : ¬ (47 : Basis) < (6 : Basis)) ordered))
    (Fin.cases (fun (ordered : (47 : Basis) < (7 : Basis)) => False.elim ((by decide +kernel : ¬ (47 : Basis) < (7 : Basis)) ordered))
    (Fin.cases (fun (ordered : (47 : Basis) < (8 : Basis)) => False.elim ((by decide +kernel : ¬ (47 : Basis) < (8 : Basis)) ordered))
    (Fin.cases (fun (ordered : (47 : Basis) < (9 : Basis)) => False.elim ((by decide +kernel : ¬ (47 : Basis) < (9 : Basis)) ordered))
    (Fin.cases (fun (ordered : (47 : Basis) < (10 : Basis)) => False.elim ((by decide +kernel : ¬ (47 : Basis) < (10 : Basis)) ordered))
    (Fin.cases (fun (ordered : (47 : Basis) < (11 : Basis)) => False.elim ((by decide +kernel : ¬ (47 : Basis) < (11 : Basis)) ordered))
    (Fin.cases (fun (ordered : (47 : Basis) < (12 : Basis)) => False.elim ((by decide +kernel : ¬ (47 : Basis) < (12 : Basis)) ordered))
    (Fin.cases (fun (ordered : (47 : Basis) < (13 : Basis)) => False.elim ((by decide +kernel : ¬ (47 : Basis) < (13 : Basis)) ordered))
    (Fin.cases (fun (ordered : (47 : Basis) < (14 : Basis)) => False.elim ((by decide +kernel : ¬ (47 : Basis) < (14 : Basis)) ordered))
    (Fin.cases (fun (ordered : (47 : Basis) < (15 : Basis)) => False.elim ((by decide +kernel : ¬ (47 : Basis) < (15 : Basis)) ordered))
    (Fin.cases (fun (ordered : (47 : Basis) < (16 : Basis)) => False.elim ((by decide +kernel : ¬ (47 : Basis) < (16 : Basis)) ordered))
    (Fin.cases (fun (ordered : (47 : Basis) < (17 : Basis)) => False.elim ((by decide +kernel : ¬ (47 : Basis) < (17 : Basis)) ordered))
    (Fin.cases (fun (ordered : (47 : Basis) < (18 : Basis)) => False.elim ((by decide +kernel : ¬ (47 : Basis) < (18 : Basis)) ordered))
    (Fin.cases (fun (ordered : (47 : Basis) < (19 : Basis)) => False.elim ((by decide +kernel : ¬ (47 : Basis) < (19 : Basis)) ordered))
    (Fin.cases (fun (ordered : (47 : Basis) < (20 : Basis)) => False.elim ((by decide +kernel : ¬ (47 : Basis) < (20 : Basis)) ordered))
    (Fin.cases (fun (ordered : (47 : Basis) < (21 : Basis)) => False.elim ((by decide +kernel : ¬ (47 : Basis) < (21 : Basis)) ordered))
    (Fin.cases (fun (ordered : (47 : Basis) < (22 : Basis)) => False.elim ((by decide +kernel : ¬ (47 : Basis) < (22 : Basis)) ordered))
    (Fin.cases (fun (ordered : (47 : Basis) < (23 : Basis)) => False.elim ((by decide +kernel : ¬ (47 : Basis) < (23 : Basis)) ordered))
    (Fin.cases (fun (ordered : (47 : Basis) < (24 : Basis)) => False.elim ((by decide +kernel : ¬ (47 : Basis) < (24 : Basis)) ordered))
    (Fin.cases (fun (ordered : (47 : Basis) < (25 : Basis)) => False.elim ((by decide +kernel : ¬ (47 : Basis) < (25 : Basis)) ordered))
    (Fin.cases (fun (ordered : (47 : Basis) < (26 : Basis)) => False.elim ((by decide +kernel : ¬ (47 : Basis) < (26 : Basis)) ordered))
    (Fin.cases (fun (ordered : (47 : Basis) < (27 : Basis)) => False.elim ((by decide +kernel : ¬ (47 : Basis) < (27 : Basis)) ordered))
    (Fin.cases (fun (ordered : (47 : Basis) < (28 : Basis)) => False.elim ((by decide +kernel : ¬ (47 : Basis) < (28 : Basis)) ordered))
    (Fin.cases (fun (ordered : (47 : Basis) < (29 : Basis)) => False.elim ((by decide +kernel : ¬ (47 : Basis) < (29 : Basis)) ordered))
    (Fin.cases (fun (ordered : (47 : Basis) < (30 : Basis)) => False.elim ((by decide +kernel : ¬ (47 : Basis) < (30 : Basis)) ordered))
    (Fin.cases (fun (ordered : (47 : Basis) < (31 : Basis)) => False.elim ((by decide +kernel : ¬ (47 : Basis) < (31 : Basis)) ordered))
    (Fin.cases (fun (ordered : (47 : Basis) < (32 : Basis)) => False.elim ((by decide +kernel : ¬ (47 : Basis) < (32 : Basis)) ordered))
    (Fin.cases (fun (ordered : (47 : Basis) < (33 : Basis)) => False.elim ((by decide +kernel : ¬ (47 : Basis) < (33 : Basis)) ordered))
    (Fin.cases (fun (ordered : (47 : Basis) < (34 : Basis)) => False.elim ((by decide +kernel : ¬ (47 : Basis) < (34 : Basis)) ordered))
    (Fin.cases (fun (ordered : (47 : Basis) < (35 : Basis)) => False.elim ((by decide +kernel : ¬ (47 : Basis) < (35 : Basis)) ordered))
    (Fin.cases (fun (ordered : (47 : Basis) < (36 : Basis)) => False.elim ((by decide +kernel : ¬ (47 : Basis) < (36 : Basis)) ordered))
    (Fin.cases (fun (ordered : (47 : Basis) < (37 : Basis)) => False.elim ((by decide +kernel : ¬ (47 : Basis) < (37 : Basis)) ordered))
    (Fin.cases (fun (ordered : (47 : Basis) < (38 : Basis)) => False.elim ((by decide +kernel : ¬ (47 : Basis) < (38 : Basis)) ordered))
    (Fin.cases (fun (ordered : (47 : Basis) < (39 : Basis)) => False.elim ((by decide +kernel : ¬ (47 : Basis) < (39 : Basis)) ordered))
    (Fin.cases (fun (ordered : (47 : Basis) < (40 : Basis)) => False.elim ((by decide +kernel : ¬ (47 : Basis) < (40 : Basis)) ordered))
    (Fin.cases (fun (ordered : (47 : Basis) < (41 : Basis)) => False.elim ((by decide +kernel : ¬ (47 : Basis) < (41 : Basis)) ordered))
    (Fin.cases (fun (ordered : (47 : Basis) < (42 : Basis)) => False.elim ((by decide +kernel : ¬ (47 : Basis) < (42 : Basis)) ordered))
    (Fin.cases (fun (ordered : (47 : Basis) < (43 : Basis)) => False.elim ((by decide +kernel : ¬ (47 : Basis) < (43 : Basis)) ordered))
    (Fin.cases (fun (ordered : (47 : Basis) < (44 : Basis)) => False.elim ((by decide +kernel : ¬ (47 : Basis) < (44 : Basis)) ordered))
    (Fin.cases (fun (ordered : (47 : Basis) < (45 : Basis)) => False.elim ((by decide +kernel : ¬ (47 : Basis) < (45 : Basis)) ordered))
    (Fin.cases (fun (ordered : (47 : Basis) < (46 : Basis)) => False.elim ((by decide +kernel : ¬ (47 : Basis) < (46 : Basis)) ordered))
    (Fin.cases (fun (ordered : (47 : Basis) < (47 : Basis)) => False.elim ((by decide +kernel : ¬ (47 : Basis) < (47 : Basis)) ordered))
    (Fin.cases (fun _ => ⟨⟨Factors.P217.factor5Plus,0,Factors.P217.checked5Plus⟩,⟨Factors.P217.factor5Minus,0,Factors.P217.checked5Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P217.factor6Plus,0,Factors.P217.checked6Plus⟩,⟨Factors.P217.factor6Minus,0,Factors.P217.checked6Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P217.factor7Plus,0,Factors.P217.checked7Plus⟩,⟨Factors.P217.factor7Minus,0,Factors.P217.checked7Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P217.factor8Plus,0,Factors.P217.checked8Plus⟩,⟨Factors.P217.factor8Minus,0,Factors.P217.checked8Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P217.factor9Plus,0,Factors.P217.checked9Plus⟩,⟨Factors.P217.factor9Minus,0,Factors.P217.checked9Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P217.factor10Plus,0,Factors.P217.checked10Plus⟩,⟨Factors.P217.factor10Minus,0,Factors.P217.checked10Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P217.factor11Plus,0,Factors.P217.checked11Plus⟩,⟨Factors.P217.factor11Minus,0,Factors.P217.checked11Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P217.factor12Plus,0,Factors.P217.checked12Plus⟩,⟨Factors.P217.factor12Minus,0,Factors.P217.checked12Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P217.factor13Plus,0,Factors.P217.checked13Plus⟩,⟨Factors.P217.factor13Minus,0,Factors.P217.checked13Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P217.factor14Plus,0,Factors.P217.checked14Plus⟩,⟨Factors.P217.factor14Minus,0,Factors.P217.checked14Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P217.factor15Plus,0,Factors.P217.checked15Plus⟩,⟨Factors.P217.factor15Minus,0,Factors.P217.checked15Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P218.factor0Plus,0,Factors.P218.checked0Plus⟩,⟨Factors.P218.factor0Minus,0,Factors.P218.checked0Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P218.factor1Plus,0,Factors.P218.checked1Plus⟩,⟨Factors.P218.factor1Minus,0,Factors.P218.checked1Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P218.factor2Plus,0,Factors.P218.checked2Plus⟩,⟨Factors.P218.factor2Minus,0,Factors.P218.checked2Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P218.factor3Plus,0,Factors.P218.checked3Plus⟩,⟨Factors.P218.factor3Minus,0,Factors.P218.checked3Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P218.factor4Plus,0,Factors.P218.checked4Plus⟩,⟨Factors.P218.factor4Minus,0,Factors.P218.checked4Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P218.factor5Plus,0,Factors.P218.checked5Plus⟩,⟨Factors.P218.factor5Minus,0,Factors.P218.checked5Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P218.factor6Plus,0,Factors.P218.checked6Plus⟩,⟨Factors.P218.factor6Minus,0,Factors.P218.checked6Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P218.factor7Plus,0,Factors.P218.checked7Plus⟩,⟨Factors.P218.factor7Minus,0,Factors.P218.checked7Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P218.factor8Plus,0,Factors.P218.checked8Plus⟩,⟨Factors.P218.factor8Minus,0,Factors.P218.checked8Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P218.factor9Plus,0,Factors.P218.checked9Plus⟩,⟨Factors.P218.factor9Minus,0,Factors.P218.checked9Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P218.factor10Plus,0,Factors.P218.checked10Plus⟩,⟨Factors.P218.factor10Minus,0,Factors.P218.checked10Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P218.factor11Plus,0,Factors.P218.checked11Plus⟩,⟨Factors.P218.factor11Minus,0,Factors.P218.checked11Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P218.factor12Plus,0,Factors.P218.checked12Plus⟩,⟨Factors.P218.factor12Minus,0,Factors.P218.checked12Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P218.factor13Plus,0,Factors.P218.checked13Plus⟩,⟨Factors.P218.factor13Minus,0,Factors.P218.checked13Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P218.factor14Plus,0,Factors.P218.checked14Plus⟩,⟨Factors.P218.factor14Minus,0,Factors.P218.checked14Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P218.factor15Plus,0,Factors.P218.checked15Plus⟩,⟨Factors.P218.factor15Minus,0,Factors.P218.checked15Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P219.factor0Plus,0,Factors.P219.checked0Plus⟩,⟨Factors.P219.factor0Minus,0,Factors.P219.checked0Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P219.factor1Plus,0,Factors.P219.checked1Plus⟩,⟨Factors.P219.factor1Minus,0,Factors.P219.checked1Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P219.factor2Plus,0,Factors.P219.checked2Plus⟩,⟨Factors.P219.factor2Minus,0,Factors.P219.checked2Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P219.factor3Plus,0,Factors.P219.checked3Plus⟩,⟨Factors.P219.factor3Minus,0,Factors.P219.checked3Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P219.factor4Plus,0,Factors.P219.checked4Plus⟩,⟨Factors.P219.factor4Minus,0,Factors.P219.checked4Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P219.factor5Plus,0,Factors.P219.checked5Plus⟩,⟨Factors.P219.factor5Minus,0,Factors.P219.checked5Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P219.factor6Plus,0,Factors.P219.checked6Plus⟩,⟨Factors.P219.factor6Minus,0,Factors.P219.checked6Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P219.factor7Plus,0,Factors.P219.checked7Plus⟩,⟨Factors.P219.factor7Minus,0,Factors.P219.checked7Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P219.factor8Plus,0,Factors.P219.checked8Plus⟩,⟨Factors.P219.factor8Minus,0,Factors.P219.checked8Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P219.factor9Plus,0,Factors.P219.checked9Plus⟩,⟨Factors.P219.factor9Minus,0,Factors.P219.checked9Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P219.factor10Plus,0,Factors.P219.checked10Plus⟩,⟨Factors.P219.factor10Minus,0,Factors.P219.checked10Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P219.factor11Plus,0,Factors.P219.checked11Plus⟩,⟨Factors.P219.factor11Minus,0,Factors.P219.checked11Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P219.factor12Plus,0,Factors.P219.checked12Plus⟩,⟨Factors.P219.factor12Minus,0,Factors.P219.checked12Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P219.factor13Plus,0,Factors.P219.checked13Plus⟩,⟨Factors.P219.factor13Minus,0,Factors.P219.checked13Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P219.factor14Plus,0,Factors.P219.checked14Plus⟩,⟨Factors.P219.factor14Minus,0,Factors.P219.checked14Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P219.factor15Plus,0,Factors.P219.checked15Plus⟩,⟨Factors.P219.factor15Minus,0,Factors.P219.checked15Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P220.factor0Plus,0,Factors.P220.checked0Plus⟩,⟨Factors.P220.factor0Minus,0,Factors.P220.checked0Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P220.factor1Plus,0,Factors.P220.checked1Plus⟩,⟨Factors.P220.factor1Minus,0,Factors.P220.checked1Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P220.factor2Plus,0,Factors.P220.checked2Plus⟩,⟨Factors.P220.factor2Minus,0,Factors.P220.checked2Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P220.factor3Plus,0,Factors.P220.checked3Plus⟩,⟨Factors.P220.factor3Minus,0,Factors.P220.checked3Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P220.factor4Plus,0,Factors.P220.checked4Plus⟩,⟨Factors.P220.factor4Minus,0,Factors.P220.checked4Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P220.factor5Plus,0,Factors.P220.checked5Plus⟩,⟨Factors.P220.factor5Minus,0,Factors.P220.checked5Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P220.factor6Plus,0,Factors.P220.checked6Plus⟩,⟨Factors.P220.factor6Minus,0,Factors.P220.checked6Minus⟩⟩)
    ((fun impossible => Fin.elim0 impossible)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))

end
end LAlanine40K2025.Thermal.Recovery.Reservoir.Pointer.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Rows
end SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule
