import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.OrdinaryPair
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P226
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P227
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P228
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P229

set_option autoImplicit false
namespace SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule
namespace LAlanine40K2025.Thermal.Recovery.Reservoir.Pointer.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Rows
open Propagation.Interface
noncomputable section

set_option maxHeartbeats 400000 in
def row50 : (b : Basis) → (50 : Basis) < b → OrdinaryPair 50 b :=
  Fin.cases (fun (ordered : (50 : Basis) < (0 : Basis)) => False.elim ((by decide +kernel : ¬ (50 : Basis) < (0 : Basis)) ordered))
    (Fin.cases (fun (ordered : (50 : Basis) < (1 : Basis)) => False.elim ((by decide +kernel : ¬ (50 : Basis) < (1 : Basis)) ordered))
    (Fin.cases (fun (ordered : (50 : Basis) < (2 : Basis)) => False.elim ((by decide +kernel : ¬ (50 : Basis) < (2 : Basis)) ordered))
    (Fin.cases (fun (ordered : (50 : Basis) < (3 : Basis)) => False.elim ((by decide +kernel : ¬ (50 : Basis) < (3 : Basis)) ordered))
    (Fin.cases (fun (ordered : (50 : Basis) < (4 : Basis)) => False.elim ((by decide +kernel : ¬ (50 : Basis) < (4 : Basis)) ordered))
    (Fin.cases (fun (ordered : (50 : Basis) < (5 : Basis)) => False.elim ((by decide +kernel : ¬ (50 : Basis) < (5 : Basis)) ordered))
    (Fin.cases (fun (ordered : (50 : Basis) < (6 : Basis)) => False.elim ((by decide +kernel : ¬ (50 : Basis) < (6 : Basis)) ordered))
    (Fin.cases (fun (ordered : (50 : Basis) < (7 : Basis)) => False.elim ((by decide +kernel : ¬ (50 : Basis) < (7 : Basis)) ordered))
    (Fin.cases (fun (ordered : (50 : Basis) < (8 : Basis)) => False.elim ((by decide +kernel : ¬ (50 : Basis) < (8 : Basis)) ordered))
    (Fin.cases (fun (ordered : (50 : Basis) < (9 : Basis)) => False.elim ((by decide +kernel : ¬ (50 : Basis) < (9 : Basis)) ordered))
    (Fin.cases (fun (ordered : (50 : Basis) < (10 : Basis)) => False.elim ((by decide +kernel : ¬ (50 : Basis) < (10 : Basis)) ordered))
    (Fin.cases (fun (ordered : (50 : Basis) < (11 : Basis)) => False.elim ((by decide +kernel : ¬ (50 : Basis) < (11 : Basis)) ordered))
    (Fin.cases (fun (ordered : (50 : Basis) < (12 : Basis)) => False.elim ((by decide +kernel : ¬ (50 : Basis) < (12 : Basis)) ordered))
    (Fin.cases (fun (ordered : (50 : Basis) < (13 : Basis)) => False.elim ((by decide +kernel : ¬ (50 : Basis) < (13 : Basis)) ordered))
    (Fin.cases (fun (ordered : (50 : Basis) < (14 : Basis)) => False.elim ((by decide +kernel : ¬ (50 : Basis) < (14 : Basis)) ordered))
    (Fin.cases (fun (ordered : (50 : Basis) < (15 : Basis)) => False.elim ((by decide +kernel : ¬ (50 : Basis) < (15 : Basis)) ordered))
    (Fin.cases (fun (ordered : (50 : Basis) < (16 : Basis)) => False.elim ((by decide +kernel : ¬ (50 : Basis) < (16 : Basis)) ordered))
    (Fin.cases (fun (ordered : (50 : Basis) < (17 : Basis)) => False.elim ((by decide +kernel : ¬ (50 : Basis) < (17 : Basis)) ordered))
    (Fin.cases (fun (ordered : (50 : Basis) < (18 : Basis)) => False.elim ((by decide +kernel : ¬ (50 : Basis) < (18 : Basis)) ordered))
    (Fin.cases (fun (ordered : (50 : Basis) < (19 : Basis)) => False.elim ((by decide +kernel : ¬ (50 : Basis) < (19 : Basis)) ordered))
    (Fin.cases (fun (ordered : (50 : Basis) < (20 : Basis)) => False.elim ((by decide +kernel : ¬ (50 : Basis) < (20 : Basis)) ordered))
    (Fin.cases (fun (ordered : (50 : Basis) < (21 : Basis)) => False.elim ((by decide +kernel : ¬ (50 : Basis) < (21 : Basis)) ordered))
    (Fin.cases (fun (ordered : (50 : Basis) < (22 : Basis)) => False.elim ((by decide +kernel : ¬ (50 : Basis) < (22 : Basis)) ordered))
    (Fin.cases (fun (ordered : (50 : Basis) < (23 : Basis)) => False.elim ((by decide +kernel : ¬ (50 : Basis) < (23 : Basis)) ordered))
    (Fin.cases (fun (ordered : (50 : Basis) < (24 : Basis)) => False.elim ((by decide +kernel : ¬ (50 : Basis) < (24 : Basis)) ordered))
    (Fin.cases (fun (ordered : (50 : Basis) < (25 : Basis)) => False.elim ((by decide +kernel : ¬ (50 : Basis) < (25 : Basis)) ordered))
    (Fin.cases (fun (ordered : (50 : Basis) < (26 : Basis)) => False.elim ((by decide +kernel : ¬ (50 : Basis) < (26 : Basis)) ordered))
    (Fin.cases (fun (ordered : (50 : Basis) < (27 : Basis)) => False.elim ((by decide +kernel : ¬ (50 : Basis) < (27 : Basis)) ordered))
    (Fin.cases (fun (ordered : (50 : Basis) < (28 : Basis)) => False.elim ((by decide +kernel : ¬ (50 : Basis) < (28 : Basis)) ordered))
    (Fin.cases (fun (ordered : (50 : Basis) < (29 : Basis)) => False.elim ((by decide +kernel : ¬ (50 : Basis) < (29 : Basis)) ordered))
    (Fin.cases (fun (ordered : (50 : Basis) < (30 : Basis)) => False.elim ((by decide +kernel : ¬ (50 : Basis) < (30 : Basis)) ordered))
    (Fin.cases (fun (ordered : (50 : Basis) < (31 : Basis)) => False.elim ((by decide +kernel : ¬ (50 : Basis) < (31 : Basis)) ordered))
    (Fin.cases (fun (ordered : (50 : Basis) < (32 : Basis)) => False.elim ((by decide +kernel : ¬ (50 : Basis) < (32 : Basis)) ordered))
    (Fin.cases (fun (ordered : (50 : Basis) < (33 : Basis)) => False.elim ((by decide +kernel : ¬ (50 : Basis) < (33 : Basis)) ordered))
    (Fin.cases (fun (ordered : (50 : Basis) < (34 : Basis)) => False.elim ((by decide +kernel : ¬ (50 : Basis) < (34 : Basis)) ordered))
    (Fin.cases (fun (ordered : (50 : Basis) < (35 : Basis)) => False.elim ((by decide +kernel : ¬ (50 : Basis) < (35 : Basis)) ordered))
    (Fin.cases (fun (ordered : (50 : Basis) < (36 : Basis)) => False.elim ((by decide +kernel : ¬ (50 : Basis) < (36 : Basis)) ordered))
    (Fin.cases (fun (ordered : (50 : Basis) < (37 : Basis)) => False.elim ((by decide +kernel : ¬ (50 : Basis) < (37 : Basis)) ordered))
    (Fin.cases (fun (ordered : (50 : Basis) < (38 : Basis)) => False.elim ((by decide +kernel : ¬ (50 : Basis) < (38 : Basis)) ordered))
    (Fin.cases (fun (ordered : (50 : Basis) < (39 : Basis)) => False.elim ((by decide +kernel : ¬ (50 : Basis) < (39 : Basis)) ordered))
    (Fin.cases (fun (ordered : (50 : Basis) < (40 : Basis)) => False.elim ((by decide +kernel : ¬ (50 : Basis) < (40 : Basis)) ordered))
    (Fin.cases (fun (ordered : (50 : Basis) < (41 : Basis)) => False.elim ((by decide +kernel : ¬ (50 : Basis) < (41 : Basis)) ordered))
    (Fin.cases (fun (ordered : (50 : Basis) < (42 : Basis)) => False.elim ((by decide +kernel : ¬ (50 : Basis) < (42 : Basis)) ordered))
    (Fin.cases (fun (ordered : (50 : Basis) < (43 : Basis)) => False.elim ((by decide +kernel : ¬ (50 : Basis) < (43 : Basis)) ordered))
    (Fin.cases (fun (ordered : (50 : Basis) < (44 : Basis)) => False.elim ((by decide +kernel : ¬ (50 : Basis) < (44 : Basis)) ordered))
    (Fin.cases (fun (ordered : (50 : Basis) < (45 : Basis)) => False.elim ((by decide +kernel : ¬ (50 : Basis) < (45 : Basis)) ordered))
    (Fin.cases (fun (ordered : (50 : Basis) < (46 : Basis)) => False.elim ((by decide +kernel : ¬ (50 : Basis) < (46 : Basis)) ordered))
    (Fin.cases (fun (ordered : (50 : Basis) < (47 : Basis)) => False.elim ((by decide +kernel : ¬ (50 : Basis) < (47 : Basis)) ordered))
    (Fin.cases (fun (ordered : (50 : Basis) < (48 : Basis)) => False.elim ((by decide +kernel : ¬ (50 : Basis) < (48 : Basis)) ordered))
    (Fin.cases (fun (ordered : (50 : Basis) < (49 : Basis)) => False.elim ((by decide +kernel : ¬ (50 : Basis) < (49 : Basis)) ordered))
    (Fin.cases (fun (ordered : (50 : Basis) < (50 : Basis)) => False.elim ((by decide +kernel : ¬ (50 : Basis) < (50 : Basis)) ordered))
    (Fin.cases (fun _ => ⟨⟨Factors.P226.factor8Plus,0,Factors.P226.checked8Plus⟩,⟨Factors.P226.factor8Minus,0,Factors.P226.checked8Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P226.factor9Plus,0,Factors.P226.checked9Plus⟩,⟨Factors.P226.factor9Minus,0,Factors.P226.checked9Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P226.factor10Plus,0,Factors.P226.checked10Plus⟩,⟨Factors.P226.factor10Minus,0,Factors.P226.checked10Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P226.factor11Plus,0,Factors.P226.checked11Plus⟩,⟨Factors.P226.factor11Minus,0,Factors.P226.checked11Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P226.factor12Plus,0,Factors.P226.checked12Plus⟩,⟨Factors.P226.factor12Minus,0,Factors.P226.checked12Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P226.factor13Plus,0,Factors.P226.checked13Plus⟩,⟨Factors.P226.factor13Minus,0,Factors.P226.checked13Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P226.factor14Plus,0,Factors.P226.checked14Plus⟩,⟨Factors.P226.factor14Minus,0,Factors.P226.checked14Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P226.factor15Plus,0,Factors.P226.checked15Plus⟩,⟨Factors.P226.factor15Minus,0,Factors.P226.checked15Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P227.factor0Plus,0,Factors.P227.checked0Plus⟩,⟨Factors.P227.factor0Minus,0,Factors.P227.checked0Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P227.factor1Plus,0,Factors.P227.checked1Plus⟩,⟨Factors.P227.factor1Minus,0,Factors.P227.checked1Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P227.factor2Plus,0,Factors.P227.checked2Plus⟩,⟨Factors.P227.factor2Minus,0,Factors.P227.checked2Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P227.factor3Plus,0,Factors.P227.checked3Plus⟩,⟨Factors.P227.factor3Minus,0,Factors.P227.checked3Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P227.factor4Plus,0,Factors.P227.checked4Plus⟩,⟨Factors.P227.factor4Minus,0,Factors.P227.checked4Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P227.factor5Plus,0,Factors.P227.checked5Plus⟩,⟨Factors.P227.factor5Minus,0,Factors.P227.checked5Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P227.factor6Plus,0,Factors.P227.checked6Plus⟩,⟨Factors.P227.factor6Minus,0,Factors.P227.checked6Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P227.factor7Plus,0,Factors.P227.checked7Plus⟩,⟨Factors.P227.factor7Minus,0,Factors.P227.checked7Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P227.factor8Plus,0,Factors.P227.checked8Plus⟩,⟨Factors.P227.factor8Minus,0,Factors.P227.checked8Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P227.factor9Plus,0,Factors.P227.checked9Plus⟩,⟨Factors.P227.factor9Minus,0,Factors.P227.checked9Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P227.factor10Plus,0,Factors.P227.checked10Plus⟩,⟨Factors.P227.factor10Minus,0,Factors.P227.checked10Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P227.factor11Plus,0,Factors.P227.checked11Plus⟩,⟨Factors.P227.factor11Minus,0,Factors.P227.checked11Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P227.factor12Plus,0,Factors.P227.checked12Plus⟩,⟨Factors.P227.factor12Minus,0,Factors.P227.checked12Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P227.factor13Plus,0,Factors.P227.checked13Plus⟩,⟨Factors.P227.factor13Minus,0,Factors.P227.checked13Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P227.factor14Plus,0,Factors.P227.checked14Plus⟩,⟨Factors.P227.factor14Minus,0,Factors.P227.checked14Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P227.factor15Plus,0,Factors.P227.checked15Plus⟩,⟨Factors.P227.factor15Minus,0,Factors.P227.checked15Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P228.factor0Plus,0,Factors.P228.checked0Plus⟩,⟨Factors.P228.factor0Minus,0,Factors.P228.checked0Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P228.factor1Plus,0,Factors.P228.checked1Plus⟩,⟨Factors.P228.factor1Minus,0,Factors.P228.checked1Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P228.factor2Plus,0,Factors.P228.checked2Plus⟩,⟨Factors.P228.factor2Minus,0,Factors.P228.checked2Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P228.factor3Plus,0,Factors.P228.checked3Plus⟩,⟨Factors.P228.factor3Minus,0,Factors.P228.checked3Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P228.factor4Plus,0,Factors.P228.checked4Plus⟩,⟨Factors.P228.factor4Minus,0,Factors.P228.checked4Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P228.factor5Plus,0,Factors.P228.checked5Plus⟩,⟨Factors.P228.factor5Minus,0,Factors.P228.checked5Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P228.factor6Plus,0,Factors.P228.checked6Plus⟩,⟨Factors.P228.factor6Minus,0,Factors.P228.checked6Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P228.factor7Plus,0,Factors.P228.checked7Plus⟩,⟨Factors.P228.factor7Minus,0,Factors.P228.checked7Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P228.factor8Plus,0,Factors.P228.checked8Plus⟩,⟨Factors.P228.factor8Minus,0,Factors.P228.checked8Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P228.factor9Plus,0,Factors.P228.checked9Plus⟩,⟨Factors.P228.factor9Minus,0,Factors.P228.checked9Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P228.factor10Plus,0,Factors.P228.checked10Plus⟩,⟨Factors.P228.factor10Minus,0,Factors.P228.checked10Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P228.factor11Plus,0,Factors.P228.checked11Plus⟩,⟨Factors.P228.factor11Minus,0,Factors.P228.checked11Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P228.factor12Plus,0,Factors.P228.checked12Plus⟩,⟨Factors.P228.factor12Minus,0,Factors.P228.checked12Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P228.factor13Plus,0,Factors.P228.checked13Plus⟩,⟨Factors.P228.factor13Minus,0,Factors.P228.checked13Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P228.factor14Plus,0,Factors.P228.checked14Plus⟩,⟨Factors.P228.factor14Minus,0,Factors.P228.checked14Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P228.factor15Plus,0,Factors.P228.checked15Plus⟩,⟨Factors.P228.factor15Minus,0,Factors.P228.checked15Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P229.factor0Plus,0,Factors.P229.checked0Plus⟩,⟨Factors.P229.factor0Minus,0,Factors.P229.checked0Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P229.factor1Plus,0,Factors.P229.checked1Plus⟩,⟨Factors.P229.factor1Minus,0,Factors.P229.checked1Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P229.factor2Plus,0,Factors.P229.checked2Plus⟩,⟨Factors.P229.factor2Minus,0,Factors.P229.checked2Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P229.factor3Plus,0,Factors.P229.checked3Plus⟩,⟨Factors.P229.factor3Minus,0,Factors.P229.checked3Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P229.factor4Plus,0,Factors.P229.checked4Plus⟩,⟨Factors.P229.factor4Minus,0,Factors.P229.checked4Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P229.factor5Plus,0,Factors.P229.checked5Plus⟩,⟨Factors.P229.factor5Minus,0,Factors.P229.checked5Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P229.factor6Plus,0,Factors.P229.checked6Plus⟩,⟨Factors.P229.factor6Minus,0,Factors.P229.checked6Minus⟩⟩)
    ((fun impossible => Fin.elim0 impossible)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))

end
end LAlanine40K2025.Thermal.Recovery.Reservoir.Pointer.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Rows
end SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule
