import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.OrdinaryPair
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P229
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P230
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P231
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P232

set_option autoImplicit false
namespace SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule
namespace LAlanine40K2025.Thermal.Recovery.Reservoir.Pointer.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Rows
open Propagation.Interface
noncomputable section

set_option maxHeartbeats 400000 in
def row51 : (b : Basis) → (51 : Basis) < b → OrdinaryPair 51 b :=
  Fin.cases (fun (ordered : (51 : Basis) < (0 : Basis)) => False.elim ((by decide +kernel : ¬ (51 : Basis) < (0 : Basis)) ordered))
    (Fin.cases (fun (ordered : (51 : Basis) < (1 : Basis)) => False.elim ((by decide +kernel : ¬ (51 : Basis) < (1 : Basis)) ordered))
    (Fin.cases (fun (ordered : (51 : Basis) < (2 : Basis)) => False.elim ((by decide +kernel : ¬ (51 : Basis) < (2 : Basis)) ordered))
    (Fin.cases (fun (ordered : (51 : Basis) < (3 : Basis)) => False.elim ((by decide +kernel : ¬ (51 : Basis) < (3 : Basis)) ordered))
    (Fin.cases (fun (ordered : (51 : Basis) < (4 : Basis)) => False.elim ((by decide +kernel : ¬ (51 : Basis) < (4 : Basis)) ordered))
    (Fin.cases (fun (ordered : (51 : Basis) < (5 : Basis)) => False.elim ((by decide +kernel : ¬ (51 : Basis) < (5 : Basis)) ordered))
    (Fin.cases (fun (ordered : (51 : Basis) < (6 : Basis)) => False.elim ((by decide +kernel : ¬ (51 : Basis) < (6 : Basis)) ordered))
    (Fin.cases (fun (ordered : (51 : Basis) < (7 : Basis)) => False.elim ((by decide +kernel : ¬ (51 : Basis) < (7 : Basis)) ordered))
    (Fin.cases (fun (ordered : (51 : Basis) < (8 : Basis)) => False.elim ((by decide +kernel : ¬ (51 : Basis) < (8 : Basis)) ordered))
    (Fin.cases (fun (ordered : (51 : Basis) < (9 : Basis)) => False.elim ((by decide +kernel : ¬ (51 : Basis) < (9 : Basis)) ordered))
    (Fin.cases (fun (ordered : (51 : Basis) < (10 : Basis)) => False.elim ((by decide +kernel : ¬ (51 : Basis) < (10 : Basis)) ordered))
    (Fin.cases (fun (ordered : (51 : Basis) < (11 : Basis)) => False.elim ((by decide +kernel : ¬ (51 : Basis) < (11 : Basis)) ordered))
    (Fin.cases (fun (ordered : (51 : Basis) < (12 : Basis)) => False.elim ((by decide +kernel : ¬ (51 : Basis) < (12 : Basis)) ordered))
    (Fin.cases (fun (ordered : (51 : Basis) < (13 : Basis)) => False.elim ((by decide +kernel : ¬ (51 : Basis) < (13 : Basis)) ordered))
    (Fin.cases (fun (ordered : (51 : Basis) < (14 : Basis)) => False.elim ((by decide +kernel : ¬ (51 : Basis) < (14 : Basis)) ordered))
    (Fin.cases (fun (ordered : (51 : Basis) < (15 : Basis)) => False.elim ((by decide +kernel : ¬ (51 : Basis) < (15 : Basis)) ordered))
    (Fin.cases (fun (ordered : (51 : Basis) < (16 : Basis)) => False.elim ((by decide +kernel : ¬ (51 : Basis) < (16 : Basis)) ordered))
    (Fin.cases (fun (ordered : (51 : Basis) < (17 : Basis)) => False.elim ((by decide +kernel : ¬ (51 : Basis) < (17 : Basis)) ordered))
    (Fin.cases (fun (ordered : (51 : Basis) < (18 : Basis)) => False.elim ((by decide +kernel : ¬ (51 : Basis) < (18 : Basis)) ordered))
    (Fin.cases (fun (ordered : (51 : Basis) < (19 : Basis)) => False.elim ((by decide +kernel : ¬ (51 : Basis) < (19 : Basis)) ordered))
    (Fin.cases (fun (ordered : (51 : Basis) < (20 : Basis)) => False.elim ((by decide +kernel : ¬ (51 : Basis) < (20 : Basis)) ordered))
    (Fin.cases (fun (ordered : (51 : Basis) < (21 : Basis)) => False.elim ((by decide +kernel : ¬ (51 : Basis) < (21 : Basis)) ordered))
    (Fin.cases (fun (ordered : (51 : Basis) < (22 : Basis)) => False.elim ((by decide +kernel : ¬ (51 : Basis) < (22 : Basis)) ordered))
    (Fin.cases (fun (ordered : (51 : Basis) < (23 : Basis)) => False.elim ((by decide +kernel : ¬ (51 : Basis) < (23 : Basis)) ordered))
    (Fin.cases (fun (ordered : (51 : Basis) < (24 : Basis)) => False.elim ((by decide +kernel : ¬ (51 : Basis) < (24 : Basis)) ordered))
    (Fin.cases (fun (ordered : (51 : Basis) < (25 : Basis)) => False.elim ((by decide +kernel : ¬ (51 : Basis) < (25 : Basis)) ordered))
    (Fin.cases (fun (ordered : (51 : Basis) < (26 : Basis)) => False.elim ((by decide +kernel : ¬ (51 : Basis) < (26 : Basis)) ordered))
    (Fin.cases (fun (ordered : (51 : Basis) < (27 : Basis)) => False.elim ((by decide +kernel : ¬ (51 : Basis) < (27 : Basis)) ordered))
    (Fin.cases (fun (ordered : (51 : Basis) < (28 : Basis)) => False.elim ((by decide +kernel : ¬ (51 : Basis) < (28 : Basis)) ordered))
    (Fin.cases (fun (ordered : (51 : Basis) < (29 : Basis)) => False.elim ((by decide +kernel : ¬ (51 : Basis) < (29 : Basis)) ordered))
    (Fin.cases (fun (ordered : (51 : Basis) < (30 : Basis)) => False.elim ((by decide +kernel : ¬ (51 : Basis) < (30 : Basis)) ordered))
    (Fin.cases (fun (ordered : (51 : Basis) < (31 : Basis)) => False.elim ((by decide +kernel : ¬ (51 : Basis) < (31 : Basis)) ordered))
    (Fin.cases (fun (ordered : (51 : Basis) < (32 : Basis)) => False.elim ((by decide +kernel : ¬ (51 : Basis) < (32 : Basis)) ordered))
    (Fin.cases (fun (ordered : (51 : Basis) < (33 : Basis)) => False.elim ((by decide +kernel : ¬ (51 : Basis) < (33 : Basis)) ordered))
    (Fin.cases (fun (ordered : (51 : Basis) < (34 : Basis)) => False.elim ((by decide +kernel : ¬ (51 : Basis) < (34 : Basis)) ordered))
    (Fin.cases (fun (ordered : (51 : Basis) < (35 : Basis)) => False.elim ((by decide +kernel : ¬ (51 : Basis) < (35 : Basis)) ordered))
    (Fin.cases (fun (ordered : (51 : Basis) < (36 : Basis)) => False.elim ((by decide +kernel : ¬ (51 : Basis) < (36 : Basis)) ordered))
    (Fin.cases (fun (ordered : (51 : Basis) < (37 : Basis)) => False.elim ((by decide +kernel : ¬ (51 : Basis) < (37 : Basis)) ordered))
    (Fin.cases (fun (ordered : (51 : Basis) < (38 : Basis)) => False.elim ((by decide +kernel : ¬ (51 : Basis) < (38 : Basis)) ordered))
    (Fin.cases (fun (ordered : (51 : Basis) < (39 : Basis)) => False.elim ((by decide +kernel : ¬ (51 : Basis) < (39 : Basis)) ordered))
    (Fin.cases (fun (ordered : (51 : Basis) < (40 : Basis)) => False.elim ((by decide +kernel : ¬ (51 : Basis) < (40 : Basis)) ordered))
    (Fin.cases (fun (ordered : (51 : Basis) < (41 : Basis)) => False.elim ((by decide +kernel : ¬ (51 : Basis) < (41 : Basis)) ordered))
    (Fin.cases (fun (ordered : (51 : Basis) < (42 : Basis)) => False.elim ((by decide +kernel : ¬ (51 : Basis) < (42 : Basis)) ordered))
    (Fin.cases (fun (ordered : (51 : Basis) < (43 : Basis)) => False.elim ((by decide +kernel : ¬ (51 : Basis) < (43 : Basis)) ordered))
    (Fin.cases (fun (ordered : (51 : Basis) < (44 : Basis)) => False.elim ((by decide +kernel : ¬ (51 : Basis) < (44 : Basis)) ordered))
    (Fin.cases (fun (ordered : (51 : Basis) < (45 : Basis)) => False.elim ((by decide +kernel : ¬ (51 : Basis) < (45 : Basis)) ordered))
    (Fin.cases (fun (ordered : (51 : Basis) < (46 : Basis)) => False.elim ((by decide +kernel : ¬ (51 : Basis) < (46 : Basis)) ordered))
    (Fin.cases (fun (ordered : (51 : Basis) < (47 : Basis)) => False.elim ((by decide +kernel : ¬ (51 : Basis) < (47 : Basis)) ordered))
    (Fin.cases (fun (ordered : (51 : Basis) < (48 : Basis)) => False.elim ((by decide +kernel : ¬ (51 : Basis) < (48 : Basis)) ordered))
    (Fin.cases (fun (ordered : (51 : Basis) < (49 : Basis)) => False.elim ((by decide +kernel : ¬ (51 : Basis) < (49 : Basis)) ordered))
    (Fin.cases (fun (ordered : (51 : Basis) < (50 : Basis)) => False.elim ((by decide +kernel : ¬ (51 : Basis) < (50 : Basis)) ordered))
    (Fin.cases (fun (ordered : (51 : Basis) < (51 : Basis)) => False.elim ((by decide +kernel : ¬ (51 : Basis) < (51 : Basis)) ordered))
    (Fin.cases (fun _ => ⟨⟨Factors.P229.factor7Plus,0,Factors.P229.checked7Plus⟩,⟨Factors.P229.factor7Minus,0,Factors.P229.checked7Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P229.factor8Plus,0,Factors.P229.checked8Plus⟩,⟨Factors.P229.factor8Minus,0,Factors.P229.checked8Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P229.factor9Plus,0,Factors.P229.checked9Plus⟩,⟨Factors.P229.factor9Minus,0,Factors.P229.checked9Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P229.factor10Plus,0,Factors.P229.checked10Plus⟩,⟨Factors.P229.factor10Minus,0,Factors.P229.checked10Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P229.factor11Plus,0,Factors.P229.checked11Plus⟩,⟨Factors.P229.factor11Minus,0,Factors.P229.checked11Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P229.factor12Plus,0,Factors.P229.checked12Plus⟩,⟨Factors.P229.factor12Minus,0,Factors.P229.checked12Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P229.factor13Plus,0,Factors.P229.checked13Plus⟩,⟨Factors.P229.factor13Minus,0,Factors.P229.checked13Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P229.factor14Plus,0,Factors.P229.checked14Plus⟩,⟨Factors.P229.factor14Minus,0,Factors.P229.checked14Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P229.factor15Plus,0,Factors.P229.checked15Plus⟩,⟨Factors.P229.factor15Minus,0,Factors.P229.checked15Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P230.factor0Plus,0,Factors.P230.checked0Plus⟩,⟨Factors.P230.factor0Minus,0,Factors.P230.checked0Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P230.factor1Plus,0,Factors.P230.checked1Plus⟩,⟨Factors.P230.factor1Minus,0,Factors.P230.checked1Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P230.factor2Plus,0,Factors.P230.checked2Plus⟩,⟨Factors.P230.factor2Minus,0,Factors.P230.checked2Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P230.factor3Plus,0,Factors.P230.checked3Plus⟩,⟨Factors.P230.factor3Minus,0,Factors.P230.checked3Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P230.factor4Plus,0,Factors.P230.checked4Plus⟩,⟨Factors.P230.factor4Minus,0,Factors.P230.checked4Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P230.factor5Plus,0,Factors.P230.checked5Plus⟩,⟨Factors.P230.factor5Minus,0,Factors.P230.checked5Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P230.factor6Plus,0,Factors.P230.checked6Plus⟩,⟨Factors.P230.factor6Minus,0,Factors.P230.checked6Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P230.factor7Plus,0,Factors.P230.checked7Plus⟩,⟨Factors.P230.factor7Minus,0,Factors.P230.checked7Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P230.factor8Plus,0,Factors.P230.checked8Plus⟩,⟨Factors.P230.factor8Minus,0,Factors.P230.checked8Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P230.factor9Plus,0,Factors.P230.checked9Plus⟩,⟨Factors.P230.factor9Minus,0,Factors.P230.checked9Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P230.factor10Plus,0,Factors.P230.checked10Plus⟩,⟨Factors.P230.factor10Minus,0,Factors.P230.checked10Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P230.factor11Plus,0,Factors.P230.checked11Plus⟩,⟨Factors.P230.factor11Minus,0,Factors.P230.checked11Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P230.factor12Plus,0,Factors.P230.checked12Plus⟩,⟨Factors.P230.factor12Minus,0,Factors.P230.checked12Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P230.factor13Plus,0,Factors.P230.checked13Plus⟩,⟨Factors.P230.factor13Minus,0,Factors.P230.checked13Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P230.factor14Plus,0,Factors.P230.checked14Plus⟩,⟨Factors.P230.factor14Minus,0,Factors.P230.checked14Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P230.factor15Plus,0,Factors.P230.checked15Plus⟩,⟨Factors.P230.factor15Minus,0,Factors.P230.checked15Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P231.factor0Plus,0,Factors.P231.checked0Plus⟩,⟨Factors.P231.factor0Minus,0,Factors.P231.checked0Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P231.factor1Plus,0,Factors.P231.checked1Plus⟩,⟨Factors.P231.factor1Minus,0,Factors.P231.checked1Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P231.factor2Plus,0,Factors.P231.checked2Plus⟩,⟨Factors.P231.factor2Minus,0,Factors.P231.checked2Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P231.factor3Plus,0,Factors.P231.checked3Plus⟩,⟨Factors.P231.factor3Minus,0,Factors.P231.checked3Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P231.factor4Plus,0,Factors.P231.checked4Plus⟩,⟨Factors.P231.factor4Minus,0,Factors.P231.checked4Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P231.factor5Plus,0,Factors.P231.checked5Plus⟩,⟨Factors.P231.factor5Minus,0,Factors.P231.checked5Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P231.factor6Plus,0,Factors.P231.checked6Plus⟩,⟨Factors.P231.factor6Minus,0,Factors.P231.checked6Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P231.factor7Plus,0,Factors.P231.checked7Plus⟩,⟨Factors.P231.factor7Minus,0,Factors.P231.checked7Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P231.factor8Plus,0,Factors.P231.checked8Plus⟩,⟨Factors.P231.factor8Minus,0,Factors.P231.checked8Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P231.factor9Plus,0,Factors.P231.checked9Plus⟩,⟨Factors.P231.factor9Minus,0,Factors.P231.checked9Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P231.factor10Plus,0,Factors.P231.checked10Plus⟩,⟨Factors.P231.factor10Minus,0,Factors.P231.checked10Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P231.factor11Plus,0,Factors.P231.checked11Plus⟩,⟨Factors.P231.factor11Minus,0,Factors.P231.checked11Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P231.factor12Plus,0,Factors.P231.checked12Plus⟩,⟨Factors.P231.factor12Minus,0,Factors.P231.checked12Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P231.factor13Plus,0,Factors.P231.checked13Plus⟩,⟨Factors.P231.factor13Minus,0,Factors.P231.checked13Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P231.factor14Plus,0,Factors.P231.checked14Plus⟩,⟨Factors.P231.factor14Minus,0,Factors.P231.checked14Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P231.factor15Plus,0,Factors.P231.checked15Plus⟩,⟨Factors.P231.factor15Minus,0,Factors.P231.checked15Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P232.factor0Plus,0,Factors.P232.checked0Plus⟩,⟨Factors.P232.factor0Minus,0,Factors.P232.checked0Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P232.factor1Plus,0,Factors.P232.checked1Plus⟩,⟨Factors.P232.factor1Minus,0,Factors.P232.checked1Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P232.factor2Plus,0,Factors.P232.checked2Plus⟩,⟨Factors.P232.factor2Minus,0,Factors.P232.checked2Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P232.factor3Plus,0,Factors.P232.checked3Plus⟩,⟨Factors.P232.factor3Minus,0,Factors.P232.checked3Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P232.factor4Plus,0,Factors.P232.checked4Plus⟩,⟨Factors.P232.factor4Minus,0,Factors.P232.checked4Minus⟩⟩)
    ((fun impossible => Fin.elim0 impossible)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))

end
end LAlanine40K2025.Thermal.Recovery.Reservoir.Pointer.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Rows
end SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule
