import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.OrdinaryPair
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P232
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P233
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P234
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P235

set_option autoImplicit false
namespace SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule
namespace LAlanine40K2025.Thermal.Recovery.Reservoir.Pointer.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Rows
open Propagation.Interface
noncomputable section

set_option maxHeartbeats 400000 in
def row52 : (b : Basis) → (52 : Basis) < b → OrdinaryPair 52 b :=
  Fin.cases (fun (ordered : (52 : Basis) < (0 : Basis)) => False.elim ((by decide +kernel : ¬ (52 : Basis) < (0 : Basis)) ordered))
    (Fin.cases (fun (ordered : (52 : Basis) < (1 : Basis)) => False.elim ((by decide +kernel : ¬ (52 : Basis) < (1 : Basis)) ordered))
    (Fin.cases (fun (ordered : (52 : Basis) < (2 : Basis)) => False.elim ((by decide +kernel : ¬ (52 : Basis) < (2 : Basis)) ordered))
    (Fin.cases (fun (ordered : (52 : Basis) < (3 : Basis)) => False.elim ((by decide +kernel : ¬ (52 : Basis) < (3 : Basis)) ordered))
    (Fin.cases (fun (ordered : (52 : Basis) < (4 : Basis)) => False.elim ((by decide +kernel : ¬ (52 : Basis) < (4 : Basis)) ordered))
    (Fin.cases (fun (ordered : (52 : Basis) < (5 : Basis)) => False.elim ((by decide +kernel : ¬ (52 : Basis) < (5 : Basis)) ordered))
    (Fin.cases (fun (ordered : (52 : Basis) < (6 : Basis)) => False.elim ((by decide +kernel : ¬ (52 : Basis) < (6 : Basis)) ordered))
    (Fin.cases (fun (ordered : (52 : Basis) < (7 : Basis)) => False.elim ((by decide +kernel : ¬ (52 : Basis) < (7 : Basis)) ordered))
    (Fin.cases (fun (ordered : (52 : Basis) < (8 : Basis)) => False.elim ((by decide +kernel : ¬ (52 : Basis) < (8 : Basis)) ordered))
    (Fin.cases (fun (ordered : (52 : Basis) < (9 : Basis)) => False.elim ((by decide +kernel : ¬ (52 : Basis) < (9 : Basis)) ordered))
    (Fin.cases (fun (ordered : (52 : Basis) < (10 : Basis)) => False.elim ((by decide +kernel : ¬ (52 : Basis) < (10 : Basis)) ordered))
    (Fin.cases (fun (ordered : (52 : Basis) < (11 : Basis)) => False.elim ((by decide +kernel : ¬ (52 : Basis) < (11 : Basis)) ordered))
    (Fin.cases (fun (ordered : (52 : Basis) < (12 : Basis)) => False.elim ((by decide +kernel : ¬ (52 : Basis) < (12 : Basis)) ordered))
    (Fin.cases (fun (ordered : (52 : Basis) < (13 : Basis)) => False.elim ((by decide +kernel : ¬ (52 : Basis) < (13 : Basis)) ordered))
    (Fin.cases (fun (ordered : (52 : Basis) < (14 : Basis)) => False.elim ((by decide +kernel : ¬ (52 : Basis) < (14 : Basis)) ordered))
    (Fin.cases (fun (ordered : (52 : Basis) < (15 : Basis)) => False.elim ((by decide +kernel : ¬ (52 : Basis) < (15 : Basis)) ordered))
    (Fin.cases (fun (ordered : (52 : Basis) < (16 : Basis)) => False.elim ((by decide +kernel : ¬ (52 : Basis) < (16 : Basis)) ordered))
    (Fin.cases (fun (ordered : (52 : Basis) < (17 : Basis)) => False.elim ((by decide +kernel : ¬ (52 : Basis) < (17 : Basis)) ordered))
    (Fin.cases (fun (ordered : (52 : Basis) < (18 : Basis)) => False.elim ((by decide +kernel : ¬ (52 : Basis) < (18 : Basis)) ordered))
    (Fin.cases (fun (ordered : (52 : Basis) < (19 : Basis)) => False.elim ((by decide +kernel : ¬ (52 : Basis) < (19 : Basis)) ordered))
    (Fin.cases (fun (ordered : (52 : Basis) < (20 : Basis)) => False.elim ((by decide +kernel : ¬ (52 : Basis) < (20 : Basis)) ordered))
    (Fin.cases (fun (ordered : (52 : Basis) < (21 : Basis)) => False.elim ((by decide +kernel : ¬ (52 : Basis) < (21 : Basis)) ordered))
    (Fin.cases (fun (ordered : (52 : Basis) < (22 : Basis)) => False.elim ((by decide +kernel : ¬ (52 : Basis) < (22 : Basis)) ordered))
    (Fin.cases (fun (ordered : (52 : Basis) < (23 : Basis)) => False.elim ((by decide +kernel : ¬ (52 : Basis) < (23 : Basis)) ordered))
    (Fin.cases (fun (ordered : (52 : Basis) < (24 : Basis)) => False.elim ((by decide +kernel : ¬ (52 : Basis) < (24 : Basis)) ordered))
    (Fin.cases (fun (ordered : (52 : Basis) < (25 : Basis)) => False.elim ((by decide +kernel : ¬ (52 : Basis) < (25 : Basis)) ordered))
    (Fin.cases (fun (ordered : (52 : Basis) < (26 : Basis)) => False.elim ((by decide +kernel : ¬ (52 : Basis) < (26 : Basis)) ordered))
    (Fin.cases (fun (ordered : (52 : Basis) < (27 : Basis)) => False.elim ((by decide +kernel : ¬ (52 : Basis) < (27 : Basis)) ordered))
    (Fin.cases (fun (ordered : (52 : Basis) < (28 : Basis)) => False.elim ((by decide +kernel : ¬ (52 : Basis) < (28 : Basis)) ordered))
    (Fin.cases (fun (ordered : (52 : Basis) < (29 : Basis)) => False.elim ((by decide +kernel : ¬ (52 : Basis) < (29 : Basis)) ordered))
    (Fin.cases (fun (ordered : (52 : Basis) < (30 : Basis)) => False.elim ((by decide +kernel : ¬ (52 : Basis) < (30 : Basis)) ordered))
    (Fin.cases (fun (ordered : (52 : Basis) < (31 : Basis)) => False.elim ((by decide +kernel : ¬ (52 : Basis) < (31 : Basis)) ordered))
    (Fin.cases (fun (ordered : (52 : Basis) < (32 : Basis)) => False.elim ((by decide +kernel : ¬ (52 : Basis) < (32 : Basis)) ordered))
    (Fin.cases (fun (ordered : (52 : Basis) < (33 : Basis)) => False.elim ((by decide +kernel : ¬ (52 : Basis) < (33 : Basis)) ordered))
    (Fin.cases (fun (ordered : (52 : Basis) < (34 : Basis)) => False.elim ((by decide +kernel : ¬ (52 : Basis) < (34 : Basis)) ordered))
    (Fin.cases (fun (ordered : (52 : Basis) < (35 : Basis)) => False.elim ((by decide +kernel : ¬ (52 : Basis) < (35 : Basis)) ordered))
    (Fin.cases (fun (ordered : (52 : Basis) < (36 : Basis)) => False.elim ((by decide +kernel : ¬ (52 : Basis) < (36 : Basis)) ordered))
    (Fin.cases (fun (ordered : (52 : Basis) < (37 : Basis)) => False.elim ((by decide +kernel : ¬ (52 : Basis) < (37 : Basis)) ordered))
    (Fin.cases (fun (ordered : (52 : Basis) < (38 : Basis)) => False.elim ((by decide +kernel : ¬ (52 : Basis) < (38 : Basis)) ordered))
    (Fin.cases (fun (ordered : (52 : Basis) < (39 : Basis)) => False.elim ((by decide +kernel : ¬ (52 : Basis) < (39 : Basis)) ordered))
    (Fin.cases (fun (ordered : (52 : Basis) < (40 : Basis)) => False.elim ((by decide +kernel : ¬ (52 : Basis) < (40 : Basis)) ordered))
    (Fin.cases (fun (ordered : (52 : Basis) < (41 : Basis)) => False.elim ((by decide +kernel : ¬ (52 : Basis) < (41 : Basis)) ordered))
    (Fin.cases (fun (ordered : (52 : Basis) < (42 : Basis)) => False.elim ((by decide +kernel : ¬ (52 : Basis) < (42 : Basis)) ordered))
    (Fin.cases (fun (ordered : (52 : Basis) < (43 : Basis)) => False.elim ((by decide +kernel : ¬ (52 : Basis) < (43 : Basis)) ordered))
    (Fin.cases (fun (ordered : (52 : Basis) < (44 : Basis)) => False.elim ((by decide +kernel : ¬ (52 : Basis) < (44 : Basis)) ordered))
    (Fin.cases (fun (ordered : (52 : Basis) < (45 : Basis)) => False.elim ((by decide +kernel : ¬ (52 : Basis) < (45 : Basis)) ordered))
    (Fin.cases (fun (ordered : (52 : Basis) < (46 : Basis)) => False.elim ((by decide +kernel : ¬ (52 : Basis) < (46 : Basis)) ordered))
    (Fin.cases (fun (ordered : (52 : Basis) < (47 : Basis)) => False.elim ((by decide +kernel : ¬ (52 : Basis) < (47 : Basis)) ordered))
    (Fin.cases (fun (ordered : (52 : Basis) < (48 : Basis)) => False.elim ((by decide +kernel : ¬ (52 : Basis) < (48 : Basis)) ordered))
    (Fin.cases (fun (ordered : (52 : Basis) < (49 : Basis)) => False.elim ((by decide +kernel : ¬ (52 : Basis) < (49 : Basis)) ordered))
    (Fin.cases (fun (ordered : (52 : Basis) < (50 : Basis)) => False.elim ((by decide +kernel : ¬ (52 : Basis) < (50 : Basis)) ordered))
    (Fin.cases (fun (ordered : (52 : Basis) < (51 : Basis)) => False.elim ((by decide +kernel : ¬ (52 : Basis) < (51 : Basis)) ordered))
    (Fin.cases (fun (ordered : (52 : Basis) < (52 : Basis)) => False.elim ((by decide +kernel : ¬ (52 : Basis) < (52 : Basis)) ordered))
    (Fin.cases (fun _ => ⟨⟨Factors.P232.factor5Plus,0,Factors.P232.checked5Plus⟩,⟨Factors.P232.factor5Minus,0,Factors.P232.checked5Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P232.factor6Plus,0,Factors.P232.checked6Plus⟩,⟨Factors.P232.factor6Minus,0,Factors.P232.checked6Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P232.factor7Plus,0,Factors.P232.checked7Plus⟩,⟨Factors.P232.factor7Minus,0,Factors.P232.checked7Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P232.factor8Plus,0,Factors.P232.checked8Plus⟩,⟨Factors.P232.factor8Minus,0,Factors.P232.checked8Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P232.factor9Plus,0,Factors.P232.checked9Plus⟩,⟨Factors.P232.factor9Minus,0,Factors.P232.checked9Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P232.factor10Plus,0,Factors.P232.checked10Plus⟩,⟨Factors.P232.factor10Minus,0,Factors.P232.checked10Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P232.factor11Plus,0,Factors.P232.checked11Plus⟩,⟨Factors.P232.factor11Minus,0,Factors.P232.checked11Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P232.factor12Plus,0,Factors.P232.checked12Plus⟩,⟨Factors.P232.factor12Minus,0,Factors.P232.checked12Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P232.factor13Plus,0,Factors.P232.checked13Plus⟩,⟨Factors.P232.factor13Minus,0,Factors.P232.checked13Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P232.factor14Plus,0,Factors.P232.checked14Plus⟩,⟨Factors.P232.factor14Minus,0,Factors.P232.checked14Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P232.factor15Plus,0,Factors.P232.checked15Plus⟩,⟨Factors.P232.factor15Minus,0,Factors.P232.checked15Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P233.factor0Plus,0,Factors.P233.checked0Plus⟩,⟨Factors.P233.factor0Minus,0,Factors.P233.checked0Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P233.factor1Plus,0,Factors.P233.checked1Plus⟩,⟨Factors.P233.factor1Minus,0,Factors.P233.checked1Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P233.factor2Plus,0,Factors.P233.checked2Plus⟩,⟨Factors.P233.factor2Minus,0,Factors.P233.checked2Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P233.factor3Plus,0,Factors.P233.checked3Plus⟩,⟨Factors.P233.factor3Minus,0,Factors.P233.checked3Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P233.factor4Plus,0,Factors.P233.checked4Plus⟩,⟨Factors.P233.factor4Minus,0,Factors.P233.checked4Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P233.factor5Plus,0,Factors.P233.checked5Plus⟩,⟨Factors.P233.factor5Minus,0,Factors.P233.checked5Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P233.factor6Plus,0,Factors.P233.checked6Plus⟩,⟨Factors.P233.factor6Minus,0,Factors.P233.checked6Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P233.factor7Plus,0,Factors.P233.checked7Plus⟩,⟨Factors.P233.factor7Minus,0,Factors.P233.checked7Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P233.factor8Plus,0,Factors.P233.checked8Plus⟩,⟨Factors.P233.factor8Minus,0,Factors.P233.checked8Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P233.factor9Plus,0,Factors.P233.checked9Plus⟩,⟨Factors.P233.factor9Minus,0,Factors.P233.checked9Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P233.factor10Plus,0,Factors.P233.checked10Plus⟩,⟨Factors.P233.factor10Minus,0,Factors.P233.checked10Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P233.factor11Plus,0,Factors.P233.checked11Plus⟩,⟨Factors.P233.factor11Minus,0,Factors.P233.checked11Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P233.factor12Plus,0,Factors.P233.checked12Plus⟩,⟨Factors.P233.factor12Minus,0,Factors.P233.checked12Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P233.factor13Plus,0,Factors.P233.checked13Plus⟩,⟨Factors.P233.factor13Minus,0,Factors.P233.checked13Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P233.factor14Plus,0,Factors.P233.checked14Plus⟩,⟨Factors.P233.factor14Minus,0,Factors.P233.checked14Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P233.factor15Plus,0,Factors.P233.checked15Plus⟩,⟨Factors.P233.factor15Minus,0,Factors.P233.checked15Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P234.factor0Plus,0,Factors.P234.checked0Plus⟩,⟨Factors.P234.factor0Minus,0,Factors.P234.checked0Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P234.factor1Plus,0,Factors.P234.checked1Plus⟩,⟨Factors.P234.factor1Minus,0,Factors.P234.checked1Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P234.factor2Plus,0,Factors.P234.checked2Plus⟩,⟨Factors.P234.factor2Minus,0,Factors.P234.checked2Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P234.factor3Plus,0,Factors.P234.checked3Plus⟩,⟨Factors.P234.factor3Minus,0,Factors.P234.checked3Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P234.factor4Plus,0,Factors.P234.checked4Plus⟩,⟨Factors.P234.factor4Minus,0,Factors.P234.checked4Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P234.factor5Plus,0,Factors.P234.checked5Plus⟩,⟨Factors.P234.factor5Minus,0,Factors.P234.checked5Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P234.factor6Plus,0,Factors.P234.checked6Plus⟩,⟨Factors.P234.factor6Minus,0,Factors.P234.checked6Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P234.factor7Plus,0,Factors.P234.checked7Plus⟩,⟨Factors.P234.factor7Minus,0,Factors.P234.checked7Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P234.factor8Plus,0,Factors.P234.checked8Plus⟩,⟨Factors.P234.factor8Minus,0,Factors.P234.checked8Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P234.factor9Plus,0,Factors.P234.checked9Plus⟩,⟨Factors.P234.factor9Minus,0,Factors.P234.checked9Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P234.factor10Plus,0,Factors.P234.checked10Plus⟩,⟨Factors.P234.factor10Minus,0,Factors.P234.checked10Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P234.factor11Plus,0,Factors.P234.checked11Plus⟩,⟨Factors.P234.factor11Minus,0,Factors.P234.checked11Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P234.factor12Plus,0,Factors.P234.checked12Plus⟩,⟨Factors.P234.factor12Minus,0,Factors.P234.checked12Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P234.factor13Plus,0,Factors.P234.checked13Plus⟩,⟨Factors.P234.factor13Minus,0,Factors.P234.checked13Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P234.factor14Plus,0,Factors.P234.checked14Plus⟩,⟨Factors.P234.factor14Minus,0,Factors.P234.checked14Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P234.factor15Plus,0,Factors.P234.checked15Plus⟩,⟨Factors.P234.factor15Minus,0,Factors.P234.checked15Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P235.factor0Plus,0,Factors.P235.checked0Plus⟩,⟨Factors.P235.factor0Minus,0,Factors.P235.checked0Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P235.factor1Plus,0,Factors.P235.checked1Plus⟩,⟨Factors.P235.factor1Minus,0,Factors.P235.checked1Minus⟩⟩)
    ((fun impossible => Fin.elim0 impossible)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))

end
end LAlanine40K2025.Thermal.Recovery.Reservoir.Pointer.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Rows
end SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule
