import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.OrdinaryPair
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P235
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P236
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P237

set_option autoImplicit false
namespace SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule
namespace LAlanine40K2025.Thermal.Recovery.Reservoir.Pointer.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Rows
open Propagation.Interface
noncomputable section

set_option maxHeartbeats 400000 in
def row53 : (b : Basis) → (53 : Basis) < b → OrdinaryPair 53 b :=
  Fin.cases (fun (ordered : (53 : Basis) < (0 : Basis)) => False.elim ((by decide +kernel : ¬ (53 : Basis) < (0 : Basis)) ordered))
    (Fin.cases (fun (ordered : (53 : Basis) < (1 : Basis)) => False.elim ((by decide +kernel : ¬ (53 : Basis) < (1 : Basis)) ordered))
    (Fin.cases (fun (ordered : (53 : Basis) < (2 : Basis)) => False.elim ((by decide +kernel : ¬ (53 : Basis) < (2 : Basis)) ordered))
    (Fin.cases (fun (ordered : (53 : Basis) < (3 : Basis)) => False.elim ((by decide +kernel : ¬ (53 : Basis) < (3 : Basis)) ordered))
    (Fin.cases (fun (ordered : (53 : Basis) < (4 : Basis)) => False.elim ((by decide +kernel : ¬ (53 : Basis) < (4 : Basis)) ordered))
    (Fin.cases (fun (ordered : (53 : Basis) < (5 : Basis)) => False.elim ((by decide +kernel : ¬ (53 : Basis) < (5 : Basis)) ordered))
    (Fin.cases (fun (ordered : (53 : Basis) < (6 : Basis)) => False.elim ((by decide +kernel : ¬ (53 : Basis) < (6 : Basis)) ordered))
    (Fin.cases (fun (ordered : (53 : Basis) < (7 : Basis)) => False.elim ((by decide +kernel : ¬ (53 : Basis) < (7 : Basis)) ordered))
    (Fin.cases (fun (ordered : (53 : Basis) < (8 : Basis)) => False.elim ((by decide +kernel : ¬ (53 : Basis) < (8 : Basis)) ordered))
    (Fin.cases (fun (ordered : (53 : Basis) < (9 : Basis)) => False.elim ((by decide +kernel : ¬ (53 : Basis) < (9 : Basis)) ordered))
    (Fin.cases (fun (ordered : (53 : Basis) < (10 : Basis)) => False.elim ((by decide +kernel : ¬ (53 : Basis) < (10 : Basis)) ordered))
    (Fin.cases (fun (ordered : (53 : Basis) < (11 : Basis)) => False.elim ((by decide +kernel : ¬ (53 : Basis) < (11 : Basis)) ordered))
    (Fin.cases (fun (ordered : (53 : Basis) < (12 : Basis)) => False.elim ((by decide +kernel : ¬ (53 : Basis) < (12 : Basis)) ordered))
    (Fin.cases (fun (ordered : (53 : Basis) < (13 : Basis)) => False.elim ((by decide +kernel : ¬ (53 : Basis) < (13 : Basis)) ordered))
    (Fin.cases (fun (ordered : (53 : Basis) < (14 : Basis)) => False.elim ((by decide +kernel : ¬ (53 : Basis) < (14 : Basis)) ordered))
    (Fin.cases (fun (ordered : (53 : Basis) < (15 : Basis)) => False.elim ((by decide +kernel : ¬ (53 : Basis) < (15 : Basis)) ordered))
    (Fin.cases (fun (ordered : (53 : Basis) < (16 : Basis)) => False.elim ((by decide +kernel : ¬ (53 : Basis) < (16 : Basis)) ordered))
    (Fin.cases (fun (ordered : (53 : Basis) < (17 : Basis)) => False.elim ((by decide +kernel : ¬ (53 : Basis) < (17 : Basis)) ordered))
    (Fin.cases (fun (ordered : (53 : Basis) < (18 : Basis)) => False.elim ((by decide +kernel : ¬ (53 : Basis) < (18 : Basis)) ordered))
    (Fin.cases (fun (ordered : (53 : Basis) < (19 : Basis)) => False.elim ((by decide +kernel : ¬ (53 : Basis) < (19 : Basis)) ordered))
    (Fin.cases (fun (ordered : (53 : Basis) < (20 : Basis)) => False.elim ((by decide +kernel : ¬ (53 : Basis) < (20 : Basis)) ordered))
    (Fin.cases (fun (ordered : (53 : Basis) < (21 : Basis)) => False.elim ((by decide +kernel : ¬ (53 : Basis) < (21 : Basis)) ordered))
    (Fin.cases (fun (ordered : (53 : Basis) < (22 : Basis)) => False.elim ((by decide +kernel : ¬ (53 : Basis) < (22 : Basis)) ordered))
    (Fin.cases (fun (ordered : (53 : Basis) < (23 : Basis)) => False.elim ((by decide +kernel : ¬ (53 : Basis) < (23 : Basis)) ordered))
    (Fin.cases (fun (ordered : (53 : Basis) < (24 : Basis)) => False.elim ((by decide +kernel : ¬ (53 : Basis) < (24 : Basis)) ordered))
    (Fin.cases (fun (ordered : (53 : Basis) < (25 : Basis)) => False.elim ((by decide +kernel : ¬ (53 : Basis) < (25 : Basis)) ordered))
    (Fin.cases (fun (ordered : (53 : Basis) < (26 : Basis)) => False.elim ((by decide +kernel : ¬ (53 : Basis) < (26 : Basis)) ordered))
    (Fin.cases (fun (ordered : (53 : Basis) < (27 : Basis)) => False.elim ((by decide +kernel : ¬ (53 : Basis) < (27 : Basis)) ordered))
    (Fin.cases (fun (ordered : (53 : Basis) < (28 : Basis)) => False.elim ((by decide +kernel : ¬ (53 : Basis) < (28 : Basis)) ordered))
    (Fin.cases (fun (ordered : (53 : Basis) < (29 : Basis)) => False.elim ((by decide +kernel : ¬ (53 : Basis) < (29 : Basis)) ordered))
    (Fin.cases (fun (ordered : (53 : Basis) < (30 : Basis)) => False.elim ((by decide +kernel : ¬ (53 : Basis) < (30 : Basis)) ordered))
    (Fin.cases (fun (ordered : (53 : Basis) < (31 : Basis)) => False.elim ((by decide +kernel : ¬ (53 : Basis) < (31 : Basis)) ordered))
    (Fin.cases (fun (ordered : (53 : Basis) < (32 : Basis)) => False.elim ((by decide +kernel : ¬ (53 : Basis) < (32 : Basis)) ordered))
    (Fin.cases (fun (ordered : (53 : Basis) < (33 : Basis)) => False.elim ((by decide +kernel : ¬ (53 : Basis) < (33 : Basis)) ordered))
    (Fin.cases (fun (ordered : (53 : Basis) < (34 : Basis)) => False.elim ((by decide +kernel : ¬ (53 : Basis) < (34 : Basis)) ordered))
    (Fin.cases (fun (ordered : (53 : Basis) < (35 : Basis)) => False.elim ((by decide +kernel : ¬ (53 : Basis) < (35 : Basis)) ordered))
    (Fin.cases (fun (ordered : (53 : Basis) < (36 : Basis)) => False.elim ((by decide +kernel : ¬ (53 : Basis) < (36 : Basis)) ordered))
    (Fin.cases (fun (ordered : (53 : Basis) < (37 : Basis)) => False.elim ((by decide +kernel : ¬ (53 : Basis) < (37 : Basis)) ordered))
    (Fin.cases (fun (ordered : (53 : Basis) < (38 : Basis)) => False.elim ((by decide +kernel : ¬ (53 : Basis) < (38 : Basis)) ordered))
    (Fin.cases (fun (ordered : (53 : Basis) < (39 : Basis)) => False.elim ((by decide +kernel : ¬ (53 : Basis) < (39 : Basis)) ordered))
    (Fin.cases (fun (ordered : (53 : Basis) < (40 : Basis)) => False.elim ((by decide +kernel : ¬ (53 : Basis) < (40 : Basis)) ordered))
    (Fin.cases (fun (ordered : (53 : Basis) < (41 : Basis)) => False.elim ((by decide +kernel : ¬ (53 : Basis) < (41 : Basis)) ordered))
    (Fin.cases (fun (ordered : (53 : Basis) < (42 : Basis)) => False.elim ((by decide +kernel : ¬ (53 : Basis) < (42 : Basis)) ordered))
    (Fin.cases (fun (ordered : (53 : Basis) < (43 : Basis)) => False.elim ((by decide +kernel : ¬ (53 : Basis) < (43 : Basis)) ordered))
    (Fin.cases (fun (ordered : (53 : Basis) < (44 : Basis)) => False.elim ((by decide +kernel : ¬ (53 : Basis) < (44 : Basis)) ordered))
    (Fin.cases (fun (ordered : (53 : Basis) < (45 : Basis)) => False.elim ((by decide +kernel : ¬ (53 : Basis) < (45 : Basis)) ordered))
    (Fin.cases (fun (ordered : (53 : Basis) < (46 : Basis)) => False.elim ((by decide +kernel : ¬ (53 : Basis) < (46 : Basis)) ordered))
    (Fin.cases (fun (ordered : (53 : Basis) < (47 : Basis)) => False.elim ((by decide +kernel : ¬ (53 : Basis) < (47 : Basis)) ordered))
    (Fin.cases (fun (ordered : (53 : Basis) < (48 : Basis)) => False.elim ((by decide +kernel : ¬ (53 : Basis) < (48 : Basis)) ordered))
    (Fin.cases (fun (ordered : (53 : Basis) < (49 : Basis)) => False.elim ((by decide +kernel : ¬ (53 : Basis) < (49 : Basis)) ordered))
    (Fin.cases (fun (ordered : (53 : Basis) < (50 : Basis)) => False.elim ((by decide +kernel : ¬ (53 : Basis) < (50 : Basis)) ordered))
    (Fin.cases (fun (ordered : (53 : Basis) < (51 : Basis)) => False.elim ((by decide +kernel : ¬ (53 : Basis) < (51 : Basis)) ordered))
    (Fin.cases (fun (ordered : (53 : Basis) < (52 : Basis)) => False.elim ((by decide +kernel : ¬ (53 : Basis) < (52 : Basis)) ordered))
    (Fin.cases (fun (ordered : (53 : Basis) < (53 : Basis)) => False.elim ((by decide +kernel : ¬ (53 : Basis) < (53 : Basis)) ordered))
    (Fin.cases (fun _ => ⟨⟨Factors.P235.factor2Plus,0,Factors.P235.checked2Plus⟩,⟨Factors.P235.factor2Minus,0,Factors.P235.checked2Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P235.factor3Plus,0,Factors.P235.checked3Plus⟩,⟨Factors.P235.factor3Minus,0,Factors.P235.checked3Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P235.factor4Plus,0,Factors.P235.checked4Plus⟩,⟨Factors.P235.factor4Minus,0,Factors.P235.checked4Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P235.factor5Plus,0,Factors.P235.checked5Plus⟩,⟨Factors.P235.factor5Minus,0,Factors.P235.checked5Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P235.factor6Plus,0,Factors.P235.checked6Plus⟩,⟨Factors.P235.factor6Minus,0,Factors.P235.checked6Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P235.factor7Plus,0,Factors.P235.checked7Plus⟩,⟨Factors.P235.factor7Minus,0,Factors.P235.checked7Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P235.factor8Plus,0,Factors.P235.checked8Plus⟩,⟨Factors.P235.factor8Minus,0,Factors.P235.checked8Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P235.factor9Plus,0,Factors.P235.checked9Plus⟩,⟨Factors.P235.factor9Minus,0,Factors.P235.checked9Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P235.factor10Plus,0,Factors.P235.checked10Plus⟩,⟨Factors.P235.factor10Minus,0,Factors.P235.checked10Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P235.factor11Plus,0,Factors.P235.checked11Plus⟩,⟨Factors.P235.factor11Minus,0,Factors.P235.checked11Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P235.factor12Plus,0,Factors.P235.checked12Plus⟩,⟨Factors.P235.factor12Minus,0,Factors.P235.checked12Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P235.factor13Plus,0,Factors.P235.checked13Plus⟩,⟨Factors.P235.factor13Minus,0,Factors.P235.checked13Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P235.factor14Plus,0,Factors.P235.checked14Plus⟩,⟨Factors.P235.factor14Minus,0,Factors.P235.checked14Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P235.factor15Plus,0,Factors.P235.checked15Plus⟩,⟨Factors.P235.factor15Minus,0,Factors.P235.checked15Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P236.factor0Plus,0,Factors.P236.checked0Plus⟩,⟨Factors.P236.factor0Minus,0,Factors.P236.checked0Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P236.factor1Plus,0,Factors.P236.checked1Plus⟩,⟨Factors.P236.factor1Minus,0,Factors.P236.checked1Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P236.factor2Plus,0,Factors.P236.checked2Plus⟩,⟨Factors.P236.factor2Minus,0,Factors.P236.checked2Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P236.factor3Plus,0,Factors.P236.checked3Plus⟩,⟨Factors.P236.factor3Minus,0,Factors.P236.checked3Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P236.factor4Plus,0,Factors.P236.checked4Plus⟩,⟨Factors.P236.factor4Minus,0,Factors.P236.checked4Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P236.factor5Plus,0,Factors.P236.checked5Plus⟩,⟨Factors.P236.factor5Minus,0,Factors.P236.checked5Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P236.factor6Plus,0,Factors.P236.checked6Plus⟩,⟨Factors.P236.factor6Minus,0,Factors.P236.checked6Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P236.factor7Plus,0,Factors.P236.checked7Plus⟩,⟨Factors.P236.factor7Minus,0,Factors.P236.checked7Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P236.factor8Plus,0,Factors.P236.checked8Plus⟩,⟨Factors.P236.factor8Minus,0,Factors.P236.checked8Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P236.factor9Plus,0,Factors.P236.checked9Plus⟩,⟨Factors.P236.factor9Minus,0,Factors.P236.checked9Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P236.factor10Plus,0,Factors.P236.checked10Plus⟩,⟨Factors.P236.factor10Minus,0,Factors.P236.checked10Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P236.factor11Plus,0,Factors.P236.checked11Plus⟩,⟨Factors.P236.factor11Minus,0,Factors.P236.checked11Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P236.factor12Plus,0,Factors.P236.checked12Plus⟩,⟨Factors.P236.factor12Minus,0,Factors.P236.checked12Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P236.factor13Plus,0,Factors.P236.checked13Plus⟩,⟨Factors.P236.factor13Minus,0,Factors.P236.checked13Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P236.factor14Plus,0,Factors.P236.checked14Plus⟩,⟨Factors.P236.factor14Minus,0,Factors.P236.checked14Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P236.factor15Plus,0,Factors.P236.checked15Plus⟩,⟨Factors.P236.factor15Minus,0,Factors.P236.checked15Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P237.factor0Plus,0,Factors.P237.checked0Plus⟩,⟨Factors.P237.factor0Minus,0,Factors.P237.checked0Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P237.factor1Plus,0,Factors.P237.checked1Plus⟩,⟨Factors.P237.factor1Minus,0,Factors.P237.checked1Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P237.factor2Plus,0,Factors.P237.checked2Plus⟩,⟨Factors.P237.factor2Minus,0,Factors.P237.checked2Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P237.factor3Plus,0,Factors.P237.checked3Plus⟩,⟨Factors.P237.factor3Minus,0,Factors.P237.checked3Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P237.factor4Plus,0,Factors.P237.checked4Plus⟩,⟨Factors.P237.factor4Minus,0,Factors.P237.checked4Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P237.factor5Plus,0,Factors.P237.checked5Plus⟩,⟨Factors.P237.factor5Minus,0,Factors.P237.checked5Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P237.factor6Plus,0,Factors.P237.checked6Plus⟩,⟨Factors.P237.factor6Minus,0,Factors.P237.checked6Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P237.factor7Plus,0,Factors.P237.checked7Plus⟩,⟨Factors.P237.factor7Minus,0,Factors.P237.checked7Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P237.factor8Plus,0,Factors.P237.checked8Plus⟩,⟨Factors.P237.factor8Minus,0,Factors.P237.checked8Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P237.factor9Plus,0,Factors.P237.checked9Plus⟩,⟨Factors.P237.factor9Minus,0,Factors.P237.checked9Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P237.factor10Plus,0,Factors.P237.checked10Plus⟩,⟨Factors.P237.factor10Minus,0,Factors.P237.checked10Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P237.factor11Plus,0,Factors.P237.checked11Plus⟩,⟨Factors.P237.factor11Minus,0,Factors.P237.checked11Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P237.factor12Plus,0,Factors.P237.checked12Plus⟩,⟨Factors.P237.factor12Minus,0,Factors.P237.checked12Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P237.factor13Plus,0,Factors.P237.checked13Plus⟩,⟨Factors.P237.factor13Minus,0,Factors.P237.checked13Minus⟩⟩)
    ((fun impossible => Fin.elim0 impossible)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))

end
end LAlanine40K2025.Thermal.Recovery.Reservoir.Pointer.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Rows
end SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule
