import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.OrdinaryPair
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P237
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P238
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P239
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P240

set_option autoImplicit false
namespace SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule
namespace LAlanine40K2025.Thermal.Recovery.Reservoir.Pointer.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Rows
open Propagation.Interface
noncomputable section

set_option maxHeartbeats 400000 in
def row54 : (b : Basis) → (54 : Basis) < b → OrdinaryPair 54 b :=
  Fin.cases (fun (ordered : (54 : Basis) < (0 : Basis)) => False.elim ((by decide +kernel : ¬ (54 : Basis) < (0 : Basis)) ordered))
    (Fin.cases (fun (ordered : (54 : Basis) < (1 : Basis)) => False.elim ((by decide +kernel : ¬ (54 : Basis) < (1 : Basis)) ordered))
    (Fin.cases (fun (ordered : (54 : Basis) < (2 : Basis)) => False.elim ((by decide +kernel : ¬ (54 : Basis) < (2 : Basis)) ordered))
    (Fin.cases (fun (ordered : (54 : Basis) < (3 : Basis)) => False.elim ((by decide +kernel : ¬ (54 : Basis) < (3 : Basis)) ordered))
    (Fin.cases (fun (ordered : (54 : Basis) < (4 : Basis)) => False.elim ((by decide +kernel : ¬ (54 : Basis) < (4 : Basis)) ordered))
    (Fin.cases (fun (ordered : (54 : Basis) < (5 : Basis)) => False.elim ((by decide +kernel : ¬ (54 : Basis) < (5 : Basis)) ordered))
    (Fin.cases (fun (ordered : (54 : Basis) < (6 : Basis)) => False.elim ((by decide +kernel : ¬ (54 : Basis) < (6 : Basis)) ordered))
    (Fin.cases (fun (ordered : (54 : Basis) < (7 : Basis)) => False.elim ((by decide +kernel : ¬ (54 : Basis) < (7 : Basis)) ordered))
    (Fin.cases (fun (ordered : (54 : Basis) < (8 : Basis)) => False.elim ((by decide +kernel : ¬ (54 : Basis) < (8 : Basis)) ordered))
    (Fin.cases (fun (ordered : (54 : Basis) < (9 : Basis)) => False.elim ((by decide +kernel : ¬ (54 : Basis) < (9 : Basis)) ordered))
    (Fin.cases (fun (ordered : (54 : Basis) < (10 : Basis)) => False.elim ((by decide +kernel : ¬ (54 : Basis) < (10 : Basis)) ordered))
    (Fin.cases (fun (ordered : (54 : Basis) < (11 : Basis)) => False.elim ((by decide +kernel : ¬ (54 : Basis) < (11 : Basis)) ordered))
    (Fin.cases (fun (ordered : (54 : Basis) < (12 : Basis)) => False.elim ((by decide +kernel : ¬ (54 : Basis) < (12 : Basis)) ordered))
    (Fin.cases (fun (ordered : (54 : Basis) < (13 : Basis)) => False.elim ((by decide +kernel : ¬ (54 : Basis) < (13 : Basis)) ordered))
    (Fin.cases (fun (ordered : (54 : Basis) < (14 : Basis)) => False.elim ((by decide +kernel : ¬ (54 : Basis) < (14 : Basis)) ordered))
    (Fin.cases (fun (ordered : (54 : Basis) < (15 : Basis)) => False.elim ((by decide +kernel : ¬ (54 : Basis) < (15 : Basis)) ordered))
    (Fin.cases (fun (ordered : (54 : Basis) < (16 : Basis)) => False.elim ((by decide +kernel : ¬ (54 : Basis) < (16 : Basis)) ordered))
    (Fin.cases (fun (ordered : (54 : Basis) < (17 : Basis)) => False.elim ((by decide +kernel : ¬ (54 : Basis) < (17 : Basis)) ordered))
    (Fin.cases (fun (ordered : (54 : Basis) < (18 : Basis)) => False.elim ((by decide +kernel : ¬ (54 : Basis) < (18 : Basis)) ordered))
    (Fin.cases (fun (ordered : (54 : Basis) < (19 : Basis)) => False.elim ((by decide +kernel : ¬ (54 : Basis) < (19 : Basis)) ordered))
    (Fin.cases (fun (ordered : (54 : Basis) < (20 : Basis)) => False.elim ((by decide +kernel : ¬ (54 : Basis) < (20 : Basis)) ordered))
    (Fin.cases (fun (ordered : (54 : Basis) < (21 : Basis)) => False.elim ((by decide +kernel : ¬ (54 : Basis) < (21 : Basis)) ordered))
    (Fin.cases (fun (ordered : (54 : Basis) < (22 : Basis)) => False.elim ((by decide +kernel : ¬ (54 : Basis) < (22 : Basis)) ordered))
    (Fin.cases (fun (ordered : (54 : Basis) < (23 : Basis)) => False.elim ((by decide +kernel : ¬ (54 : Basis) < (23 : Basis)) ordered))
    (Fin.cases (fun (ordered : (54 : Basis) < (24 : Basis)) => False.elim ((by decide +kernel : ¬ (54 : Basis) < (24 : Basis)) ordered))
    (Fin.cases (fun (ordered : (54 : Basis) < (25 : Basis)) => False.elim ((by decide +kernel : ¬ (54 : Basis) < (25 : Basis)) ordered))
    (Fin.cases (fun (ordered : (54 : Basis) < (26 : Basis)) => False.elim ((by decide +kernel : ¬ (54 : Basis) < (26 : Basis)) ordered))
    (Fin.cases (fun (ordered : (54 : Basis) < (27 : Basis)) => False.elim ((by decide +kernel : ¬ (54 : Basis) < (27 : Basis)) ordered))
    (Fin.cases (fun (ordered : (54 : Basis) < (28 : Basis)) => False.elim ((by decide +kernel : ¬ (54 : Basis) < (28 : Basis)) ordered))
    (Fin.cases (fun (ordered : (54 : Basis) < (29 : Basis)) => False.elim ((by decide +kernel : ¬ (54 : Basis) < (29 : Basis)) ordered))
    (Fin.cases (fun (ordered : (54 : Basis) < (30 : Basis)) => False.elim ((by decide +kernel : ¬ (54 : Basis) < (30 : Basis)) ordered))
    (Fin.cases (fun (ordered : (54 : Basis) < (31 : Basis)) => False.elim ((by decide +kernel : ¬ (54 : Basis) < (31 : Basis)) ordered))
    (Fin.cases (fun (ordered : (54 : Basis) < (32 : Basis)) => False.elim ((by decide +kernel : ¬ (54 : Basis) < (32 : Basis)) ordered))
    (Fin.cases (fun (ordered : (54 : Basis) < (33 : Basis)) => False.elim ((by decide +kernel : ¬ (54 : Basis) < (33 : Basis)) ordered))
    (Fin.cases (fun (ordered : (54 : Basis) < (34 : Basis)) => False.elim ((by decide +kernel : ¬ (54 : Basis) < (34 : Basis)) ordered))
    (Fin.cases (fun (ordered : (54 : Basis) < (35 : Basis)) => False.elim ((by decide +kernel : ¬ (54 : Basis) < (35 : Basis)) ordered))
    (Fin.cases (fun (ordered : (54 : Basis) < (36 : Basis)) => False.elim ((by decide +kernel : ¬ (54 : Basis) < (36 : Basis)) ordered))
    (Fin.cases (fun (ordered : (54 : Basis) < (37 : Basis)) => False.elim ((by decide +kernel : ¬ (54 : Basis) < (37 : Basis)) ordered))
    (Fin.cases (fun (ordered : (54 : Basis) < (38 : Basis)) => False.elim ((by decide +kernel : ¬ (54 : Basis) < (38 : Basis)) ordered))
    (Fin.cases (fun (ordered : (54 : Basis) < (39 : Basis)) => False.elim ((by decide +kernel : ¬ (54 : Basis) < (39 : Basis)) ordered))
    (Fin.cases (fun (ordered : (54 : Basis) < (40 : Basis)) => False.elim ((by decide +kernel : ¬ (54 : Basis) < (40 : Basis)) ordered))
    (Fin.cases (fun (ordered : (54 : Basis) < (41 : Basis)) => False.elim ((by decide +kernel : ¬ (54 : Basis) < (41 : Basis)) ordered))
    (Fin.cases (fun (ordered : (54 : Basis) < (42 : Basis)) => False.elim ((by decide +kernel : ¬ (54 : Basis) < (42 : Basis)) ordered))
    (Fin.cases (fun (ordered : (54 : Basis) < (43 : Basis)) => False.elim ((by decide +kernel : ¬ (54 : Basis) < (43 : Basis)) ordered))
    (Fin.cases (fun (ordered : (54 : Basis) < (44 : Basis)) => False.elim ((by decide +kernel : ¬ (54 : Basis) < (44 : Basis)) ordered))
    (Fin.cases (fun (ordered : (54 : Basis) < (45 : Basis)) => False.elim ((by decide +kernel : ¬ (54 : Basis) < (45 : Basis)) ordered))
    (Fin.cases (fun (ordered : (54 : Basis) < (46 : Basis)) => False.elim ((by decide +kernel : ¬ (54 : Basis) < (46 : Basis)) ordered))
    (Fin.cases (fun (ordered : (54 : Basis) < (47 : Basis)) => False.elim ((by decide +kernel : ¬ (54 : Basis) < (47 : Basis)) ordered))
    (Fin.cases (fun (ordered : (54 : Basis) < (48 : Basis)) => False.elim ((by decide +kernel : ¬ (54 : Basis) < (48 : Basis)) ordered))
    (Fin.cases (fun (ordered : (54 : Basis) < (49 : Basis)) => False.elim ((by decide +kernel : ¬ (54 : Basis) < (49 : Basis)) ordered))
    (Fin.cases (fun (ordered : (54 : Basis) < (50 : Basis)) => False.elim ((by decide +kernel : ¬ (54 : Basis) < (50 : Basis)) ordered))
    (Fin.cases (fun (ordered : (54 : Basis) < (51 : Basis)) => False.elim ((by decide +kernel : ¬ (54 : Basis) < (51 : Basis)) ordered))
    (Fin.cases (fun (ordered : (54 : Basis) < (52 : Basis)) => False.elim ((by decide +kernel : ¬ (54 : Basis) < (52 : Basis)) ordered))
    (Fin.cases (fun (ordered : (54 : Basis) < (53 : Basis)) => False.elim ((by decide +kernel : ¬ (54 : Basis) < (53 : Basis)) ordered))
    (Fin.cases (fun (ordered : (54 : Basis) < (54 : Basis)) => False.elim ((by decide +kernel : ¬ (54 : Basis) < (54 : Basis)) ordered))
    (Fin.cases (fun _ => ⟨⟨Factors.P237.factor14Plus,0,Factors.P237.checked14Plus⟩,⟨Factors.P237.factor14Minus,0,Factors.P237.checked14Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P237.factor15Plus,0,Factors.P237.checked15Plus⟩,⟨Factors.P237.factor15Minus,0,Factors.P237.checked15Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P238.factor0Plus,0,Factors.P238.checked0Plus⟩,⟨Factors.P238.factor0Minus,0,Factors.P238.checked0Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P238.factor1Plus,0,Factors.P238.checked1Plus⟩,⟨Factors.P238.factor1Minus,0,Factors.P238.checked1Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P238.factor2Plus,0,Factors.P238.checked2Plus⟩,⟨Factors.P238.factor2Minus,0,Factors.P238.checked2Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P238.factor3Plus,0,Factors.P238.checked3Plus⟩,⟨Factors.P238.factor3Minus,0,Factors.P238.checked3Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P238.factor4Plus,0,Factors.P238.checked4Plus⟩,⟨Factors.P238.factor4Minus,0,Factors.P238.checked4Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P238.factor5Plus,0,Factors.P238.checked5Plus⟩,⟨Factors.P238.factor5Minus,0,Factors.P238.checked5Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P238.factor6Plus,0,Factors.P238.checked6Plus⟩,⟨Factors.P238.factor6Minus,0,Factors.P238.checked6Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P238.factor7Plus,0,Factors.P238.checked7Plus⟩,⟨Factors.P238.factor7Minus,0,Factors.P238.checked7Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P238.factor8Plus,0,Factors.P238.checked8Plus⟩,⟨Factors.P238.factor8Minus,0,Factors.P238.checked8Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P238.factor9Plus,0,Factors.P238.checked9Plus⟩,⟨Factors.P238.factor9Minus,0,Factors.P238.checked9Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P238.factor10Plus,0,Factors.P238.checked10Plus⟩,⟨Factors.P238.factor10Minus,0,Factors.P238.checked10Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P238.factor11Plus,0,Factors.P238.checked11Plus⟩,⟨Factors.P238.factor11Minus,0,Factors.P238.checked11Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P238.factor12Plus,0,Factors.P238.checked12Plus⟩,⟨Factors.P238.factor12Minus,0,Factors.P238.checked12Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P238.factor13Plus,0,Factors.P238.checked13Plus⟩,⟨Factors.P238.factor13Minus,0,Factors.P238.checked13Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P238.factor14Plus,0,Factors.P238.checked14Plus⟩,⟨Factors.P238.factor14Minus,0,Factors.P238.checked14Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P238.factor15Plus,0,Factors.P238.checked15Plus⟩,⟨Factors.P238.factor15Minus,0,Factors.P238.checked15Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P239.factor0Plus,0,Factors.P239.checked0Plus⟩,⟨Factors.P239.factor0Minus,0,Factors.P239.checked0Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P239.factor1Plus,0,Factors.P239.checked1Plus⟩,⟨Factors.P239.factor1Minus,0,Factors.P239.checked1Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P239.factor2Plus,0,Factors.P239.checked2Plus⟩,⟨Factors.P239.factor2Minus,0,Factors.P239.checked2Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P239.factor3Plus,0,Factors.P239.checked3Plus⟩,⟨Factors.P239.factor3Minus,0,Factors.P239.checked3Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P239.factor4Plus,0,Factors.P239.checked4Plus⟩,⟨Factors.P239.factor4Minus,0,Factors.P239.checked4Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P239.factor5Plus,0,Factors.P239.checked5Plus⟩,⟨Factors.P239.factor5Minus,0,Factors.P239.checked5Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P239.factor6Plus,0,Factors.P239.checked6Plus⟩,⟨Factors.P239.factor6Minus,0,Factors.P239.checked6Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P239.factor7Plus,0,Factors.P239.checked7Plus⟩,⟨Factors.P239.factor7Minus,0,Factors.P239.checked7Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P239.factor8Plus,0,Factors.P239.checked8Plus⟩,⟨Factors.P239.factor8Minus,0,Factors.P239.checked8Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P239.factor9Plus,0,Factors.P239.checked9Plus⟩,⟨Factors.P239.factor9Minus,0,Factors.P239.checked9Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P239.factor10Plus,0,Factors.P239.checked10Plus⟩,⟨Factors.P239.factor10Minus,0,Factors.P239.checked10Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P239.factor11Plus,0,Factors.P239.checked11Plus⟩,⟨Factors.P239.factor11Minus,0,Factors.P239.checked11Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P239.factor12Plus,0,Factors.P239.checked12Plus⟩,⟨Factors.P239.factor12Minus,0,Factors.P239.checked12Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P239.factor13Plus,0,Factors.P239.checked13Plus⟩,⟨Factors.P239.factor13Minus,0,Factors.P239.checked13Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P239.factor14Plus,0,Factors.P239.checked14Plus⟩,⟨Factors.P239.factor14Minus,0,Factors.P239.checked14Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P239.factor15Plus,0,Factors.P239.checked15Plus⟩,⟨Factors.P239.factor15Minus,0,Factors.P239.checked15Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P240.factor0Plus,0,Factors.P240.checked0Plus⟩,⟨Factors.P240.factor0Minus,0,Factors.P240.checked0Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P240.factor1Plus,0,Factors.P240.checked1Plus⟩,⟨Factors.P240.factor1Minus,0,Factors.P240.checked1Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P240.factor2Plus,0,Factors.P240.checked2Plus⟩,⟨Factors.P240.factor2Minus,0,Factors.P240.checked2Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P240.factor3Plus,0,Factors.P240.checked3Plus⟩,⟨Factors.P240.factor3Minus,0,Factors.P240.checked3Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P240.factor4Plus,0,Factors.P240.checked4Plus⟩,⟨Factors.P240.factor4Minus,0,Factors.P240.checked4Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P240.factor5Plus,0,Factors.P240.checked5Plus⟩,⟨Factors.P240.factor5Minus,0,Factors.P240.checked5Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P240.factor6Plus,0,Factors.P240.checked6Plus⟩,⟨Factors.P240.factor6Minus,0,Factors.P240.checked6Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P240.factor7Plus,0,Factors.P240.checked7Plus⟩,⟨Factors.P240.factor7Minus,0,Factors.P240.checked7Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P240.factor8Plus,0,Factors.P240.checked8Plus⟩,⟨Factors.P240.factor8Minus,0,Factors.P240.checked8Minus⟩⟩)
    ((fun impossible => Fin.elim0 impossible)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))

end
end LAlanine40K2025.Thermal.Recovery.Reservoir.Pointer.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Rows
end SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule
