import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.OrdinaryPair
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P245
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P246
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P247
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P248

set_option autoImplicit false
namespace SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule
namespace LAlanine40K2025.Thermal.Recovery.Reservoir.Pointer.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Rows
open Propagation.Interface
noncomputable section

set_option maxHeartbeats 400000 in
def row57 : (b : Basis) → (57 : Basis) < b → OrdinaryPair 57 b :=
  Fin.cases (fun (ordered : (57 : Basis) < (0 : Basis)) => False.elim ((by decide +kernel : ¬ (57 : Basis) < (0 : Basis)) ordered))
    (Fin.cases (fun (ordered : (57 : Basis) < (1 : Basis)) => False.elim ((by decide +kernel : ¬ (57 : Basis) < (1 : Basis)) ordered))
    (Fin.cases (fun (ordered : (57 : Basis) < (2 : Basis)) => False.elim ((by decide +kernel : ¬ (57 : Basis) < (2 : Basis)) ordered))
    (Fin.cases (fun (ordered : (57 : Basis) < (3 : Basis)) => False.elim ((by decide +kernel : ¬ (57 : Basis) < (3 : Basis)) ordered))
    (Fin.cases (fun (ordered : (57 : Basis) < (4 : Basis)) => False.elim ((by decide +kernel : ¬ (57 : Basis) < (4 : Basis)) ordered))
    (Fin.cases (fun (ordered : (57 : Basis) < (5 : Basis)) => False.elim ((by decide +kernel : ¬ (57 : Basis) < (5 : Basis)) ordered))
    (Fin.cases (fun (ordered : (57 : Basis) < (6 : Basis)) => False.elim ((by decide +kernel : ¬ (57 : Basis) < (6 : Basis)) ordered))
    (Fin.cases (fun (ordered : (57 : Basis) < (7 : Basis)) => False.elim ((by decide +kernel : ¬ (57 : Basis) < (7 : Basis)) ordered))
    (Fin.cases (fun (ordered : (57 : Basis) < (8 : Basis)) => False.elim ((by decide +kernel : ¬ (57 : Basis) < (8 : Basis)) ordered))
    (Fin.cases (fun (ordered : (57 : Basis) < (9 : Basis)) => False.elim ((by decide +kernel : ¬ (57 : Basis) < (9 : Basis)) ordered))
    (Fin.cases (fun (ordered : (57 : Basis) < (10 : Basis)) => False.elim ((by decide +kernel : ¬ (57 : Basis) < (10 : Basis)) ordered))
    (Fin.cases (fun (ordered : (57 : Basis) < (11 : Basis)) => False.elim ((by decide +kernel : ¬ (57 : Basis) < (11 : Basis)) ordered))
    (Fin.cases (fun (ordered : (57 : Basis) < (12 : Basis)) => False.elim ((by decide +kernel : ¬ (57 : Basis) < (12 : Basis)) ordered))
    (Fin.cases (fun (ordered : (57 : Basis) < (13 : Basis)) => False.elim ((by decide +kernel : ¬ (57 : Basis) < (13 : Basis)) ordered))
    (Fin.cases (fun (ordered : (57 : Basis) < (14 : Basis)) => False.elim ((by decide +kernel : ¬ (57 : Basis) < (14 : Basis)) ordered))
    (Fin.cases (fun (ordered : (57 : Basis) < (15 : Basis)) => False.elim ((by decide +kernel : ¬ (57 : Basis) < (15 : Basis)) ordered))
    (Fin.cases (fun (ordered : (57 : Basis) < (16 : Basis)) => False.elim ((by decide +kernel : ¬ (57 : Basis) < (16 : Basis)) ordered))
    (Fin.cases (fun (ordered : (57 : Basis) < (17 : Basis)) => False.elim ((by decide +kernel : ¬ (57 : Basis) < (17 : Basis)) ordered))
    (Fin.cases (fun (ordered : (57 : Basis) < (18 : Basis)) => False.elim ((by decide +kernel : ¬ (57 : Basis) < (18 : Basis)) ordered))
    (Fin.cases (fun (ordered : (57 : Basis) < (19 : Basis)) => False.elim ((by decide +kernel : ¬ (57 : Basis) < (19 : Basis)) ordered))
    (Fin.cases (fun (ordered : (57 : Basis) < (20 : Basis)) => False.elim ((by decide +kernel : ¬ (57 : Basis) < (20 : Basis)) ordered))
    (Fin.cases (fun (ordered : (57 : Basis) < (21 : Basis)) => False.elim ((by decide +kernel : ¬ (57 : Basis) < (21 : Basis)) ordered))
    (Fin.cases (fun (ordered : (57 : Basis) < (22 : Basis)) => False.elim ((by decide +kernel : ¬ (57 : Basis) < (22 : Basis)) ordered))
    (Fin.cases (fun (ordered : (57 : Basis) < (23 : Basis)) => False.elim ((by decide +kernel : ¬ (57 : Basis) < (23 : Basis)) ordered))
    (Fin.cases (fun (ordered : (57 : Basis) < (24 : Basis)) => False.elim ((by decide +kernel : ¬ (57 : Basis) < (24 : Basis)) ordered))
    (Fin.cases (fun (ordered : (57 : Basis) < (25 : Basis)) => False.elim ((by decide +kernel : ¬ (57 : Basis) < (25 : Basis)) ordered))
    (Fin.cases (fun (ordered : (57 : Basis) < (26 : Basis)) => False.elim ((by decide +kernel : ¬ (57 : Basis) < (26 : Basis)) ordered))
    (Fin.cases (fun (ordered : (57 : Basis) < (27 : Basis)) => False.elim ((by decide +kernel : ¬ (57 : Basis) < (27 : Basis)) ordered))
    (Fin.cases (fun (ordered : (57 : Basis) < (28 : Basis)) => False.elim ((by decide +kernel : ¬ (57 : Basis) < (28 : Basis)) ordered))
    (Fin.cases (fun (ordered : (57 : Basis) < (29 : Basis)) => False.elim ((by decide +kernel : ¬ (57 : Basis) < (29 : Basis)) ordered))
    (Fin.cases (fun (ordered : (57 : Basis) < (30 : Basis)) => False.elim ((by decide +kernel : ¬ (57 : Basis) < (30 : Basis)) ordered))
    (Fin.cases (fun (ordered : (57 : Basis) < (31 : Basis)) => False.elim ((by decide +kernel : ¬ (57 : Basis) < (31 : Basis)) ordered))
    (Fin.cases (fun (ordered : (57 : Basis) < (32 : Basis)) => False.elim ((by decide +kernel : ¬ (57 : Basis) < (32 : Basis)) ordered))
    (Fin.cases (fun (ordered : (57 : Basis) < (33 : Basis)) => False.elim ((by decide +kernel : ¬ (57 : Basis) < (33 : Basis)) ordered))
    (Fin.cases (fun (ordered : (57 : Basis) < (34 : Basis)) => False.elim ((by decide +kernel : ¬ (57 : Basis) < (34 : Basis)) ordered))
    (Fin.cases (fun (ordered : (57 : Basis) < (35 : Basis)) => False.elim ((by decide +kernel : ¬ (57 : Basis) < (35 : Basis)) ordered))
    (Fin.cases (fun (ordered : (57 : Basis) < (36 : Basis)) => False.elim ((by decide +kernel : ¬ (57 : Basis) < (36 : Basis)) ordered))
    (Fin.cases (fun (ordered : (57 : Basis) < (37 : Basis)) => False.elim ((by decide +kernel : ¬ (57 : Basis) < (37 : Basis)) ordered))
    (Fin.cases (fun (ordered : (57 : Basis) < (38 : Basis)) => False.elim ((by decide +kernel : ¬ (57 : Basis) < (38 : Basis)) ordered))
    (Fin.cases (fun (ordered : (57 : Basis) < (39 : Basis)) => False.elim ((by decide +kernel : ¬ (57 : Basis) < (39 : Basis)) ordered))
    (Fin.cases (fun (ordered : (57 : Basis) < (40 : Basis)) => False.elim ((by decide +kernel : ¬ (57 : Basis) < (40 : Basis)) ordered))
    (Fin.cases (fun (ordered : (57 : Basis) < (41 : Basis)) => False.elim ((by decide +kernel : ¬ (57 : Basis) < (41 : Basis)) ordered))
    (Fin.cases (fun (ordered : (57 : Basis) < (42 : Basis)) => False.elim ((by decide +kernel : ¬ (57 : Basis) < (42 : Basis)) ordered))
    (Fin.cases (fun (ordered : (57 : Basis) < (43 : Basis)) => False.elim ((by decide +kernel : ¬ (57 : Basis) < (43 : Basis)) ordered))
    (Fin.cases (fun (ordered : (57 : Basis) < (44 : Basis)) => False.elim ((by decide +kernel : ¬ (57 : Basis) < (44 : Basis)) ordered))
    (Fin.cases (fun (ordered : (57 : Basis) < (45 : Basis)) => False.elim ((by decide +kernel : ¬ (57 : Basis) < (45 : Basis)) ordered))
    (Fin.cases (fun (ordered : (57 : Basis) < (46 : Basis)) => False.elim ((by decide +kernel : ¬ (57 : Basis) < (46 : Basis)) ordered))
    (Fin.cases (fun (ordered : (57 : Basis) < (47 : Basis)) => False.elim ((by decide +kernel : ¬ (57 : Basis) < (47 : Basis)) ordered))
    (Fin.cases (fun (ordered : (57 : Basis) < (48 : Basis)) => False.elim ((by decide +kernel : ¬ (57 : Basis) < (48 : Basis)) ordered))
    (Fin.cases (fun (ordered : (57 : Basis) < (49 : Basis)) => False.elim ((by decide +kernel : ¬ (57 : Basis) < (49 : Basis)) ordered))
    (Fin.cases (fun (ordered : (57 : Basis) < (50 : Basis)) => False.elim ((by decide +kernel : ¬ (57 : Basis) < (50 : Basis)) ordered))
    (Fin.cases (fun (ordered : (57 : Basis) < (51 : Basis)) => False.elim ((by decide +kernel : ¬ (57 : Basis) < (51 : Basis)) ordered))
    (Fin.cases (fun (ordered : (57 : Basis) < (52 : Basis)) => False.elim ((by decide +kernel : ¬ (57 : Basis) < (52 : Basis)) ordered))
    (Fin.cases (fun (ordered : (57 : Basis) < (53 : Basis)) => False.elim ((by decide +kernel : ¬ (57 : Basis) < (53 : Basis)) ordered))
    (Fin.cases (fun (ordered : (57 : Basis) < (54 : Basis)) => False.elim ((by decide +kernel : ¬ (57 : Basis) < (54 : Basis)) ordered))
    (Fin.cases (fun (ordered : (57 : Basis) < (55 : Basis)) => False.elim ((by decide +kernel : ¬ (57 : Basis) < (55 : Basis)) ordered))
    (Fin.cases (fun (ordered : (57 : Basis) < (56 : Basis)) => False.elim ((by decide +kernel : ¬ (57 : Basis) < (56 : Basis)) ordered))
    (Fin.cases (fun (ordered : (57 : Basis) < (57 : Basis)) => False.elim ((by decide +kernel : ¬ (57 : Basis) < (57 : Basis)) ordered))
    (Fin.cases (fun _ => ⟨⟨Factors.P245.factor12Plus,0,Factors.P245.checked12Plus⟩,⟨Factors.P245.factor12Minus,0,Factors.P245.checked12Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P245.factor13Plus,0,Factors.P245.checked13Plus⟩,⟨Factors.P245.factor13Minus,0,Factors.P245.checked13Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P245.factor14Plus,0,Factors.P245.checked14Plus⟩,⟨Factors.P245.factor14Minus,0,Factors.P245.checked14Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P245.factor15Plus,0,Factors.P245.checked15Plus⟩,⟨Factors.P245.factor15Minus,0,Factors.P245.checked15Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P246.factor0Plus,0,Factors.P246.checked0Plus⟩,⟨Factors.P246.factor0Minus,0,Factors.P246.checked0Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P246.factor1Plus,0,Factors.P246.checked1Plus⟩,⟨Factors.P246.factor1Minus,0,Factors.P246.checked1Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P246.factor2Plus,0,Factors.P246.checked2Plus⟩,⟨Factors.P246.factor2Minus,0,Factors.P246.checked2Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P246.factor3Plus,0,Factors.P246.checked3Plus⟩,⟨Factors.P246.factor3Minus,0,Factors.P246.checked3Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P246.factor4Plus,0,Factors.P246.checked4Plus⟩,⟨Factors.P246.factor4Minus,0,Factors.P246.checked4Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P246.factor5Plus,0,Factors.P246.checked5Plus⟩,⟨Factors.P246.factor5Minus,0,Factors.P246.checked5Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P246.factor6Plus,0,Factors.P246.checked6Plus⟩,⟨Factors.P246.factor6Minus,0,Factors.P246.checked6Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P246.factor7Plus,0,Factors.P246.checked7Plus⟩,⟨Factors.P246.factor7Minus,0,Factors.P246.checked7Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P246.factor8Plus,0,Factors.P246.checked8Plus⟩,⟨Factors.P246.factor8Minus,0,Factors.P246.checked8Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P246.factor9Plus,0,Factors.P246.checked9Plus⟩,⟨Factors.P246.factor9Minus,0,Factors.P246.checked9Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P246.factor10Plus,0,Factors.P246.checked10Plus⟩,⟨Factors.P246.factor10Minus,0,Factors.P246.checked10Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P246.factor11Plus,0,Factors.P246.checked11Plus⟩,⟨Factors.P246.factor11Minus,0,Factors.P246.checked11Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P246.factor12Plus,0,Factors.P246.checked12Plus⟩,⟨Factors.P246.factor12Minus,0,Factors.P246.checked12Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P246.factor13Plus,0,Factors.P246.checked13Plus⟩,⟨Factors.P246.factor13Minus,0,Factors.P246.checked13Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P246.factor14Plus,0,Factors.P246.checked14Plus⟩,⟨Factors.P246.factor14Minus,0,Factors.P246.checked14Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P246.factor15Plus,0,Factors.P246.checked15Plus⟩,⟨Factors.P246.factor15Minus,0,Factors.P246.checked15Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P247.factor0Plus,0,Factors.P247.checked0Plus⟩,⟨Factors.P247.factor0Minus,0,Factors.P247.checked0Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P247.factor1Plus,0,Factors.P247.checked1Plus⟩,⟨Factors.P247.factor1Minus,0,Factors.P247.checked1Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P247.factor2Plus,0,Factors.P247.checked2Plus⟩,⟨Factors.P247.factor2Minus,0,Factors.P247.checked2Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P247.factor3Plus,0,Factors.P247.checked3Plus⟩,⟨Factors.P247.factor3Minus,0,Factors.P247.checked3Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P247.factor4Plus,0,Factors.P247.checked4Plus⟩,⟨Factors.P247.factor4Minus,0,Factors.P247.checked4Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P247.factor5Plus,0,Factors.P247.checked5Plus⟩,⟨Factors.P247.factor5Minus,0,Factors.P247.checked5Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P247.factor6Plus,0,Factors.P247.checked6Plus⟩,⟨Factors.P247.factor6Minus,0,Factors.P247.checked6Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P247.factor7Plus,0,Factors.P247.checked7Plus⟩,⟨Factors.P247.factor7Minus,0,Factors.P247.checked7Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P247.factor8Plus,0,Factors.P247.checked8Plus⟩,⟨Factors.P247.factor8Minus,0,Factors.P247.checked8Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P247.factor9Plus,0,Factors.P247.checked9Plus⟩,⟨Factors.P247.factor9Minus,0,Factors.P247.checked9Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P247.factor10Plus,0,Factors.P247.checked10Plus⟩,⟨Factors.P247.factor10Minus,0,Factors.P247.checked10Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P247.factor11Plus,0,Factors.P247.checked11Plus⟩,⟨Factors.P247.factor11Minus,0,Factors.P247.checked11Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P247.factor12Plus,0,Factors.P247.checked12Plus⟩,⟨Factors.P247.factor12Minus,0,Factors.P247.checked12Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P247.factor13Plus,0,Factors.P247.checked13Plus⟩,⟨Factors.P247.factor13Minus,0,Factors.P247.checked13Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P247.factor14Plus,0,Factors.P247.checked14Plus⟩,⟨Factors.P247.factor14Minus,0,Factors.P247.checked14Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P247.factor15Plus,0,Factors.P247.checked15Plus⟩,⟨Factors.P247.factor15Minus,0,Factors.P247.checked15Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P248.factor0Plus,0,Factors.P248.checked0Plus⟩,⟨Factors.P248.factor0Minus,0,Factors.P248.checked0Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P248.factor1Plus,0,Factors.P248.checked1Plus⟩,⟨Factors.P248.factor1Minus,0,Factors.P248.checked1Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P248.factor2Plus,0,Factors.P248.checked2Plus⟩,⟨Factors.P248.factor2Minus,0,Factors.P248.checked2Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P248.factor3Plus,0,Factors.P248.checked3Plus⟩,⟨Factors.P248.factor3Minus,0,Factors.P248.checked3Minus⟩⟩)
    ((fun impossible => Fin.elim0 impossible)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))

end
end LAlanine40K2025.Thermal.Recovery.Reservoir.Pointer.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Rows
end SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule
