import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.OrdinaryPair
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P250
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P251
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P252
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P253

set_option autoImplicit false
namespace SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule
namespace LAlanine40K2025.Thermal.Recovery.Reservoir.Pointer.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Rows
open Propagation.Interface
noncomputable section

set_option maxHeartbeats 400000 in
def row59 : (b : Basis) → (59 : Basis) < b → OrdinaryPair 59 b :=
  Fin.cases (fun (ordered : (59 : Basis) < (0 : Basis)) => False.elim ((by decide +kernel : ¬ (59 : Basis) < (0 : Basis)) ordered))
    (Fin.cases (fun (ordered : (59 : Basis) < (1 : Basis)) => False.elim ((by decide +kernel : ¬ (59 : Basis) < (1 : Basis)) ordered))
    (Fin.cases (fun (ordered : (59 : Basis) < (2 : Basis)) => False.elim ((by decide +kernel : ¬ (59 : Basis) < (2 : Basis)) ordered))
    (Fin.cases (fun (ordered : (59 : Basis) < (3 : Basis)) => False.elim ((by decide +kernel : ¬ (59 : Basis) < (3 : Basis)) ordered))
    (Fin.cases (fun (ordered : (59 : Basis) < (4 : Basis)) => False.elim ((by decide +kernel : ¬ (59 : Basis) < (4 : Basis)) ordered))
    (Fin.cases (fun (ordered : (59 : Basis) < (5 : Basis)) => False.elim ((by decide +kernel : ¬ (59 : Basis) < (5 : Basis)) ordered))
    (Fin.cases (fun (ordered : (59 : Basis) < (6 : Basis)) => False.elim ((by decide +kernel : ¬ (59 : Basis) < (6 : Basis)) ordered))
    (Fin.cases (fun (ordered : (59 : Basis) < (7 : Basis)) => False.elim ((by decide +kernel : ¬ (59 : Basis) < (7 : Basis)) ordered))
    (Fin.cases (fun (ordered : (59 : Basis) < (8 : Basis)) => False.elim ((by decide +kernel : ¬ (59 : Basis) < (8 : Basis)) ordered))
    (Fin.cases (fun (ordered : (59 : Basis) < (9 : Basis)) => False.elim ((by decide +kernel : ¬ (59 : Basis) < (9 : Basis)) ordered))
    (Fin.cases (fun (ordered : (59 : Basis) < (10 : Basis)) => False.elim ((by decide +kernel : ¬ (59 : Basis) < (10 : Basis)) ordered))
    (Fin.cases (fun (ordered : (59 : Basis) < (11 : Basis)) => False.elim ((by decide +kernel : ¬ (59 : Basis) < (11 : Basis)) ordered))
    (Fin.cases (fun (ordered : (59 : Basis) < (12 : Basis)) => False.elim ((by decide +kernel : ¬ (59 : Basis) < (12 : Basis)) ordered))
    (Fin.cases (fun (ordered : (59 : Basis) < (13 : Basis)) => False.elim ((by decide +kernel : ¬ (59 : Basis) < (13 : Basis)) ordered))
    (Fin.cases (fun (ordered : (59 : Basis) < (14 : Basis)) => False.elim ((by decide +kernel : ¬ (59 : Basis) < (14 : Basis)) ordered))
    (Fin.cases (fun (ordered : (59 : Basis) < (15 : Basis)) => False.elim ((by decide +kernel : ¬ (59 : Basis) < (15 : Basis)) ordered))
    (Fin.cases (fun (ordered : (59 : Basis) < (16 : Basis)) => False.elim ((by decide +kernel : ¬ (59 : Basis) < (16 : Basis)) ordered))
    (Fin.cases (fun (ordered : (59 : Basis) < (17 : Basis)) => False.elim ((by decide +kernel : ¬ (59 : Basis) < (17 : Basis)) ordered))
    (Fin.cases (fun (ordered : (59 : Basis) < (18 : Basis)) => False.elim ((by decide +kernel : ¬ (59 : Basis) < (18 : Basis)) ordered))
    (Fin.cases (fun (ordered : (59 : Basis) < (19 : Basis)) => False.elim ((by decide +kernel : ¬ (59 : Basis) < (19 : Basis)) ordered))
    (Fin.cases (fun (ordered : (59 : Basis) < (20 : Basis)) => False.elim ((by decide +kernel : ¬ (59 : Basis) < (20 : Basis)) ordered))
    (Fin.cases (fun (ordered : (59 : Basis) < (21 : Basis)) => False.elim ((by decide +kernel : ¬ (59 : Basis) < (21 : Basis)) ordered))
    (Fin.cases (fun (ordered : (59 : Basis) < (22 : Basis)) => False.elim ((by decide +kernel : ¬ (59 : Basis) < (22 : Basis)) ordered))
    (Fin.cases (fun (ordered : (59 : Basis) < (23 : Basis)) => False.elim ((by decide +kernel : ¬ (59 : Basis) < (23 : Basis)) ordered))
    (Fin.cases (fun (ordered : (59 : Basis) < (24 : Basis)) => False.elim ((by decide +kernel : ¬ (59 : Basis) < (24 : Basis)) ordered))
    (Fin.cases (fun (ordered : (59 : Basis) < (25 : Basis)) => False.elim ((by decide +kernel : ¬ (59 : Basis) < (25 : Basis)) ordered))
    (Fin.cases (fun (ordered : (59 : Basis) < (26 : Basis)) => False.elim ((by decide +kernel : ¬ (59 : Basis) < (26 : Basis)) ordered))
    (Fin.cases (fun (ordered : (59 : Basis) < (27 : Basis)) => False.elim ((by decide +kernel : ¬ (59 : Basis) < (27 : Basis)) ordered))
    (Fin.cases (fun (ordered : (59 : Basis) < (28 : Basis)) => False.elim ((by decide +kernel : ¬ (59 : Basis) < (28 : Basis)) ordered))
    (Fin.cases (fun (ordered : (59 : Basis) < (29 : Basis)) => False.elim ((by decide +kernel : ¬ (59 : Basis) < (29 : Basis)) ordered))
    (Fin.cases (fun (ordered : (59 : Basis) < (30 : Basis)) => False.elim ((by decide +kernel : ¬ (59 : Basis) < (30 : Basis)) ordered))
    (Fin.cases (fun (ordered : (59 : Basis) < (31 : Basis)) => False.elim ((by decide +kernel : ¬ (59 : Basis) < (31 : Basis)) ordered))
    (Fin.cases (fun (ordered : (59 : Basis) < (32 : Basis)) => False.elim ((by decide +kernel : ¬ (59 : Basis) < (32 : Basis)) ordered))
    (Fin.cases (fun (ordered : (59 : Basis) < (33 : Basis)) => False.elim ((by decide +kernel : ¬ (59 : Basis) < (33 : Basis)) ordered))
    (Fin.cases (fun (ordered : (59 : Basis) < (34 : Basis)) => False.elim ((by decide +kernel : ¬ (59 : Basis) < (34 : Basis)) ordered))
    (Fin.cases (fun (ordered : (59 : Basis) < (35 : Basis)) => False.elim ((by decide +kernel : ¬ (59 : Basis) < (35 : Basis)) ordered))
    (Fin.cases (fun (ordered : (59 : Basis) < (36 : Basis)) => False.elim ((by decide +kernel : ¬ (59 : Basis) < (36 : Basis)) ordered))
    (Fin.cases (fun (ordered : (59 : Basis) < (37 : Basis)) => False.elim ((by decide +kernel : ¬ (59 : Basis) < (37 : Basis)) ordered))
    (Fin.cases (fun (ordered : (59 : Basis) < (38 : Basis)) => False.elim ((by decide +kernel : ¬ (59 : Basis) < (38 : Basis)) ordered))
    (Fin.cases (fun (ordered : (59 : Basis) < (39 : Basis)) => False.elim ((by decide +kernel : ¬ (59 : Basis) < (39 : Basis)) ordered))
    (Fin.cases (fun (ordered : (59 : Basis) < (40 : Basis)) => False.elim ((by decide +kernel : ¬ (59 : Basis) < (40 : Basis)) ordered))
    (Fin.cases (fun (ordered : (59 : Basis) < (41 : Basis)) => False.elim ((by decide +kernel : ¬ (59 : Basis) < (41 : Basis)) ordered))
    (Fin.cases (fun (ordered : (59 : Basis) < (42 : Basis)) => False.elim ((by decide +kernel : ¬ (59 : Basis) < (42 : Basis)) ordered))
    (Fin.cases (fun (ordered : (59 : Basis) < (43 : Basis)) => False.elim ((by decide +kernel : ¬ (59 : Basis) < (43 : Basis)) ordered))
    (Fin.cases (fun (ordered : (59 : Basis) < (44 : Basis)) => False.elim ((by decide +kernel : ¬ (59 : Basis) < (44 : Basis)) ordered))
    (Fin.cases (fun (ordered : (59 : Basis) < (45 : Basis)) => False.elim ((by decide +kernel : ¬ (59 : Basis) < (45 : Basis)) ordered))
    (Fin.cases (fun (ordered : (59 : Basis) < (46 : Basis)) => False.elim ((by decide +kernel : ¬ (59 : Basis) < (46 : Basis)) ordered))
    (Fin.cases (fun (ordered : (59 : Basis) < (47 : Basis)) => False.elim ((by decide +kernel : ¬ (59 : Basis) < (47 : Basis)) ordered))
    (Fin.cases (fun (ordered : (59 : Basis) < (48 : Basis)) => False.elim ((by decide +kernel : ¬ (59 : Basis) < (48 : Basis)) ordered))
    (Fin.cases (fun (ordered : (59 : Basis) < (49 : Basis)) => False.elim ((by decide +kernel : ¬ (59 : Basis) < (49 : Basis)) ordered))
    (Fin.cases (fun (ordered : (59 : Basis) < (50 : Basis)) => False.elim ((by decide +kernel : ¬ (59 : Basis) < (50 : Basis)) ordered))
    (Fin.cases (fun (ordered : (59 : Basis) < (51 : Basis)) => False.elim ((by decide +kernel : ¬ (59 : Basis) < (51 : Basis)) ordered))
    (Fin.cases (fun (ordered : (59 : Basis) < (52 : Basis)) => False.elim ((by decide +kernel : ¬ (59 : Basis) < (52 : Basis)) ordered))
    (Fin.cases (fun (ordered : (59 : Basis) < (53 : Basis)) => False.elim ((by decide +kernel : ¬ (59 : Basis) < (53 : Basis)) ordered))
    (Fin.cases (fun (ordered : (59 : Basis) < (54 : Basis)) => False.elim ((by decide +kernel : ¬ (59 : Basis) < (54 : Basis)) ordered))
    (Fin.cases (fun (ordered : (59 : Basis) < (55 : Basis)) => False.elim ((by decide +kernel : ¬ (59 : Basis) < (55 : Basis)) ordered))
    (Fin.cases (fun (ordered : (59 : Basis) < (56 : Basis)) => False.elim ((by decide +kernel : ¬ (59 : Basis) < (56 : Basis)) ordered))
    (Fin.cases (fun (ordered : (59 : Basis) < (57 : Basis)) => False.elim ((by decide +kernel : ¬ (59 : Basis) < (57 : Basis)) ordered))
    (Fin.cases (fun (ordered : (59 : Basis) < (58 : Basis)) => False.elim ((by decide +kernel : ¬ (59 : Basis) < (58 : Basis)) ordered))
    (Fin.cases (fun (ordered : (59 : Basis) < (59 : Basis)) => False.elim ((by decide +kernel : ¬ (59 : Basis) < (59 : Basis)) ordered))
    (Fin.cases (fun _ => ⟨⟨Factors.P250.factor11Plus,0,Factors.P250.checked11Plus⟩,⟨Factors.P250.factor11Minus,0,Factors.P250.checked11Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P250.factor12Plus,0,Factors.P250.checked12Plus⟩,⟨Factors.P250.factor12Minus,0,Factors.P250.checked12Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P250.factor13Plus,0,Factors.P250.checked13Plus⟩,⟨Factors.P250.factor13Minus,0,Factors.P250.checked13Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P250.factor14Plus,0,Factors.P250.checked14Plus⟩,⟨Factors.P250.factor14Minus,0,Factors.P250.checked14Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P250.factor15Plus,0,Factors.P250.checked15Plus⟩,⟨Factors.P250.factor15Minus,0,Factors.P250.checked15Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P251.factor0Plus,0,Factors.P251.checked0Plus⟩,⟨Factors.P251.factor0Minus,0,Factors.P251.checked0Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P251.factor1Plus,0,Factors.P251.checked1Plus⟩,⟨Factors.P251.factor1Minus,0,Factors.P251.checked1Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P251.factor2Plus,0,Factors.P251.checked2Plus⟩,⟨Factors.P251.factor2Minus,0,Factors.P251.checked2Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P251.factor3Plus,0,Factors.P251.checked3Plus⟩,⟨Factors.P251.factor3Minus,0,Factors.P251.checked3Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P251.factor4Plus,0,Factors.P251.checked4Plus⟩,⟨Factors.P251.factor4Minus,0,Factors.P251.checked4Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P251.factor5Plus,0,Factors.P251.checked5Plus⟩,⟨Factors.P251.factor5Minus,0,Factors.P251.checked5Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P251.factor6Plus,0,Factors.P251.checked6Plus⟩,⟨Factors.P251.factor6Minus,0,Factors.P251.checked6Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P251.factor7Plus,0,Factors.P251.checked7Plus⟩,⟨Factors.P251.factor7Minus,0,Factors.P251.checked7Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P251.factor8Plus,0,Factors.P251.checked8Plus⟩,⟨Factors.P251.factor8Minus,0,Factors.P251.checked8Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P251.factor9Plus,0,Factors.P251.checked9Plus⟩,⟨Factors.P251.factor9Minus,0,Factors.P251.checked9Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P251.factor10Plus,0,Factors.P251.checked10Plus⟩,⟨Factors.P251.factor10Minus,0,Factors.P251.checked10Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P251.factor11Plus,0,Factors.P251.checked11Plus⟩,⟨Factors.P251.factor11Minus,0,Factors.P251.checked11Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P251.factor12Plus,0,Factors.P251.checked12Plus⟩,⟨Factors.P251.factor12Minus,0,Factors.P251.checked12Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P251.factor13Plus,0,Factors.P251.checked13Plus⟩,⟨Factors.P251.factor13Minus,0,Factors.P251.checked13Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P251.factor14Plus,0,Factors.P251.checked14Plus⟩,⟨Factors.P251.factor14Minus,0,Factors.P251.checked14Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P251.factor15Plus,0,Factors.P251.checked15Plus⟩,⟨Factors.P251.factor15Minus,0,Factors.P251.checked15Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P252.factor0Plus,0,Factors.P252.checked0Plus⟩,⟨Factors.P252.factor0Minus,0,Factors.P252.checked0Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P252.factor1Plus,0,Factors.P252.checked1Plus⟩,⟨Factors.P252.factor1Minus,0,Factors.P252.checked1Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P252.factor2Plus,0,Factors.P252.checked2Plus⟩,⟨Factors.P252.factor2Minus,0,Factors.P252.checked2Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P252.factor3Plus,0,Factors.P252.checked3Plus⟩,⟨Factors.P252.factor3Minus,0,Factors.P252.checked3Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P252.factor4Plus,0,Factors.P252.checked4Plus⟩,⟨Factors.P252.factor4Minus,0,Factors.P252.checked4Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P252.factor5Plus,0,Factors.P252.checked5Plus⟩,⟨Factors.P252.factor5Minus,0,Factors.P252.checked5Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P252.factor6Plus,0,Factors.P252.checked6Plus⟩,⟨Factors.P252.factor6Minus,0,Factors.P252.checked6Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P252.factor7Plus,0,Factors.P252.checked7Plus⟩,⟨Factors.P252.factor7Minus,0,Factors.P252.checked7Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P252.factor8Plus,0,Factors.P252.checked8Plus⟩,⟨Factors.P252.factor8Minus,0,Factors.P252.checked8Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P252.factor9Plus,0,Factors.P252.checked9Plus⟩,⟨Factors.P252.factor9Minus,0,Factors.P252.checked9Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P252.factor10Plus,0,Factors.P252.checked10Plus⟩,⟨Factors.P252.factor10Minus,0,Factors.P252.checked10Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P252.factor11Plus,0,Factors.P252.checked11Plus⟩,⟨Factors.P252.factor11Minus,0,Factors.P252.checked11Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P252.factor12Plus,0,Factors.P252.checked12Plus⟩,⟨Factors.P252.factor12Minus,0,Factors.P252.checked12Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P252.factor13Plus,0,Factors.P252.checked13Plus⟩,⟨Factors.P252.factor13Minus,0,Factors.P252.checked13Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P252.factor14Plus,0,Factors.P252.checked14Plus⟩,⟨Factors.P252.factor14Minus,0,Factors.P252.checked14Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P252.factor15Plus,0,Factors.P252.checked15Plus⟩,⟨Factors.P252.factor15Minus,0,Factors.P252.checked15Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P253.factor0Plus,0,Factors.P253.checked0Plus⟩,⟨Factors.P253.factor0Minus,0,Factors.P253.checked0Minus⟩⟩)
    ((fun impossible => Fin.elim0 impossible)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))

end
end LAlanine40K2025.Thermal.Recovery.Reservoir.Pointer.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Rows
end SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule
