import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.OrdinaryPair
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P253
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P254
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P255

set_option autoImplicit false
namespace SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule
namespace LAlanine40K2025.Thermal.Recovery.Reservoir.Pointer.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Rows
open Propagation.Interface
noncomputable section

set_option maxHeartbeats 400000 in
def row60 : (b : Basis) → (60 : Basis) < b → OrdinaryPair 60 b :=
  Fin.cases (fun (ordered : (60 : Basis) < (0 : Basis)) => False.elim ((by decide +kernel : ¬ (60 : Basis) < (0 : Basis)) ordered))
    (Fin.cases (fun (ordered : (60 : Basis) < (1 : Basis)) => False.elim ((by decide +kernel : ¬ (60 : Basis) < (1 : Basis)) ordered))
    (Fin.cases (fun (ordered : (60 : Basis) < (2 : Basis)) => False.elim ((by decide +kernel : ¬ (60 : Basis) < (2 : Basis)) ordered))
    (Fin.cases (fun (ordered : (60 : Basis) < (3 : Basis)) => False.elim ((by decide +kernel : ¬ (60 : Basis) < (3 : Basis)) ordered))
    (Fin.cases (fun (ordered : (60 : Basis) < (4 : Basis)) => False.elim ((by decide +kernel : ¬ (60 : Basis) < (4 : Basis)) ordered))
    (Fin.cases (fun (ordered : (60 : Basis) < (5 : Basis)) => False.elim ((by decide +kernel : ¬ (60 : Basis) < (5 : Basis)) ordered))
    (Fin.cases (fun (ordered : (60 : Basis) < (6 : Basis)) => False.elim ((by decide +kernel : ¬ (60 : Basis) < (6 : Basis)) ordered))
    (Fin.cases (fun (ordered : (60 : Basis) < (7 : Basis)) => False.elim ((by decide +kernel : ¬ (60 : Basis) < (7 : Basis)) ordered))
    (Fin.cases (fun (ordered : (60 : Basis) < (8 : Basis)) => False.elim ((by decide +kernel : ¬ (60 : Basis) < (8 : Basis)) ordered))
    (Fin.cases (fun (ordered : (60 : Basis) < (9 : Basis)) => False.elim ((by decide +kernel : ¬ (60 : Basis) < (9 : Basis)) ordered))
    (Fin.cases (fun (ordered : (60 : Basis) < (10 : Basis)) => False.elim ((by decide +kernel : ¬ (60 : Basis) < (10 : Basis)) ordered))
    (Fin.cases (fun (ordered : (60 : Basis) < (11 : Basis)) => False.elim ((by decide +kernel : ¬ (60 : Basis) < (11 : Basis)) ordered))
    (Fin.cases (fun (ordered : (60 : Basis) < (12 : Basis)) => False.elim ((by decide +kernel : ¬ (60 : Basis) < (12 : Basis)) ordered))
    (Fin.cases (fun (ordered : (60 : Basis) < (13 : Basis)) => False.elim ((by decide +kernel : ¬ (60 : Basis) < (13 : Basis)) ordered))
    (Fin.cases (fun (ordered : (60 : Basis) < (14 : Basis)) => False.elim ((by decide +kernel : ¬ (60 : Basis) < (14 : Basis)) ordered))
    (Fin.cases (fun (ordered : (60 : Basis) < (15 : Basis)) => False.elim ((by decide +kernel : ¬ (60 : Basis) < (15 : Basis)) ordered))
    (Fin.cases (fun (ordered : (60 : Basis) < (16 : Basis)) => False.elim ((by decide +kernel : ¬ (60 : Basis) < (16 : Basis)) ordered))
    (Fin.cases (fun (ordered : (60 : Basis) < (17 : Basis)) => False.elim ((by decide +kernel : ¬ (60 : Basis) < (17 : Basis)) ordered))
    (Fin.cases (fun (ordered : (60 : Basis) < (18 : Basis)) => False.elim ((by decide +kernel : ¬ (60 : Basis) < (18 : Basis)) ordered))
    (Fin.cases (fun (ordered : (60 : Basis) < (19 : Basis)) => False.elim ((by decide +kernel : ¬ (60 : Basis) < (19 : Basis)) ordered))
    (Fin.cases (fun (ordered : (60 : Basis) < (20 : Basis)) => False.elim ((by decide +kernel : ¬ (60 : Basis) < (20 : Basis)) ordered))
    (Fin.cases (fun (ordered : (60 : Basis) < (21 : Basis)) => False.elim ((by decide +kernel : ¬ (60 : Basis) < (21 : Basis)) ordered))
    (Fin.cases (fun (ordered : (60 : Basis) < (22 : Basis)) => False.elim ((by decide +kernel : ¬ (60 : Basis) < (22 : Basis)) ordered))
    (Fin.cases (fun (ordered : (60 : Basis) < (23 : Basis)) => False.elim ((by decide +kernel : ¬ (60 : Basis) < (23 : Basis)) ordered))
    (Fin.cases (fun (ordered : (60 : Basis) < (24 : Basis)) => False.elim ((by decide +kernel : ¬ (60 : Basis) < (24 : Basis)) ordered))
    (Fin.cases (fun (ordered : (60 : Basis) < (25 : Basis)) => False.elim ((by decide +kernel : ¬ (60 : Basis) < (25 : Basis)) ordered))
    (Fin.cases (fun (ordered : (60 : Basis) < (26 : Basis)) => False.elim ((by decide +kernel : ¬ (60 : Basis) < (26 : Basis)) ordered))
    (Fin.cases (fun (ordered : (60 : Basis) < (27 : Basis)) => False.elim ((by decide +kernel : ¬ (60 : Basis) < (27 : Basis)) ordered))
    (Fin.cases (fun (ordered : (60 : Basis) < (28 : Basis)) => False.elim ((by decide +kernel : ¬ (60 : Basis) < (28 : Basis)) ordered))
    (Fin.cases (fun (ordered : (60 : Basis) < (29 : Basis)) => False.elim ((by decide +kernel : ¬ (60 : Basis) < (29 : Basis)) ordered))
    (Fin.cases (fun (ordered : (60 : Basis) < (30 : Basis)) => False.elim ((by decide +kernel : ¬ (60 : Basis) < (30 : Basis)) ordered))
    (Fin.cases (fun (ordered : (60 : Basis) < (31 : Basis)) => False.elim ((by decide +kernel : ¬ (60 : Basis) < (31 : Basis)) ordered))
    (Fin.cases (fun (ordered : (60 : Basis) < (32 : Basis)) => False.elim ((by decide +kernel : ¬ (60 : Basis) < (32 : Basis)) ordered))
    (Fin.cases (fun (ordered : (60 : Basis) < (33 : Basis)) => False.elim ((by decide +kernel : ¬ (60 : Basis) < (33 : Basis)) ordered))
    (Fin.cases (fun (ordered : (60 : Basis) < (34 : Basis)) => False.elim ((by decide +kernel : ¬ (60 : Basis) < (34 : Basis)) ordered))
    (Fin.cases (fun (ordered : (60 : Basis) < (35 : Basis)) => False.elim ((by decide +kernel : ¬ (60 : Basis) < (35 : Basis)) ordered))
    (Fin.cases (fun (ordered : (60 : Basis) < (36 : Basis)) => False.elim ((by decide +kernel : ¬ (60 : Basis) < (36 : Basis)) ordered))
    (Fin.cases (fun (ordered : (60 : Basis) < (37 : Basis)) => False.elim ((by decide +kernel : ¬ (60 : Basis) < (37 : Basis)) ordered))
    (Fin.cases (fun (ordered : (60 : Basis) < (38 : Basis)) => False.elim ((by decide +kernel : ¬ (60 : Basis) < (38 : Basis)) ordered))
    (Fin.cases (fun (ordered : (60 : Basis) < (39 : Basis)) => False.elim ((by decide +kernel : ¬ (60 : Basis) < (39 : Basis)) ordered))
    (Fin.cases (fun (ordered : (60 : Basis) < (40 : Basis)) => False.elim ((by decide +kernel : ¬ (60 : Basis) < (40 : Basis)) ordered))
    (Fin.cases (fun (ordered : (60 : Basis) < (41 : Basis)) => False.elim ((by decide +kernel : ¬ (60 : Basis) < (41 : Basis)) ordered))
    (Fin.cases (fun (ordered : (60 : Basis) < (42 : Basis)) => False.elim ((by decide +kernel : ¬ (60 : Basis) < (42 : Basis)) ordered))
    (Fin.cases (fun (ordered : (60 : Basis) < (43 : Basis)) => False.elim ((by decide +kernel : ¬ (60 : Basis) < (43 : Basis)) ordered))
    (Fin.cases (fun (ordered : (60 : Basis) < (44 : Basis)) => False.elim ((by decide +kernel : ¬ (60 : Basis) < (44 : Basis)) ordered))
    (Fin.cases (fun (ordered : (60 : Basis) < (45 : Basis)) => False.elim ((by decide +kernel : ¬ (60 : Basis) < (45 : Basis)) ordered))
    (Fin.cases (fun (ordered : (60 : Basis) < (46 : Basis)) => False.elim ((by decide +kernel : ¬ (60 : Basis) < (46 : Basis)) ordered))
    (Fin.cases (fun (ordered : (60 : Basis) < (47 : Basis)) => False.elim ((by decide +kernel : ¬ (60 : Basis) < (47 : Basis)) ordered))
    (Fin.cases (fun (ordered : (60 : Basis) < (48 : Basis)) => False.elim ((by decide +kernel : ¬ (60 : Basis) < (48 : Basis)) ordered))
    (Fin.cases (fun (ordered : (60 : Basis) < (49 : Basis)) => False.elim ((by decide +kernel : ¬ (60 : Basis) < (49 : Basis)) ordered))
    (Fin.cases (fun (ordered : (60 : Basis) < (50 : Basis)) => False.elim ((by decide +kernel : ¬ (60 : Basis) < (50 : Basis)) ordered))
    (Fin.cases (fun (ordered : (60 : Basis) < (51 : Basis)) => False.elim ((by decide +kernel : ¬ (60 : Basis) < (51 : Basis)) ordered))
    (Fin.cases (fun (ordered : (60 : Basis) < (52 : Basis)) => False.elim ((by decide +kernel : ¬ (60 : Basis) < (52 : Basis)) ordered))
    (Fin.cases (fun (ordered : (60 : Basis) < (53 : Basis)) => False.elim ((by decide +kernel : ¬ (60 : Basis) < (53 : Basis)) ordered))
    (Fin.cases (fun (ordered : (60 : Basis) < (54 : Basis)) => False.elim ((by decide +kernel : ¬ (60 : Basis) < (54 : Basis)) ordered))
    (Fin.cases (fun (ordered : (60 : Basis) < (55 : Basis)) => False.elim ((by decide +kernel : ¬ (60 : Basis) < (55 : Basis)) ordered))
    (Fin.cases (fun (ordered : (60 : Basis) < (56 : Basis)) => False.elim ((by decide +kernel : ¬ (60 : Basis) < (56 : Basis)) ordered))
    (Fin.cases (fun (ordered : (60 : Basis) < (57 : Basis)) => False.elim ((by decide +kernel : ¬ (60 : Basis) < (57 : Basis)) ordered))
    (Fin.cases (fun (ordered : (60 : Basis) < (58 : Basis)) => False.elim ((by decide +kernel : ¬ (60 : Basis) < (58 : Basis)) ordered))
    (Fin.cases (fun (ordered : (60 : Basis) < (59 : Basis)) => False.elim ((by decide +kernel : ¬ (60 : Basis) < (59 : Basis)) ordered))
    (Fin.cases (fun (ordered : (60 : Basis) < (60 : Basis)) => False.elim ((by decide +kernel : ¬ (60 : Basis) < (60 : Basis)) ordered))
    (Fin.cases (fun _ => ⟨⟨Factors.P253.factor1Plus,0,Factors.P253.checked1Plus⟩,⟨Factors.P253.factor1Minus,0,Factors.P253.checked1Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P253.factor2Plus,0,Factors.P253.checked2Plus⟩,⟨Factors.P253.factor2Minus,0,Factors.P253.checked2Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P253.factor3Plus,0,Factors.P253.checked3Plus⟩,⟨Factors.P253.factor3Minus,0,Factors.P253.checked3Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P253.factor4Plus,0,Factors.P253.checked4Plus⟩,⟨Factors.P253.factor4Minus,0,Factors.P253.checked4Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P253.factor5Plus,0,Factors.P253.checked5Plus⟩,⟨Factors.P253.factor5Minus,0,Factors.P253.checked5Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P253.factor6Plus,0,Factors.P253.checked6Plus⟩,⟨Factors.P253.factor6Minus,0,Factors.P253.checked6Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P253.factor7Plus,0,Factors.P253.checked7Plus⟩,⟨Factors.P253.factor7Minus,0,Factors.P253.checked7Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P253.factor8Plus,0,Factors.P253.checked8Plus⟩,⟨Factors.P253.factor8Minus,0,Factors.P253.checked8Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P253.factor9Plus,0,Factors.P253.checked9Plus⟩,⟨Factors.P253.factor9Minus,0,Factors.P253.checked9Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P253.factor10Plus,0,Factors.P253.checked10Plus⟩,⟨Factors.P253.factor10Minus,0,Factors.P253.checked10Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P253.factor11Plus,0,Factors.P253.checked11Plus⟩,⟨Factors.P253.factor11Minus,0,Factors.P253.checked11Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P253.factor12Plus,0,Factors.P253.checked12Plus⟩,⟨Factors.P253.factor12Minus,0,Factors.P253.checked12Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P253.factor13Plus,0,Factors.P253.checked13Plus⟩,⟨Factors.P253.factor13Minus,0,Factors.P253.checked13Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P253.factor14Plus,0,Factors.P253.checked14Plus⟩,⟨Factors.P253.factor14Minus,0,Factors.P253.checked14Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P253.factor15Plus,0,Factors.P253.checked15Plus⟩,⟨Factors.P253.factor15Minus,0,Factors.P253.checked15Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P254.factor0Plus,0,Factors.P254.checked0Plus⟩,⟨Factors.P254.factor0Minus,0,Factors.P254.checked0Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P254.factor1Plus,0,Factors.P254.checked1Plus⟩,⟨Factors.P254.factor1Minus,0,Factors.P254.checked1Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P254.factor2Plus,0,Factors.P254.checked2Plus⟩,⟨Factors.P254.factor2Minus,0,Factors.P254.checked2Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P254.factor3Plus,0,Factors.P254.checked3Plus⟩,⟨Factors.P254.factor3Minus,0,Factors.P254.checked3Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P254.factor4Plus,0,Factors.P254.checked4Plus⟩,⟨Factors.P254.factor4Minus,0,Factors.P254.checked4Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P254.factor5Plus,0,Factors.P254.checked5Plus⟩,⟨Factors.P254.factor5Minus,0,Factors.P254.checked5Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P254.factor6Plus,0,Factors.P254.checked6Plus⟩,⟨Factors.P254.factor6Minus,0,Factors.P254.checked6Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P254.factor7Plus,0,Factors.P254.checked7Plus⟩,⟨Factors.P254.factor7Minus,0,Factors.P254.checked7Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P254.factor8Plus,0,Factors.P254.checked8Plus⟩,⟨Factors.P254.factor8Minus,0,Factors.P254.checked8Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P254.factor9Plus,0,Factors.P254.checked9Plus⟩,⟨Factors.P254.factor9Minus,0,Factors.P254.checked9Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P254.factor10Plus,0,Factors.P254.checked10Plus⟩,⟨Factors.P254.factor10Minus,0,Factors.P254.checked10Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P254.factor11Plus,0,Factors.P254.checked11Plus⟩,⟨Factors.P254.factor11Minus,0,Factors.P254.checked11Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P254.factor12Plus,0,Factors.P254.checked12Plus⟩,⟨Factors.P254.factor12Minus,0,Factors.P254.checked12Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P254.factor13Plus,0,Factors.P254.checked13Plus⟩,⟨Factors.P254.factor13Minus,0,Factors.P254.checked13Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P254.factor14Plus,0,Factors.P254.checked14Plus⟩,⟨Factors.P254.factor14Minus,0,Factors.P254.checked14Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P254.factor15Plus,0,Factors.P254.checked15Plus⟩,⟨Factors.P254.factor15Minus,0,Factors.P254.checked15Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P255.factor0Plus,0,Factors.P255.checked0Plus⟩,⟨Factors.P255.factor0Minus,0,Factors.P255.checked0Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P255.factor1Plus,0,Factors.P255.checked1Plus⟩,⟨Factors.P255.factor1Minus,0,Factors.P255.checked1Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P255.factor2Plus,0,Factors.P255.checked2Plus⟩,⟨Factors.P255.factor2Minus,0,Factors.P255.checked2Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P255.factor3Plus,0,Factors.P255.checked3Plus⟩,⟨Factors.P255.factor3Minus,0,Factors.P255.checked3Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P255.factor4Plus,0,Factors.P255.checked4Plus⟩,⟨Factors.P255.factor4Minus,0,Factors.P255.checked4Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P255.factor5Plus,0,Factors.P255.checked5Plus⟩,⟨Factors.P255.factor5Minus,0,Factors.P255.checked5Minus⟩⟩)
    ((fun impossible => Fin.elim0 impossible)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))

end
end LAlanine40K2025.Thermal.Recovery.Reservoir.Pointer.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Rows
end SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule
