import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.OrdinaryPair
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P255
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P256
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P257

set_option autoImplicit false
namespace SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule
namespace LAlanine40K2025.Thermal.Recovery.Reservoir.Pointer.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Rows
open Propagation.Interface
noncomputable section

set_option maxHeartbeats 400000 in
def row61 : (b : Basis) → (61 : Basis) < b → OrdinaryPair 61 b :=
  Fin.cases (fun (ordered : (61 : Basis) < (0 : Basis)) => False.elim ((by decide +kernel : ¬ (61 : Basis) < (0 : Basis)) ordered))
    (Fin.cases (fun (ordered : (61 : Basis) < (1 : Basis)) => False.elim ((by decide +kernel : ¬ (61 : Basis) < (1 : Basis)) ordered))
    (Fin.cases (fun (ordered : (61 : Basis) < (2 : Basis)) => False.elim ((by decide +kernel : ¬ (61 : Basis) < (2 : Basis)) ordered))
    (Fin.cases (fun (ordered : (61 : Basis) < (3 : Basis)) => False.elim ((by decide +kernel : ¬ (61 : Basis) < (3 : Basis)) ordered))
    (Fin.cases (fun (ordered : (61 : Basis) < (4 : Basis)) => False.elim ((by decide +kernel : ¬ (61 : Basis) < (4 : Basis)) ordered))
    (Fin.cases (fun (ordered : (61 : Basis) < (5 : Basis)) => False.elim ((by decide +kernel : ¬ (61 : Basis) < (5 : Basis)) ordered))
    (Fin.cases (fun (ordered : (61 : Basis) < (6 : Basis)) => False.elim ((by decide +kernel : ¬ (61 : Basis) < (6 : Basis)) ordered))
    (Fin.cases (fun (ordered : (61 : Basis) < (7 : Basis)) => False.elim ((by decide +kernel : ¬ (61 : Basis) < (7 : Basis)) ordered))
    (Fin.cases (fun (ordered : (61 : Basis) < (8 : Basis)) => False.elim ((by decide +kernel : ¬ (61 : Basis) < (8 : Basis)) ordered))
    (Fin.cases (fun (ordered : (61 : Basis) < (9 : Basis)) => False.elim ((by decide +kernel : ¬ (61 : Basis) < (9 : Basis)) ordered))
    (Fin.cases (fun (ordered : (61 : Basis) < (10 : Basis)) => False.elim ((by decide +kernel : ¬ (61 : Basis) < (10 : Basis)) ordered))
    (Fin.cases (fun (ordered : (61 : Basis) < (11 : Basis)) => False.elim ((by decide +kernel : ¬ (61 : Basis) < (11 : Basis)) ordered))
    (Fin.cases (fun (ordered : (61 : Basis) < (12 : Basis)) => False.elim ((by decide +kernel : ¬ (61 : Basis) < (12 : Basis)) ordered))
    (Fin.cases (fun (ordered : (61 : Basis) < (13 : Basis)) => False.elim ((by decide +kernel : ¬ (61 : Basis) < (13 : Basis)) ordered))
    (Fin.cases (fun (ordered : (61 : Basis) < (14 : Basis)) => False.elim ((by decide +kernel : ¬ (61 : Basis) < (14 : Basis)) ordered))
    (Fin.cases (fun (ordered : (61 : Basis) < (15 : Basis)) => False.elim ((by decide +kernel : ¬ (61 : Basis) < (15 : Basis)) ordered))
    (Fin.cases (fun (ordered : (61 : Basis) < (16 : Basis)) => False.elim ((by decide +kernel : ¬ (61 : Basis) < (16 : Basis)) ordered))
    (Fin.cases (fun (ordered : (61 : Basis) < (17 : Basis)) => False.elim ((by decide +kernel : ¬ (61 : Basis) < (17 : Basis)) ordered))
    (Fin.cases (fun (ordered : (61 : Basis) < (18 : Basis)) => False.elim ((by decide +kernel : ¬ (61 : Basis) < (18 : Basis)) ordered))
    (Fin.cases (fun (ordered : (61 : Basis) < (19 : Basis)) => False.elim ((by decide +kernel : ¬ (61 : Basis) < (19 : Basis)) ordered))
    (Fin.cases (fun (ordered : (61 : Basis) < (20 : Basis)) => False.elim ((by decide +kernel : ¬ (61 : Basis) < (20 : Basis)) ordered))
    (Fin.cases (fun (ordered : (61 : Basis) < (21 : Basis)) => False.elim ((by decide +kernel : ¬ (61 : Basis) < (21 : Basis)) ordered))
    (Fin.cases (fun (ordered : (61 : Basis) < (22 : Basis)) => False.elim ((by decide +kernel : ¬ (61 : Basis) < (22 : Basis)) ordered))
    (Fin.cases (fun (ordered : (61 : Basis) < (23 : Basis)) => False.elim ((by decide +kernel : ¬ (61 : Basis) < (23 : Basis)) ordered))
    (Fin.cases (fun (ordered : (61 : Basis) < (24 : Basis)) => False.elim ((by decide +kernel : ¬ (61 : Basis) < (24 : Basis)) ordered))
    (Fin.cases (fun (ordered : (61 : Basis) < (25 : Basis)) => False.elim ((by decide +kernel : ¬ (61 : Basis) < (25 : Basis)) ordered))
    (Fin.cases (fun (ordered : (61 : Basis) < (26 : Basis)) => False.elim ((by decide +kernel : ¬ (61 : Basis) < (26 : Basis)) ordered))
    (Fin.cases (fun (ordered : (61 : Basis) < (27 : Basis)) => False.elim ((by decide +kernel : ¬ (61 : Basis) < (27 : Basis)) ordered))
    (Fin.cases (fun (ordered : (61 : Basis) < (28 : Basis)) => False.elim ((by decide +kernel : ¬ (61 : Basis) < (28 : Basis)) ordered))
    (Fin.cases (fun (ordered : (61 : Basis) < (29 : Basis)) => False.elim ((by decide +kernel : ¬ (61 : Basis) < (29 : Basis)) ordered))
    (Fin.cases (fun (ordered : (61 : Basis) < (30 : Basis)) => False.elim ((by decide +kernel : ¬ (61 : Basis) < (30 : Basis)) ordered))
    (Fin.cases (fun (ordered : (61 : Basis) < (31 : Basis)) => False.elim ((by decide +kernel : ¬ (61 : Basis) < (31 : Basis)) ordered))
    (Fin.cases (fun (ordered : (61 : Basis) < (32 : Basis)) => False.elim ((by decide +kernel : ¬ (61 : Basis) < (32 : Basis)) ordered))
    (Fin.cases (fun (ordered : (61 : Basis) < (33 : Basis)) => False.elim ((by decide +kernel : ¬ (61 : Basis) < (33 : Basis)) ordered))
    (Fin.cases (fun (ordered : (61 : Basis) < (34 : Basis)) => False.elim ((by decide +kernel : ¬ (61 : Basis) < (34 : Basis)) ordered))
    (Fin.cases (fun (ordered : (61 : Basis) < (35 : Basis)) => False.elim ((by decide +kernel : ¬ (61 : Basis) < (35 : Basis)) ordered))
    (Fin.cases (fun (ordered : (61 : Basis) < (36 : Basis)) => False.elim ((by decide +kernel : ¬ (61 : Basis) < (36 : Basis)) ordered))
    (Fin.cases (fun (ordered : (61 : Basis) < (37 : Basis)) => False.elim ((by decide +kernel : ¬ (61 : Basis) < (37 : Basis)) ordered))
    (Fin.cases (fun (ordered : (61 : Basis) < (38 : Basis)) => False.elim ((by decide +kernel : ¬ (61 : Basis) < (38 : Basis)) ordered))
    (Fin.cases (fun (ordered : (61 : Basis) < (39 : Basis)) => False.elim ((by decide +kernel : ¬ (61 : Basis) < (39 : Basis)) ordered))
    (Fin.cases (fun (ordered : (61 : Basis) < (40 : Basis)) => False.elim ((by decide +kernel : ¬ (61 : Basis) < (40 : Basis)) ordered))
    (Fin.cases (fun (ordered : (61 : Basis) < (41 : Basis)) => False.elim ((by decide +kernel : ¬ (61 : Basis) < (41 : Basis)) ordered))
    (Fin.cases (fun (ordered : (61 : Basis) < (42 : Basis)) => False.elim ((by decide +kernel : ¬ (61 : Basis) < (42 : Basis)) ordered))
    (Fin.cases (fun (ordered : (61 : Basis) < (43 : Basis)) => False.elim ((by decide +kernel : ¬ (61 : Basis) < (43 : Basis)) ordered))
    (Fin.cases (fun (ordered : (61 : Basis) < (44 : Basis)) => False.elim ((by decide +kernel : ¬ (61 : Basis) < (44 : Basis)) ordered))
    (Fin.cases (fun (ordered : (61 : Basis) < (45 : Basis)) => False.elim ((by decide +kernel : ¬ (61 : Basis) < (45 : Basis)) ordered))
    (Fin.cases (fun (ordered : (61 : Basis) < (46 : Basis)) => False.elim ((by decide +kernel : ¬ (61 : Basis) < (46 : Basis)) ordered))
    (Fin.cases (fun (ordered : (61 : Basis) < (47 : Basis)) => False.elim ((by decide +kernel : ¬ (61 : Basis) < (47 : Basis)) ordered))
    (Fin.cases (fun (ordered : (61 : Basis) < (48 : Basis)) => False.elim ((by decide +kernel : ¬ (61 : Basis) < (48 : Basis)) ordered))
    (Fin.cases (fun (ordered : (61 : Basis) < (49 : Basis)) => False.elim ((by decide +kernel : ¬ (61 : Basis) < (49 : Basis)) ordered))
    (Fin.cases (fun (ordered : (61 : Basis) < (50 : Basis)) => False.elim ((by decide +kernel : ¬ (61 : Basis) < (50 : Basis)) ordered))
    (Fin.cases (fun (ordered : (61 : Basis) < (51 : Basis)) => False.elim ((by decide +kernel : ¬ (61 : Basis) < (51 : Basis)) ordered))
    (Fin.cases (fun (ordered : (61 : Basis) < (52 : Basis)) => False.elim ((by decide +kernel : ¬ (61 : Basis) < (52 : Basis)) ordered))
    (Fin.cases (fun (ordered : (61 : Basis) < (53 : Basis)) => False.elim ((by decide +kernel : ¬ (61 : Basis) < (53 : Basis)) ordered))
    (Fin.cases (fun (ordered : (61 : Basis) < (54 : Basis)) => False.elim ((by decide +kernel : ¬ (61 : Basis) < (54 : Basis)) ordered))
    (Fin.cases (fun (ordered : (61 : Basis) < (55 : Basis)) => False.elim ((by decide +kernel : ¬ (61 : Basis) < (55 : Basis)) ordered))
    (Fin.cases (fun (ordered : (61 : Basis) < (56 : Basis)) => False.elim ((by decide +kernel : ¬ (61 : Basis) < (56 : Basis)) ordered))
    (Fin.cases (fun (ordered : (61 : Basis) < (57 : Basis)) => False.elim ((by decide +kernel : ¬ (61 : Basis) < (57 : Basis)) ordered))
    (Fin.cases (fun (ordered : (61 : Basis) < (58 : Basis)) => False.elim ((by decide +kernel : ¬ (61 : Basis) < (58 : Basis)) ordered))
    (Fin.cases (fun (ordered : (61 : Basis) < (59 : Basis)) => False.elim ((by decide +kernel : ¬ (61 : Basis) < (59 : Basis)) ordered))
    (Fin.cases (fun (ordered : (61 : Basis) < (60 : Basis)) => False.elim ((by decide +kernel : ¬ (61 : Basis) < (60 : Basis)) ordered))
    (Fin.cases (fun (ordered : (61 : Basis) < (61 : Basis)) => False.elim ((by decide +kernel : ¬ (61 : Basis) < (61 : Basis)) ordered))
    (Fin.cases (fun _ => ⟨⟨Factors.P255.factor6Plus,0,Factors.P255.checked6Plus⟩,⟨Factors.P255.factor6Minus,0,Factors.P255.checked6Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P255.factor7Plus,0,Factors.P255.checked7Plus⟩,⟨Factors.P255.factor7Minus,0,Factors.P255.checked7Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P255.factor8Plus,0,Factors.P255.checked8Plus⟩,⟨Factors.P255.factor8Minus,0,Factors.P255.checked8Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P255.factor9Plus,0,Factors.P255.checked9Plus⟩,⟨Factors.P255.factor9Minus,0,Factors.P255.checked9Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P255.factor10Plus,0,Factors.P255.checked10Plus⟩,⟨Factors.P255.factor10Minus,0,Factors.P255.checked10Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P255.factor11Plus,0,Factors.P255.checked11Plus⟩,⟨Factors.P255.factor11Minus,0,Factors.P255.checked11Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P255.factor12Plus,0,Factors.P255.checked12Plus⟩,⟨Factors.P255.factor12Minus,0,Factors.P255.checked12Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P255.factor13Plus,0,Factors.P255.checked13Plus⟩,⟨Factors.P255.factor13Minus,0,Factors.P255.checked13Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P255.factor14Plus,0,Factors.P255.checked14Plus⟩,⟨Factors.P255.factor14Minus,0,Factors.P255.checked14Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P255.factor15Plus,0,Factors.P255.checked15Plus⟩,⟨Factors.P255.factor15Minus,0,Factors.P255.checked15Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P256.factor0Plus,0,Factors.P256.checked0Plus⟩,⟨Factors.P256.factor0Minus,0,Factors.P256.checked0Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P256.factor1Plus,0,Factors.P256.checked1Plus⟩,⟨Factors.P256.factor1Minus,0,Factors.P256.checked1Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P256.factor2Plus,0,Factors.P256.checked2Plus⟩,⟨Factors.P256.factor2Minus,0,Factors.P256.checked2Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P256.factor3Plus,0,Factors.P256.checked3Plus⟩,⟨Factors.P256.factor3Minus,0,Factors.P256.checked3Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P256.factor4Plus,0,Factors.P256.checked4Plus⟩,⟨Factors.P256.factor4Minus,0,Factors.P256.checked4Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P256.factor5Plus,0,Factors.P256.checked5Plus⟩,⟨Factors.P256.factor5Minus,0,Factors.P256.checked5Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P256.factor6Plus,0,Factors.P256.checked6Plus⟩,⟨Factors.P256.factor6Minus,0,Factors.P256.checked6Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P256.factor7Plus,0,Factors.P256.checked7Plus⟩,⟨Factors.P256.factor7Minus,0,Factors.P256.checked7Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P256.factor8Plus,0,Factors.P256.checked8Plus⟩,⟨Factors.P256.factor8Minus,0,Factors.P256.checked8Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P256.factor9Plus,0,Factors.P256.checked9Plus⟩,⟨Factors.P256.factor9Minus,0,Factors.P256.checked9Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P256.factor10Plus,0,Factors.P256.checked10Plus⟩,⟨Factors.P256.factor10Minus,0,Factors.P256.checked10Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P256.factor11Plus,0,Factors.P256.checked11Plus⟩,⟨Factors.P256.factor11Minus,0,Factors.P256.checked11Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P256.factor12Plus,0,Factors.P256.checked12Plus⟩,⟨Factors.P256.factor12Minus,0,Factors.P256.checked12Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P256.factor13Plus,0,Factors.P256.checked13Plus⟩,⟨Factors.P256.factor13Minus,0,Factors.P256.checked13Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P256.factor14Plus,0,Factors.P256.checked14Plus⟩,⟨Factors.P256.factor14Minus,0,Factors.P256.checked14Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P256.factor15Plus,0,Factors.P256.checked15Plus⟩,⟨Factors.P256.factor15Minus,0,Factors.P256.checked15Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P257.factor0Plus,0,Factors.P257.checked0Plus⟩,⟨Factors.P257.factor0Minus,0,Factors.P257.checked0Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P257.factor1Plus,0,Factors.P257.checked1Plus⟩,⟨Factors.P257.factor1Minus,0,Factors.P257.checked1Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P257.factor2Plus,0,Factors.P257.checked2Plus⟩,⟨Factors.P257.factor2Minus,0,Factors.P257.checked2Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P257.factor3Plus,0,Factors.P257.checked3Plus⟩,⟨Factors.P257.factor3Minus,0,Factors.P257.checked3Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P257.factor4Plus,0,Factors.P257.checked4Plus⟩,⟨Factors.P257.factor4Minus,0,Factors.P257.checked4Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P257.factor5Plus,0,Factors.P257.checked5Plus⟩,⟨Factors.P257.factor5Minus,0,Factors.P257.checked5Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P257.factor6Plus,0,Factors.P257.checked6Plus⟩,⟨Factors.P257.factor6Minus,0,Factors.P257.checked6Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P257.factor7Plus,0,Factors.P257.checked7Plus⟩,⟨Factors.P257.factor7Minus,0,Factors.P257.checked7Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P257.factor8Plus,0,Factors.P257.checked8Plus⟩,⟨Factors.P257.factor8Minus,0,Factors.P257.checked8Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P257.factor9Plus,0,Factors.P257.checked9Plus⟩,⟨Factors.P257.factor9Minus,0,Factors.P257.checked9Minus⟩⟩)
    ((fun impossible => Fin.elim0 impossible)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))

end
end LAlanine40K2025.Thermal.Recovery.Reservoir.Pointer.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Rows
end SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule
