import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.OrdinaryPair
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P259
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P260
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P261

set_option autoImplicit false
namespace SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule
namespace LAlanine40K2025.Thermal.Recovery.Reservoir.Pointer.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Rows
open Propagation.Interface
noncomputable section

set_option maxHeartbeats 400000 in
def row63 : (b : Basis) → (63 : Basis) < b → OrdinaryPair 63 b :=
  Fin.cases (fun (ordered : (63 : Basis) < (0 : Basis)) => False.elim ((by decide +kernel : ¬ (63 : Basis) < (0 : Basis)) ordered))
    (Fin.cases (fun (ordered : (63 : Basis) < (1 : Basis)) => False.elim ((by decide +kernel : ¬ (63 : Basis) < (1 : Basis)) ordered))
    (Fin.cases (fun (ordered : (63 : Basis) < (2 : Basis)) => False.elim ((by decide +kernel : ¬ (63 : Basis) < (2 : Basis)) ordered))
    (Fin.cases (fun (ordered : (63 : Basis) < (3 : Basis)) => False.elim ((by decide +kernel : ¬ (63 : Basis) < (3 : Basis)) ordered))
    (Fin.cases (fun (ordered : (63 : Basis) < (4 : Basis)) => False.elim ((by decide +kernel : ¬ (63 : Basis) < (4 : Basis)) ordered))
    (Fin.cases (fun (ordered : (63 : Basis) < (5 : Basis)) => False.elim ((by decide +kernel : ¬ (63 : Basis) < (5 : Basis)) ordered))
    (Fin.cases (fun (ordered : (63 : Basis) < (6 : Basis)) => False.elim ((by decide +kernel : ¬ (63 : Basis) < (6 : Basis)) ordered))
    (Fin.cases (fun (ordered : (63 : Basis) < (7 : Basis)) => False.elim ((by decide +kernel : ¬ (63 : Basis) < (7 : Basis)) ordered))
    (Fin.cases (fun (ordered : (63 : Basis) < (8 : Basis)) => False.elim ((by decide +kernel : ¬ (63 : Basis) < (8 : Basis)) ordered))
    (Fin.cases (fun (ordered : (63 : Basis) < (9 : Basis)) => False.elim ((by decide +kernel : ¬ (63 : Basis) < (9 : Basis)) ordered))
    (Fin.cases (fun (ordered : (63 : Basis) < (10 : Basis)) => False.elim ((by decide +kernel : ¬ (63 : Basis) < (10 : Basis)) ordered))
    (Fin.cases (fun (ordered : (63 : Basis) < (11 : Basis)) => False.elim ((by decide +kernel : ¬ (63 : Basis) < (11 : Basis)) ordered))
    (Fin.cases (fun (ordered : (63 : Basis) < (12 : Basis)) => False.elim ((by decide +kernel : ¬ (63 : Basis) < (12 : Basis)) ordered))
    (Fin.cases (fun (ordered : (63 : Basis) < (13 : Basis)) => False.elim ((by decide +kernel : ¬ (63 : Basis) < (13 : Basis)) ordered))
    (Fin.cases (fun (ordered : (63 : Basis) < (14 : Basis)) => False.elim ((by decide +kernel : ¬ (63 : Basis) < (14 : Basis)) ordered))
    (Fin.cases (fun (ordered : (63 : Basis) < (15 : Basis)) => False.elim ((by decide +kernel : ¬ (63 : Basis) < (15 : Basis)) ordered))
    (Fin.cases (fun (ordered : (63 : Basis) < (16 : Basis)) => False.elim ((by decide +kernel : ¬ (63 : Basis) < (16 : Basis)) ordered))
    (Fin.cases (fun (ordered : (63 : Basis) < (17 : Basis)) => False.elim ((by decide +kernel : ¬ (63 : Basis) < (17 : Basis)) ordered))
    (Fin.cases (fun (ordered : (63 : Basis) < (18 : Basis)) => False.elim ((by decide +kernel : ¬ (63 : Basis) < (18 : Basis)) ordered))
    (Fin.cases (fun (ordered : (63 : Basis) < (19 : Basis)) => False.elim ((by decide +kernel : ¬ (63 : Basis) < (19 : Basis)) ordered))
    (Fin.cases (fun (ordered : (63 : Basis) < (20 : Basis)) => False.elim ((by decide +kernel : ¬ (63 : Basis) < (20 : Basis)) ordered))
    (Fin.cases (fun (ordered : (63 : Basis) < (21 : Basis)) => False.elim ((by decide +kernel : ¬ (63 : Basis) < (21 : Basis)) ordered))
    (Fin.cases (fun (ordered : (63 : Basis) < (22 : Basis)) => False.elim ((by decide +kernel : ¬ (63 : Basis) < (22 : Basis)) ordered))
    (Fin.cases (fun (ordered : (63 : Basis) < (23 : Basis)) => False.elim ((by decide +kernel : ¬ (63 : Basis) < (23 : Basis)) ordered))
    (Fin.cases (fun (ordered : (63 : Basis) < (24 : Basis)) => False.elim ((by decide +kernel : ¬ (63 : Basis) < (24 : Basis)) ordered))
    (Fin.cases (fun (ordered : (63 : Basis) < (25 : Basis)) => False.elim ((by decide +kernel : ¬ (63 : Basis) < (25 : Basis)) ordered))
    (Fin.cases (fun (ordered : (63 : Basis) < (26 : Basis)) => False.elim ((by decide +kernel : ¬ (63 : Basis) < (26 : Basis)) ordered))
    (Fin.cases (fun (ordered : (63 : Basis) < (27 : Basis)) => False.elim ((by decide +kernel : ¬ (63 : Basis) < (27 : Basis)) ordered))
    (Fin.cases (fun (ordered : (63 : Basis) < (28 : Basis)) => False.elim ((by decide +kernel : ¬ (63 : Basis) < (28 : Basis)) ordered))
    (Fin.cases (fun (ordered : (63 : Basis) < (29 : Basis)) => False.elim ((by decide +kernel : ¬ (63 : Basis) < (29 : Basis)) ordered))
    (Fin.cases (fun (ordered : (63 : Basis) < (30 : Basis)) => False.elim ((by decide +kernel : ¬ (63 : Basis) < (30 : Basis)) ordered))
    (Fin.cases (fun (ordered : (63 : Basis) < (31 : Basis)) => False.elim ((by decide +kernel : ¬ (63 : Basis) < (31 : Basis)) ordered))
    (Fin.cases (fun (ordered : (63 : Basis) < (32 : Basis)) => False.elim ((by decide +kernel : ¬ (63 : Basis) < (32 : Basis)) ordered))
    (Fin.cases (fun (ordered : (63 : Basis) < (33 : Basis)) => False.elim ((by decide +kernel : ¬ (63 : Basis) < (33 : Basis)) ordered))
    (Fin.cases (fun (ordered : (63 : Basis) < (34 : Basis)) => False.elim ((by decide +kernel : ¬ (63 : Basis) < (34 : Basis)) ordered))
    (Fin.cases (fun (ordered : (63 : Basis) < (35 : Basis)) => False.elim ((by decide +kernel : ¬ (63 : Basis) < (35 : Basis)) ordered))
    (Fin.cases (fun (ordered : (63 : Basis) < (36 : Basis)) => False.elim ((by decide +kernel : ¬ (63 : Basis) < (36 : Basis)) ordered))
    (Fin.cases (fun (ordered : (63 : Basis) < (37 : Basis)) => False.elim ((by decide +kernel : ¬ (63 : Basis) < (37 : Basis)) ordered))
    (Fin.cases (fun (ordered : (63 : Basis) < (38 : Basis)) => False.elim ((by decide +kernel : ¬ (63 : Basis) < (38 : Basis)) ordered))
    (Fin.cases (fun (ordered : (63 : Basis) < (39 : Basis)) => False.elim ((by decide +kernel : ¬ (63 : Basis) < (39 : Basis)) ordered))
    (Fin.cases (fun (ordered : (63 : Basis) < (40 : Basis)) => False.elim ((by decide +kernel : ¬ (63 : Basis) < (40 : Basis)) ordered))
    (Fin.cases (fun (ordered : (63 : Basis) < (41 : Basis)) => False.elim ((by decide +kernel : ¬ (63 : Basis) < (41 : Basis)) ordered))
    (Fin.cases (fun (ordered : (63 : Basis) < (42 : Basis)) => False.elim ((by decide +kernel : ¬ (63 : Basis) < (42 : Basis)) ordered))
    (Fin.cases (fun (ordered : (63 : Basis) < (43 : Basis)) => False.elim ((by decide +kernel : ¬ (63 : Basis) < (43 : Basis)) ordered))
    (Fin.cases (fun (ordered : (63 : Basis) < (44 : Basis)) => False.elim ((by decide +kernel : ¬ (63 : Basis) < (44 : Basis)) ordered))
    (Fin.cases (fun (ordered : (63 : Basis) < (45 : Basis)) => False.elim ((by decide +kernel : ¬ (63 : Basis) < (45 : Basis)) ordered))
    (Fin.cases (fun (ordered : (63 : Basis) < (46 : Basis)) => False.elim ((by decide +kernel : ¬ (63 : Basis) < (46 : Basis)) ordered))
    (Fin.cases (fun (ordered : (63 : Basis) < (47 : Basis)) => False.elim ((by decide +kernel : ¬ (63 : Basis) < (47 : Basis)) ordered))
    (Fin.cases (fun (ordered : (63 : Basis) < (48 : Basis)) => False.elim ((by decide +kernel : ¬ (63 : Basis) < (48 : Basis)) ordered))
    (Fin.cases (fun (ordered : (63 : Basis) < (49 : Basis)) => False.elim ((by decide +kernel : ¬ (63 : Basis) < (49 : Basis)) ordered))
    (Fin.cases (fun (ordered : (63 : Basis) < (50 : Basis)) => False.elim ((by decide +kernel : ¬ (63 : Basis) < (50 : Basis)) ordered))
    (Fin.cases (fun (ordered : (63 : Basis) < (51 : Basis)) => False.elim ((by decide +kernel : ¬ (63 : Basis) < (51 : Basis)) ordered))
    (Fin.cases (fun (ordered : (63 : Basis) < (52 : Basis)) => False.elim ((by decide +kernel : ¬ (63 : Basis) < (52 : Basis)) ordered))
    (Fin.cases (fun (ordered : (63 : Basis) < (53 : Basis)) => False.elim ((by decide +kernel : ¬ (63 : Basis) < (53 : Basis)) ordered))
    (Fin.cases (fun (ordered : (63 : Basis) < (54 : Basis)) => False.elim ((by decide +kernel : ¬ (63 : Basis) < (54 : Basis)) ordered))
    (Fin.cases (fun (ordered : (63 : Basis) < (55 : Basis)) => False.elim ((by decide +kernel : ¬ (63 : Basis) < (55 : Basis)) ordered))
    (Fin.cases (fun (ordered : (63 : Basis) < (56 : Basis)) => False.elim ((by decide +kernel : ¬ (63 : Basis) < (56 : Basis)) ordered))
    (Fin.cases (fun (ordered : (63 : Basis) < (57 : Basis)) => False.elim ((by decide +kernel : ¬ (63 : Basis) < (57 : Basis)) ordered))
    (Fin.cases (fun (ordered : (63 : Basis) < (58 : Basis)) => False.elim ((by decide +kernel : ¬ (63 : Basis) < (58 : Basis)) ordered))
    (Fin.cases (fun (ordered : (63 : Basis) < (59 : Basis)) => False.elim ((by decide +kernel : ¬ (63 : Basis) < (59 : Basis)) ordered))
    (Fin.cases (fun (ordered : (63 : Basis) < (60 : Basis)) => False.elim ((by decide +kernel : ¬ (63 : Basis) < (60 : Basis)) ordered))
    (Fin.cases (fun (ordered : (63 : Basis) < (61 : Basis)) => False.elim ((by decide +kernel : ¬ (63 : Basis) < (61 : Basis)) ordered))
    (Fin.cases (fun (ordered : (63 : Basis) < (62 : Basis)) => False.elim ((by decide +kernel : ¬ (63 : Basis) < (62 : Basis)) ordered))
    (Fin.cases (fun (ordered : (63 : Basis) < (63 : Basis)) => False.elim ((by decide +kernel : ¬ (63 : Basis) < (63 : Basis)) ordered))
    (Fin.cases (fun _ => ⟨⟨Factors.P259.factor13Plus,0,Factors.P259.checked13Plus⟩,⟨Factors.P259.factor13Minus,0,Factors.P259.checked13Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P259.factor14Plus,0,Factors.P259.checked14Plus⟩,⟨Factors.P259.factor14Minus,0,Factors.P259.checked14Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P259.factor15Plus,0,Factors.P259.checked15Plus⟩,⟨Factors.P259.factor15Minus,0,Factors.P259.checked15Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P260.factor0Plus,0,Factors.P260.checked0Plus⟩,⟨Factors.P260.factor0Minus,0,Factors.P260.checked0Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P260.factor1Plus,0,Factors.P260.checked1Plus⟩,⟨Factors.P260.factor1Minus,0,Factors.P260.checked1Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P260.factor2Plus,0,Factors.P260.checked2Plus⟩,⟨Factors.P260.factor2Minus,0,Factors.P260.checked2Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P260.factor3Plus,0,Factors.P260.checked3Plus⟩,⟨Factors.P260.factor3Minus,0,Factors.P260.checked3Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P260.factor4Plus,0,Factors.P260.checked4Plus⟩,⟨Factors.P260.factor4Minus,0,Factors.P260.checked4Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P260.factor5Plus,0,Factors.P260.checked5Plus⟩,⟨Factors.P260.factor5Minus,0,Factors.P260.checked5Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P260.factor6Plus,0,Factors.P260.checked6Plus⟩,⟨Factors.P260.factor6Minus,0,Factors.P260.checked6Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P260.factor7Plus,0,Factors.P260.checked7Plus⟩,⟨Factors.P260.factor7Minus,0,Factors.P260.checked7Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P260.factor8Plus,0,Factors.P260.checked8Plus⟩,⟨Factors.P260.factor8Minus,0,Factors.P260.checked8Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P260.factor9Plus,0,Factors.P260.checked9Plus⟩,⟨Factors.P260.factor9Minus,0,Factors.P260.checked9Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P260.factor10Plus,0,Factors.P260.checked10Plus⟩,⟨Factors.P260.factor10Minus,0,Factors.P260.checked10Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P260.factor11Plus,0,Factors.P260.checked11Plus⟩,⟨Factors.P260.factor11Minus,0,Factors.P260.checked11Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P260.factor12Plus,0,Factors.P260.checked12Plus⟩,⟨Factors.P260.factor12Minus,0,Factors.P260.checked12Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P260.factor13Plus,0,Factors.P260.checked13Plus⟩,⟨Factors.P260.factor13Minus,0,Factors.P260.checked13Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P260.factor14Plus,0,Factors.P260.checked14Plus⟩,⟨Factors.P260.factor14Minus,0,Factors.P260.checked14Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P260.factor15Plus,0,Factors.P260.checked15Plus⟩,⟨Factors.P260.factor15Minus,0,Factors.P260.checked15Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P261.factor0Plus,0,Factors.P261.checked0Plus⟩,⟨Factors.P261.factor0Minus,0,Factors.P261.checked0Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P261.factor1Plus,0,Factors.P261.checked1Plus⟩,⟨Factors.P261.factor1Minus,0,Factors.P261.checked1Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P261.factor2Plus,0,Factors.P261.checked2Plus⟩,⟨Factors.P261.factor2Minus,0,Factors.P261.checked2Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P261.factor3Plus,0,Factors.P261.checked3Plus⟩,⟨Factors.P261.factor3Minus,0,Factors.P261.checked3Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P261.factor4Plus,0,Factors.P261.checked4Plus⟩,⟨Factors.P261.factor4Minus,0,Factors.P261.checked4Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P261.factor5Plus,0,Factors.P261.checked5Plus⟩,⟨Factors.P261.factor5Minus,0,Factors.P261.checked5Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P261.factor6Plus,0,Factors.P261.checked6Plus⟩,⟨Factors.P261.factor6Minus,0,Factors.P261.checked6Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P261.factor7Plus,0,Factors.P261.checked7Plus⟩,⟨Factors.P261.factor7Minus,0,Factors.P261.checked7Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P261.factor8Plus,0,Factors.P261.checked8Plus⟩,⟨Factors.P261.factor8Minus,0,Factors.P261.checked8Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P261.factor9Plus,0,Factors.P261.checked9Plus⟩,⟨Factors.P261.factor9Minus,0,Factors.P261.checked9Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P261.factor10Plus,0,Factors.P261.checked10Plus⟩,⟨Factors.P261.factor10Minus,0,Factors.P261.checked10Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P261.factor11Plus,0,Factors.P261.checked11Plus⟩,⟨Factors.P261.factor11Minus,0,Factors.P261.checked11Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P261.factor12Plus,0,Factors.P261.checked12Plus⟩,⟨Factors.P261.factor12Minus,0,Factors.P261.checked12Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P261.factor13Plus,0,Factors.P261.checked13Plus⟩,⟨Factors.P261.factor13Minus,0,Factors.P261.checked13Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P261.factor14Plus,0,Factors.P261.checked14Plus⟩,⟨Factors.P261.factor14Minus,0,Factors.P261.checked14Minus⟩⟩)
    ((fun impossible => Fin.elim0 impossible)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))

end
end LAlanine40K2025.Thermal.Recovery.Reservoir.Pointer.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Rows
end SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule
