import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.OrdinaryPair
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P264
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P265

set_option autoImplicit false
namespace SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule
namespace LAlanine40K2025.Thermal.Recovery.Reservoir.Pointer.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Rows
open Propagation.Interface
noncomputable section

set_option maxHeartbeats 400000 in
def row65 : (b : Basis) → (65 : Basis) < b → OrdinaryPair 65 b :=
  Fin.cases (fun (ordered : (65 : Basis) < (0 : Basis)) => False.elim ((by decide +kernel : ¬ (65 : Basis) < (0 : Basis)) ordered))
    (Fin.cases (fun (ordered : (65 : Basis) < (1 : Basis)) => False.elim ((by decide +kernel : ¬ (65 : Basis) < (1 : Basis)) ordered))
    (Fin.cases (fun (ordered : (65 : Basis) < (2 : Basis)) => False.elim ((by decide +kernel : ¬ (65 : Basis) < (2 : Basis)) ordered))
    (Fin.cases (fun (ordered : (65 : Basis) < (3 : Basis)) => False.elim ((by decide +kernel : ¬ (65 : Basis) < (3 : Basis)) ordered))
    (Fin.cases (fun (ordered : (65 : Basis) < (4 : Basis)) => False.elim ((by decide +kernel : ¬ (65 : Basis) < (4 : Basis)) ordered))
    (Fin.cases (fun (ordered : (65 : Basis) < (5 : Basis)) => False.elim ((by decide +kernel : ¬ (65 : Basis) < (5 : Basis)) ordered))
    (Fin.cases (fun (ordered : (65 : Basis) < (6 : Basis)) => False.elim ((by decide +kernel : ¬ (65 : Basis) < (6 : Basis)) ordered))
    (Fin.cases (fun (ordered : (65 : Basis) < (7 : Basis)) => False.elim ((by decide +kernel : ¬ (65 : Basis) < (7 : Basis)) ordered))
    (Fin.cases (fun (ordered : (65 : Basis) < (8 : Basis)) => False.elim ((by decide +kernel : ¬ (65 : Basis) < (8 : Basis)) ordered))
    (Fin.cases (fun (ordered : (65 : Basis) < (9 : Basis)) => False.elim ((by decide +kernel : ¬ (65 : Basis) < (9 : Basis)) ordered))
    (Fin.cases (fun (ordered : (65 : Basis) < (10 : Basis)) => False.elim ((by decide +kernel : ¬ (65 : Basis) < (10 : Basis)) ordered))
    (Fin.cases (fun (ordered : (65 : Basis) < (11 : Basis)) => False.elim ((by decide +kernel : ¬ (65 : Basis) < (11 : Basis)) ordered))
    (Fin.cases (fun (ordered : (65 : Basis) < (12 : Basis)) => False.elim ((by decide +kernel : ¬ (65 : Basis) < (12 : Basis)) ordered))
    (Fin.cases (fun (ordered : (65 : Basis) < (13 : Basis)) => False.elim ((by decide +kernel : ¬ (65 : Basis) < (13 : Basis)) ordered))
    (Fin.cases (fun (ordered : (65 : Basis) < (14 : Basis)) => False.elim ((by decide +kernel : ¬ (65 : Basis) < (14 : Basis)) ordered))
    (Fin.cases (fun (ordered : (65 : Basis) < (15 : Basis)) => False.elim ((by decide +kernel : ¬ (65 : Basis) < (15 : Basis)) ordered))
    (Fin.cases (fun (ordered : (65 : Basis) < (16 : Basis)) => False.elim ((by decide +kernel : ¬ (65 : Basis) < (16 : Basis)) ordered))
    (Fin.cases (fun (ordered : (65 : Basis) < (17 : Basis)) => False.elim ((by decide +kernel : ¬ (65 : Basis) < (17 : Basis)) ordered))
    (Fin.cases (fun (ordered : (65 : Basis) < (18 : Basis)) => False.elim ((by decide +kernel : ¬ (65 : Basis) < (18 : Basis)) ordered))
    (Fin.cases (fun (ordered : (65 : Basis) < (19 : Basis)) => False.elim ((by decide +kernel : ¬ (65 : Basis) < (19 : Basis)) ordered))
    (Fin.cases (fun (ordered : (65 : Basis) < (20 : Basis)) => False.elim ((by decide +kernel : ¬ (65 : Basis) < (20 : Basis)) ordered))
    (Fin.cases (fun (ordered : (65 : Basis) < (21 : Basis)) => False.elim ((by decide +kernel : ¬ (65 : Basis) < (21 : Basis)) ordered))
    (Fin.cases (fun (ordered : (65 : Basis) < (22 : Basis)) => False.elim ((by decide +kernel : ¬ (65 : Basis) < (22 : Basis)) ordered))
    (Fin.cases (fun (ordered : (65 : Basis) < (23 : Basis)) => False.elim ((by decide +kernel : ¬ (65 : Basis) < (23 : Basis)) ordered))
    (Fin.cases (fun (ordered : (65 : Basis) < (24 : Basis)) => False.elim ((by decide +kernel : ¬ (65 : Basis) < (24 : Basis)) ordered))
    (Fin.cases (fun (ordered : (65 : Basis) < (25 : Basis)) => False.elim ((by decide +kernel : ¬ (65 : Basis) < (25 : Basis)) ordered))
    (Fin.cases (fun (ordered : (65 : Basis) < (26 : Basis)) => False.elim ((by decide +kernel : ¬ (65 : Basis) < (26 : Basis)) ordered))
    (Fin.cases (fun (ordered : (65 : Basis) < (27 : Basis)) => False.elim ((by decide +kernel : ¬ (65 : Basis) < (27 : Basis)) ordered))
    (Fin.cases (fun (ordered : (65 : Basis) < (28 : Basis)) => False.elim ((by decide +kernel : ¬ (65 : Basis) < (28 : Basis)) ordered))
    (Fin.cases (fun (ordered : (65 : Basis) < (29 : Basis)) => False.elim ((by decide +kernel : ¬ (65 : Basis) < (29 : Basis)) ordered))
    (Fin.cases (fun (ordered : (65 : Basis) < (30 : Basis)) => False.elim ((by decide +kernel : ¬ (65 : Basis) < (30 : Basis)) ordered))
    (Fin.cases (fun (ordered : (65 : Basis) < (31 : Basis)) => False.elim ((by decide +kernel : ¬ (65 : Basis) < (31 : Basis)) ordered))
    (Fin.cases (fun (ordered : (65 : Basis) < (32 : Basis)) => False.elim ((by decide +kernel : ¬ (65 : Basis) < (32 : Basis)) ordered))
    (Fin.cases (fun (ordered : (65 : Basis) < (33 : Basis)) => False.elim ((by decide +kernel : ¬ (65 : Basis) < (33 : Basis)) ordered))
    (Fin.cases (fun (ordered : (65 : Basis) < (34 : Basis)) => False.elim ((by decide +kernel : ¬ (65 : Basis) < (34 : Basis)) ordered))
    (Fin.cases (fun (ordered : (65 : Basis) < (35 : Basis)) => False.elim ((by decide +kernel : ¬ (65 : Basis) < (35 : Basis)) ordered))
    (Fin.cases (fun (ordered : (65 : Basis) < (36 : Basis)) => False.elim ((by decide +kernel : ¬ (65 : Basis) < (36 : Basis)) ordered))
    (Fin.cases (fun (ordered : (65 : Basis) < (37 : Basis)) => False.elim ((by decide +kernel : ¬ (65 : Basis) < (37 : Basis)) ordered))
    (Fin.cases (fun (ordered : (65 : Basis) < (38 : Basis)) => False.elim ((by decide +kernel : ¬ (65 : Basis) < (38 : Basis)) ordered))
    (Fin.cases (fun (ordered : (65 : Basis) < (39 : Basis)) => False.elim ((by decide +kernel : ¬ (65 : Basis) < (39 : Basis)) ordered))
    (Fin.cases (fun (ordered : (65 : Basis) < (40 : Basis)) => False.elim ((by decide +kernel : ¬ (65 : Basis) < (40 : Basis)) ordered))
    (Fin.cases (fun (ordered : (65 : Basis) < (41 : Basis)) => False.elim ((by decide +kernel : ¬ (65 : Basis) < (41 : Basis)) ordered))
    (Fin.cases (fun (ordered : (65 : Basis) < (42 : Basis)) => False.elim ((by decide +kernel : ¬ (65 : Basis) < (42 : Basis)) ordered))
    (Fin.cases (fun (ordered : (65 : Basis) < (43 : Basis)) => False.elim ((by decide +kernel : ¬ (65 : Basis) < (43 : Basis)) ordered))
    (Fin.cases (fun (ordered : (65 : Basis) < (44 : Basis)) => False.elim ((by decide +kernel : ¬ (65 : Basis) < (44 : Basis)) ordered))
    (Fin.cases (fun (ordered : (65 : Basis) < (45 : Basis)) => False.elim ((by decide +kernel : ¬ (65 : Basis) < (45 : Basis)) ordered))
    (Fin.cases (fun (ordered : (65 : Basis) < (46 : Basis)) => False.elim ((by decide +kernel : ¬ (65 : Basis) < (46 : Basis)) ordered))
    (Fin.cases (fun (ordered : (65 : Basis) < (47 : Basis)) => False.elim ((by decide +kernel : ¬ (65 : Basis) < (47 : Basis)) ordered))
    (Fin.cases (fun (ordered : (65 : Basis) < (48 : Basis)) => False.elim ((by decide +kernel : ¬ (65 : Basis) < (48 : Basis)) ordered))
    (Fin.cases (fun (ordered : (65 : Basis) < (49 : Basis)) => False.elim ((by decide +kernel : ¬ (65 : Basis) < (49 : Basis)) ordered))
    (Fin.cases (fun (ordered : (65 : Basis) < (50 : Basis)) => False.elim ((by decide +kernel : ¬ (65 : Basis) < (50 : Basis)) ordered))
    (Fin.cases (fun (ordered : (65 : Basis) < (51 : Basis)) => False.elim ((by decide +kernel : ¬ (65 : Basis) < (51 : Basis)) ordered))
    (Fin.cases (fun (ordered : (65 : Basis) < (52 : Basis)) => False.elim ((by decide +kernel : ¬ (65 : Basis) < (52 : Basis)) ordered))
    (Fin.cases (fun (ordered : (65 : Basis) < (53 : Basis)) => False.elim ((by decide +kernel : ¬ (65 : Basis) < (53 : Basis)) ordered))
    (Fin.cases (fun (ordered : (65 : Basis) < (54 : Basis)) => False.elim ((by decide +kernel : ¬ (65 : Basis) < (54 : Basis)) ordered))
    (Fin.cases (fun (ordered : (65 : Basis) < (55 : Basis)) => False.elim ((by decide +kernel : ¬ (65 : Basis) < (55 : Basis)) ordered))
    (Fin.cases (fun (ordered : (65 : Basis) < (56 : Basis)) => False.elim ((by decide +kernel : ¬ (65 : Basis) < (56 : Basis)) ordered))
    (Fin.cases (fun (ordered : (65 : Basis) < (57 : Basis)) => False.elim ((by decide +kernel : ¬ (65 : Basis) < (57 : Basis)) ordered))
    (Fin.cases (fun (ordered : (65 : Basis) < (58 : Basis)) => False.elim ((by decide +kernel : ¬ (65 : Basis) < (58 : Basis)) ordered))
    (Fin.cases (fun (ordered : (65 : Basis) < (59 : Basis)) => False.elim ((by decide +kernel : ¬ (65 : Basis) < (59 : Basis)) ordered))
    (Fin.cases (fun (ordered : (65 : Basis) < (60 : Basis)) => False.elim ((by decide +kernel : ¬ (65 : Basis) < (60 : Basis)) ordered))
    (Fin.cases (fun (ordered : (65 : Basis) < (61 : Basis)) => False.elim ((by decide +kernel : ¬ (65 : Basis) < (61 : Basis)) ordered))
    (Fin.cases (fun (ordered : (65 : Basis) < (62 : Basis)) => False.elim ((by decide +kernel : ¬ (65 : Basis) < (62 : Basis)) ordered))
    (Fin.cases (fun (ordered : (65 : Basis) < (63 : Basis)) => False.elim ((by decide +kernel : ¬ (65 : Basis) < (63 : Basis)) ordered))
    (Fin.cases (fun (ordered : (65 : Basis) < (64 : Basis)) => False.elim ((by decide +kernel : ¬ (65 : Basis) < (64 : Basis)) ordered))
    (Fin.cases (fun (ordered : (65 : Basis) < (65 : Basis)) => False.elim ((by decide +kernel : ¬ (65 : Basis) < (65 : Basis)) ordered))
    (Fin.cases (fun _ => ⟨⟨Factors.P264.factor0Plus,0,Factors.P264.checked0Plus⟩,⟨Factors.P264.factor0Minus,0,Factors.P264.checked0Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P264.factor1Plus,0,Factors.P264.checked1Plus⟩,⟨Factors.P264.factor1Minus,0,Factors.P264.checked1Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P264.factor2Plus,0,Factors.P264.checked2Plus⟩,⟨Factors.P264.factor2Minus,0,Factors.P264.checked2Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P264.factor3Plus,0,Factors.P264.checked3Plus⟩,⟨Factors.P264.factor3Minus,0,Factors.P264.checked3Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P264.factor4Plus,0,Factors.P264.checked4Plus⟩,⟨Factors.P264.factor4Minus,0,Factors.P264.checked4Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P264.factor5Plus,0,Factors.P264.checked5Plus⟩,⟨Factors.P264.factor5Minus,0,Factors.P264.checked5Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P264.factor6Plus,0,Factors.P264.checked6Plus⟩,⟨Factors.P264.factor6Minus,0,Factors.P264.checked6Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P264.factor7Plus,0,Factors.P264.checked7Plus⟩,⟨Factors.P264.factor7Minus,0,Factors.P264.checked7Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P264.factor8Plus,0,Factors.P264.checked8Plus⟩,⟨Factors.P264.factor8Minus,0,Factors.P264.checked8Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P264.factor9Plus,0,Factors.P264.checked9Plus⟩,⟨Factors.P264.factor9Minus,0,Factors.P264.checked9Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P264.factor10Plus,0,Factors.P264.checked10Plus⟩,⟨Factors.P264.factor10Minus,0,Factors.P264.checked10Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P264.factor11Plus,0,Factors.P264.checked11Plus⟩,⟨Factors.P264.factor11Minus,0,Factors.P264.checked11Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P264.factor12Plus,0,Factors.P264.checked12Plus⟩,⟨Factors.P264.factor12Minus,0,Factors.P264.checked12Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P264.factor13Plus,0,Factors.P264.checked13Plus⟩,⟨Factors.P264.factor13Minus,0,Factors.P264.checked13Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P264.factor14Plus,0,Factors.P264.checked14Plus⟩,⟨Factors.P264.factor14Minus,0,Factors.P264.checked14Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P264.factor15Plus,0,Factors.P264.checked15Plus⟩,⟨Factors.P264.factor15Minus,0,Factors.P264.checked15Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P265.factor0Plus,0,Factors.P265.checked0Plus⟩,⟨Factors.P265.factor0Minus,0,Factors.P265.checked0Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P265.factor1Plus,0,Factors.P265.checked1Plus⟩,⟨Factors.P265.factor1Minus,0,Factors.P265.checked1Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P265.factor2Plus,0,Factors.P265.checked2Plus⟩,⟨Factors.P265.factor2Minus,0,Factors.P265.checked2Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P265.factor3Plus,0,Factors.P265.checked3Plus⟩,⟨Factors.P265.factor3Minus,0,Factors.P265.checked3Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P265.factor4Plus,0,Factors.P265.checked4Plus⟩,⟨Factors.P265.factor4Minus,0,Factors.P265.checked4Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P265.factor5Plus,0,Factors.P265.checked5Plus⟩,⟨Factors.P265.factor5Minus,0,Factors.P265.checked5Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P265.factor6Plus,0,Factors.P265.checked6Plus⟩,⟨Factors.P265.factor6Minus,0,Factors.P265.checked6Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P265.factor7Plus,0,Factors.P265.checked7Plus⟩,⟨Factors.P265.factor7Minus,0,Factors.P265.checked7Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P265.factor8Plus,0,Factors.P265.checked8Plus⟩,⟨Factors.P265.factor8Minus,0,Factors.P265.checked8Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P265.factor9Plus,0,Factors.P265.checked9Plus⟩,⟨Factors.P265.factor9Minus,0,Factors.P265.checked9Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P265.factor10Plus,0,Factors.P265.checked10Plus⟩,⟨Factors.P265.factor10Minus,0,Factors.P265.checked10Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P265.factor11Plus,0,Factors.P265.checked11Plus⟩,⟨Factors.P265.factor11Minus,0,Factors.P265.checked11Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P265.factor12Plus,0,Factors.P265.checked12Plus⟩,⟨Factors.P265.factor12Minus,0,Factors.P265.checked12Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P265.factor13Plus,0,Factors.P265.checked13Plus⟩,⟨Factors.P265.factor13Minus,0,Factors.P265.checked13Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P265.factor14Plus,0,Factors.P265.checked14Plus⟩,⟨Factors.P265.factor14Minus,0,Factors.P265.checked14Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P265.factor15Plus,0,Factors.P265.checked15Plus⟩,⟨Factors.P265.factor15Minus,0,Factors.P265.checked15Minus⟩⟩)
    ((fun impossible => Fin.elim0 impossible)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))

end
end LAlanine40K2025.Thermal.Recovery.Reservoir.Pointer.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Rows
end SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule
