import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.OrdinaryPair
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P266
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P267

set_option autoImplicit false
namespace SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule
namespace LAlanine40K2025.Thermal.Recovery.Reservoir.Pointer.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Rows
open Propagation.Interface
noncomputable section

set_option maxHeartbeats 400000 in
def row66 : (b : Basis) → (66 : Basis) < b → OrdinaryPair 66 b :=
  Fin.cases (fun (ordered : (66 : Basis) < (0 : Basis)) => False.elim ((by decide +kernel : ¬ (66 : Basis) < (0 : Basis)) ordered))
    (Fin.cases (fun (ordered : (66 : Basis) < (1 : Basis)) => False.elim ((by decide +kernel : ¬ (66 : Basis) < (1 : Basis)) ordered))
    (Fin.cases (fun (ordered : (66 : Basis) < (2 : Basis)) => False.elim ((by decide +kernel : ¬ (66 : Basis) < (2 : Basis)) ordered))
    (Fin.cases (fun (ordered : (66 : Basis) < (3 : Basis)) => False.elim ((by decide +kernel : ¬ (66 : Basis) < (3 : Basis)) ordered))
    (Fin.cases (fun (ordered : (66 : Basis) < (4 : Basis)) => False.elim ((by decide +kernel : ¬ (66 : Basis) < (4 : Basis)) ordered))
    (Fin.cases (fun (ordered : (66 : Basis) < (5 : Basis)) => False.elim ((by decide +kernel : ¬ (66 : Basis) < (5 : Basis)) ordered))
    (Fin.cases (fun (ordered : (66 : Basis) < (6 : Basis)) => False.elim ((by decide +kernel : ¬ (66 : Basis) < (6 : Basis)) ordered))
    (Fin.cases (fun (ordered : (66 : Basis) < (7 : Basis)) => False.elim ((by decide +kernel : ¬ (66 : Basis) < (7 : Basis)) ordered))
    (Fin.cases (fun (ordered : (66 : Basis) < (8 : Basis)) => False.elim ((by decide +kernel : ¬ (66 : Basis) < (8 : Basis)) ordered))
    (Fin.cases (fun (ordered : (66 : Basis) < (9 : Basis)) => False.elim ((by decide +kernel : ¬ (66 : Basis) < (9 : Basis)) ordered))
    (Fin.cases (fun (ordered : (66 : Basis) < (10 : Basis)) => False.elim ((by decide +kernel : ¬ (66 : Basis) < (10 : Basis)) ordered))
    (Fin.cases (fun (ordered : (66 : Basis) < (11 : Basis)) => False.elim ((by decide +kernel : ¬ (66 : Basis) < (11 : Basis)) ordered))
    (Fin.cases (fun (ordered : (66 : Basis) < (12 : Basis)) => False.elim ((by decide +kernel : ¬ (66 : Basis) < (12 : Basis)) ordered))
    (Fin.cases (fun (ordered : (66 : Basis) < (13 : Basis)) => False.elim ((by decide +kernel : ¬ (66 : Basis) < (13 : Basis)) ordered))
    (Fin.cases (fun (ordered : (66 : Basis) < (14 : Basis)) => False.elim ((by decide +kernel : ¬ (66 : Basis) < (14 : Basis)) ordered))
    (Fin.cases (fun (ordered : (66 : Basis) < (15 : Basis)) => False.elim ((by decide +kernel : ¬ (66 : Basis) < (15 : Basis)) ordered))
    (Fin.cases (fun (ordered : (66 : Basis) < (16 : Basis)) => False.elim ((by decide +kernel : ¬ (66 : Basis) < (16 : Basis)) ordered))
    (Fin.cases (fun (ordered : (66 : Basis) < (17 : Basis)) => False.elim ((by decide +kernel : ¬ (66 : Basis) < (17 : Basis)) ordered))
    (Fin.cases (fun (ordered : (66 : Basis) < (18 : Basis)) => False.elim ((by decide +kernel : ¬ (66 : Basis) < (18 : Basis)) ordered))
    (Fin.cases (fun (ordered : (66 : Basis) < (19 : Basis)) => False.elim ((by decide +kernel : ¬ (66 : Basis) < (19 : Basis)) ordered))
    (Fin.cases (fun (ordered : (66 : Basis) < (20 : Basis)) => False.elim ((by decide +kernel : ¬ (66 : Basis) < (20 : Basis)) ordered))
    (Fin.cases (fun (ordered : (66 : Basis) < (21 : Basis)) => False.elim ((by decide +kernel : ¬ (66 : Basis) < (21 : Basis)) ordered))
    (Fin.cases (fun (ordered : (66 : Basis) < (22 : Basis)) => False.elim ((by decide +kernel : ¬ (66 : Basis) < (22 : Basis)) ordered))
    (Fin.cases (fun (ordered : (66 : Basis) < (23 : Basis)) => False.elim ((by decide +kernel : ¬ (66 : Basis) < (23 : Basis)) ordered))
    (Fin.cases (fun (ordered : (66 : Basis) < (24 : Basis)) => False.elim ((by decide +kernel : ¬ (66 : Basis) < (24 : Basis)) ordered))
    (Fin.cases (fun (ordered : (66 : Basis) < (25 : Basis)) => False.elim ((by decide +kernel : ¬ (66 : Basis) < (25 : Basis)) ordered))
    (Fin.cases (fun (ordered : (66 : Basis) < (26 : Basis)) => False.elim ((by decide +kernel : ¬ (66 : Basis) < (26 : Basis)) ordered))
    (Fin.cases (fun (ordered : (66 : Basis) < (27 : Basis)) => False.elim ((by decide +kernel : ¬ (66 : Basis) < (27 : Basis)) ordered))
    (Fin.cases (fun (ordered : (66 : Basis) < (28 : Basis)) => False.elim ((by decide +kernel : ¬ (66 : Basis) < (28 : Basis)) ordered))
    (Fin.cases (fun (ordered : (66 : Basis) < (29 : Basis)) => False.elim ((by decide +kernel : ¬ (66 : Basis) < (29 : Basis)) ordered))
    (Fin.cases (fun (ordered : (66 : Basis) < (30 : Basis)) => False.elim ((by decide +kernel : ¬ (66 : Basis) < (30 : Basis)) ordered))
    (Fin.cases (fun (ordered : (66 : Basis) < (31 : Basis)) => False.elim ((by decide +kernel : ¬ (66 : Basis) < (31 : Basis)) ordered))
    (Fin.cases (fun (ordered : (66 : Basis) < (32 : Basis)) => False.elim ((by decide +kernel : ¬ (66 : Basis) < (32 : Basis)) ordered))
    (Fin.cases (fun (ordered : (66 : Basis) < (33 : Basis)) => False.elim ((by decide +kernel : ¬ (66 : Basis) < (33 : Basis)) ordered))
    (Fin.cases (fun (ordered : (66 : Basis) < (34 : Basis)) => False.elim ((by decide +kernel : ¬ (66 : Basis) < (34 : Basis)) ordered))
    (Fin.cases (fun (ordered : (66 : Basis) < (35 : Basis)) => False.elim ((by decide +kernel : ¬ (66 : Basis) < (35 : Basis)) ordered))
    (Fin.cases (fun (ordered : (66 : Basis) < (36 : Basis)) => False.elim ((by decide +kernel : ¬ (66 : Basis) < (36 : Basis)) ordered))
    (Fin.cases (fun (ordered : (66 : Basis) < (37 : Basis)) => False.elim ((by decide +kernel : ¬ (66 : Basis) < (37 : Basis)) ordered))
    (Fin.cases (fun (ordered : (66 : Basis) < (38 : Basis)) => False.elim ((by decide +kernel : ¬ (66 : Basis) < (38 : Basis)) ordered))
    (Fin.cases (fun (ordered : (66 : Basis) < (39 : Basis)) => False.elim ((by decide +kernel : ¬ (66 : Basis) < (39 : Basis)) ordered))
    (Fin.cases (fun (ordered : (66 : Basis) < (40 : Basis)) => False.elim ((by decide +kernel : ¬ (66 : Basis) < (40 : Basis)) ordered))
    (Fin.cases (fun (ordered : (66 : Basis) < (41 : Basis)) => False.elim ((by decide +kernel : ¬ (66 : Basis) < (41 : Basis)) ordered))
    (Fin.cases (fun (ordered : (66 : Basis) < (42 : Basis)) => False.elim ((by decide +kernel : ¬ (66 : Basis) < (42 : Basis)) ordered))
    (Fin.cases (fun (ordered : (66 : Basis) < (43 : Basis)) => False.elim ((by decide +kernel : ¬ (66 : Basis) < (43 : Basis)) ordered))
    (Fin.cases (fun (ordered : (66 : Basis) < (44 : Basis)) => False.elim ((by decide +kernel : ¬ (66 : Basis) < (44 : Basis)) ordered))
    (Fin.cases (fun (ordered : (66 : Basis) < (45 : Basis)) => False.elim ((by decide +kernel : ¬ (66 : Basis) < (45 : Basis)) ordered))
    (Fin.cases (fun (ordered : (66 : Basis) < (46 : Basis)) => False.elim ((by decide +kernel : ¬ (66 : Basis) < (46 : Basis)) ordered))
    (Fin.cases (fun (ordered : (66 : Basis) < (47 : Basis)) => False.elim ((by decide +kernel : ¬ (66 : Basis) < (47 : Basis)) ordered))
    (Fin.cases (fun (ordered : (66 : Basis) < (48 : Basis)) => False.elim ((by decide +kernel : ¬ (66 : Basis) < (48 : Basis)) ordered))
    (Fin.cases (fun (ordered : (66 : Basis) < (49 : Basis)) => False.elim ((by decide +kernel : ¬ (66 : Basis) < (49 : Basis)) ordered))
    (Fin.cases (fun (ordered : (66 : Basis) < (50 : Basis)) => False.elim ((by decide +kernel : ¬ (66 : Basis) < (50 : Basis)) ordered))
    (Fin.cases (fun (ordered : (66 : Basis) < (51 : Basis)) => False.elim ((by decide +kernel : ¬ (66 : Basis) < (51 : Basis)) ordered))
    (Fin.cases (fun (ordered : (66 : Basis) < (52 : Basis)) => False.elim ((by decide +kernel : ¬ (66 : Basis) < (52 : Basis)) ordered))
    (Fin.cases (fun (ordered : (66 : Basis) < (53 : Basis)) => False.elim ((by decide +kernel : ¬ (66 : Basis) < (53 : Basis)) ordered))
    (Fin.cases (fun (ordered : (66 : Basis) < (54 : Basis)) => False.elim ((by decide +kernel : ¬ (66 : Basis) < (54 : Basis)) ordered))
    (Fin.cases (fun (ordered : (66 : Basis) < (55 : Basis)) => False.elim ((by decide +kernel : ¬ (66 : Basis) < (55 : Basis)) ordered))
    (Fin.cases (fun (ordered : (66 : Basis) < (56 : Basis)) => False.elim ((by decide +kernel : ¬ (66 : Basis) < (56 : Basis)) ordered))
    (Fin.cases (fun (ordered : (66 : Basis) < (57 : Basis)) => False.elim ((by decide +kernel : ¬ (66 : Basis) < (57 : Basis)) ordered))
    (Fin.cases (fun (ordered : (66 : Basis) < (58 : Basis)) => False.elim ((by decide +kernel : ¬ (66 : Basis) < (58 : Basis)) ordered))
    (Fin.cases (fun (ordered : (66 : Basis) < (59 : Basis)) => False.elim ((by decide +kernel : ¬ (66 : Basis) < (59 : Basis)) ordered))
    (Fin.cases (fun (ordered : (66 : Basis) < (60 : Basis)) => False.elim ((by decide +kernel : ¬ (66 : Basis) < (60 : Basis)) ordered))
    (Fin.cases (fun (ordered : (66 : Basis) < (61 : Basis)) => False.elim ((by decide +kernel : ¬ (66 : Basis) < (61 : Basis)) ordered))
    (Fin.cases (fun (ordered : (66 : Basis) < (62 : Basis)) => False.elim ((by decide +kernel : ¬ (66 : Basis) < (62 : Basis)) ordered))
    (Fin.cases (fun (ordered : (66 : Basis) < (63 : Basis)) => False.elim ((by decide +kernel : ¬ (66 : Basis) < (63 : Basis)) ordered))
    (Fin.cases (fun (ordered : (66 : Basis) < (64 : Basis)) => False.elim ((by decide +kernel : ¬ (66 : Basis) < (64 : Basis)) ordered))
    (Fin.cases (fun (ordered : (66 : Basis) < (65 : Basis)) => False.elim ((by decide +kernel : ¬ (66 : Basis) < (65 : Basis)) ordered))
    (Fin.cases (fun (ordered : (66 : Basis) < (66 : Basis)) => False.elim ((by decide +kernel : ¬ (66 : Basis) < (66 : Basis)) ordered))
    (Fin.cases (fun _ => ⟨⟨Factors.P266.factor0Plus,0,Factors.P266.checked0Plus⟩,⟨Factors.P266.factor0Minus,0,Factors.P266.checked0Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P266.factor1Plus,0,Factors.P266.checked1Plus⟩,⟨Factors.P266.factor1Minus,0,Factors.P266.checked1Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P266.factor2Plus,0,Factors.P266.checked2Plus⟩,⟨Factors.P266.factor2Minus,0,Factors.P266.checked2Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P266.factor3Plus,0,Factors.P266.checked3Plus⟩,⟨Factors.P266.factor3Minus,0,Factors.P266.checked3Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P266.factor4Plus,0,Factors.P266.checked4Plus⟩,⟨Factors.P266.factor4Minus,0,Factors.P266.checked4Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P266.factor5Plus,0,Factors.P266.checked5Plus⟩,⟨Factors.P266.factor5Minus,0,Factors.P266.checked5Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P266.factor6Plus,0,Factors.P266.checked6Plus⟩,⟨Factors.P266.factor6Minus,0,Factors.P266.checked6Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P266.factor7Plus,0,Factors.P266.checked7Plus⟩,⟨Factors.P266.factor7Minus,0,Factors.P266.checked7Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P266.factor8Plus,0,Factors.P266.checked8Plus⟩,⟨Factors.P266.factor8Minus,0,Factors.P266.checked8Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P266.factor9Plus,0,Factors.P266.checked9Plus⟩,⟨Factors.P266.factor9Minus,0,Factors.P266.checked9Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P266.factor10Plus,0,Factors.P266.checked10Plus⟩,⟨Factors.P266.factor10Minus,0,Factors.P266.checked10Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P266.factor11Plus,0,Factors.P266.checked11Plus⟩,⟨Factors.P266.factor11Minus,0,Factors.P266.checked11Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P266.factor12Plus,0,Factors.P266.checked12Plus⟩,⟨Factors.P266.factor12Minus,0,Factors.P266.checked12Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P266.factor13Plus,0,Factors.P266.checked13Plus⟩,⟨Factors.P266.factor13Minus,0,Factors.P266.checked13Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P266.factor14Plus,0,Factors.P266.checked14Plus⟩,⟨Factors.P266.factor14Minus,0,Factors.P266.checked14Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P266.factor15Plus,0,Factors.P266.checked15Plus⟩,⟨Factors.P266.factor15Minus,0,Factors.P266.checked15Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P267.factor0Plus,0,Factors.P267.checked0Plus⟩,⟨Factors.P267.factor0Minus,0,Factors.P267.checked0Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P267.factor1Plus,0,Factors.P267.checked1Plus⟩,⟨Factors.P267.factor1Minus,0,Factors.P267.checked1Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P267.factor2Plus,0,Factors.P267.checked2Plus⟩,⟨Factors.P267.factor2Minus,0,Factors.P267.checked2Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P267.factor3Plus,0,Factors.P267.checked3Plus⟩,⟨Factors.P267.factor3Minus,0,Factors.P267.checked3Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P267.factor4Plus,0,Factors.P267.checked4Plus⟩,⟨Factors.P267.factor4Minus,0,Factors.P267.checked4Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P267.factor5Plus,0,Factors.P267.checked5Plus⟩,⟨Factors.P267.factor5Minus,0,Factors.P267.checked5Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P267.factor6Plus,0,Factors.P267.checked6Plus⟩,⟨Factors.P267.factor6Minus,0,Factors.P267.checked6Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P267.factor7Plus,0,Factors.P267.checked7Plus⟩,⟨Factors.P267.factor7Minus,0,Factors.P267.checked7Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P267.factor8Plus,0,Factors.P267.checked8Plus⟩,⟨Factors.P267.factor8Minus,0,Factors.P267.checked8Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P267.factor9Plus,0,Factors.P267.checked9Plus⟩,⟨Factors.P267.factor9Minus,0,Factors.P267.checked9Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P267.factor10Plus,0,Factors.P267.checked10Plus⟩,⟨Factors.P267.factor10Minus,0,Factors.P267.checked10Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P267.factor11Plus,0,Factors.P267.checked11Plus⟩,⟨Factors.P267.factor11Minus,0,Factors.P267.checked11Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P267.factor12Plus,0,Factors.P267.checked12Plus⟩,⟨Factors.P267.factor12Minus,0,Factors.P267.checked12Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P267.factor13Plus,0,Factors.P267.checked13Plus⟩,⟨Factors.P267.factor13Minus,0,Factors.P267.checked13Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P267.factor14Plus,0,Factors.P267.checked14Plus⟩,⟨Factors.P267.factor14Minus,0,Factors.P267.checked14Minus⟩⟩)
    ((fun impossible => Fin.elim0 impossible)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))

end
end LAlanine40K2025.Thermal.Recovery.Reservoir.Pointer.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Rows
end SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule
