import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.OrdinaryPair
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P289
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P290

set_option autoImplicit false
namespace SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule
namespace LAlanine40K2025.Thermal.Recovery.Reservoir.Pointer.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Rows
open Propagation.Interface
noncomputable section

set_option maxHeartbeats 400000 in
def row82 : (b : Basis) → (82 : Basis) < b → OrdinaryPair 82 b :=
  Fin.cases (fun (ordered : (82 : Basis) < (0 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (0 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (1 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (1 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (2 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (2 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (3 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (3 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (4 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (4 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (5 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (5 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (6 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (6 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (7 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (7 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (8 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (8 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (9 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (9 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (10 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (10 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (11 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (11 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (12 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (12 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (13 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (13 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (14 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (14 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (15 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (15 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (16 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (16 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (17 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (17 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (18 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (18 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (19 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (19 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (20 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (20 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (21 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (21 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (22 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (22 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (23 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (23 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (24 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (24 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (25 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (25 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (26 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (26 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (27 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (27 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (28 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (28 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (29 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (29 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (30 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (30 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (31 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (31 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (32 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (32 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (33 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (33 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (34 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (34 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (35 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (35 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (36 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (36 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (37 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (37 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (38 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (38 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (39 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (39 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (40 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (40 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (41 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (41 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (42 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (42 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (43 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (43 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (44 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (44 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (45 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (45 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (46 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (46 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (47 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (47 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (48 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (48 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (49 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (49 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (50 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (50 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (51 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (51 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (52 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (52 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (53 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (53 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (54 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (54 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (55 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (55 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (56 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (56 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (57 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (57 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (58 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (58 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (59 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (59 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (60 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (60 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (61 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (61 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (62 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (62 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (63 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (63 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (64 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (64 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (65 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (65 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (66 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (66 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (67 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (67 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (68 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (68 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (69 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (69 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (70 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (70 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (71 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (71 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (72 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (72 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (73 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (73 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (74 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (74 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (75 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (75 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (76 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (76 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (77 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (77 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (78 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (78 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (79 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (79 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (80 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (80 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (81 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (81 : Basis)) ordered))
    (Fin.cases (fun (ordered : (82 : Basis) < (82 : Basis)) => False.elim ((by decide +kernel : ¬ (82 : Basis) < (82 : Basis)) ordered))
    (Fin.cases (fun _ => ⟨⟨Factors.P289.factor8Plus,0,Factors.P289.checked8Plus⟩,⟨Factors.P289.factor8Minus,0,Factors.P289.checked8Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P289.factor9Plus,0,Factors.P289.checked9Plus⟩,⟨Factors.P289.factor9Minus,0,Factors.P289.checked9Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P289.factor10Plus,0,Factors.P289.checked10Plus⟩,⟨Factors.P289.factor10Minus,0,Factors.P289.checked10Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P289.factor11Plus,0,Factors.P289.checked11Plus⟩,⟨Factors.P289.factor11Minus,0,Factors.P289.checked11Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P289.factor12Plus,0,Factors.P289.checked12Plus⟩,⟨Factors.P289.factor12Minus,0,Factors.P289.checked12Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P289.factor13Plus,0,Factors.P289.checked13Plus⟩,⟨Factors.P289.factor13Minus,0,Factors.P289.checked13Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P289.factor14Plus,0,Factors.P289.checked14Plus⟩,⟨Factors.P289.factor14Minus,0,Factors.P289.checked14Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P289.factor15Plus,0,Factors.P289.checked15Plus⟩,⟨Factors.P289.factor15Minus,0,Factors.P289.checked15Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P290.factor0Plus,0,Factors.P290.checked0Plus⟩,⟨Factors.P290.factor0Minus,0,Factors.P290.checked0Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P290.factor1Plus,0,Factors.P290.checked1Plus⟩,⟨Factors.P290.factor1Minus,0,Factors.P290.checked1Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P290.factor2Plus,0,Factors.P290.checked2Plus⟩,⟨Factors.P290.factor2Minus,0,Factors.P290.checked2Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P290.factor3Plus,0,Factors.P290.checked3Plus⟩,⟨Factors.P290.factor3Minus,0,Factors.P290.checked3Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P290.factor4Plus,0,Factors.P290.checked4Plus⟩,⟨Factors.P290.factor4Minus,0,Factors.P290.checked4Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P290.factor5Plus,0,Factors.P290.checked5Plus⟩,⟨Factors.P290.factor5Minus,0,Factors.P290.checked5Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P290.factor6Plus,0,Factors.P290.checked6Plus⟩,⟨Factors.P290.factor6Minus,0,Factors.P290.checked6Minus⟩⟩)
    ((fun impossible => Fin.elim0 impossible)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))

end
end LAlanine40K2025.Thermal.Recovery.Reservoir.Pointer.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Rows
end SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule
