import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.OrdinaryPair
import H0mework.Versions.R9c73a630.ReleaseMaterials.SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.Thermal.Recovery.Reservoir.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Factors.P296

set_option autoImplicit false
namespace SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule
namespace LAlanine40K2025.Thermal.Recovery.Reservoir.Pointer.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Rows
open Propagation.Interface
noncomputable section

set_option maxHeartbeats 400000 in
def row94 : (b : Basis) → (94 : Basis) < b → OrdinaryPair 94 b :=
  Fin.cases (fun (ordered : (94 : Basis) < (0 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (0 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (1 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (1 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (2 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (2 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (3 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (3 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (4 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (4 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (5 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (5 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (6 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (6 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (7 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (7 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (8 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (8 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (9 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (9 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (10 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (10 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (11 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (11 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (12 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (12 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (13 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (13 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (14 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (14 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (15 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (15 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (16 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (16 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (17 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (17 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (18 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (18 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (19 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (19 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (20 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (20 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (21 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (21 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (22 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (22 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (23 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (23 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (24 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (24 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (25 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (25 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (26 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (26 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (27 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (27 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (28 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (28 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (29 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (29 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (30 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (30 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (31 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (31 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (32 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (32 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (33 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (33 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (34 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (34 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (35 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (35 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (36 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (36 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (37 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (37 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (38 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (38 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (39 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (39 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (40 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (40 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (41 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (41 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (42 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (42 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (43 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (43 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (44 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (44 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (45 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (45 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (46 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (46 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (47 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (47 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (48 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (48 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (49 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (49 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (50 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (50 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (51 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (51 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (52 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (52 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (53 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (53 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (54 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (54 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (55 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (55 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (56 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (56 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (57 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (57 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (58 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (58 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (59 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (59 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (60 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (60 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (61 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (61 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (62 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (62 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (63 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (63 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (64 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (64 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (65 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (65 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (66 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (66 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (67 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (67 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (68 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (68 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (69 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (69 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (70 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (70 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (71 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (71 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (72 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (72 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (73 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (73 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (74 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (74 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (75 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (75 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (76 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (76 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (77 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (77 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (78 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (78 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (79 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (79 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (80 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (80 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (81 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (81 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (82 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (82 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (83 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (83 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (84 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (84 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (85 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (85 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (86 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (86 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (87 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (87 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (88 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (88 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (89 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (89 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (90 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (90 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (91 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (91 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (92 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (92 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (93 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (93 : Basis)) ordered))
    (Fin.cases (fun (ordered : (94 : Basis) < (94 : Basis)) => False.elim ((by decide +kernel : ¬ (94 : Basis) < (94 : Basis)) ordered))
    (Fin.cases (fun _ => ⟨⟨Factors.P296.factor10Plus,0,Factors.P296.checked10Plus⟩,⟨Factors.P296.factor10Minus,0,Factors.P296.checked10Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P296.factor11Plus,0,Factors.P296.checked11Plus⟩,⟨Factors.P296.factor11Minus,0,Factors.P296.checked11Minus⟩⟩)
    (Fin.cases (fun _ => ⟨⟨Factors.P296.factor12Plus,0,Factors.P296.checked12Plus⟩,⟨Factors.P296.factor12Minus,0,Factors.P296.checked12Minus⟩⟩)
    ((fun impossible => Fin.elim0 impossible)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))

end
end LAlanine40K2025.Thermal.Recovery.Reservoir.Pointer.Feedback.Renewal.Direction.Blocks.EnergyFrame.Inverse.Scaled.Finite.SquareRoot.Full.Rows
end SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule
