import H0mework.Versions.R9c73a630.Chemistry.LAlanineBandCall040.TubeCacheB0
import H0mework.Versions.R9c73a630.Chemistry.LAlanineBandCall040.TubeCacheB1
import H0mework.Versions.R9c73a630.Chemistry.LAlanineBandCall040.TubeCacheB2
import H0mework.Versions.R9c73a630.Chemistry.LAlanineBandCall040.TubeCacheB3
import H0mework.Versions.R9c73a630.Chemistry.LAlanineBandCall040.TubeCacheB4
import H0mework.Versions.R9c73a630.Chemistry.LAlanineBandCall040.TubeCacheB5
import H0mework.Versions.R9c73a630.Chemistry.LAlanineBandCall040.TubeCacheB6
import H0mework.Versions.R9c73a630.Chemistry.LAlanineBandCall040.TubeCacheB7

set_option autoImplicit false

namespace SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.BasinRefinement.TrueTubeWholeCache.Call40

open SourceRectangle SourceSignedEvaluator SourceGaussianModel SourceFiniteData SourceRectangleChecks SourceFields

assembleLowFieldGroups

end SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.BasinRefinement.TrueTubeWholeCache.Call40
