import H0mework.Versions.R9c73a630.Chemistry.LAlanineBandCall015.FieldData

set_option autoImplicit false

namespace SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule
namespace LAlanine40K2025.BasinRefinement.WholeBandCache.Call15

checkWholeBandOrbitals 0 98

end LAlanine40K2025.BasinRefinement.WholeBandCache.Call15
end SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule
