import H0mework.Versions.R9c73a630.Chemistry.LAlanineBandCall098.FieldData

set_option autoImplicit false

namespace SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule
namespace LAlanine40K2025.BasinRefinement.WholeBandCache.Call98

checkWholeBandGroups 0 94

end LAlanine40K2025.BasinRefinement.WholeBandCache.Call98
end SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule
