import H0mework.Chemistry.LAlanineBandCall037.TubeCacheB0
import H0mework.Chemistry.LAlanineBandCall037.TubeCacheB1
import H0mework.Chemistry.LAlanineBandCall037.TubeCacheB2
import H0mework.Chemistry.LAlanineBandCall037.TubeCacheB3
import H0mework.Chemistry.LAlanineBandCall037.TubeCacheB4
import H0mework.Chemistry.LAlanineBandCall037.TubeCacheB5
import H0mework.Chemistry.LAlanineBandCall037.TubeCacheB6
import H0mework.Chemistry.LAlanineBandCall037.TubeCacheB7

set_option autoImplicit false

namespace SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.BasinRefinement.TrueTubeWholeCache.Call37

open SourceRectangle SourceSignedEvaluator SourceGaussianModel SourceFiniteData SourceRectangleChecks SourceFields

assembleLowFieldGroups

end SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.BasinRefinement.TrueTubeWholeCache.Call37
