import H0mework.Chemistry.LAlanineBandCall002.FieldMatrixData

set_option autoImplicit false
set_option maxRecDepth 4096

namespace SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule
namespace LAlanine40K2025.BasinRefinement.WholeBandCache.Call2

checkWholeBandMatrixRows 0 1

end LAlanine40K2025.BasinRefinement.WholeBandCache.Call2
end SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule
