import H0mework.Chemistry.LAlanineBandCall018.FieldData

set_option autoImplicit false

namespace SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule
namespace LAlanine40K2025.BasinRefinement.WholeBandCache.Call18

checkWholeBandGroups 0 94

end LAlanine40K2025.BasinRefinement.WholeBandCache.Call18
end SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule
