import H0mework.Chemistry.LAlanineBandInputs.Reifier

set_option autoImplicit false
set_option maxRecDepth 16384
set_option maxHeartbeats 2000000

namespace SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule
namespace LAlanine40K2025.BasinRefinement.WholeBandGeneratedInputs.Block16_013

open SourceSignedEvaluator SourceRectangle WholeBandSource WholeBandSaturation

generateBandInputCalculations 208 224

end LAlanine40K2025.BasinRefinement.WholeBandGeneratedInputs.Block16_013
end SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule
