import H0mework.Versions.R9c73a630.Chemistry.LAlanineBandCall048.TubeMatrixAssembled
import H0mework.Versions.R9c73a630.Chemistry.LAlanineBandCall048.TubeCacheComplete

namespace SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.BasinRefinement.TrueTubeWholeMatrix.C48

open WholeCellMatrix SourceIntegerGrid SourceFields SourceFiniteData SourceSignedEvaluator SourceRectangle SourceGaussianModel

assembleTrueTubeCallMatrix 48

end SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.BasinRefinement.TrueTubeWholeMatrix.C48
