import H0mework.Versions.R9c73a630.Chemistry.LAlanineCellField47.MatrixAssembled
import H0mework.Versions.R9c73a630.Chemistry.LAlanineCellField47.CacheComplete

namespace SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.BasinRefinement.WholeCellMatrix.F47

open SourceIntegerGrid SourceFields SourceFiniteData SourceSignedEvaluator SourceRectangle SourceGaussianModel

assembleWholeCellMatrix 47

end SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.BasinRefinement.WholeCellMatrix.F47
