import H0mework.Chemistry.LAlanineTrueTube.MatrixF2Data
import H0mework.Chemistry.LAlanineWholeCell.MatrixCertificate

namespace SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.BasinRefinement.TrueTubeMatrix.F2

checkWholeCellMatrixRow 6
checkWholeCellMatrixRow 7

end SaturationMonoid.NoIslandNoMagic.Consciousness.Immortality.Embodied.Molecule.LAlanine40K2025.BasinRefinement.TrueTubeMatrix.F2
