import CPS1MaterialIncidence.NativeRawRegularity
import CPS1MaterialIncidence.NativeFullSmooth
#print axioms CPS1MaterialIncidence.NativeBodyFunctionProbe.full_raw_nuclear_differentiable
#print axioms CPS1MaterialIncidence.NativeBodyFunctionProbe.full_raw_core_differentiable
#print axioms CPS1MaterialIncidence.NativeBodyFunctionProbe.full_raw_trace_differentiable
#print axioms CPS1MaterialIncidence.NativeBodyFunctionProbe.full_raw_energy_differentiable
#print axioms CPS1MaterialIncidence.NativeBodyFunctionProbe.post_full_smooth
#print axioms CPS1MaterialIncidence.NativeBodyFunctionProbe.post_nondifferentiable_impossible
#print axioms CPS1MaterialIncidence.NativeBodyFunctionProbe.native_body_full_smooth
#print axioms CPS1MaterialIncidence.NativeBodyFunctionProbe.body_function_nondifferentiable_impossible
