import H0mework.Realization.Residual.P243

/-!
# Proposition 303: iteration generates the arithmetic spine; satOr is derived

The failed route was to treat noisy-OR `satOr` as if it were a replacement for
the ordinary ring multiplication.  The correct hierarchy is:

* repeated `bumpSat`/`relaxModule` steps are indexed by `n : ℕ`;
* serializing runs gives addition of iteration counts;
* iterating a run gives multiplication of iteration counts;
* ordinary rings/fields are the ambient Mathlib arithmetic built from that
  natural-number spine;
* noisy-OR is the derived effective-rate operation on that ambient arithmetic:
  it is exactly the rate of serially composing relaxation steps.

This file formalizes the framework-specific part of that hierarchy.  The
standard construction `ℕ → ℤ → ℚ → ℝ` is supplied by Mathlib; the new theorem is
that saturation's effective rates respect the `ℕ` addition/multiplication
generated by iteration.
-/

namespace SaturationMonoid
namespace AffineRelaxation

variable {K : Type*} [Field K]

/-- The effective single-step rate obtained by applying a fixed rate `σ` for
`n` iterations. -/
def iteratedRate (σ : K) (n : ℕ) : K :=
  1 - (1 - σ) ^ n

/-- THEOREM 1: zero iterations have effective rate `0`. -/
@[simp] theorem iteratedRate_zero (σ : K) :
    iteratedRate σ 0 = 0 := by
  simp [iteratedRate]

/-- THEOREM 2: one iteration has the original rate. -/
@[simp] theorem iteratedRate_one (σ : K) :
    iteratedRate σ 1 = σ := by
  simp [iteratedRate]

/-- THEOREM 3: the residual keep-rate of `n` iterations is `(1 - σ)^n`. -/
theorem keep_iteratedRate (σ : K) (n : ℕ) :
    1 - iteratedRate σ n = (1 - σ) ^ n := by
  simp [iteratedRate]

/-- THEOREM 4: serializing `n` iterations and then `m` iterations gives
addition of iteration counts.  In rate coordinates, addition is seen as
noisy-OR composition. -/
theorem iteratedRate_add
    (σ : K) (n m : ℕ) :
    iteratedRate σ (n + m) =
      satOrField (iteratedRate σ n) (iteratedRate σ m) := by
  simp [iteratedRate, satOrField, pow_add]

/-- THEOREM 5: iterating an `n`-step effective run `m` times gives
multiplication of iteration counts. -/
theorem iteratedRate_iteratedRate
    (σ : K) (n m : ℕ) :
    iteratedRate (iteratedRate σ n) m =
      iteratedRate σ (n * m) := by
  unfold iteratedRate
  simp
  rw [pow_mul]

/-- THEOREM 6: P243 phrased through `iteratedRate`: `n` repetitions of a
fixed-rate relaxation are one relaxation at the effective iterated rate. -/
theorem relaxModule_iterate_eq_single_iteratedRate
    {E : Type*} [AddCommGroup E] [Module K E]
    (target : E) (σ : K) (x : E) (n : ℕ) :
    (fun y : E => relaxModule target σ y)^[n] x =
      relaxModule target (iteratedRate σ n) x := by
  simpa [iteratedRate] using
    relaxModule_iterate_eq_single_pow_rate target σ x n

/-- THEOREM 7: the two-step noisy-OR law is exactly the `n=1,m=1` serial
iteration case. -/
theorem satOrField_eq_serial_one_one
    (σ : K) :
    satOrField (iteratedRate σ 1) (iteratedRate σ 1) =
      iteratedRate σ (1 + 1) := by
  rw [iteratedRate_add]

/-- A compact certificate for the corrected hierarchy:
iteration-count arithmetic first, noisy-OR effective rates second. -/
structure IterationArithmeticSpineCertificate where
  zero_rate : ∀ σ : K, iteratedRate σ 0 = 0
  one_rate : ∀ σ : K, iteratedRate σ 1 = σ
  residual : ∀ (σ : K) (n : ℕ), 1 - iteratedRate σ n = (1 - σ) ^ n
  serial_add :
    ∀ (σ : K) (n m : ℕ),
      iteratedRate σ (n + m) =
        satOrField (iteratedRate σ n) (iteratedRate σ m)
  iterated_mul :
    ∀ (σ : K) (n m : ℕ),
      iteratedRate (iteratedRate σ n) m =
        iteratedRate σ (n * m)
  relax_single :
    ∀ {E : Type*} [AddCommGroup E] [Module K E]
      (target : E) (σ : K) (x : E) (n : ℕ),
      (fun y : E => relaxModule target σ y)^[n] x =
        relaxModule target (iteratedRate σ n) x

/-- THEOREM 8: the canonical iteration-arithmetic spine certificate. -/
theorem iterationArithmeticSpineCertificate :
    IterationArithmeticSpineCertificate (K := K) where
  zero_rate := iteratedRate_zero
  one_rate := iteratedRate_one
  residual := keep_iteratedRate
  serial_add := iteratedRate_add
  iterated_mul := iteratedRate_iteratedRate
  relax_single := by
    intro E _ _ target σ x n
    exact relaxModule_iterate_eq_single_iteratedRate target σ x n

end AffineRelaxation
end SaturationMonoid
